### ISSUE TITLE
search with just a resource id should retrieve the resource?

### ISSUE THREAD

**Issue by xristy** [buda-base/public-digital-library#10]
In the [tbrc](https://www.tbrc.org) site entering ``G9GBX420325000`` in the search box returns the corresponding resource.

In [bdrc library](http://library.bdrc.io) entering ``bdr:G9GBX420325000`` returns a list of resources that refer to ``bdr:G9GBX420325000`` but not ``bdr:G9GBX420325000`` itself.

There doesn't seem to be an obvious way of entering a resource id at [bdrc library](http://library.bdrc.io) to simply retrieve the resource.

Maybe a show text entry box in addition to the search box or detect that a resource is being mentioned in the search box (which is what is done on the tbrc.org site)

**Comment by berger-n** [comment]
I see
you are right
another section would be pertinent ahead of other sections eg "Searched Resource"
so as to have a direct link to the searched resource

**Comment by berger-n** [comment]
sorry you can now have a look:
http://library.bdrc.io/search?r=bdr:G9GBX420325000

searching for any resource gives a result page with *at least* the searched resource:
http://library.bdrc.io/search?r=bdr:R39

**Comment by xristy** [comment]
Thank you very much. Now, as an encore, perhaps you could also permit ontology/vocabulary ids also. For example, bdo:Person or :workHasCreator or adm:status and so on.

**Comment by berger-n** [comment]
you're welcome!
I wonder what you have in mind when searching for `bdo:Person` or `:workHasCreator`...
shall we return ontology properties definition eg http://purl.bdrc.io/ontology/core/Person ?

**Comment by xristy** [comment]
Yes, what I had in mind was to  just retrieve the defn for the ontology item.

**Comment by berger-n** [comment]
here we are:
http://library.bdrc.io/search?p=bdo:Person
http://library.bdrc.io/search?p=:workCreator
http://library.bdrc.io/search?p=adm:status

**Comment by xristy** [comment]
Thanks! Maybe the search could redirect to purl.bdrc.io without the intermediate result? At any rate it's nice to have the access in one place.

**Comment by berger-n** [comment]
not sure what you mean here:
* link to http://purl.bdrc.io/ontology instead of http://purl.bdrc.io/ontology/core/Topic?
* redirect page to http://purl.bdrc.io/ontology/core/Topic when bdo:Topic has been searched?

**Comment by eroux** [comment]
the latter I think

**Comment by berger-n** [comment]
sounds a bit strange to me
open in other tab maybe?

**Comment by xristy** [comment]
We can try "open in new tab". You have a good point that replacing the current library page w/ a purl page can produce cognitive dissonance

**Comment by eroux** [comment]
I think that's quite awful...

this is a really weird design pattern anyway (I've never seen that on a website), maybe we can give up on the ontology part?

**Comment by eroux** [comment]
I guess we could do that by adding `rdfs:label`s to the core ontology vocabulary (like `rdfs:subclassOf`, etc.), that's certainly possible but it doesn't look to me like the most urgent thing...

**Comment by xristy** [comment]
It is indeed not most urgent. It is one of those little details that can certainly help create a positive impression of BUDA if it is done tastefully and in a manner consistent with the rest of the library interface.

**Comment by berger-n** [comment]
now we can view ontology property as any other resource:
http://library.bdrc.io/show/bdo:Person
http://library.bdrc.io/search?p=bdo:Person

**Comment by berger-n** [comment]
indeed
seems to be fixed with latest commit

**Comment by xristy** [comment]
thank you
