### ISSUE TITLE
better placement for Browse Associated Resources

### ISSUE THREAD

**Issue by xristy** [buda-base/public-digital-library#101]
Jann has mentioned that the "Browse Associated Resources" is not as visible or prominent as its functionality warrants.

In tbrc.org there are tabs that call attention to various kinds of associated resources and a common use of visiting a Person resource for example is to look for associated Works.

Perhaps try putting the link in bold just below the **Name** list in bold like:

  >  **Browse Associated Resources**

**Comment by berger-n** [comment]
just tried something
put the link just below the title and replaced it by an icon in the top menu
feel free to comment in any way

http://library-dev.bdrc.io/show/bdr:P6161

![image](https://user-images.githubusercontent.com/33383857/66853187-f5301e80-ef7e-11e9-9231-a773da592d77.png)

**Comment by xristy** [comment]
It looks good to me. Thx. We'll see what Jann thinks when he's back from China
