### ISSUE TITLE
close button + url for mirador

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#106]
cc. @subsystem7 

For the mobile app, we need to have a close button in mirador in the embed-iframe environment. The close button will open a special url that will close the window on mobile. The idea is the following:

when the url of the embed-iframe page has `?closeUrl=XXX`, we need to pass it to the mirador config and it must display a close button with the label "exit viewer", and open the `XXX` url when clicked.

@subsystem7 how should it open the url (should it be a `<a>`? with what arguments?) Do you have a link describing the mechanism?

**Comment by subsystem7** [comment]
This is essentially to facilitate communication between the web based javascript IIIF viewer and the BDRC Lib Mobile Application. 

Perhaps what we should decide on is an extendable methodology, such as:

```
?callerURI=URL_ENCODED_STRING
```

For example:

```http://library.bdrc.io/view/bdr:W22084?callerURI=bdrclibapp%3A%2F%2F```

Where the decoded value of callerURI would be:

```
bdrclibapp://
```
and the expectation is that a range of commands could be called if desired, such as share requests, save requests, bookmark requests, whatever.

The first use would be the close action, which would be activated by adding "?action=close" to the URI.  So, the close button would be like this:

```
<a href="bdrclibapp://?action=close">close</a>
```

**Comment by berger-n** [comment]
[there you are](http://library.bdrc.io/view/bdr:W22084?callerURI=bdrclibapp://)
a *Close Viewer* button with link to `bdrclibapp://?action=close`

**Comment by eroux** [comment]
@subsystem7 can we close this?
