### ISSUE TITLE
display of agent as creator

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#109]
This is the only pattern that we have in this form, but in http://library.bdrc.io/show/bdr:W0NGMCP37611 the "has creator" should display a link to bdr:P4956 and the label of bdr:R0ER0019, in a relatively condensed way.

**Comment by berger-n** [comment]
looking at the ttl file the `bdo:AgentAsCreator` node has an odd `rdfs:label` 
(see http://purl.bdrc.io/resource/W0NGMCP37611.ttl)
whereas there isn't in other Works, 
for example http://purl.bdrc.io/resource/W0GR0357.ttl
which has more extensive display:
![image](https://user-images.githubusercontent.com/33383857/70917248-43b07680-201d-11ea-9d45-68b03edfdcc8.png)
thus removing the label from the creator node should fix the problem

**Comment by eroux** [comment]
yes, sorry, in most cases there's no rdfs:label but we want to support the cases where there is, in that case the rdfs:label should be used instead of the skos:prefLabel associated with the person resource
