### ISSUE TITLE
consistent choice of prefLabel lang in lists

### ISSUE THREAD

**Issue by xristy** [buda-base/public-digital-library#11]
Following [bdr:G9GBX420325000](http://library.bdrc.io/show/bdr:G9GBX420325000) the **Contains:** list displays a mix of Chinese and English prefLabels.

There probably should be a way to control the choice of prefLabel lang so that a consistent display is achieved. Currently, it appears that the _first_ label in the results is chosen and Fuseki/Jena is arbitrary in what order the prefLabels for a resource are returned

**Comment by berger-n** [comment]
actually there already is ! ^^
http://library.bdrc.io/search?r=bdr:G9GBX420325000&t=Place
![image](https://user-images.githubusercontent.com/33383857/44726255-9cca6300-aad7-11e8-8ee4-cd59b585786b.png)
there is a specific issue with Chinese in that data randomly use zh, zh-hans or zh-hant and even other I think
we might be interested in that choosing Chinese/zh returns any zh-* label

**Comment by xristy** [comment]
I tried selecting _Chinese_ and _Chinese (Hanzi)_ to no avail with:

<img width="997" alt="screen shot 2018-08-28 at 11 04 57 am" src="https://user-images.githubusercontent.com/3542294/44735646-abeaea00-aab2-11e8-9cba-1c02aeb42219.png">

[overflow town](http://library.bdrc.io/show/bdr:G9GBX420323101) has a zh-hans prefLabel but for some reason only the English appears. When selecting English indeed all the displayed prefLabels are English. Similarly for [G9GBX420324000](http://library.bdrc.io/search?r=bdr:G9GBX420324000) and [G9GBX420325000](http://library.bdrc.io/search?r=bdr:G9GBX420325000).

**Comment by berger-n** [comment]
- sorting labels by language might help to achieve consistency in display 
the question being: which order to use ?
maybe sa-* > bo-* > zh-* > en-*
and choose transliterations only when an original language is not available ?

- the zh-hans selector is obviously missing... must add it

**Comment by xristy** [comment]
I'm a bit confused. When I select _English_ I see all English labels. When I select _Chinese_ or _Chinese (Hanzi)_ or _Chinese (Pinyin)_ I just see a mix of Chinese and English. I assume that _Chinese (Hanzi)_ should select either zh-hans or zh-hant.

**Comment by berger-n** [comment]
added simplified/traditional Chinese selector in results language widget
does most of the consistency job:
![image](https://user-images.githubusercontent.com/33383857/44783101-9c8aa000-ab89-11e8-97db-fb49ccc1dbaf.png)

but we obviously need a language setting button on resource page I think

**Comment by eroux** [comment]
I think the best solution would be to have lists of priorities, and allowing users to choose these priorities, maybe with some predefined profiles. For instance a "Chinese (Trad)" profile would have the priority:

- zh-Hant
- zh-Hans
- sa*
- en*
- pi*
- zh-latn-pinyin
- bo*

something like that... (zh-latn-pinyin is not a very high priority as people from Taiwan or Singapore, who use traditional characters, use a different phonetic system and don't understand pinyin.

**Comment by berger-n** [comment]
just added consistent language choice: http://library.bdrc.io/search?r=bdr:G9GBX420325000&t=Place
as a beginning it is hard-coded and cannot be switched at runtime
but one can unselected a given language and see labels change accordingly to next available language in label:
![image](https://user-images.githubusercontent.com/33383857/46678982-37918380-cbe6-11e8-9011-e65bcf7531f4.png)
![image](https://user-images.githubusercontent.com/33383857/46679004-437d4580-cbe6-11e8-94a4-25c5411e084e.png)
I need to add some more interactivity now, especially in Resource page eg http://library.bdrc.io/show/bdr:G9GBX420325000
I think of adding the same panel on the right of the window
including a new widget so as to choose "latin first" or "chinese first" kindof predefined profiles, which would change the order in which laguages are tested and displayed

**Comment by eroux** [comment]
I think the list should be a set of items that we can drag and drop to form the desired order, not a list where we can check/uncheck languages

**Comment by berger-n** [comment]
I agree

**Comment by eroux** [comment]
we may have to rework that a bit in the future but let's close it for now
