### ISSUE TITLE
images for W1KG25734 not showing

### ISSUE THREAD

**Issue by xristy** [buda-base/public-digital-library#110]
I just noticed that [library W1KG25734](http://library.bdrc.io/show/bdr:W1KG25734) does not display images while [tbrc W1KG25734](https://www.tbrc.org/#!rid=W1KG25734) does.

**Comment by berger-n** [comment]
it appears that https://iiif.bdrc.io/bdr:V1KG25734_I1KG25736::I1KG257360003.jpg/full/,600/0/default.jpg returns error 500 without any more hint
