### ISSUE TITLE
Etext search results feature request

### ISSUE THREAD

**Issue by MarcAgate** [buda-base/public-digital-library#111]
While investigating a couple of texts and trying to identify the source of a quote I found in some commentary, I happened to search for the following « string » : sgyu ma rnam par nyams (སྒྱུ་མ་རྣམ་པར་ཉམས ) 

I first ran this search on AIBS database (kangyur and tengyur) http://databases.aibs.columbia.edu/  and got the following result:

*************************
AIBS search

**Your query returned 2 instances in 2 texts.**

◀ Tengyur: tantra / rgyud 'grel ▶
Kulika Puṇḍarīka / Avalokiteśvara // Vimalaprabhā-nāma-mūlatantrānusāriṇī-dvādaśasāhasrikā-laghukālacakratantrarāja-ṭīkā // bsdus pa'i rgyud kyi rgyal po dus kyi 'khor lo'i 'grel bshad, rtsa ba'i rgyud kyi rjes su 'jug pa stong phrag bcu gnyis pa dri ma med pa'i 'od ces bya ba
sgyu ma rnam par nyams par byed pa yin
D 1347: vol. 11, folio/line 111a.6  |  view ACIP source |  View complete sentence
Anupamarakṣita // ṣaḍaṅgayoga // sbyor ba yan lag drug pa
sgyu ma rnam par nyams par byed par 'gyur
D 1387: vol. 14, folio/line 288a.4  |  view ACIP source |  View complete sentence

**If I click on the first « view complete sentence », the I get :**

sdig pa dang ni shing srin [111a.6] sems can rnams, gang las byung ba de dag de nyams byed, de bzhin rnal 'byor dag gi sems de ni, sgyu ma rnam par nyams par byed pa yin,

******************************
tbrc.org search

**Then I went to the library search feature and ran the same query, I get 8 results. Among them I have the vimalaprabha:**

bsdus pa'i rgyud kyi rgyal po dus kyi 'khor lo'i 'grel bshad rtsa ba'i rgyud kyi rjes su 'jug pa stong phrag bcu gnyis pa dri ma med pa'i 'od/
pod 6 bstan 'gyur/ (dpe bsdur ma)
... རྒྱས་ཉིད་འབྲས་ཏེ།།ཆུ་ཤིང་གི་ནི་འབྲས་བུ་སྨིན་པ་དང་རྙི། །ཆུ་ཤིང་ཉམས་པས་ཡང་དག་འབྱུང་བ་བཞིན་།་ །སྡིག་པ་དང་ནི་ཤིང་སྲིན་སེམས་ཅན་རྣམས། །གང་ལས་བྱུང་བ་དེ་དག་དེ་ཉམས་བྱེད། །དེ་བཞིན་རྣལ་འབྱོར་དག་གི་་སེམས་དེ་ནི། ། སྒྱུ་མ་རྣམ་པར་ཉམས ་པར་བྱེད་པ་ཡིན། །གཉིས་མེད་གཡོ་བ་མེད་དང་རིགས་མེད་དང་། །འདོད་དང་མཆོག་ཏུ་མི་འགྱུར་འདོད་ཆགས་ཆེ། །དངོས་དང་དངོས་པོ་མེད་པ་6—263

Expand context
View scanned page: 282
View text: bsdus pa'i rgyud kyi rgyal po dus kyi 'khor lo'i 'grel bshad rtsa ba'i rgyud kyi rjes su 'jug pa stong phrag bcu gnyis pa dri ma med pa'i 'od/
work:volume:page:pubinfo W1PD95844:6:282: krung go'i bod rig pa'i dpe skrun khang / 1994-2008

**When I click on « Expand context » I have a wonderful extract from the text !**

****************************
Buda library search

**I have 8 etexts:** 
http://library.bdrc.io/search?q=%22sgyu%20ma%20rnam%20par%20nyams%22&lg=bo-x-ewts&t=Etext

**However**

1) I cannot read the title of the matching works except for #5 
2) I have no way to find the vimalaprabha (well... I know it’s the second one (pod 6 bstan 'gyur/ (dpe bsdur ma) ) from my previous search on tbrc.org)
3) If I click on any of these results, I got the whole text (I have to scroll for that) but I cannot find the extract containing my search string (unless I scroll all the way down and do a search using the browser)

I think we should do at least as well as on tbrc.org where we can read the titles and get the search string in context. As they are now, the search results for etexts don’t help.
It would be great to have an equivalent of the « expand context » feature on tbrc.org and possibly a « browse the whole text » button.

**Comment by eroux** [comment]
I think this is fixed, I opened https://github.com/buda-base/lds-queries/issues/35 when testing but it's unrelated to the original issue
