### ISSUE TITLE
When searching for a Resource ID just display the Resource view directly

### ISSUE THREAD

**Issue by xristy** [buda-base/public-digital-library#113]
When searching for a Resource ID the UI should just display the _Resource View_ directly without the intervening search results display, which will typically have a single **Resource Id Matching** and one or more **Persons** results which are easily accessible from the _Resource View_.

This is the behavior we have on [tbrc.org](https://tbrc.org/). The intervening search results display in really not needed.

**Comment by berger-n** [comment]
as of today searching for a resource ID without prefix directly opens the resource page
(which fixes #112 as well)
tell me if you need that prefixed resource IDs also redirect to resource page

**Comment by xristy** [comment]
@berger-n Yes it would be great if the prefixed RIDs go directly to the resource display. The RIDs w/o prefix only cover the bdr: since other RIDs will need the prewfrix to distinguish what namespace
