### ISSUE TITLE
UI/UX approach for refine search filters

### ISSUE THREAD

**Issue by xristy** [buda-base/public-digital-library#114]
The current approach to handling initial display of search results is somewhat disruptive:
![Current filters display](https://user-images.githubusercontent.com/3542294/73202703-39e05f80-4101-11ea-9cce-4ffdc1ff0eed.png)

The active filters lay on top of the search results and have to be dismissed before the user can survey the search results summary display. This means an additional mouse movement and click to get an unobscured view unless the screen is opened quite wide.

An alternative to consider is something like in Adobe Acrobat:
![Screen Shot 2020-01-27 at 12 25 40 PM](https://user-images.githubusercontent.com/3542294/73203016-de62a180-4101-11ea-88f9-f628c7a8c167.png)

where there is a vertical bar along the left side that allows for expansion of a navigation area that may include the filter refinement display or other features:
![Screen Shot 2020-01-27 at 12 25 53 PM](https://user-images.githubusercontent.com/3542294/73203198-313c5900-4102-11ea-930a-9183d5baf713.png)

Clicking the bookmark icon (in blue) displays an area similar to the filter/facet area:
![Screen Shot 2020-01-27 at 12 26 10 PM](https://user-images.githubusercontent.com/3542294/73203387-92fcc300-4102-11ea-9728-dccc160a94ae.png)

**Notice** that as these areas are expanded they push the main display to the right rather than obscuring the main display as in the current approach.

**Comment by eroux** [comment]
I think we won't really change that now
