### ISSUE TITLE
https://library.bdrc.io does not work for "naked" RIDs

### ISSUE THREAD

**Issue by xristy** [buda-base/public-digital-library#115]
When visiting [https://library.bdrc.io](https://library.bdrc.io) and entering an RID, like W12827, the result is **No result found.** This doesn't happen when visiting [http://library.bdrc.io](http://library.bdrc.io)

Also bdr:W12827 and searches work fine with https. Its just the new "naked" RID case.

**Comment by berger-n** [comment]
can't reproduce bug
(both working same for me)
this might be a cache issue
does it work in incognito mode?


Le lun. 27 janv. 2020 à 20:40, Chris Tomlinson <notifications@github.com> a
écrit :

**Comment by xristy** [comment]
Well there's a problem. Jim, Travis and myself are getting distinctly different behaviors for http vs https.

I'm now having a problem that I've seen before where with https I don't see images in Safari or FF on two different computer systems on all three browser types despite clearing caches and browsing data on Safari and FF numerous times. Also seeing same behavior on iPad Safari.

FF http:
![Screen Shot 2020-01-27 at 2 27 55 PM](https://user-images.githubusercontent.com/3542294/73211530-0f4ad280-4112-11ea-9d1b-f9f9326e3088.png)

FF https:
![Screen Shot 2020-01-27 at 2 29 05 PM](https://user-images.githubusercontent.com/3542294/73211620-35707280-4112-11ea-9f52-1f1ac14ea864.png)

I'm at a loss as to how to deal with this. I don't know how to clear browsing data on Chrome despite trying to follow google instructions.

Is there anyway that the client app can force a clearing of browser data related to the app assuming it can detect out of date app data or some such?

**Comment by eroux** [comment]
nginx has a nice system of having the client clear the cache when file of the app changed so we already have something. Can you open the developer tool bar and check if there are error in the console or in the network tab?

**Comment by TBRC-Travis** [comment]
![Screen Shot 2020-01-27 at 3 51 58 PM](https://user-images.githubusercontent.com/19354126/73212803-03184280-411d-11ea-95ea-f9aba0d39c93.png)

**Comment by TBRC-Travis** [comment]
And before that error I see this:

![image](https://user-images.githubusercontent.com/19354126/73212940-4377c080-411d-11ea-829d-93cbd011af7d.png)

**Comment by eroux** [comment]
Ok, the problem is that the app looks for manifests in http, and the requests are blocked by the browser. @berger-n the solution is to use `//iiifpres.bdrc.io/etc.` instead of `http://iiifpres.bdrc.io/etc.`. Can you also grep the source code to make sure we don't do that anywhere else?

**Comment by xristy** [comment]
the whole console log

[HTTPS_LIB_FAIL.txt](https://github.com/buda-base/public-digital-library/files/4119309/HTTPS_LIB_FAIL.txt)

**Comment by berger-n** [comment]
thanks @TBRC-Travis & @eroux for the hint
seems to be ok now:
![image](https://user-images.githubusercontent.com/33383857/73252593-44f7c600-41bb-11ea-90c0-a8b69cc321dc.png)
Note that I had to force reload (SHIFT+CTRL+R in Chrome) after updating code, even though I had console opened with "cache disabled" on Network tab before first, standard reload...
(awesome scans BTW)

**Comment by eroux** [comment]
I think we solved both the rid and the cache issue
