### ISSUE TITLE
Not viewing all pages of Fair use work while being logged on

### ISSUE THREAD

**Issue by MarcAgate** [buda-base/public-digital-library#118]
When logged off, going here : http://library-dev.bdrc.io/show/bdr:W1AC296 which is a FAIR USE type work, I see only 40 images and I get a 40 pages pdf, that's ok.

If i log on, then I get the full pdf (that's ok) but still, I can only browse 40 pages in the viewer.

**Comment by berger-n** [comment]
it is ok now
(it also works for copyrighted/restricted works like http://library-dev.bdrc.io/show/bdr:W8LS18997)

**Comment by MarcAgate** [comment]
Thanks a lot. Perfect!
