### ISSUE TITLE
"root" tab for workPart

### ISSUE THREAD

**Issue by berger-n** [buda-base/public-digital-library#119]
there could be a "root" tab for work parts that doesn't have an `instanceOf`, for example:
http://library-dev.bdrc.io/show/bdr:MW22084_S0008
http://library-dev.bdrc.io/show/bdr:MW1GS66367_08A847

(contrary to http://library-dev.bdrc.io/show/bdr:MW22084_0009 that has an `instanceOf` Work tab)

**Comment by eroux** [comment]
hmmm... good question! I think in the future outline display we won't display obvious links to that kind of intermediate entity so no need to spend too much time on the design

**Comment by eroux** [comment]
with the outlines now finished I think we can close this one
