### ISSUE TITLE
needed window width too wide

### ISSUE THREAD

**Issue by xristy** [buda-base/public-digital-library#121]
here's a couple of screenshots with inspectors showing the px width x height:

This is the view when I open the url from the meeting notes in a _reasonable_ width window:

![Screen Shot 2020-04-24 at 9 31 54 AM](https://user-images.githubusercontent.com/3542294/80226050-7f81cb00-8611-11ea-8045-8e1412a856d8.png)

This is how wide I need to open to get the whole view to fit:

![Screen Shot 2020-04-24 at 9 30 48 AM](https://user-images.githubusercontent.com/3542294/80226489-0b93f280-8612-11ea-8db8-82845cf8b9dd.png)

and this is what happens when I scroll the window in the original window width to view the Image tab:

![Screen Shot 2020-04-24 at 9 31 25 AM](https://user-images.githubusercontent.com/3542294/80226066-83ade880-8611-11ea-8d17-f455cd5ecade.png)

Shouldn't there be some elasticity to the window width?

**Comment by berger-n** [comment]
should be much better now
![image](https://user-images.githubusercontent.com/33383857/80388913-bf171400-88aa-11ea-9842-f79bbe774817.png)

**Comment by xristy** [comment]
Thanks, that is better. 

I notice that with a bit narrower window I can horizontal scroll the window and the left-hand navigation area slides on top of the main content. Perhaps it could slide under?

![Screen Shot 2020-04-27 at 10 30 12 AM](https://user-images.githubusercontent.com/3542294/80390709-6c216a80-8872-11ea-8ca1-b67888751afc.png)

**Comment by xristy** [comment]
Thanks @berger-n. The [commit 8a4c88](https://github.com/buda-base/public-digital-library/commit/8a4c88ec0e6c8077fa91412e258cae2af42e00cc) seems to work quite nicely to me.
