### ISSUE TITLE
error in build on the ZJU server

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#124]
the error report contains just:

```
[root@zju-debian01 /mnt/data/pdl]$ bash -x /pdl.sh

...
+ yarn -s --non-interactive build
/bin/sh: 1: react-scripts: not found
```

Nicolas, do you know where this could come from?

**Comment by eroux** [comment]
Here's the full log. It contains some warnings, and we should probably move to `yarn.lock` instead of `package-lock.json`

[pdl.log.txt](https://github.com/buda-base/public-digital-library/files/4809781/pdl.log.txt)

**Comment by berger-n** [comment]
not clear where that package-lock.json comes from (https://github.com/buda-base/public-digital-library?files=1)
I would try `yarn global add react-scripts`

**Comment by eroux** [comment]
hah, weird for the `package-lock.json`... 

can you make sure that https://github.com/buda-base/buda-base/blob/master/scripts/pdl.sh is up to date and perhaps add the `react-scripts`?

**Comment by berger-n** [comment]
I've added the line for `react-scripts` ([commit](https://github.com/buda-base/buda-base/commit/d6d0dfd77b6bb97e9a736b11af9815a694bbc2e8))
yet if I read that script well we need to remove `public-digital-library` directory first before running it

**Comment by eroux** [comment]
Thanks, the script still fails, here's the new log:

[pdl-0622.log.txt](https://github.com/buda-base/public-digital-library/files/4812339/pdl-0622.log.txt)

**Comment by berger-n** [comment]
build should succeed now
