### ISSUE TITLE
different URL for queries accessing chunks

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#125]
I'm going to remove 

http://purl.bdrc.io/query/graph/ChunksByPage
http://purl.bdrc.io/query/graph/Chunks

as they've been replaced with

http://purl.bdrc.io/lib/ChunksByPage
http://purl.bdrc.io/lib/Chunks

which check the georestriction and the user access through the token (which must be sent). @berger-n this has lower priority than the translations and ZJU stuff but it should be relatively straightforward (although maybe a bit of work is needed for the token). Tell me when it's done and I'll remove the public queries.

**Comment by berger-n** [comment]
in this [example](http://library.bdrc.io/show/bdr:UTIE0OPP000509_v001#open-viewer) 
[query/graph/Chunks](http://purl.bdrc.io/query/graph/Chunks?R_RES=bdr%3AUTIE0OPP010371_v001&I_START=0&I_END=10000) has results whereas [lib/Chunks](http://purl.bdrc.io/lib/Chunks?R_RES=bdr%3AUTIE0OPP010371_v001&I_START=0&I_END=10000) returns `"Nothing found"`
even with token sent in header:
![image](https://user-images.githubusercontent.com/33383857/85283730-1fcb6300-b48e-11ea-8e8f-d61ba8ee4911.png)

**Comment by eroux** [comment]
are you in the admin group? @MarcAgate can you make a small check?

**Comment by MarcAgate** [comment]
I just added Nicolas to the admin group. Let's give auth0 webhook some time to call ldspdi so the auth model is updated.

**Comment by berger-n** [comment]
unfortunately I was already logged using your admin credentials @MarcAgate (tchame@...)

**Comment by eroux** [comment]
ah... well... can you deploy the new version of the pdl? it will be easier to fix the server side then

**Comment by berger-n** [comment]
done
