### ISSUE TITLE
Missing scans [report by user aVNWKbpO0wc]

### ISSUE THREAD

**Issue by TBRC-pmench** [buda-base/public-digital-library#128]
Some images are (possibly) not appearing on library.bdrc.io. 

The bug report was for missing images on: https://library.bdrc.io/show/bdr:W1NLM283 

Images appear on tbrc.org: https://www.tbrc.org/#!rid=W1NLM283

User also reported: "The reason is probably that the website tries to load:
https://iiifpres.bdrc.io/vo:bdr:I1NLM283_001/manifest

And the Server responds with an internal server error (error code 500) with the following data: {"timestamp":"2020-06-29T05:47:54.316+0000","status":500,"error":"Internal Server Error","message":"No message available","path":"/vo:bdr:I1NLM283_001/manifest"}"

Images appear for me on both sites so I suspect this is a sync delay and not a bug. I will follow up with the user to see if the issue persists for them. If not, I will close this issue.

**Comment by TBRC-Travis** [comment]
For what it's worth I was able to load the images on https://library.bdrc.io/show/bdr:W1NLM283 this morning but checking again now I'm getting the "spinning wheel" and the images aren't loading.  Seems like an intermittent issue.

**Comment by eroux** [comment]
yes, sorry, we just fixed something and there were a few minutes of down time. The images also appear for me, and https://iiifpres.bdrc.io/vo:bdr:I1NLM283_001/manifest works fine... The images and dimensions.json have been synced since April so it's not a sync issue... I can't see it in the logs neither... do you know at what date this happened?

**Comment by TBRC-pmench** [comment]
I'm not certain exactly when the user tried to access. The report was filed 9 hours ago.

**Comment by eroux** [comment]
let's see if we receive more of those, closing this issue in the meantime
