### ISSUE TITLE
Broken header [report by user aVNWKbpO0wc]

### ISSUE THREAD

**Issue by TBRC-pmench** [buda-base/public-digital-library#130]
> When going through the works of Je Tsongkhapa and clicking on one the header broke for me. The link that I got when clicking on one of the works from the search result list is the following (which is also suspiciously long):
http://library.bdrc.io/show/bdr:WA1CZ1011?s=t%3DWork%26r%3Dbdr%3AP64%26pg%3D1%26f%3Dtree%2Cinc%2Cbdr%3AT1763%26f%3Dtree%2Cinc%2Cbdr%3AT61%26f%3Dtree%2Cinc%2Cbdr%3AT1029%26f%3Dtree%2Cinc%2Cbdr%3AT2339%26f%3Dtree%2Cinc%2Cbdr%3AT012AG03703%26f%3Dtree%2Cinc%2Cbdr%3AT11MS21%26f%3Dtree%2Cinc%2Cbdr%3AT1CZ56%26f%3Dtree%2Cinc%2Cbdr%3AT132%26f%3Dtree%2Cinc%2Cbdr%3AT1491%26f%3Dtree%2Cinc%2Cbdr%3AT2398%26f%3Dtree%2Cinc%2Cbdr%3AT304%26f%3Dtree%2Cinc%2Cbdr%3AT1KG8787%26f%3Dtree%2Cinc%2Cbdr%3AT2397%26f%3Dtree%2Cinc%2Cbdr%3AT770%26f%3Dtree%2Cinc%2Cbdr%3AT1871%26f%3Dtree%2Cinc%2Cbdr%3AT102%26f%3Dtree%2Cinc%2Cbdr%3AT28%26f%3Dtree%2Cinc%2Cbdr%3AT615%26f%3Dtree%2Cinc%2Cbdr%3AT447%26f%3Dtree%2Cinc%2Cbdr%3AT200%26f%3Dtree%2Cinc%2Cbdr%3AT395%26f%3Dtree%2Cinc%2Cbdr%3AT1593%26f%3Dtree%2Cinc%2Cbdr%3AT2366%26f%3Dtree%2Cinc%2Cbdr%3AT67%26f%3Dtree%2Cinc%2Cbdr%3AT1478%26f%3Dtree%2Cinc%2Cbdr%3AT454%26f%3Dtree%2Cinc%2Cbdr%3AT1366%26f%3Dtree%2Cinc%2Cbdr%3AT1028%26f%3Dtree%2Cinc%2Cbdr%3AT1742%26f%3Dtree%2Cinc%2Cbdr%3AT1GS10764%26f%3Dtree%2Cinc%2Cbdr%3AT1458%26f%3Dtree%2Cinc%2Cbdr%3AT1736%26f%3Dtree%2Cinc%2Cbdr%3AT1CZ17%26f%3Dtree%2Cinc%2Cbdr%3AT1726%26f%3Dtree%2Cinc%2Cbdr%3AT872%26f%3Dtree%2Cinc%2Cbdr%3AT175%26f%3Dtree%2Cinc%2Cbdr%3AT19%26f%3Dtree%2Cinc%2Cbdr%3AT1AT269%26f%3Dtree%2Cinc%2Cbdr%3AT7%26f%3Dtree%2Cinc%2Cbdr%3AT977%26f%3Dtree%2Cinc%2Cbdr%3AT48%26f%3Dtree%2Cinc%2Cbdr%3AT8%26f%3Dtree%2Cinc%2Cbdr%3AT11%26f%3Dtree%2Cinc%2Cbdr%3AT1GS147797%26f%3Dtree%2Cinc%2Cbdr%3AT00JR690%26f%3Dtree%2Cinc%2Cbdr%3AT936%26f%3Dtree%2Cinc%2Cbdr%3AT843%26f%3Dtree%2Cinc%2Cbdr%3AT138%26f%3Dtree%2Cinc%2Cbdr%3AT933%26f%3Dtree%2Cinc%2Cbdr%3AT536%26f%3Dtree%2Cinc%2Cbdr%3AT2186%26f%3Dtree%2Cinc%2Cbdr%3AT1575%26f%3Dtree%2Cinc%2Cbdr%3AT1336%26f%3Dtree%2Cinc%2Cbdr%3AT356%26f%3Dtree%2Cinc%2Cbdr%3AT163%26f%3Dtree%2Cinc%2Cbdr%3AT394%26f%3Dtree%2Cinc%2Cbdr%3AT1606%26f%3Dtree%2Cinc%2Cbdr%3AT307%26f%3Dtree%2Cinc%2Cbdr%3AT969%26f%3Dtree%2Cinc%2Cbdr%3AT15%26f%3Dtree%2Cinc%2Cbdr%3AT1562%26f%3Dtree%2Cinc%2Cbdr%3AT1408%26f%3Dtree%2Cinc%2Cbdr%3AT1CZ29%26f%3Dtree%2Cinc%2Cbdr%3AT80%26f%3Dtree%2Cinc%2Cbdr%3AT151%26f%3Dtree%2Cinc%2Cbdr%3AT2MS13267%26f%3Dtree%2Cinc%2Cbdr%3AT475%26f%3Dtree%2Cinc%2Cbdr%3AT159%26f%3Dtree%2Cinc%2Cbdr%3AT5%26f%3Dtree%2Cinc%2Cbdr%3AT4%26f%3Dtree%2Cinc%2Cbdr%3AT164%26f%3Dtree%2Cinc%2Cbdr%3AT1%26f%3Dtree%2Cinc%2Cbdr%3AT1181%26f%3Dtree%2Cinc%2Cbdr%3AT968%26f%3Dtree%2Cinc%2Cbdr%3AT627%26f%3Dtree%2Cinc%2Cbdr%3AT27%26f%3Dtree%2Cinc%2Cbdr%3AT1992%26f%3Dtree%2Cinc%2Cbdr%3AT299%26f%3Dtree%2Cinc%2Cbdr%3AT1215%26f%3Dtree%2Cinc%2Cbdr%3AT385%26f%3Dtree%2Cinc%2Cbdr%3AT381%26f%3Dtree%2Cinc%2Cbdr%3AT354%26f%3Dtree%2Cinc%2Cbdr%3AT233%26f%3Dtree%2Cinc%2Cbdr%3AT942%26f%3Dtree%2Cinc%2Cbdr%3AT1441%26f%3Dtree%2Cinc%2Cbdr%3AT55%26f%3Dtree%2Cinc%2Cbdr%3AT1787%26f%3Dtree%2Cinc%2Cbdr%3AT1368%26f%3Dtree%2Cinc%2Cbdr%3AT2GS983%26f%3Dtree%2Cinc%2Cbdr%3AT1298%26f%3Dtree%2Cinc%2Cbdr%3AT1358%26f%3Dtree%2Cinc%2Cbdr%3AT541%26f%3Dtree%2Cinc%2Cbdr%3AT012AG03497%26f%3Dtree%2Cinc%2Cbdr%3AT393%26f%3Dtree%2Cinc%2Cbdr%3AT238%26f%3Dtree%2Cinc%2Cbdr%3AT2MS5993%26f%3Dtree%2Cinc%2Cbdr%3AT1353%26f%3Dtree%2Cinc%2Cbdr%3AT1796%26f%3Dtree%2Cinc%2Cbdr%3AT211%26f%3Dtree%2Cinc%2Cbdr%3AT2117%26f%3Dtree%2Cinc%2Cbdr%3AT313%26f%3Dtree%2Cinc%2Cbdr%3AT1091%26f%3Dtree%2Cinc%2Cbdr%3AT36%26f%3Dtree%2Cinc%2Cbdr%3AT1230%26f%3Dtree%2Cinc%2Cbdr%3AT2005%26f%3Dtree%2Cinc%2Cbdr%3AT769%26f%3Dtree%2Cinc%2Cbdr%3AT59%26f%3Dtree%2Cinc%2Cbdr%3AT2281%26f%3Dtree%2Cinc%2Cbdr%3AT1361%26f%3Dtree%2Cinc%2Cbdr%3AT10%26f%3Dtree%2Cinc%2Cbdr%3AT2DB4587%26f%3Dtree%2Cinc%2Cbdr%3AT1400%26f%3Dtree%2Cinc%2Cbdr%3AT1858%26f%3Dtree%2Cinc%2Cbdr%3AT386%26f%3Dtree%2Cinc%2Cbdr%3AT1760%26f%3Dtree%2Cinc%2Cbdr%3AT456%26f%3Dtree%2Cinc%2Cbdr%3AT58%26f%3Dtree%2Cinc%2Cbdr%3AT00KG02742%26f%3Dtree%2Cinc%2Cbdr%3AT613%26f%3Dtree%2Cinc%2Cbdr%3AT34%26f%3Dtree%2Cinc%2Cbdr%3AT433%26f%3Dtree%2Cinc%2Cbdr%3AT1051%26f%3Dtree%2Cinc%2Cbdr%3AT140%26f%3Dtree%2Cinc%2Cbdr%3AT859%26f%3Dtree%2Cinc%2Cbdr%3AT529%26f%3Dtree%2Cinc%2Cbdr%3AT2001%26f%3Dtree%2Cinc%2Cbdr%3AT337%26f%3Dtree%2Cinc%2Cbdr%3AT1892%26n%3D1

When the detail page loads for this work I get the following. It looks as if there is some overflow and maybe some problem with escaping in the background so part of the URL data appears directly within the page:
![image](https://user-images.githubusercontent.com/48484924/86024113-93272480-b9fa-11ea-996f-acdceae07c98.png)

**Comment by berger-n** [comment]
thanks! it's fixed now
![image](https://user-images.githubusercontent.com/33383857/86031574-4cefb680-ba36-11ea-85ed-3b45369eb5f1.png)
