### ISSUE TITLE
ToL links missing [report by user aVNWKbpO0wc]

### ISSUE THREAD

**Issue by TBRC-pmench** [buda-base/public-digital-library#132]
> The old page for Tsonkhapa had an external hyperlink to an external website (Treasury of Lives) as part of the information:
https://www.tbrc.org/#!rid=P64
> On the new site (http://library.bdrc.io/show/bdr:P64) this link is not there anymore.

I believe this is a user issue but would like to confirm before providing guidance. I believe the link to ToL can be opened as in the following screenshot:
![image](https://user-images.githubusercontent.com/48484924/86025008-b7cfcc00-b9fb-11ea-980b-7e437b26a76e.png)

**Comment by eroux** [comment]
right, external links have moved there. @TBRC-TimB that could be something to put in the FAQ
