### ISSUE TITLE
Tibetan font too small

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#136]
It would be good to make the Tibetan font bigger (everywhere), it's currently too small for most users. I'll let @ngawangtrinley give some numbers on how much bigger it should be

**Comment by jeehuajian** [comment]
Before and after the font size adjustment

![001](https://user-images.githubusercontent.com/42564256/86446888-2045e280-bd47-11ea-9d94-9f2e1b39f377.gif)


Tibetan font adjustment

![image](https://user-images.githubusercontent.com/42564256/86445926-cabd0600-bd45-11ea-96a9-2f4b592995e2.png)
![image](https://user-images.githubusercontent.com/42564256/86445986-dd373f80-bd45-11ea-931d-f7e7e47b8e76.png)

**Comment by eroux** [comment]
Thanks, that's very helpful!

**Comment by eroux** [comment]
P.S.: note also the untranslated "publisher name", @berger-n do you know where that might come from?

**Comment by berger-n** [comment]
thanks!
@eroux I think there is no translation in the ontology, see http://purl.bdrc.io/ontology/data/json

**Comment by eroux** [comment]
@ngawangtrinley @jeehuajian I've just added publisher name and publisher location to transifex, can you translate them? I'll update the ontology once it's done

**Comment by berger-n** [comment]
I think I have made all these changes

**Comment by eroux** [comment]
@jeehuajian @ngawangtrinley does this work now?

**Comment by ngawangtrinley** [comment]
Perfect!

**Comment by eroux** [comment]
thanks!
