### ISSUE TITLE
navigation from instance to reproduction

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#137]
It's currently by far the biggest issue in the current UX. Let's fix it in priority. I think what we should have is something like:

- "Scans: " and a big icon with the thumbnail of the image instances (in a first approximation it can be the thumbnail of the instance that we currently have)
- "Etexts": with a big icon of etexts

We don't have very relevant labels for these so let's just keep things visual

**Comment by berger-n** [comment]
this is how [this](http://library.bdrc.io/show/bdr:MW00KG03940) looks like now:
![image](https://user-images.githubusercontent.com/33383857/86392023-08188980-bc9b-11ea-8151-cdcb43db57f3.png)

**Comment by eroux** [comment]
@ngawangtrinley wdyt?
