### ISSUE TITLE
more guidance when there are no results

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#144]
ideas taken from https://github.com/buda-base/public-digital-library/issues/131 

- [x] always display the type that has been searched on the left bar, even where there are no results
- [x] always display Person, place, work and instance on the left even when there are no results
- [x] instead of just "no results found", there should be "no result found for XXX (YYY) in ZZZ", where
   * XXX is the search string
   * YYY is the language of the search string
   * ZZZ is the type
- [x] when the search is done, make a small highlight animation on the types in the left bar that have results, in order to draw the user's attention towards them
- [x] when the user clicks in the search bar, the language selection tool should appear even without a key stroke

**Comment by berger-n** [comment]
deployed here: http://library-dev.bdrc.io/
maybe there could also be a tooltip or something saying "*start typing, possible languages will be detected automatically*"

**Comment by eroux** [comment]
ah yes, good idea! This could be appearing below the search bar when the cursor is in, using the same format as an item in the list of detected languages

**Comment by berger-n** [comment]
what do you think of updating placeholder text when searchbar has focus?
![image](https://user-images.githubusercontent.com/33383857/86613756-51761b00-bfb2-11ea-90e9-eaa2ee54586c.png)

**Comment by eroux** [comment]
I think the list of possible language on an empty string is a bit bizarre and won't really help users... why not replacing it with just one item saying "guessing language..."?

Also, "in versions" would be more helpful than "Version" I think... perhaps even with the icon? maybe that would eat too much room

**Comment by berger-n** [comment]
![image](https://user-images.githubusercontent.com/33383857/86621711-f565c380-bfbe-11ea-8680-53d8578704dc.png)

I'll try to add datatype icons tomorrow

**Comment by eroux** [comment]
oh, that doesn't work at all, sorry... what about removing the block entirely when there's no guess?

**Comment by berger-n** [comment]
![image](https://user-images.githubusercontent.com/33383857/86785490-fbad7b80-c062-11ea-8088-3903eb63dbbc.png)

![image](https://user-images.githubusercontent.com/33383857/86785537-1384ff80-c063-11ea-9101-36b666679081.png)

(http://library-dev.bdrc.io/)

**Comment by eroux** [comment]
very nice!

**Comment by berger-n** [comment]
if there are results in other data types:
![image](https://user-images.githubusercontent.com/33383857/86944499-245b7100-c148-11ea-80d3-a3e72e6af213.png)

if there are filters on:
![image](https://user-images.githubusercontent.com/33383857/86944606-48b74d80-c148-11ea-8c09-cc93326c3488.png)

(just updated [library-dev](http://library-dev.bdrc.io/search?q=%22candrakirti%22&lg=sa-x-ndia&t=Instance&s=closest%20matches%20forced))

**Comment by eroux** [comment]
excellent, thanks!
