### ISSUE TITLE
Image viewer not opening 

### ISSUE THREAD

**Issue by jeehuajian** [buda-base/public-digital-library#147]
Cant view the [scan images of the work](http://library.bdrc.io/show/bdr:W15659?s=q%3D%2522%25E0%25BD%25A6%25E0%25BE%25A4%25E0%25BE%25B1%25E0%25BD%25BC%25E0%25BD%2591%25E0%25BC%258B%25E0%25BD%25A0%25E0%25BD%2587%25E0%25BD%25B4%25E0%25BD%2582%2522%26lg%3Dbo%26t%3DInstance%26s%3D%25E0%25BD%25A2%25E0%25BE%2592%25E0%25BE%25B1%25E0%25BD%25B4%25E0%25BD%2582%25E0%25BD%25A6%25E0%25BC%258B%25E0%25BD%2586%25E0%25BD%25BA%25E0%25BC%258B%25E0%25BD%2596%25E0%25BC%258D%26n%3D1#open-viewer) even after 10 minutes. 

![image](https://user-images.githubusercontent.com/42564256/86447712-56d02d00-bd48-11ea-8aff-26b0b3f2ed4e.png)

**Comment by eroux** [comment]
hmm I can't reproduce the problem... can you indicate the steps that lead to this? also, what's your browser version (with version number) and OS?

**Comment by jeehuajian** [comment]
Steps involved. 

![002](https://user-images.githubusercontent.com/42564256/86870958-ee000080-c10b-11ea-8ad7-c74192bef1d8.gif)

Google Chrome - Version 83.0.4103.116 (Official Build) (64-bit)

**Comment by berger-n** [comment]
I can't reproduce this bug either...

could you please open the inspector and take a screenshot:
![image](https://user-images.githubusercontent.com/33383857/86908193-71beea80-c116-11ea-9693-2a6011fe3431.png)

it would also be interesting to have a look at the network tab to check if anything is red/failing to load 
(you might open tab first then reload page):
![image](https://user-images.githubusercontent.com/33383857/86908390-bc406700-c116-11ea-87ed-d92f5193b3bb.png)

**Comment by jeehuajian** [comment]
A)
![image](https://user-images.githubusercontent.com/42564256/86994698-a47de700-c1d9-11ea-8a91-d07756523980.png)

B)
![image](https://user-images.githubusercontent.com/42564256/86995208-f2dfb580-c1da-11ea-8d98-64041622788a.png)

**Comment by jeehuajian** [comment]
It was because i didnot clean the cache. I will close this issue.
