### ISSUE TITLE
allowing space between matched tokens

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#155]
When the javascript client constructs the lucene query from the user input in the search bar, instead of just surrounding it with quotes, it should also add a `~1` at the end after the quotes. So the url when searching `'phags brtsegs` would be

http://library.bdrc.io/search?q=%22%27phags%20brtsegs%22~1&lg=bo-x-ewts&t=Instance&s=closest%20matches%20forced

instead of 

http://library.bdrc.io/search?q=%22%27phags%20brtsegs%22&lg=bo-x-ewts&t=Instance&s=closest%20matches%20forced

That's going to give more results. @JannTibetan that's what we were discussing. We could even think of increasing it to 2... I haven't measured the impact on the performance, but I suspect it's very minimal.

**Comment by xristy** [comment]
There's no meaningful performance hit with small proximity values on small phrases. There needs to be some consideration regarding the _trick_ of searching for 300-400 syllable searches as are apparently used on tbrc.org to scrape etexts. I made a change a few months ago to limit the cost of such queries on tbrc.org

**Comment by eroux** [comment]
Sure. The hope is that with the new etext download system (and the new restriction that give no result for copyrighted material anyways), that kind of query will go away... but that doesn't mean we shouldn't be careful of course

**Comment by eroux** [comment]
Actually... I don't think it makes a lot of sense for languages other than Tibetan... so let's use that just for lang tags starting with "bo"
