### ISSUE TITLE
These titles look not complete. Can be improving!

### ISSUE THREAD

**Issue by tadhondup** [buda-base/public-digital-library#156]
I am not sure if it can be making look nicer no. Anyway, not look like a real title when open it. there no Shad(།) at the end. [Link](http://library.bdrc.io/show/bdr:WSBB_WKG)
![06](https://user-images.githubusercontent.com/28945342/87110525-d48cbf00-c299-11ea-8521-9ef819407c4a.gif)

**Comment by eroux** [comment]
Well, I'm sure one day @brunogml will a nice catalog of the Wenli... in the meantime that's what we got from the National Library of Berlin! Let's not open issues about data, 99% of the time it's not in the tech team's hands
