### ISSUE TITLE
Where can we translate this (Load Previous Pages)?

### ISSUE THREAD

**Issue by tadhondup** [buda-base/public-digital-library#157]
Can't find this (Load Previous Pages) to be translating. Not sure if separate words or together.
[Link](http://library.bdrc.io/show/bdr:UTIE0OPP009633_v046?startChar=445807&keyword=%22%E0%BD%A6%E0%BE%A1%E0%BD%B2%E0%BD%82%E0%BC%8B%E0%BD%94%E0%BC%8B%E0%BD%85%E0%BD%B2%E0%BC%8B%E0%BD%A1%E0%BD%84%E0%BC%8B%E0%BD%98%E0%BD%B2%E0%BC%8B%E0%BD%96%E0%BE%B1%E0%BC%8B%E0%BD%9E%E0%BD%B2%E0%BD%84%E0%BC%8B%22@bo#open-viewer)

**Comment by eroux** [comment]
I think this can be closed, please reopen if not

**Comment by tadhondup** [comment]
Yes sure.
