### ISSUE TITLE
Tibetan font resizing

### ISSUE THREAD

**Issue by jeehuajian** [buda-base/public-digital-library#167]
![005](https://user-images.githubusercontent.com/42564256/87624976-9e4cb500-c75b-11ea-8a7c-44c64819b00d.gif)
![image](https://user-images.githubusercontent.com/42564256/87625007-b15f8500-c75b-11ea-903b-953941952fa8.png)
![image](https://user-images.githubusercontent.com/42564256/87625037-c0dece00-c75b-11ea-958f-36af4d651201.png)

**Comment by berger-n** [comment]
is it ok now?
(it seems it does not use the same font on my computer)
![image](https://user-images.githubusercontent.com/33383857/89283492-8b881a80-d64d-11ea-9fa0-2a7521ad6554.png)

**Comment by jeehuajian** [comment]
Great. thank you.
