### ISSUE TITLE
Search requires re-selecting search box before executing

### ISSUE THREAD

**Issue by TBRC-pmench** [buda-base/public-digital-library#172]
When executing a search after entering the search term and selecting e.g. Wylie, the search bar requires that you place your cursor back into the search box and press enter before it will execute search. If you do not place your cursor back in the search box and simply press enter nothing will happen. This is confusing for users.

**Comment by eroux** [comment]
I'm not entirely sure what you mean... can you record a small screencast?

**Comment by TBRC-pmench** [comment]
In this screencast, I search mdzod, select Wylie, and then hit enter immediately. Nothing happens.
![Screen Recording 2020-07-21 at 4 37 13 PM](https://user-images.githubusercontent.com/48484924/88104811-fbd46d80-cb70-11ea-9f92-2e73045b61f7.gif)

In this screencast, I search mdzod, select Wylie, place my cursor back in the search box, then hit enter. The search executes.
![Screen Recording 2020-07-21 at 4 37 48 PM](https://user-images.githubusercontent.com/48484924/88104815-fd059a80-cb70-11ea-8797-c91ba107c965.gif)

This seems like something that might cause minor confusion for users.

**Comment by eroux** [comment]
oh, I see... let me guess: you're on Safari? I don't have this behavior on Firefox. @berger-n can you take a look?

**Comment by TBRC-pmench** [comment]
This is in Chrome. I just checked in Safari and didn't have the same behavior: when selecting Wylie, the search automatically executes.

**Comment by eroux** [comment]
ah, interesting... thanks!

**Comment by berger-n** [comment]
I can't reproduce this bug on Chrome (I'm using version 81.0.4044.92)
everything's fine for me:
![Kazam_screencast_00000](https://user-images.githubusercontent.com/33383857/88158008-c6c92900-cc0b-11ea-905b-4a01a33657b2.gif)

is that a new behaviour or has it been like that for some time? 

it could be useful to take a screenshot of some error message in red that would be displayed in the error console when search doesn't start after clicking on the language
for example:
![image](https://user-images.githubusercontent.com/33383857/88158371-40f9ad80-cc0c-11ea-9a43-de76b2466ddf.png)

**Comment by TBRC-pmench** [comment]
![Screen Recording 2020-07-22 at 9 32 19 AM](https://user-images.githubusercontent.com/48484924/88183014-e7d74d00-cbfe-11ea-8fb3-7efdf450280a.gif)
It doesn't seem to generate any errors. I'm running Chrome Version 83.0.4103.116 (Official Build) (64-bit). This also happened on another computer running Chrome.

I'm not sure whether it is new or not, I'm afraid. I hadn't noticed it before but another BDRC person using the site for the first time (the second computer I mentioned) got confused by this issue and asked me about it, which is when I noticed it.

**Comment by TBRC-pmench** [comment]
And, yes, I think the version was the root of the problem. Chrome just released a new update (Version 84.0.4147.89). After updating, I no longer have this issue. Let me check with the other person who was having this issue, too.
