### ISSUE TITLE
allow lower case rid match and improve UX

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#175]
the detection or RIDs in the search should:
- [ ] be extended for lower case strings matching the regexp `^([cpgwrt]|mw|wa|ws)\d[^ ]$`
- [ ] when a possible RID is detected in the search form, it should add a first `(ID)` thing in the list of languages below, and it should be the top one

**Comment by berger-n** [comment]
- detection of RID is done [here](https://github.com/buda-base/public-digital-library/blob/1bacccc63ac6b4d9120a6973fdf936d34973e942/src/components/App.js#L924)
- list of suggestions is computed [here](https://github.com/buda-base/public-digital-library/blob/1bacccc63ac6b4d9120a6973fdf936d34973e942/src/components/App.js#L4921) then displayed [here](https://github.com/buda-base/public-digital-library/blob/1bacccc63ac6b4d9120a6973fdf936d34973e942/src/components/App.js#L5032)
