### ISSUE TITLE
improving search UI

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#176]
When a user types in the search bar, there's a list of possible languages popping up below, with currently no language selected. We should make the first one selected (highlighted) and use it if the user presses enter or clicks on search without having selected a language

**Comment by berger-n** [comment]
I guess a bit of css [around here](https://github.com/buda-base/public-digital-library/blob/1c3d93a7e83d6984484ca085cc87ec831a856ffb/src/components/App.css#L268) could be enough
(`#suggestions li:first-child { ... }` or something)

which makes me think that another improvement could be to be able to select language using up/down arrows

**Comment by eroux** [comment]
the up/down arrows is a very good idea yes
