### ISSUE TITLE
small adjustments in metadata block

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#183]
http://library-dev.bdrc.io/show/bdr:MW1NPL146?tabs=bdr:W1NPL146

has two strange features:
- it doesn't display the black metadata block under the Work tab
- it does display "Provided by CUDL under the CC BY NC 3.0, etc." in the metadata block of the instance, which I believe is not correct

**Comment by berger-n** [comment]
it seems to be a data issue
- in http://purl.bdrc.io/query/graph/ResInfo-SameAs?R_RES=bdr%3AMW1NPL146&format=json
you can find:
![image](https://user-images.githubusercontent.com/33383857/89201591-03086c00-d5b2-11ea-9a52-47696edd4ea3.png)
![image](https://user-images.githubusercontent.com/33383857/89201648-1fa4a400-d5b2-11ea-8525-3e97397c5930.png)
which is then displayed as is

- comparing the Work tab with the one https://library.bdrc.io/show/bdr:WA12827?tabs=bdr:MW12827,bdr:W12827 (which shows the metadata block)
in http://purl.bdrc.io/query/graph/ResInfo-SameAs?R_RES=bdr%3AWA1NPL146&format=json there is no `adm:metadataLegal` property
whereas there is one in http://purl.bdrc.io/query/graph/ResInfo-SameAs?R_RES=bdr%3AWA12827&format=json:
![image](https://user-images.githubusercontent.com/33383857/89202014-a2c5fa00-d5b2-11ea-8bf7-5f5922fa41e1.png)

**Comment by eroux** [comment]
moved to https://github.com/buda-base/xmltoldmigration/issues/125
