### ISSUE TITLE
improve outlines

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#189]
For each node of the outlines there should be:
- [x] some properties hidden by default but accessible through a "see more" button (ex: colophon, incipit, authorship statement, notes, etc.)
- [x] IDs (objects of bf:identifiedBy) should be displayed (perhaps after the title, in upper case and semi-bold?)
- [x] seeAlso / sameAs should be displayed with the same icons as the permalink tab of the main page
- [ ] location should be displayed in the following way:
   * when there is a contentlocationstatement, it should be the only thing displayed, the properties of the contentlocation should just be in the tooltip of it
   * when there is not, keep the current display

**Comment by berger-n** [comment]
you can have a first look at IDs here: http://library-dev.bdrc.io/show/bdr:MW22084?part=bdr:MW22084_0001-1

**Comment by berger-n** [comment]
added sameAs icons ([example](https://library.bdrc.io/show/bdr:MW22084?part=bdr:MW22084_0068)):
![image](https://user-images.githubusercontent.com/33383857/89775957-2f1f7200-db09-11ea-9bce-15ea4f3bf6b4.png)

and seeAlso links ([example]()):
![image](https://user-images.githubusercontent.com/33383857/89776150-976e5380-db09-11ea-9637-d54c5d17e9b1.png)

**Comment by berger-n** [comment]
with the see more/hide button:
![image](https://user-images.githubusercontent.com/33383857/89796406-ec21c680-db29-11ea-94b7-5ee19f605628.png)

deployed here: http://library-dev.bdrc.io/show/bdr:MW22084?part=bdr:MW22084_0045

further customization might be needed regarding what exactly to show
(for now everything is hidden by default except `bdo:location` and title either of type `bdo:Title` or matching a search)

**Comment by eroux** [comment]
excellent, thanks!

**Comment by berger-n** [comment]
now the `contentLocationStatement` is displayed when available, with other `contentLocation` values in tooltip/hover

yet they seem never to match:

![image](https://user-images.githubusercontent.com/33383857/89812081-de773b80-db3f-11ea-94fe-843a86794909.png)

this is [the only work](https://library.bdrc.io/show/bdr:MW7477?part=bdr:MW7477_334ADF) (in more than a dozen found using fuseki online) where they exactly match (though there are three `locationStatement` here...) :

![image](https://user-images.githubusercontent.com/33383857/89811782-745e9680-db3f-11ea-99cd-d8a2fbf98e22.png)

this seem to come from deep in the data ([link](https://library.bdrc.io/show/bdr:MW1PD107937?part=bdr:MW1PD107937_8F319D)):

![image](https://user-images.githubusercontent.com/33383857/89812440-72490780-db40-11ea-8b11-185bd0713db5.png)

![image](https://user-images.githubusercontent.com/33383857/89812498-812fba00-db40-11ea-8121-490e02b8033c.png)

**Comment by eroux** [comment]
that's perfect, thanks! They almost never match indeed, one is the page number and the other is the image number, I need to fix the labels in the ontology
