### ISSUE TITLE
Change Tibetan on language switcher

### ISSUE THREAD

**Issue by TBRC-pmench** [buda-base/public-digital-library#190]
The language switcher on library.bdrc.io should be updated. It currently has བོད་སྐད༏ This should be changed to བོད་ཡིག༏

**Comment by eroux** [comment]
I think it should be  just བོད་ཡིག right? with no ༏

**Comment by TBRC-pmench** [comment]
Thanks. No shey. Just  བོད་ཡིག

**Comment by TBRC-pmench** [comment]
It should also be updated in the e-text viewer (if that needs to be done separately).
![image](https://user-images.githubusercontent.com/48484924/89051102-bc044780-d321-11ea-9d32-700396d6e9d0.png)

**Comment by eroux** [comment]
@ngawangtrinley wdyt? If you agree can your team make the change? Or are there cases where it should be bod skad (like for the UI language) and others where it should be bod yig (like for the search)?

**Comment by ngawangtrinley** [comment]
yes, we did it purposely to follow the language/script distinction, but it will look like a mistake to many. we already discussed this quite a bit so I can say that we're good with updating it to བོད་ཡིག

**Comment by eroux** [comment]
well, I think it makes sense to make the skad/yig distinction in the bibliographical data... the UI is a sort of separate issue yes. Thanks!
