### ISSUE TITLE
Tibetan font resizing (too small)

### ISSUE THREAD

**Issue by jeehuajian** [buda-base/public-digital-library#194]
The Tibetan in footer section looks too small too see. and the Tibetan in italic doesnt fit there. better with no font formatting.

1) Original.
![001BDRC](https://user-images.githubusercontent.com/42564256/89143225-7099a580-d57c-11ea-86d8-5acbec8d82d0.PNG)

2) Suggested changes.
![003](https://user-images.githubusercontent.com/42564256/89143231-73949600-d57c-11ea-8eda-f219f3e24709.PNG)

**Comment by berger-n** [comment]
this is how it looks now:

![image](https://user-images.githubusercontent.com/33383857/89902407-b4c51f80-dbe6-11ea-93eb-f42859e44399.png)

**Comment by jeehuajian** [comment]
looks great. thanks
