### ISSUE TITLE
missing display of noteMatch in Topics search

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#197]
https://library.bdrc.io/search?q=%22mahamudra%22&lg=en&t=Topic doesn't show any matches in the note, while they're returned in https://purl.bdrc.io/lib/typeSimpleGraph?LG_NAME=en&R_TYPE=bdo%3ATopic&L_NAME=%22mahamudra%22

**Comment by berger-n** [comment]
fixed:

![image](https://user-images.githubusercontent.com/33383857/89888087-ac151f00-dbcf-11ea-8700-ac3b81f52d02.png)

![image](https://user-images.githubusercontent.com/33383857/89888196-d8c93680-dbcf-11ea-9ec3-51015e49c267.png)

**Comment by eroux** [comment]
perfect thanks!
