### ISSUE TITLE
Add message about registration to front page

### ISSUE THREAD

**Issue by TBRC-pmench** [buda-base/public-digital-library#198]
Can we add the following message to the front page to let people know they need to create a new account?

> All users, including users with existing accounts on tbrc.org, will need to register for a free BDRC account for full access. Click on the Register link above to create a new account.

![image](https://user-images.githubusercontent.com/48484924/89223040-14e31280-d5a4-11ea-8dcb-68aef6e3f69f.png)

**Comment by berger-n** [comment]
I've just added the message, this is how it looks now:

![image](https://user-images.githubusercontent.com/33383857/89278062-e61d7880-d645-11ea-8cdd-32111ad69176.png)

I am wondering whether we should make the word "register" clickable and maybe modify the message a bit?

**Comment by TBRC-pmench** [comment]
Making the word "register" a link would be good. What did you have in mind for edits to the message? Happy to change the language if you have suggestions.

**Comment by berger-n** [comment]
`Register`s are now clickable:

![image](https://user-images.githubusercontent.com/33383857/89318037-898a7f80-d67e-11ea-9aca-c45d57e5c7a3.png)

actually the message is ok for me as is
