### ISSUE TITLE
bug/improvement in ToL results

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#199]
https://library.bdrc.io/show/bdr:P314 has a sameAs to TOL, which should appear in the permalink bar with the proper logo. Note that the URI of the same as is http, but it should be transformed in the usual way: `http://` --> `//`. Also the metadata block should have the TOL icon

**Comment by berger-n** [comment]
it works now:

![image](https://user-images.githubusercontent.com/33383857/89404803-dcb21000-d71a-11ea-80fd-0f1914bc2d09.png)

![image](https://user-images.githubusercontent.com/33383857/89404835-e9366880-d71a-11ea-89c1-f669e1b100f6.png)

I went through two data issues here though:
- `bdr:isIncarnation`  node is missing in [query](http://purl.bdrc.io/query/graph/ResInfo-SameAs?R_RES=bdr%3AP314&format=json)
- [ToL link](https://api.treasuryoflives.org/resource/TOLP2882) for [`bdr:P1583`](https://library.bdrc.io/show/bdr:P1583) does not work:
![image](https://user-images.githubusercontent.com/33383857/89405213-7ed1f800-d71b-11ea-8c36-79fcc0a86460.png)

**Comment by eroux** [comment]
perfect, thanks! I'll communicate the dead link to them
