### ISSUE TITLE
handle error on first image / thumbnail more gracefully

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#200]
See https://github.com/buda-base/archive-ops/issues/141 

On https://library.bdrc.io/show/bdr:W19974 the iiif server can't open the preview image because it asks for 

https://iiif.bdrc.io/bdr:I4230::42300003.jpg/full/1000,/0/default.jpg

but the image is less than 1000px wide... I'm only selecting images of reasonable size for thumbnails, so I'm thinking for this big thumbnail we have two solutions:
- the best one in the long term is to look at https://iiif.bdrc.io/bdr:I4230::42300003.jpg/info.json , see that `width = 827` and take the min of 827 and 1000, in that case 827
- a short term fix is to require the full version

**Comment by berger-n** [comment]
now when it fails loading the thumbnail from ResInfo it uses the manifest to fetch the right url:
![image](https://user-images.githubusercontent.com/33383857/89516642-016cbd00-d7d9-11ea-809b-09a8cf336600.png)
