### ISSUE TITLE
Translation problem due to shad"།"

### ISSUE THREAD

**Issue by jeehuajian** [buda-base/public-digital-library#201]
In english version has two "Register" with link. We try to translate but difficult to adjust as it has Shad "།" both the tibetan translation which we cant put in between the sentence. So can we have something like showed in second image?

![image](https://user-images.githubusercontent.com/42564256/89487165-5f000a00-d7d7-11ea-9d86-363e4566d98b.png)

![image](https://user-images.githubusercontent.com/42564256/89487222-835be680-d7d7-11ea-8280-f5ac10d729a0.png)

**Comment by berger-n** [comment]
I've just added two new 'register' in translation [here](https://github.com/buda-base/public-digital-library/blob/37881ba58d64ea6822ee5eb1ab68ffb1b461abc6/src/translations/en.js#L25) (distinct from the one used in topbar)
does that help?

**Comment by jeehuajian** [comment]
Great..... Problem solved. Thank you.
