### ISSUE TITLE
Cannot fix wrong email format in profile

### ISSUE THREAD

**Issue by MarcAgate** [buda-base/public-digital-library#210]
If I log in, then go to my profile, then change the email to a wrong email and click "update", then I get the message "wrong email format".
However, if I change the value to a valid email, I cannot update it since the update button is still disabled.

**Comment by berger-n** [comment]
I can't reproduce... is it on library.bdrc.io?
if i modify the email to a incorrect one I get this:
![image](https://user-images.githubusercontent.com/33383857/90018422-2ebfdc00-dcad-11ea-891a-864338505b61.png)

button is still clickable (I remember fixing this precisely)
then I change to another email and let it update:

![image](https://user-images.githubusercontent.com/33383857/90018541-5dd64d80-dcad-11ea-9a4c-d150a39aa9f0.png)

if I logout and login with this new email it works
