### ISSUE TITLE
bug on a specific page

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#211]
in https://library.bdrc.io/show/bdr:MW1KG8321?part=bdr:MW1KG8321_1C92B4&s=q%3D%2522phrin%2520las%2520rnam%2520rol%2520snying%2520po%2522~1%26lg%3Dbo-x-ewts%26t%3DInstance%26n%3D11 there's a console error that makes the website crash

**Comment by berger-n** [comment]
it is now fixed

**Comment by eroux** [comment]
thanks! a little improvement: when I go to https://library.bdrc.io/show/bdr:MW1KG8321?part=bdr:MW1KG8321_1C92B4&s=q%3D%2522phrin%2520las%2520rnam%2520rol%2520snying%2520po%2522~1%26lg%3Dbo-x-ewts%26t%3DInstance%26n%3D11

the page scrolls down a little bit but not to the text, just to the parent volume... here's what I see:

![Capture d’écran de 2020-08-12 18-09-57](https://user-images.githubusercontent.com/60868/90039568-1b216f00-dcc7-11ea-908a-55b15e0a2f11.png)

**Comment by eroux** [comment]
note that it might be due to the nature of the data, which has two locations... it's very weird and shouldn't happen, I'll fix that tomorrow

**Comment by eroux** [comment]
perfect, thanks!
