### ISSUE TITLE
case-sensitive EWTS search

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#215]
see https://github.com/buda-base/lucene-bo/issues/26 . The problem here is a bit complex: some users will want to search in EWTS but in a sort of invalid EWTS that is case-insensitive. 

For instance if they search `Dgongs pa rab gsal` (`ཌགོངས་པ་རབ་གསལ`) and find results for `dgongs pa rab gsal` (`དགོངས་པ་རབ་གསལ`). I'm reluctant to make them equivalent in the Lucene index as it's an awful lot of work and server load for little benefit... a solution I would prefer would be to essentially lower case the search in ewts in the UI unless the user does not want to. A possible UI would be:

if the query string in ewts contains an upper case letter, instead of listing just one option for wylie/ewts, we would list 2:
- `dgongs pa rab gsal` (lower case, wylie)
- `Dgongs pa rab gsal` (wylie)

(in that order, the default being to lower case). If the user chooses the first option, the query is lower cased when passed in the URL, etc.

**Comment by berger-n** [comment]
done:
![image](https://user-images.githubusercontent.com/33383857/90271468-278b0080-de5c-11ea-8601-87cc29381492.png)

**Comment by eroux** [comment]
excellent! do you display it also when there is no upper case letter in the search? (we shouldn't I think)

**Comment by berger-n** [comment]
no:

![image](https://user-images.githubusercontent.com/33383857/90272953-789bf400-de5e-11ea-880a-be894e182d32.png)

**Comment by eroux** [comment]
excellent! perfect
