### ISSUE TITLE
empty outlines shouldn't be displayed

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#218]
For instance on https://library.bdrc.io/show/bdr:MW0IA_HOD13 , also, when the root instance is queried (like in this case), there's no reason to scroll down to the outline)

**Comment by berger-n** [comment]
no outline there anymore:

![image](https://user-images.githubusercontent.com/33383857/90234213-99912480-de1f-11ea-96cf-da57897207f2.png)
