### ISSUE TITLE
"thob yig" search finds bdr:T192 but "gsan yig" doesn't

### ISSUE THREAD

**Issue by xristy** [buda-base/public-digital-library#22]
at [Library](http://library.bdrc.io/) a search for ``gsan yig`` returns no results whereas for ``thob yig`` the results include [bdr:T1902](http://library.bdrc.io/show/bdr:T192)

<img width="580" alt="screen shot 2018-10-09 at 9 53 59 am" src="https://user-images.githubusercontent.com/3542294/46678034-5aea0d80-cba9-11e8-8d67-f5dd128addcc.png">

**Comment by berger-n** [comment]
first it should be noted that http://purl.bdrc.io/lib/rootSearchGraph?LG_NAME=bo-x-ewts&I_LIM=500&L_NAME=%22gsan%20yig%22 unexpectedly fails

still I think searching for `thob yig` can and should display `thob yig` here
as it is a `prefLabel` of `bdr:T192` and is already returned by the query http://purl.bdrc.io/lib/rootSearchGraph?LG_NAME=bo-x-ewts&I_LIM=500&L_NAME=%22thob%20yig%22 :
![image](https://user-images.githubusercontent.com/33383857/46680059-850ef000-cbe8-11e8-9a58-f554d8765089.png)

**Comment by berger-n** [comment]
thanks to https://github.com/BuddhistDigitalResourceCenter/lds-pdi/issues/93 a search for [gsan yig](http://library.bdrc.io/search?q=%22gsan%20yig%22&lg=bo-x-ewts&t=Topic) now has results:
![image](https://user-images.githubusercontent.com/33383857/46880278-83436780-ce48-11e8-8007-e162e708f8fe.png)

I also fixed the code to make results display the right label:
 ![image](https://user-images.githubusercontent.com/33383857/46880147-2c3d9280-ce48-11e8-8ee1-415d49e91648.png)
