### ISSUE TITLE
UI in viewer seems stuck on Tibetan

### ISSUE THREAD

**Issue by TBRC-pmench** [buda-base/public-digital-library#225]
The navigation in the viewer only displays in Tibetan.

![image](https://user-images.githubusercontent.com/48484924/90289999-0d94f200-de4b-11ea-827b-c7f1bca8d7cb.png)

**Comment by berger-n** [comment]
it's fixed:

![image](https://user-images.githubusercontent.com/33383857/90543692-5bc92e80-e186-11ea-9c09-0ee89f32d801.png)

![image](https://user-images.githubusercontent.com/33383857/90544072-e4e06580-e186-11ea-8933-205b679df664.png)

**Comment by eroux** [comment]
closing, @TBRC-pmench don't hesitate to reopen if you're still experiencing it
