### ISSUE TITLE
need to be able to reset "Refine Search"

### ISSUE THREAD

**Issue by xristy** [buda-base/public-digital-library#23]
When visiting the [library](http://library.bdrc.io/) the left hand menu will display a list of all possible resource types that can be searched for:

<img width="1137" alt="screen shot 2018-10-09 at 9 17 15 am" src="https://user-images.githubusercontent.com/3542294/46678175-b1efe280-cba9-11e8-9353-f7bd64df70e3.png">

However, after a search the list is narrowed to just the types of results, but there is no obvious way to issue a new search and make a restriction on the types without clearing the address bar and visiting [library](http://library.bdrc.io/) fresh or having a bookmark or similar:

<img width="1141" alt="screen shot 2018-10-09 at 9 19 01 am" src="https://user-images.githubusercontent.com/3542294/46678315-fed3b900-cba9-11e8-97d6-e0a5a3fc563a.png">

There needs to be some approach to resetting the refine menu / clearing search results

**Comment by berger-n** [comment]
+1
definitely
will do
