### ISSUE TITLE
can't open viewer in some outline nodes

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#230]
On https://library.bdrc.io/show/bdr:MW1KG8321?part=bdr:MW1KG8321_1C92B4 when I click on "view scans", the page changes url, scrolls up a bit, but then nothing happens

**Comment by berger-n** [comment]
I think this can come from the fact that there are no `canvases` in the `sequences` in the corresponding manifest https://iiifpres.bdrc.io/wvo:bdr:MW1KG8321_1C92B4::bdr:I1KG8360/manifest

**Comment by eroux** [comment]
about that, see https://github.com/buda-base/buda-iiif-presentation/issues/93

**Comment by eroux** [comment]
see also https://github.com/buda-base/archive-ops/issues/145
