### ISSUE TITLE
Request: on work records imported from NGMCP, please supply URL to the record on the NGMCP site

### ISSUE THREAD

**Issue by JannTibetan** [buda-base/public-digital-library#234]
http://purl.bdrc.io/resource/WA0NGMCP45418 

This isn't urgent but at some point can we provide links to the original records on the NGMCP site? Alternatively can we display more of the NGMCP data. It is very detailed (ex., https://catalogue.ngmcp.uni-hamburg.de/receive/aaingmcp_tbtdocument_00059493)

**Comment by eroux** [comment]
they're present in the instance (ex: https://library.bdrc.io/show/bdr:MW0NGMCP45418 ) but not on the work. i'll add them on the works too. Note that here there's something bizarre as the work and the instance are not linked... thanks for noticing!

**Comment by JannTibetan** [comment]
Yes, I figured that the issue a matter of a bug and not some weird decision to offer very limited metadata. Thanks for fixing this.

**Comment by JannTibetan** [comment]
One more thing, our person record for sgam po pa should override the "has creator" field when they add a correction (for the sake of being able to link back to the broader database).

<img width="775" alt="Screen Shot 2020-08-24 at 10 59 12 AM" src="https://user-images.githubusercontent.com/44705185/91060405-e7184900-e5f8-11ea-9da5-95ae6d0eec28.png">

**Comment by eroux** [comment]
yes, I noticed that, this is quite a strange record you found... should be easy to fix

**Comment by eroux** [comment]
@berger-n actually the hasCreator should be a link as the data is there:

```ttl
bdr:MW0NGMCP45418_AAC a bdo:AgentAsCreator ;
    rdfs:label "chos rje <sic corr=\\\"dwags\\\">dags</sic> po lha rje/"@bo-x-ewts ;
    bdo:agent bdr:P1844 ;
    bdo:role bdr:R0ER0019 .
```

I'll remove the xml markup which doesn't look great... can you add the link?

**Comment by eroux** [comment]
@JannTibetan  if you open https://library.bdrc.io/show/bdr:WA0NGMCP45418 in a browser which didn't cache the page (like in a private browsing window) you should see an update, it looks better now... (otherwise the cache is 6h long)
