### ISSUE TITLE
associated resources doesn't seem to work

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#236]
https://library.bdrc.io/search?r=bdr:PR1CTC17&t=Instance

doesn't even trigger an ldspdi query

**Comment by berger-n** [comment]
works better now:
![image](https://user-images.githubusercontent.com/33383857/91327896-73c43200-e7c6-11ea-8015-e6359b0c7be2.png)

but this resource does not seem to exist: https://purl.bdrc.io/query/graph/ResInfo-SameAs?R_RES=bdr%3APR1CTC17&format=json

**Comment by eroux** [comment]
perfect, thanks! the rest will be handled in the queries

**Comment by eroux** [comment]
well, sorry, it was `bda:` and not `bdr:` hence your query finding nothing... but now https://library.bdrc.io/search?r=bda:PR1CTC17&t=Instance still doesn't work
