### ISSUE TITLE
display number of translations per parallel

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#237]
It's kind of a new UI pattern (which is quite annoying and time consuming unfortunately), but we need to display the number of translations per parallel, somewhere after the title. For instance currently we have

`has parallel in : foo`

what we want is something like:

`has parallel in : foo (X translations)`

A good example is https://library.bdrc.io/show/bdr:WA4CZ16799 the number of translations is in the query: https://purl.bdrc.io/query/graph/ResInfo-SameAs?R_RES=bdr%3AWA4CZ16799&format=json (property `tmp:nbTranslations`).

see also https://github.com/buda-base/lds-queries/issues/46

**Comment by berger-n** [comment]
done:

![image](https://user-images.githubusercontent.com/33383857/91565598-bf9be600-e942-11ea-8b07-46b6b85fce95.png)

**Comment by eroux** [comment]
wonderful, thanks!
