### ISSUE TITLE
adding latest syncs on the front page

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#239]
There's a new query to get just the latest synced image instances:

http://purl.bdrc.io/query/graph/latestsyncssince?D_SINCE=2020-08-20T00:00:00

I made it using a similar format as the related works in ResInfo, so that it's (hopefully) easy to use as a basis for the same ui. The main difference is that these will eventually have thumbnails, although not yet... in the meantime the fallback icon (instead of the thumbnail) can be the images icon.

**Comment by eroux** [comment]
P.S.: the date in argument of the query could be set to one or two weeks before the current time, but always at midnight (so that the query can be properly cached)

**Comment by berger-n** [comment]
WIP on http://library-dev.bdrc.io:

![image](https://user-images.githubusercontent.com/33383857/91878483-a6b36d80-ec7f-11ea-857b-dd54ebf4251a.png)

**Comment by eroux** [comment]
Wonderful, thanks!

**Comment by TBRC-Travis** [comment]
Excellent!  Looks great.  Thank you for adding this.

**Comment by berger-n** [comment]
with thumbnails now:
![image](https://user-images.githubusercontent.com/33383857/92258768-4dde1200-eed7-11ea-848c-346acebeec4d.png)
thanks @eroux for the query!

**Comment by eroux** [comment]
this is great!

**Comment by TBRC-Travis** [comment]
Very cool.  Wonderful way to highlight newly released works.  Looks great.

**Comment by xristy** [comment]
It does look very nice. Anyway to raise it up towards the top? Less border width around the "Welcome"?

**Comment by eroux** [comment]
The next phase is ready, see

http://ldspdi.bdrc.io/lib/iinstanceSyncedIn?D_START=2020-08-20T00:00:00&D_END=2020-08-27T00:00:00

basically it's a query that should be called with an interval that is constant during one day (so that we can cache things properly, like the `latestSyncsIn` query), I think it can be a 7 days interval.

The results are in the same format as the instanceFacetGraph so it should work directly. The main difference is that there is another sorting order which is tmp:lastSync, which should do from latest to oldest, and should be the default.

**Comment by eroux** [comment]
I added a hack in http://purl.bdrc.io/query/graph/latestsyncssince?D_SINCE=2020-09-01T00:00:02 so that you can display the total number of syncs in the last 7 days on the front page without making another query... So I think the title should be "New scans this week", and the link to the proper search should be "see all XXX" where XXX is the total

**Comment by berger-n** [comment]
some interesting WIP on http://library-dev.bdrc.io/:

![image](https://user-images.githubusercontent.com/33383857/92763559-f555bb80-f393-11ea-9609-8bf2546b6d9c.png)

---
on http://library-dev.bdrc.io/latest:


![image](https://user-images.githubusercontent.com/33383857/92763664-10283000-f394-11ea-8115-e6ec7026f79d.png)

(you might need to login to actually see all the 12 image instances)

**Comment by eroux** [comment]
A little bug: in the query for the main list, the upper boundary of the dates is not good. For instance it currently searches

http://purl.bdrc.io/lib/iinstanceSyncedIn?D_START=2020-09-05T00%3A00%3A00&D_END=2020-09-12T00%3A00%3A00&format=json

so all syncs until last midnight. The thing is, the sync scripts is triggered after midnight... and there shouldn't be any sync in the future anyways, so having today +1 day (or even 2) at midnight would be better.

**Comment by eroux** [comment]
(just fixed it)

**Comment by berger-n** [comment]
this is now on homepage: https://library.bdrc.io/

**Comment by eroux** [comment]
This is really great, thanks a lot!
