### ISSUE TITLE
Move the language label on Works

### ISSUE THREAD

**Issue by JannTibetan** [buda-base/public-digital-library#241]
The current placement of the language field is far from the text it applies to. Please put above the Parallels field, perhaps even under "variant label"
<img width="709" alt="Screen Shot 2020-08-31 at 9 41 27 AM" src="https://user-images.githubusercontent.com/44705185/91726413-310bac80-eb6e-11ea-8504-6ae39f3a4186.png">

**Comment by berger-n** [comment]
is it better like this?

![image](https://user-images.githubusercontent.com/33383857/91748351-267a0300-ebc0-11ea-93d3-4275debe918c.png)

**Comment by JannTibetan** [comment]
Yes, I believe so. Thanks.
