### ISSUE TITLE
PDF corrupted W1PD107142

### ISSUE THREAD

**Issue by TBRC-pmench** [buda-base/public-digital-library#243]
The file that downloads for W1PD107142 is corrupted.

![Screen Recording 2020-09-01 at 11 19 44 AM](https://user-images.githubusercontent.com/48484924/91872117-81a20900-ec45-11ea-9290-23317754d9b5.gif)

**Comment by xristy** [comment]
I think the issue is not peculiar to W1PD107142. W22084 and W12827 seem to also exhibit the issue:

[I0916_1-0.pdf](https://github.com/buda-base/public-digital-library/files/5157557/I0916_1-0.pdf)


[I2061_1-0.pdf](https://github.com/buda-base/public-digital-library/files/5157559/I2061_1-0.pdf)

**Comment by eroux** [comment]
Ah, I heard something like that was happening at some point but couldn't reproduce it, it's very useful to have the corrupted PDFs, thanks! I think it's just that they're empty, not really corrupted... @MarcAgate can you take a look?

**Comment by eroux** [comment]
one obvious improvement would be to issue a 404 instead of an empty PDF (like we do with manifests), another improvement is to see what's going on... I suspect it's another case where the AWS library says the `dimensions.json` doesn't exist while it clearly does... very annoying... let's first try to update the aws library too.

**Comment by TBRC-Travis** [comment]
For what's worth, I've noticed this issue intermittently as well.  The PDFs do seem to load just fine on the legacy site so it's something to do with the new implementation, not something wrong with the images themselves.

**Comment by eroux** [comment]
yes, the images are fine... actually the PDF generation from the images is fine, the weak spot is the dimensions.json... but I really can't understand why

**Comment by eroux** [comment]
should be fixed, it was an error in the iiif server

**Comment by TBRC-pmench** [comment]
Works for me now.
