### ISSUE TITLE
wiring associated instances

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#250]
there's a new query "associatedInstances" that lists instances associated with anything (as opposed to: instances of works associated with anything):

http://purl.bdrc.io/lib/associatedInstances?R_RES=bdr:G1657

The main use case is instances associated with a printery, it's the tab "litterary production" of https://www.tbrc.org/#!rid=G1657. I think if we just wire it to the instances type of associated resources people will be a little confused... but I can't see any better way at the moment and I think this would be an improvement nonetheless so let's do it. We'll improve the UI later.

**Comment by berger-n** [comment]
everything already seems fine with the results: http://library-dev.bdrc.io/search?r=bdr:G1657&t=Instance
regarding the place record, we could adapt the "Related Works" block
someting like:
![image](https://user-images.githubusercontent.com/33383857/95214968-bc710100-07f0-11eb-9675-d375d477651e.png)
but with "Related Resources" and "Works" / "Instances" tabs?

**Comment by eroux** [comment]
yes, that's a very good solution!

**Comment by berger-n** [comment]
see http://library-dev.bdrc.io/show/bdr:G1657

![image](https://user-images.githubusercontent.com/33383857/95235229-e84ab180-0805-11eb-8578-bb308fe0931d.png)

note something requested some time ago,
add resource title to tabs: http://library-dev.bdrc.io/show/bdr:P1583

![image](https://user-images.githubusercontent.com/33383857/95235871-6c049e00-0806-11eb-831b-e45f2b2e2a44.png)

(about https://github.com/buda-base/lds-queries/commit/3d41fcc9a6949697a8e11a5b52ead48f0fba4da4
I'm wondering whether to sort `printedAt` Instances by corresponding Work `entityScore`?
query is ready in fuseki)

**Comment by eroux** [comment]
perfect, thanks a lot!! It would probably be best to sort by something yes, just so that the results are not changing all the time

**Comment by berger-n** [comment]
ok
I'll also check to be sure whether this score is actually used when displaying Related Resources
and why not add arrows to view more related resources from within the page? 
(like latest syncs on homepage)

**Comment by eroux** [comment]
ah sure, arrows would be good too!

**Comment by berger-n** [comment]
now with arrows: http://library-dev.bdrc.io/show/bdr:G1657

![image](https://user-images.githubusercontent.com/33383857/95775680-2727ae00-0cc3-11eb-90aa-2b233f195abe.png)

BTW score was missing in query (a typo) see https://github.com/buda-base/public-digital-library/commit/6764d20fbd90c70d0677dd5906c22f6dc8811bad in `master`
do you think it can be merged in `dev` branch as is? so as to be available on `ldspdi-dev` I guess

**Comment by eroux** [comment]
ah sure, I think we're good to merge yes. Thanks for the arrows!
