### ISSUE TITLE
opening "relation type" by default

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#251]
In associated resources results (like https://library.bdrc.io/search?r=bdr:P9963&t=Work&pg=1&f=language,inc,bdr:LangInc ), the "relation type" facet group should be open by default. There should  be a generic way to do so as there may be other groups we want open by default... Note that this group only exists in associated search so it can be always open

**Comment by berger-n** [comment]
an extra field in `config.json` would work:
```js
   "facets-open":[
      "relation", // not restricted by type, always open when available
      { 
         "types": [ "Work" ], // only open when search type is Work
         "facets": [ "tree" ]
      }
   ],
```
we may think of an "associated search only" flag if needed

**Comment by eroux** [comment]
works for me

**Comment by berger-n** [comment]
done
see https://library.bdrc.io/search?r=bdr:P9963&t=Work&pg=1&f=language,inc,bdr:LangInc
![image](https://user-images.githubusercontent.com/33383857/93324717-8efaee00-f816-11ea-9497-389dd861805a.png)

**Comment by eroux** [comment]
great, thanks!
