### ISSUE TITLE
trimming search value

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#252]
The text input by the user in the search bar should be trimmed before being processed. A symptom of the problem is that if you start your search with a space, it doens't find much of anything, for instance

```
 'gos chos grub
```

(with a space at the beginning) has 0 results in person, while the version with no space at the beginning has 1. I don't think there's any case where a space is relevant at the beginning or end of the search so we should remove them.

**Comment by berger-n** [comment]
done
if you type "  'gos chos grub  " it removes spaces at start/end before starting search and returns 1 person

**Comment by eroux** [comment]
wonderful, thanks!
