### ISSUE TITLE
missing provenance information for event properties

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#253]
In https://library.bdrc.io/show/bdr:P8LS68062 there's a merge of two sources: bdr:P8LS68062 and http://api.treasuryoflives.org/resource/TOLP13634 , and the event displays the two information correctly, but without indicating what date comes from what source. For instance on the TOL event I'm getting:

![Capture d’écran de 2020-09-16 09-08-50](https://user-images.githubusercontent.com/60868/93303985-9ad9b680-f7fc-11ea-8ffa-a19035e1732d.png)

(note that I'm going to adjust the TOL data so it might need to be reproduced on another entity)

**Comment by eroux** [comment]
I've fixed the TOL data and the problem is still visible so that's good, there are two other issues:
- when displaying a `xsd:gYear`, the initial `0` should be removed
- same year values should be merged (there should be only one value, with two sources). This is probably the most difficult part as this means having a sort of function to check if two events are "the same"

**Comment by berger-n** [comment]
some progress here:

![image](https://user-images.githubusercontent.com/33383857/93363325-5e7f7800-f847-11ea-9df7-7a4f39806221.png)

![image](https://user-images.githubusercontent.com/33383857/93363372-6d662a80-f847-11ea-88ed-53c8d9db12a5.png)

using fuseki to find more example of that kind of data I found https://library.bdrc.io/show/bdr:P1650 
where some event information lacks of source tagging as well

then the case of source tagging names/titles (which currently are not, I'm afraid) leads to additional complexity
looking at https://library.bdrc.io/show/bdr:P8LS68062?cw=none (with data from sameAs hidden) it comes that *Go Chodrub* is `:OtherName` in `bdr` record but `PrimaryName` in `tol` record (see [data from query](https://purl.bdrc.io/query/graph/ResInfo-SameAs?R_RES=bdr%3AP8LS68062))
should they be merged or not? is type of name significant or a given label is considered "same" even in two different types on name?

**Comment by eroux** [comment]
excellent, thanks! that looks great

hmm, interesting question for merging the OtherName/PrimaryName... I think it's a flaw in the data more than a technical problem (what's the difference between primary, personal and other name ? I'm not sure there's any interesting one...). I'll open a separate issue for that (on another repo), you can display them separately for now

**Comment by berger-n** [comment]
I've just added provenance on person names as well: http://library-dev.bdrc.io/show/bdr:P8LS68062
![image](https://user-images.githubusercontent.com/33383857/94589177-3cddb200-0285-11eb-8b41-c0a2593ab173.png)

I was wondering about merging names such as "Go Chodrub/" & "Go Chodrub" (both are `:OtherName`)
but first one is `bo-x-ewts` and second one is `english`
so I think I won't

**Comment by eroux** [comment]
no indeed no need to merge them. Looks perfect, thanks a lot!
