### ISSUE TITLE
opening an outline node when highligted in the outline

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#254]
when a user reaches https://library.bdrc.io/show/bdr:MW6493?part=bdr:MW6493_CF203E , they see the info the title but not the children nodes, and in order to see them they need to click on the title, which is fairly unintuitive... it would be best to open open the node when we display the info

**Comment by berger-n** [comment]
done

![image](https://user-images.githubusercontent.com/33383857/93475738-4831f480-f8f9-11ea-8ce6-b331cc2bbe21.png)

**Comment by eroux** [comment]
great, thanks!
