### ISSUE TITLE
indicating provider in instance list in work record

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#256]
for instance in https://library.bdrc.io/show/bdr:WA4CZ16799

Maybe something is missing from the query, if that's the case I'll add it

**Comment by berger-n** [comment]
added provider icon on top of thumbnails:

![image](https://user-images.githubusercontent.com/33383857/96885765-31943580-1483-11eb-9d61-588e19182181.png)

**Comment by eroux** [comment]
oh, very nice thanks!
