### ISSUE TITLE
improving provenance data display

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#257]
Here are a few ideas:
- the little hover that appears on the i should appear on hover on the whole gray area
- the big popup that appears when clicking the i should appear when clicking the gray area? (I'm not so sure actually... we can give it a try)
- the big popup should stay at the same place on the page instead of staying at the same place on the screen (when I scroll down/up on Firefox the popup stays while what it's attached to moves)

**Comment by berger-n** [comment]
- not finished yet but you can already try clicking on the gray area in the Variant Labels of http://library-dev.bdrc.io/show/bdr:P1583 (in left column there's a placement bug I would need to fix)
- big popup is now moving with the scroll

**Comment by berger-n** [comment]
see http://library-dev.bdrc.io/show/bdr:P1583
big popup now behaves well in every case [edit: needs some more debug when click is in a left column and window is less than 1600px]
you can also try to click on gray area in Teachers/Students (on hover cursor becomes a question mark or something)

**Comment by eroux** [comment]
very nice, thanks!

**Comment by berger-n** [comment]
now the provenance tooltip is shown when mouse hovers over gray area:
(works on all properties but Note/Event/PersonName for now)
![image](https://user-images.githubusercontent.com/33383857/94150984-1fba7500-fe7a-11ea-8f5c-53aafbb4c087.png)

**Comment by eroux** [comment]
excellent, thanks!

**Comment by berger-n** [comment]
I think we're good here
let's merge this and deploy on library?

**Comment by eroux** [comment]
yes, that would be good! I noticed that on library the extended properties are closed by default, can we also deploy #263 ?

**Comment by berger-n** [comment]
sure (it's in the same branch)

**Comment by berger-n** [comment]
done: https://library.bdrc.io/show/bdr:MW12827

![image](https://user-images.githubusercontent.com/33383857/94674807-06ea0d80-0319-11eb-91c9-7ef89a60c88f.png)

**Comment by eroux** [comment]
excellent, thanks!
