### ISSUE TITLE
"log in" need to move to the end of the sentence

### ISSUE THREAD

**Issue by jeehuajian** [buda-base/public-digital-library#259]
"log in" does not fit in middle of sentence in Tibetan sentence structure. So can we have something like show in second image where the "log in" at end of the sentence.

![image](https://user-images.githubusercontent.com/42564256/93839589-0968b980-fcc0-11ea-9255-99ba682dbaf2.png)

**Comment by berger-n** [comment]
is it ok like this?

![image](https://user-images.githubusercontent.com/33383857/94292528-62a14900-ff5d-11ea-869e-81b7b09256ee.png)

**Comment by jeehuajian** [comment]
> is it ok like this?
> 
> ![image](https://user-images.githubusercontent.com/33383857/94292528-62a14900-ff5d-11ea-869e-81b7b09256ee.png)
