### ISSUE TITLE
Need to add space

### ISSUE THREAD

**Issue by jeehuajian** [buda-base/public-digital-library#260]
Need to add space in between those two in the red box. [link to the site](https://library.bdrc.io/)

![image](https://user-images.githubusercontent.com/42564256/93840425-eb508880-fcc2-11ea-9e06-a39ab5a0e4b3.png)

**Comment by berger-n** [comment]
done:
![image](https://user-images.githubusercontent.com/33383857/94293577-c1b38d80-ff5e-11ea-92bd-00501f306d91.png)
