### ISSUE TITLE
thumbnail for a specific reproduction

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#261]
currently (because of historical reasons) the thumbnail displayed for a reproduction is the thumbnail of the main instance, which works when there's only one reproduction but I'm importing cases where we have several, for instance

http://library-dev.bdrc.io/show/bdr:MW0NGMCP57499

I've added the thumbnails for the reproductions in

http://purl.bdrc.io/query/graph/ResInfo-SameAs?R_RES=bdr%3AMW0NGMCP57499&format=json

(we currently only have the images for one so there's just one thumbnail but the rest will come)

**Comment by berger-n** [comment]
not sure to understand this one...
what is to fix?

**Comment by eroux** [comment]
here:

![Capture d’écran de 2020-09-23 19-23-52](https://user-images.githubusercontent.com/60868/94047497-766c7400-fdd2-11ea-8f06-53c5e5d2490d.png)

the same thumbnail is used for the 3 image instances, but they should have different thumbnails

**Comment by eroux** [comment]
in the same area of the code: when I go to 

https://library.bdrc.io/show/bdr:MW3CN1302?tabs=bdr:W3CN1302

and look at the network tabs, I see that there's a request on the collection and manifest on iiifpres... the thumbnails are present in the code so I think we should avoid these calls

**Comment by berger-n** [comment]
this is now fixed: https://library.bdrc.io/show/bdr:MW0NGMCP57499
![image](https://user-images.githubusercontent.com/33383857/94159479-e4bd3f00-fe83-11ea-824a-0eda67972eff.png)

**Comment by eroux** [comment]
perfect, thanks!

**Comment by berger-n** [comment]
regarding the manifest/collection request, it's actually needed to know whether the "Open Viewer" side menu button is disabled or not...

**Comment by eroux** [comment]
Ah, I see! Interesting case... we can optimize that by having it always enabled on the openaccess instances... I'll open a separate issue for that but it's not really urgent, closing this one

**Comment by eroux** [comment]
I'm not sure what the logic of the implementation is, but I think it should find the thumbnail of 

https://library.bdrc.io/show/bdr:MW0NGMCP39309

should be able to find the thumbnail. in 

https://purl.bdrc.io/query/graph/ResInfo-SameAs?R_RES=bdr%3AMW0NGMCP39309&format=json

there is `bdr:MW0NGMCP39309` hasReproduction `bdr:W0NGMCP39309` and `bdr:MW0NGMCP39309` has a thumbnail...

**Comment by berger-n** [comment]
it seems to work now:

![image](https://user-images.githubusercontent.com/33383857/94448083-cec4bc80-01aa-11eb-98af-6504459e0a4f.png)

**Comment by eroux** [comment]
yes perfect, thanks!
