### ISSUE TITLE
multiple bdrc icons in metadata

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#262]
This is kind of an edge case, but on http://library-dev.bdrc.io/show/bdr:MW0NGMCP57499 several entities in the bdrc database are merged. Generally speaking it works fine, except for the metadata legal info block that has 3 bdrc logos on the same line where one would be enough

**Comment by berger-n** [comment]
works fine now: https://library.bdrc.io/show/bdr:MW0NGMCP57499

**Comment by eroux** [comment]
great, thanks!
