### ISSUE TITLE
extended information should be open by default

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#263]
the title of this issue should be straightforward enough

**Comment by berger-n** [comment]
done
see http://library-dev.bdrc.io/show/bdr:MW22084
I kept notes and identifiedBy still closed by default but any comment welcome

**Comment by eroux** [comment]
thanks! I think you can just open everything... I guess this will need a small redesign though, as the long line with the arrow at the end makes it very difficult to read

**Comment by berger-n** [comment]
done for the open everything part
do you have something in mind about the redesign? 
I'm not sure I see what you mean about the long line with the arrow at end

**Comment by eroux** [comment]
Thanks! The problem is made quite explicit in this screenshot of the URL above:

![Capture d’écran de 2020-09-23 19-25-59](https://user-images.githubusercontent.com/60868/94047713-c3504a80-fdd2-11ea-990d-3a2e7c439e2b.png)

Here what's on the left column is vertically aligned with a horizontal line, and the value it corresponds to is below this horizontal line, which makes it very difficult to read
