### ISSUE TITLE
products are back in the bdr: namespace

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#265]
for instance bda:PR1CTC17 is now bdr:PR1CTC17. Also they are called "Collections" now instead of products. Other than that there's no difference

**Comment by berger-n** [comment]
see https://library.bdrc.io/show/bdr:PR1CTC17 and https://library.bdrc.io/search?r=bdr:PR1CTC17&t=Scan&s=title
changed translation to "Collection" (the same we did for Instance --> Version )
I also updated the icon to "C"

there is something I don't understand though
`typeSimpleGraph` query over Products does not have results anymore on `ldspdi`: http://ldspdi.bdrc.io/lib/typeSimpleGraph?LG_NAME=en&R_TYPE=adm%3AProduct&L_NAME=%22tbrc%22~1
but it stille has on `ldspdi-dev`:http://ldspdi-dev.bdrc.io/lib/typeSimpleGraph?LG_NAME=en&R_TYPE=adm%3AProduct&L_NAME=%22tbrc%22~1

would there be something else that needs updating?

**Comment by eroux** [comment]
Yes, sorry, the type is now `bdo:Collection`, see http://ldspdi.bdrc.io/lib/typeSimpleGraph?LG_NAME=en&R_TYPE=bdo%3ACollection&L_NAME=%22tbrc%22~1 I should have been more specific. Thanks for the support, it looks great!

**Comment by berger-n** [comment]
search in collections works now as well:  https://library.bdrc.io/search?q=%22tbrc%22&lg=en&t=Product&s=title
