### ISSUE TITLE
allow search on type (under certain conditions)

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#270]
Some types don't have a lot of individuals and it would be reasonable to allow direct search, one of them is `bdo:SerialWork`. I naively tried https://library.bdrc.io/search?r=bdo:SerialWork&t=Work but it does nothing (doesn't trigger an API call). I'm wondering if we could allow that to happen? That would make a nice list of all the series we have. OTOH, we really don't want people to do that with `bdo:Work` as it would crash everything... so I suspect there must be safeguards with everything that starts with `bdo:`, perhaps a white list...

**Comment by berger-n** [comment]
it now has results: https://library.bdrc.io/search?r=bdo:SerialWork&t=Work
