### ISSUE TITLE
series indication in search results

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#271]
For instance in https://library.bdrc.io/search?q=%22sata%20pitaka%22&lg=en&t=Work&s=closest%20matches%20forced it would be good to distinguish the regular works from the `bdo:SerialWork`s (which is a subtype of Work). They should be indicated with "series" in the rectangle instead of "work"... and maybe have a different icon? For now let's not worry about the icon

**Comment by berger-n** [comment]
done: 
![image](https://user-images.githubusercontent.com/33383857/94042345-be3bcd00-fdcb-11ea-85df-69fe7b015936.png)

(we could need a new icon for Product/Collection as well...)

**Comment by eroux** [comment]
great! Yes, we'll have to design these indeed... I'll open an issue for a next design mission
