### ISSUE TITLE
provider icon too large in some results

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#274]
see the rKTs icon in

https://library.bdrc.io/search?q=%22saddharmapundarika%22&lg=sa-x-ndia&t=Work

**Comment by berger-n** [comment]
fixed:
![image](https://user-images.githubusercontent.com/33383857/94129874-36ea6a00-fe5c-11ea-8374-4340ea4bd9fa.png)

**Comment by eroux** [comment]
perfect, thanks!
