### ISSUE TITLE
"images not yet available" message

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#276]
on image instances (such as https://www.tbrc.org/#!rid=W2KG5019 for now), we should have a message "images not yet availble"

**Comment by berger-n** [comment]
do you mean that https://iiifpres.bdrc.io/vo:bdr:I2KG212666/manifest returning 
```
"status": 500,
"code": 5001,
"message": "io.bdrc.iiif.presentation.exceptions.BDRCAPIException: resource not found",
"link": null,
"developerMessage": "java.util.concurrent.ExecutionException: io.bdrc.iiif.presentation.exceptions.BDRCAPIException: resource not found(...)"
```
should be interpreted as "images not yet available" ?

**Comment by eroux** [comment]
hmmm... yes and no, I'll change that to a 404, which you can interpret as an absence of images

**Comment by eroux** [comment]
done

**Comment by eroux** [comment]
(note that on a 500 we could have an error message like "an error occured while trying to access the images")

**Comment by berger-n** [comment]
ok thanks!

**Comment by berger-n** [comment]
done
see https://library.bdrc.io/show/bdr:W2KG5019
![image](https://user-images.githubusercontent.com/33383857/94175845-8a2dde00-fe97-11ea-827c-4854eabc509b.png)
