### ISSUE TITLE
Sanskrit + Pali = Indic

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#277]
I'm not entirely sure we're going to keep this feature, but let's give it a try:
- we now have:
   * `inc-x-iast` that queries over `sa-x-iast` + `pi-x-iast`
   * `inc-x-ndia` that queries over `sa-x-ndia` + `pi-x-ndia` (well it's not actually true but it will soon)
- there's a request to use Indic in the list of possible search languages instead of having Sanskrit and Pali

let's try and replace *Sanskrit (Lenient)* and *Pali (Rom)* by *Indic (Sskt, Pali, Lenient)* which will lead to a search in `inc-x-ndia`. The language detection is the same as Sanskrit in romanization (that currently leads to *Sanskrit (Lenient)*).

**Comment by berger-n** [comment]
seems to be quite straightforward from the client point of view: 
![image](https://user-images.githubusercontent.com/33383857/94253186-3a95f380-ff25-11ea-9f1b-2067404fca29.png)

noted a few minor bugs in the queries results:

- in Person search http://purl.bdrc.io/lib/personGraph?LG_NAME=inc-x-ndia&L_NAME=%22manjusri%22 there is an empty `nameMatch`:
![image](https://user-images.githubusercontent.com/33383857/94252692-9318c100-ff24-11ea-8146-717c2fa91d19.png)

- in Version search http://purl.bdrc.io/lib/instanceFacetGraph?LG_NAME=inc-x-ndia&L_NAME=%22manjusri%22 there are Etexts in the results:
![image](https://user-images.githubusercontent.com/33383857/94253063-0cb0af00-ff25-11ea-93f7-51b5929c9a21.png)

do you want me to push it to library-dev as is?

**Comment by eroux** [comment]
yes! etext instances are fine, no problem. I noticed the empty label match too, it's a bit weird... I'll take a closer look

**Comment by berger-n** [comment]
here it is: http://library-dev.bdrc.io/search?q=%22manjusri%22&lg=inc-x-ndia&t=Instance
(library-dev currently still configured to use ldspdi not ldspdi-dev)
