### ISSUE TITLE
Possible search results issue (Deb ther dMar po)

### ISSUE THREAD

**Issue by TBRC-pmench** [buda-base/public-digital-library#279]
I observed potentially aberrant behavior with search results for Deb ther dMar po. 

I get different search results in Safari and in Chrome, with two resources in Safari appearing greyed out with "status editing" warnings. Chrome search results look different.

Safari: https://share.getcloudapp.com/mXu6RYzA
Chrome: https://share.getcloudapp.com/RBuW6mvp

**Comment by eroux** [comment]
are you logged in under Safari and not Chrome perhaps? editing records are not shown to non-admin users
