### ISSUE TITLE
wrong work tab when there is no work

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#283]
in some rare cases, an instance has no work, for instance in:

https://library.bdrc.io/show/bdr:MW6493_CF25E9

(in that case it's an error but still). In these cases there should be no work tab instead of the work tab of the root instance

**Comment by berger-n** [comment]
fixed
there is now a difference between opening record from https://library.bdrc.io/show/bdr:MW6493?part=bdr:MW6493_CF25E9 (no work tab)
and from https://library.bdrc.io/show/bdr:MW6493?part=bdr:MW6493_D76DB3 (work tab)

**Comment by eroux** [comment]
excellent, thanks!
