### ISSUE TITLE
image group record display

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#284]
on image group records such as http://library-dev.bdrc.io/show/bdr:I1KG9186 there needs to be two changes:
- when there's no image, there should be the image icon in the yellow header
- when there are images they should be displayed just like they are on an image instance. The URI for iiifpres can be the one of the manifest directly, in that case https://iiifpres.bdrc.io/vo:bdr:I1KG9186/manifest

**Comment by berger-n** [comment]
done: http://library-dev.bdrc.io/show/bdr:I1KG9186

![image](https://user-images.githubusercontent.com/33383857/95102878-37c0ad00-0734-11eb-83b1-e3328fb57b04.png)

it should also work when there is no image but I don't know where to find such a Volume, do you?

**Comment by eroux** [comment]
excellent, thanks! http://library-dev.bdrc.io/show/bdr:I4CZ75273 has no images and works well
