### ISSUE TITLE
mirador reading view / etexts

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#285]
When browsing a volume of http://library-dev.bdrc.io/show/bdr:W4CZ7445 in the mirador reading view, I get a lot of calls to URLs like

- https://ldspdi.bdrc.io/lib/ChunksByPage?R_RES=bdr:UTIE0OPP000542_v108&I_START=351&I_END=370

even when I don't have the etext open. These shouldn't be called when the etext is not displayed

**Comment by berger-n** [comment]
I think code was not up to date on library-dev regarding this point
it is now
there is only one call to `ChunksByPage` for 20 pages:

![image](https://user-images.githubusercontent.com/33383857/95062722-a5051b80-06fd-11eb-912b-a9c514a02184.png)

is it ok like this?

**Comment by eroux** [comment]
no sorry, there should be no call at all. The problem is that if you scroll down in the reading view the images take forever to load because of this

**Comment by berger-n** [comment]
etext is now fetched only when displayed: http://library-dev.bdrc.io/view/bdr:I1KG9868

**Comment by eroux** [comment]
wonderful, thanks!!
