### ISSUE TITLE
chinese mirror links to CBETA

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#286]
On the Chinese mirror (which should be a variable in the configuration), the links starting with 

```
https://cbetaonline.dila.edu.tw
```

should be replaced by links starting with

```
http://cbetaonline.cn
```

the rest of the URL is the same. Note the difference between http and https.

**Comment by berger-n** [comment]
added a `chineseMirror` boolean parameter in `config.json`
temporarily set to `true` on library-dev, see the links: 

- in  [search results](http://library-dev.bdrc.io/search?q=%22%E5%A6%99%E6%B3%95%E8%93%AE%E8%8F%AF%E7%B6%93%22&lg=zh-hant&t=Work)
![image](https://user-images.githubusercontent.com/33383857/95079526-0980a480-0717-11eb-918e-89b213b4c2ad.png)

-in  [record page](http://library-dev.bdrc.io/show/bdr:WA0TTET0262?s=q%3D%2522%25E5%25A6%2599%25E6%25B3%2595%25E8%2593%25AE%25E8%258F%25AF%25E7%25B6%2593%2522%26lg%3Dzh-hant%26t%3DWork%26s%3Dclosest%2520matches%2520forced%26n%3D1)
![image](https://user-images.githubusercontent.com/33383857/95079574-1d2c0b00-0717-11eb-810b-7927776d814b.png)

**Comment by eroux** [comment]
excellent, thanks!
