### ISSUE TITLE
add links to SAT and CBETA in the Taisho outline

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#288]
in the outline of https://library.bdrc.io/show/bdr:MW0TT0000 it would be good to have all the links to CBETA and SAT. I'm just opening the issue to track it but it might require some changes in the data or queries...

**Comment by eroux** [comment]
@berger-n this one should be doable now, I've added the necessary seeAlso in the outline nodes

**Comment by berger-n** [comment]
it's online now: https://library.bdrc.io/show/bdr:MW0TT0000?part=bdr:MW0TTT0001

![image](https://user-images.githubusercontent.com/33383857/97207671-910f7f80-17ba-11eb-8ff0-e444130452d8.png)

another example here: https://library.bdrc.io/show/bdr:MW0NGMCPMTM1284?part=bdr:MW0NGMCP38891

![image](https://user-images.githubusercontent.com/33383857/97208892-f152f100-17bb-11eb-8b23-7c734e1b32d2.png)

yet looking back at https://github.com/buda-base/public-digital-library/issues/189
there used to be `sameAs` links here: https://library.bdrc.io/show/bdr:MW22084?part=bdr:MW22084_0068
it seems that data is still here https://purl.bdrc.io/resource/MW22084_0068.ttl
but not returned by query anymore https://purl.bdrc.io/query/graph/Outline_root?R_RES=bdr%3AMW22084_S0009

**Comment by eroux** [comment]
thanks! looks ok to me, @JannTibetan is that satisfactory?

**Comment by JannTibetan** [comment]
More than satisfactory! The Taisho outline looks very polished and even stylish (great color choices). The parallel links are working great as well. In particular I like that the Tibetan and Sanskrit title/links are clearly distinguished. 
My one new request is for you guys to look into deactivating the parallel field when there is no parallel (either within the Taisho or to texts in other languages). This is especially an issue in the first section of the Taisho, i,.e., Agamas.
<img width="1357" alt="Screen Shot 2020-10-26 at 7 36 09 PM" src="https://user-images.githubusercontent.com/44705185/97239645-83f68e80-17c2-11eb-87e7-ed3b3bef18f3.png">

**Comment by JannTibetan** [comment]
The NGMPP outline and pop-up links are fantastic as well. Great job gentlemen

**Comment by eroux** [comment]
Ah, it's in the data, I'll fix that

**Comment by eroux** [comment]
done
