### ISSUE TITLE
handling missing volumes in mirador

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#289]
see https://github.com/buda-base/library-issues/issues/296#issuecomment-704968947

volume 69 of http://library-dev.bdrc.io/show/bdr:W4CZ7445 is missing and

http://iiifpres-dev.bdrc.io/vo:bdr:I1KG9936/manifest?continuous=true

correctly returns a 404, in that case instead of "loading manifest..." we should display "images not available"

**Comment by berger-n** [comment]
done: http://library-dev.bdrc.io/view/bdr:W4CZ7445?lang=bo-x-ewts

![image](https://user-images.githubusercontent.com/33383857/95361759-70e05500-08cd-11eb-8f11-c293191f5a47.png)

**Comment by TBRC-Travis** [comment]
looks pretty good.  IMHO it would also be nice to replace the "404" with the BDRC icon as well.

**Comment by eroux** [comment]
Yes, 404 is kind of bizare... looks like the 90s

**Comment by TBRC-Travis** [comment]
:P

**Comment by berger-n** [comment]
now with a few changes:

![image](https://user-images.githubusercontent.com/33383857/95447879-be5ad180-0962-11eb-8cd8-98647a346a26.png)

**Comment by eroux** [comment]
perfect, thanks!
