### ISSUE TITLE
wrong link on outline nodes with no title

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#293]
In

https://library.bdrc.io/show/bdr:MW1KG13607

if you open the section *dkon btsegs*, you'll see that one of the nodes doens't have a title and instead of the title there's the ID, which is not unreasonable. The problems is that unlike on other nodes, when you click on this title, you go to the record directly instead of staying in the outline. That shouldn't happen.

Also, when there's no title is it possible to replace by a string that can be translated? Something like `[no title]` would do (with the square brackets).

**Comment by berger-n** [comment]
*et voilà*:

![image](https://user-images.githubusercontent.com/33383857/95861612-fa76a380-0d61-11eb-9ef7-c8880f342c50.png)

it also opens/closes like other nodes

**Comment by eroux** [comment]
excellent, thanks!
