### ISSUE TITLE
Display of birth-death dates on person records

### ISSUE THREAD

**Issue by JannTibetan** [buda-base/public-digital-library#295]
The search results for person records conveniently shows the birth-death dates of every person (when known). That info doesn't appear in the full person records though. Instead you see the dates for all of the major rites of passage, including birth and death, but never a simple presentation of the their "year of birth _hyphen_  year of death." Can we add a field for that? Additionally may I request we put it immediately under the H1 name. It's important to put the dates at the very top because some lamas have so many names and titles that it takes up an entire screen, thereby forcing people to scroll down just to discover the year of birth. Thanks
http://purl.bdrc.io/resource/P169

**Comment by eroux** [comment]
Good idea yes!

**Comment by eroux** [comment]
Note that a problem of P169 (already on [tbrc.org](https://www.tbrc.org/#!rid=P169)) is that the record has duplicate data, for instance the event of 1764 is recorded twice. @karmagongde maybe this is something that could be fixed?

**Comment by berger-n** [comment]
done:

![image](https://user-images.githubusercontent.com/33383857/96120485-dbf1e300-0eee-11eb-99d5-d6f41453baeb.png)

should be 100% similar to what is displayed in results: https://library.bdrc.io/show/bdr:P707

![image](https://user-images.githubusercontent.com/33383857/96120742-4d319600-0eef-11eb-8162-302752b5e16c.png)

**Comment by JannTibetan** [comment]
Thank you gentlemen

**Comment by eroux** [comment]
yes, perfect!
