### ISSUE TITLE
improving thumbnails in collection view

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#296]
in https://library.bdrc.io/view/bdr:W4CZ45313 some of the thumbnails of the volumes have a few problems:
- it seems the first canvas is taken, but when some pages are missing, the canvas is empty (no image), so there are a few solutions:
   * get the "thumbnail" value of the manifest instead of the first canvas (when available, that would be best)
   * (if there's no thumbnail) get the first canvas that has the URL in the `startCanvas` property of the main sequence
- also, maybe we could try to use a version of the thumbnail that's 246px high, so that they're a bit smaller

**Comment by berger-n** [comment]
done:
![image](https://user-images.githubusercontent.com/33383857/96286236-5cdcd780-0fe0-11eb-9a84-b5d178957dfb.png)

now it uses manifest thumnail then first canvas which id is in `startCanvas` 
and thumbs are 246px high
