### ISSUE TITLE
bug in some volumes in mirador

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#297]
When I visit https://library.bdrc.io/view/bdr:W1KG13607 then click on the first volume (with the dev tools open), I get this kind of view:

![Capture d’écran de 2020-10-18 10-13-00](https://user-images.githubusercontent.com/60868/96362014-96215e80-112a-11eb-80b9-48ad5aa65cea.png)

where:
- the images never load
- the images are actually never requested if I look at the network tab
- there's no particular error in the console
- if I try to debug the javascript, nothing happens except always the same timer, every 100ms, but nothng in between
- even after a few minutes nothing happens

so I don't really know what's going on but it seems like some function is not called...

**Comment by berger-n** [comment]
should be ok now

**Comment by berger-n** [comment]
now pagination is rendered when an image is loaded
so it doesn't lag anymore when initialising reading view

**Comment by eroux** [comment]
Thanks! Now the labels for missing images aren't working anymore though: https://library.bdrc.io/view/bdr:I3CN1304

**Comment by eroux** [comment]
also, I'm a bit curious as so what lines of code are taking such a long time to execute... is it the jquery line? or some filters? it seems to me that all of this should be more or less instantaneous even if we do it for all the images at once...

**Comment by berger-n** [comment]
labels for missing images are back:

![image](https://user-images.githubusercontent.com/33383857/96612686-58752f00-12fe-11eb-96c3-68ba15eb1182.png)

(from the tests I've just made the bottleneck here seems to be the language selection/ordering function: https://github.com/buda-base/public-digital-library/blob/master/src/lib/transliterators.js#L108 )

**Comment by eroux** [comment]
excellent, thanks! It's quite an important function and one with impact on performance so let's handle it well... I'll open an issue for that separately
