### ISSUE TITLE
improving thumbnail IIIF fetching

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#300]
Instead of calling URLs like `/full/,145/0/default.jpg` and have an alternative when it fails, we could instead call URLs like `/full/!2000,145/0/default.jpg` that never fail. The value `2000` is a bit random but should work in most cases... perhaps it could be even greater to account for FEMC palm leaves which are very large... an example of this type of URL:

https://iiif.bdrc.io/bdr:I3733::37330621.tif/full/!2000,145/0/default.png

**Comment by eroux** [comment]
ah thanks! I think the mirador thumbnails are fine, I was thinking more of the thubmnails in the general website (which doesn't have information on the size of the original image

**Comment by berger-n** [comment]
no problem I've updated this as well

**Comment by eroux** [comment]
I think we could put the back in place?

**Comment by eroux** [comment]
let's see if it works well with the IIIF servers of our partners, but an idea that I got from the Leiden manifests could also be to use `pct:50`, so that we get the image scaled half... it's not as good as the `!145` but in case it can't work on some IIIF servers that could be an alternative

**Comment by berger-n** [comment]
done
I've checked all IIIF servers and I'm not sure what to do now:
- some seem to work fine:
  - SAT: https://candra.dhii.jp/iipsrv/iipsrv.fcgi?IIIF=/taisho/01/01_0001.tif/full/!2000,145/0/default.jpg
  - LUL: https://iiif.universiteitleiden.nl/iiif/2/hdl%3A1887.1%2Fitem%3A1646861/full/!2000,145/0/default.jpg
  - CUDL: https://images.lib.cam.ac.uk/iiif/MS-ADD-01326-000-00001.jp2/full/!2000,145/0/default.jpg
  - LOC: https://tile.loc.gov/image-services/iiif/service:asian:asianscd:2018305008:0001/full/!2000,145/0/default.jpg
- some others seem not to take care of parameters:
  - EAP: https://images.eap.bl.uk/EAP676/EAP676_12_2/0.jp2/full/!2000,145/0/default.jpg
  - SBB: https://content.staatsbibliothek-berlin.de/dc/3376911134-0005/full/!2000,145/0/default.jpg
- one fails:
  - IA: https://iiif.archivelab.org/iiif/rashodgson68$1/full/!2000,145/0/default.jpg

**Comment by eroux** [comment]
Arf, that's depressing... https://github.com/ArchiveLabs/iiif.archivelab.org/issues/52

But well... let's revert to the previous state, and thanks a lot for testing!

**Comment by berger-n** [comment]
is it ok to keep using the "!2000,145" syntax for thumbnails at iiif.bdrc.io and use ",145" for external thumbnails?
this is what I just did

**Comment by eroux** [comment]
that's perfect!!
