### ISSUE TITLE
disclaimer on OCR texts

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#301]
On the resource pages of OCR etext versions, and also those of etexts there should be a disclaimer reading:

```
These etexts were created through OCR (optical character recognition), not manually input, and have not been edited. OCR for Tibetan script is not 100% perfect but it is accurate enough to create text that will enhance the BDRC database. We hope that etexts like these improve the discoverability and usefulness of the BDRC archive for you.
```

The way to discriminate an OCR from an input etext is... hmm, a bit clumsy at the moment, let me fix that first, I'll track progress here

**Comment by eroux** [comment]
so, the method is whether there is `?rid bdo:contentMethod bdr:ContentMethod_OCR` where `?rid` is the etext instance, like [bdrIE0OPP000471](http://purl.bdrc.io/resource/IE0OPP000471.ttl)

**Comment by JannTibetan** [comment]
Great. Please let me know once the disclaimer goes live. Thanks

**Comment by berger-n** [comment]
here it is: https://library.bdrc.io/show/bdr:IE0OPP000471

![image](https://user-images.githubusercontent.com/33383857/97323558-371dc100-1871-11eb-97d8-9c1add8d6bdf.png)

**Comment by JannTibetan** [comment]
Wonderful. Thanks.
