### ISSUE TITLE
crash when visiting outline node record

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#304]
see https://library.bdrc.io/show/bdr:MW1KG9258_215FAF

**Comment by berger-n** [comment]
it's fixed for the crash
now i'll check why manifest is restricted but there was no `adm:access` property available

**Comment by eroux** [comment]
hmm strange, the access in [W1KG9258](http://purl.bdrc.io/graph/W1KG9258.ttl) is `AccessRestrictedByTbrc`

**Comment by berger-n** [comment]
updated query so that root instance `access` is now available in outline nodes: https://library.bdrc.io/show/bdr:MW30287_515313

![image](https://user-images.githubusercontent.com/33383857/97344395-f92c9700-1888-11eb-94a7-bc2110828a49.png)
