### ISSUE TITLE
eText tab gets stuck and doesn't switch to Scans after viewing scans

### ISSUE THREAD

**Issue by JannTibetan** [buda-base/public-digital-library#305]
Today I opened a version record and was presented with the option of viewing both an etext and scans. I first looked at the etexts and then navigated back to the record via the "return to buda" link. I then clicked to view the scans and then again returned to the record via the "return to buda" link. However when I reached the version record this time the third tab was still set to etexts (see image). Can this be fixed so that it automatically switches to whichever media was most recently viewed?
<img width="980" alt="Screen Shot 2020-10-27 at 12 53 28 PM" src="https://user-images.githubusercontent.com/44705185/97349807-4f3c1300-1866-11eb-8953-cad60f8e5359.png">

**Comment by berger-n** [comment]
I think this is ok now
see https://library.bdrc.io/show/bdr:MW28811
if you click the etext tab then the version tab, the etext tab is still there ;
if you open the scans record then click the version tab, the scans tab is still there ;
if you open viewer then "return to BUDA", the scans tab is still there ;
if you click the work tab then click the other version, there is no etext tab.

**Comment by berger-n** [comment]
just noticed this: https://library.bdrc.io/show/bdr:IE3JT13307

**Comment by berger-n** [comment]
can anybody reproduce? I can't myself...

**Comment by berger-n** [comment]
duplicate etext tab is now fixed
(it was used as instance when loading work then as etext when opening etext record)

**Comment by eroux** [comment]
wonderful, thanks!
