### ISSUE TITLE
filter "root" instance vs. outline nodes

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#307]
This can be done easily by checking the presence of the `inRootInstance` property. Ideally there should be a "version type" facet, always open when searching in versions, with two values that can be checked:
- standalone
- part of another version

This has a pretty high priority

**Comment by berger-n** [comment]
done: https://library.bdrc.io/search?q=%22spyod%20%27jug%22&lg=bo-x-ewts&t=Instance

![image](https://user-images.githubusercontent.com/33383857/97441721-4eb88080-1929-11eb-90ef-177e7ca0345f.png)

**Comment by eroux** [comment]
excellent! can we put it first in the left bar?

**Comment by berger-n** [comment]
yes indeed:

![image](https://user-images.githubusercontent.com/33383857/97454749-639c1080-1937-11eb-9c7a-2ed0f62202b3.png)

**Comment by eroux** [comment]
perfect, thanks! I don't know if it's easy and sorry for being picky, but can we have "Standalone" first?

**Comment by berger-n** [comment]
it is due to global behaviour of sorting according to number of occurrence
do you wish to change that?

**Comment by eroux** [comment]
maybe not now, I guess it creates more noise in the code for little benefit, let's not do that... thanks a lot!
