### ISSUE TITLE
missing display of matches on notes when searching person

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#308]
ex: on https://library.bdrc.io/search?q=%22ngag%20dbang%20blo%20bzang%22&lg=en&t=Person there are matches in the notes (as seen in the [json](https://purl.bdrc.io/lib/personGraph?LG_NAME=bo-x-ewts&L_NAME=%22ngag%20dbang%20blo%20bzang%22~1)) but they're not displayed

**Comment by berger-n** [comment]
fixed: http://library-dev.bdrc.io/search?q=%22ngag%20dbang%20blo%20bzang%22&lg=en&t=Person

![image](https://user-images.githubusercontent.com/33383857/97586990-31ec7d80-19fb-11eb-8071-cfc4a253c60f.png)

**Comment by eroux** [comment]
ah thanks, that's much better!
