### ISSUE TITLE
adjustments for the ZJU server

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#309]
Two things:
- when the configuration says "in China", links to bdrc.io (in about us and in the logo) should be disabled
- we should introduce a new configuration option to disable login/registering, which we'll use on the Chinese mirror

**Comment by berger-n** [comment]
you can test on http://library-dev.bdrc.io/
(no link to bdrc in header - what about footer Contact, Donate etc.?)
BTW removing "auth" section in config file disables/hides everything

**Comment by berger-n** [comment]
regarding latest syncs
we should also disable it shouldn't we?
at least when there are no result like now http://buda.zju.edu.cn/ldspdi/query/graph/latestsyncssince?D_SINCE=2020-10-21T00%3A00%3A00&format=json

**Comment by eroux** [comment]
ah, right, good idea yes!

I think the Donate button could disappear for now yes... contact too

**Comment by eroux** [comment]
@berger-n the [configuration](http://buda.zju.edu.cn/config.json) doesn't have an "auth" section, but I think it displays the login, etc. nonetheless... (although it's super slow now so I'm not sure)

**Comment by eroux** [comment]
ah, sorry, it removes the buttons in the header indeed! Maybe the report was about the messages like the copyright or restricted warning messages?

**Comment by berger-n** [comment]
now there is not notification nor icon about access type anymore
see [search results](http://library-dev.bdrc.io/search?q=%22gsung%20%27bum/%20ngag%20dbang%20blo%20bzang%20rgya%20mtsho/%22&lg=bo-x-ewts&t=Instance) or [fair use record](http://library-dev.bdrc.io/show/bdr:W3CN22340)

yet it was difficult to find data to test... 
it seems that something has changed
there used to be all kind of access type here: https://library.bdrc.io/search?q=%22spyod%20%27jug%22&lg=bo-x-ewts&t=Instance&pg=1&f=asset,exc,tmp:hasOpen)

**Comment by eroux** [comment]
Thanks! I didn't mean such a dramatic change, we can keep the messages, the icons, etc. I just meant removing the links in the messages. But it's not that urgent, let's just revert to the previous state for now. Also, can we remove the donate button?

**Comment by eroux** [comment]
also the whole yellow and black parts of the footer on the home page should go

**Comment by berger-n** [comment]
made some updates here: http://library-dev.bdrc.io/
- removed donate and footer 
- added back access messages and icons

**Comment by eroux** [comment]
great thanks! can we also either have a separate configuration for not displaying the "new syncs this week" or disable it through the Chinese mirror option?

**Comment by berger-n** [comment]
there are now hidden (according to `config.chineseMirror` value)

**Comment by eroux** [comment]
great, thanks!

**Comment by eroux** [comment]
Sorry, reopening... For the Chinese mirror the ontology should be fetched on `/ldspdi/ontology/data/json` instead of http://purl.bdrc.io/ontology/data/json . There's a configuration already for the location of ldspdi, it can be used for that

**Comment by berger-n** [comment]
it's done

**Comment by eroux** [comment]
thanks!

**Comment by eroux** [comment]
Two more things:
- [ ] In China we shouldn't display the paragraph starting with "All users, including users with existing accounts..." on the home page (in any language)
- [ ] we also don't want to display any map (Google Maps is blocked anyways, so let's not try to load it)

**Comment by berger-n** [comment]
done, see : http://library-dev.bdrc.io/?uilang=zh

![image](https://user-images.githubusercontent.com/33383857/97853712-c5be9200-1cf8-11eb-931a-afa0b43c2121.png)

and: http://library-dev.bdrc.io/show/bdr:G1654?uilang=zh

![image](https://user-images.githubusercontent.com/33383857/97853793-e25aca00-1cf8-11eb-8b74-04034e043a21.png)

**Comment by eroux** [comment]
excellent, thanks!
