### ISSUE TITLE
Version does not appear in the Work tab

### ISSUE THREAD

**Issue by JannTibetan** [buda-base/public-digital-library#310]
This might be an isolated case but in case it's not I want to mention it here. http://purl.bdrc.io/resource/MW3PD1002 is an edition of the CW of Khyentse Wangpo. This edition is fully represented in the Version and Scans tabs of this record but is absent in the Work tab. The Work tab gives the names and thumbnails of 2 other versions of this work but not this edition (the Dzongsar Edition).

**Comment by eroux** [comment]
hmm, interesting, can you take a screenshot and give the version of the browser you're using? Here's what I see:

![Capture d’écran de 2020-10-28 18-16-38](https://user-images.githubusercontent.com/60868/97472157-d0b8a180-1949-11eb-809b-7ce7e73343f4.png)

**Comment by JannTibetan** [comment]
OK I think this is a similar case to Issue #227 in the sense that there is always one less item appearing. There are 3 Sungbums for Jamyang Khyentse but only 2 appear in the work tab. Here's another example: https://www.tbrc.org/#!rid=P423 shows 5 Sungbums in faceted search but BUDA shows me 4. 
<img width="869" alt="Screen Shot 2020-10-28 at 1 17 00 PM" src="https://user-images.githubusercontent.com/44705185/97472358-25dfbd80-1920-11eb-9eb4-4bb7b424d18f.png">
<img width="914" alt="Screen Shot 2020-10-28 at 1 18 35 PM" src="https://user-images.githubusercontent.com/44705185/97472376-2a0bdb00-1920-11eb-897a-907e2d4afcfc.png">

**Comment by JannTibetan** [comment]
I'm using the most recent version of Safari
<img width="686" alt="Screen Shot 2020-10-28 at 1 19 44 PM" src="https://user-images.githubusercontent.com/44705185/97472554-545d9880-1920-11eb-9da2-cf322b2e3d0f.png">

**Comment by JannTibetan** [comment]
I tried to replicate the issue on Firefox and it didn't replicate - everything was working fine on Firefox.

**Comment by eroux** [comment]
ok thanks!

**Comment by berger-n** [comment]
seems to be fixed:

![image](https://user-images.githubusercontent.com/33383857/97871256-81d98600-1d14-11eb-9814-31bc4f81ae15.png)

**Comment by eroux** [comment]
excellent, thanks!
