### ISSUE TITLE
Highlighting of search string on search results page (an inconsistency)

### ISSUE THREAD

**Issue by JannTibetan** [buda-base/public-digital-library#312]
The main text field isn't highlighted and this seems to be an issue only with person records.
<img width="644" alt="Screen Shot 2020-10-28 at 6 09 45 PM" src="https://user-images.githubusercontent.com/44705185/97502075-c649d800-1948-11eb-9e2b-859349e823e4.png">

Not a problem with instances, [for example](https://library.bdrc.io/search?q=%22དགོངས་པ་རབ་གསལ་%22~1&lg=bo&t=Instance)

**Comment by berger-n** [comment]
it seems to be fixed now: https://library.bdrc.io/search?q=%22chos%20blo%20gros%22~1&lg=bo-x-ewts&t=Person

![image](https://user-images.githubusercontent.com/33383857/97590559-08cdec00-19ff-11eb-90d1-c757f9381758.png)
