### ISSUE TITLE
static pages

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#313]
We need that for the Chinese server but we'll need that at some point for the main server too... The idea would be the following:

The route `/static/xxx/yyy` would read `public/static/xxx/yyy.lt.html` where `lt` is the lang tag of the ui. A fallback mechanism should probably be implemented... and then the page is just displayed in the main block, with nothing in the left bar.

**Comment by berger-n** [comment]
![image](https://user-images.githubusercontent.com/33383857/97989218-836f8080-1dde-11eb-84bd-63f637e153f7.png)

http://library-dev.bdrc.io/static/test/hello

(files are here: https://github.com/buda-base/public-digital-library/tree/master/public/static/test)

loads the file using the locale: http://library-dev.bdrc.io/static/test/hello?uilang=bo
fallback to English if locale not available: http://library-dev.bdrc.io/static/test/hello?uilang=fr
redirect to home if nothing found: http://library-dev.bdrc.io/static/test/hallo

**Comment by eroux** [comment]
excellent, thanks! The first use will be an "about" page for the Chinese mirror. The Content will be static, I'll send it to you as soon as I have it. It will be linked to from a "about us" link in the header. It would be best if it had some parts of the website, like the header, the general css, etc.

**Comment by berger-n** [comment]
almost ready: http://library-dev.bdrc.io/static/test/hello/

![image](https://user-images.githubusercontent.com/33383857/98714150-d4581980-2388-11eb-8cc3-74daf5cd6a94.png)

what about the route: `/static/about/bdrc`?

**Comment by berger-n** [comment]
it's done: http://library-dev.bdrc.io/static/about?uilang=zh

![image](https://user-images.githubusercontent.com/33383857/98943675-22d3f800-24f0-11eb-8ab5-4afa8f5be5a0.png)

**Comment by eroux** [comment]
excellent, thanks a lot! can you plug it on the about us button on the Chinese server?

**Comment by berger-n** [comment]
actually it already is I think: http://library-dev.bdrc.io/
can you confirm?

**Comment by eroux** [comment]
ah yes, thanks! the transition is kind of brutal (at least in my browser, it goes back to a completely grey page, then it rerenders everything from scratch)... I'm wondering if there might be a way to improve that?

**Comment by berger-n** [comment]
I think I already fixed that too... ;-)

![Kazam_screencast_00001 mp4](https://user-images.githubusercontent.com/33383857/98948130-574ab280-24f6-11eb-9065-492f7d61759a.gif)

**Comment by eroux** [comment]
it's more apparent when you click on the BUDA or New Search from the about page

**Comment by berger-n** [comment]
(works much better now)

**Comment by eroux** [comment]
ah yes, excellent, thanks!
