### ISSUE TITLE
missing Chinese translations

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#314]
the "in XXX" where XXX is a type (like "in versions") is not translated in Chinese anymore when the UI is switched to zh

**Comment by eroux** [comment]
also, when searching with the UI in Chinese (and thus Tibetan Unicode as the main language for results in Tibetan, as opposed to Wylie):

![Capture d’écran de 2020-10-29 14-27-33](https://user-images.githubusercontent.com/60868/97580423-91468f80-19f3-11eb-92ae-7fbfb27fa8a6.png)

**Comment by berger-n** [comment]
not perfect but better: http://library-dev.bdrc.io/search?q=%22mi%20la%20ras%20pa%22&lg=bo-x-ewts&t=Instance&f=asset,inc,tmp:hasOpen

![image](https://user-images.githubusercontent.com/33383857/97611361-615cb380-1a16-11eb-9e47-5dc679e73d8a.png)

"Note" needs a translation (`bdo:biblioNote` in `prop`, see https://github.com/buda-base/public-digital-library/blob/0846b56bd19a8e4c82f323e706c03dfc8b3cd0ce/src/translations/en.js#L169)

**Comment by eroux** [comment]
thanks, better indeed! I'll complete the bo and zh files tomorrow. I think the best would be to have a workflow where each time we add a translation in en, we add it (in English) in the other languages, that way it's obvious what needs to be translated. I'll make a small python script to do that though, should be easy enough
