### ISSUE TITLE
fixing the logic for etext page / image correspondence

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#317]
When I visit

https://library.bdrc.io/show/bdr:UTIE0OPP008105_v001#open-viewer

or 

https://library.bdrc.io/show/bdr:I4CZ75258#open-viewer and open the etext

the image and etext are completely off. I think it's because we've taken a few shortcuts that were OK at some point but aren't anymore, especially with the new pagination. Here's the correct way to get the correspondence:

1. get the image list for the volume, in that case on https://iiifpres.bdrc.io/il/v:bdr:I4CZ75258

2. to have the etext page to iiif canvas correspondence, do:
- for image X
- take the (X-1)th element of the image list for the volume
- take the filename value of this element
- construct the iiif canvas from there

In our case, if you want the iiif image for image number 4 of the OCR (`@#/_/_rgyagar skad da sa`), take 3rd element of the list (starting at index 0 of course): 

```
{"width":2550,"height":786,"filename":"I4CZ752580004.jpg"}
```

extract the filename `I4CZ752580004.jpg` and get the canvas: `https://iiifpres.bdrc.io/v:bdr:I4CZ75258/canvas/I4CZ752580004.jpg` or the image service directly: `https://iiif.bdrc.io/bdr:I4CZ75258::I4CZ752580004.jpg`

3. for the image to text this is a little bit more complex because we're querying etexts by image range, but it's still manageable if we just query several ranges if necessary. The idea is the following:
- in the manifest, parse the image number in the label (`i. 4` is image number 4)
- this is the etext page that must be printed

**Comment by berger-n** [comment]
seems to be much better now: 

- http://library-dev.bdrc.io/view/bdr:I4CZ75258

![image](https://user-images.githubusercontent.com/33383857/97744324-4a39c680-1ae7-11eb-9635-ae752a2fb00a.png)

---

- http://library-dev.bdrc.io/show/bdr:UTIE0OPP008105_v001#open-viewer

![image](https://user-images.githubusercontent.com/33383857/97744465-8ff68f00-1ae7-11eb-826a-093d9278d190.png)

we could also use the (multiple) image label(s) in the etext view, shouldn't we?

**Comment by eroux** [comment]
great, thanks a lot!!!

Well... ideally yes we could use the labels, but in the case of the etext viewer it's not particularly trivial... so let's not do that now. Thanks again!

**Comment by eroux** [comment]
well, actually if it's just the labels we could get them from the manifest, it wouldn't be too difficult... but then ideally we would handle reordering of images at the etext level, and that's a completely different story

**Comment by berger-n** [comment]
I've just fixed loading images after etext is scrolled to bottom, when next pages are reloaded (which was not working here: http://library-dev.bdrc.io/show/bdr:UTIE0OPP008105_v001#open-viewer)

at first I was testing using https://library.bdrc.io/show/bdr:UTIE0OPP006627_v002#open-viewer where I limited width to 3500px BTW

yet it was really difficult to tell if image and etext are really corresponding...
in this volume https://library.bdrc.io/show/bdr:UTIE0OPP006627_v001#open-viewer images are not too bad quality
so i'm not sure if it is due to average/bad results from OCR or if pages/images are messed up

**Comment by eroux** [comment]
hmm... this OCR is very bizarre indeed! I'll report it to OpenPecha

**Comment by berger-n** [comment]
ok! thanks
