### ISSUE TITLE
small vertical offset bug 

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#318]
in the titles of etexts in the latest Firefox (82.0.2):

![Capture d’écran de 2020-10-30 11-24-53](https://user-images.githubusercontent.com/60868/97694445-de356f00-1aa2-11eb-9a30-925caafa4543.png)

**Comment by berger-n** [comment]
fixed: https://library.bdrc.io/show/bdr:UTIE0OPP008105_v001

![image](https://user-images.githubusercontent.com/33383857/97700237-c7474a80-1aab-11eb-8ce8-ace662cbad5a.png)

**Comment by eroux** [comment]
wonderful, thanks!
