### ISSUE TITLE
replacing the UI language selector icon

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#320]
A request from the board a long time ago that's becoming slightly more pressing: let's replace the UI language selection icon in the header with https://www.materialui.co/icon/translate

**Comment by eroux** [comment]
also, let's change the order of the languages (everything is political!) to:
- Tibetan - English - Chinese on the main website
- Chinese - Tibetan - English on the Chinese mirror

**Comment by berger-n** [comment]
done: https://library.bdrc.io/

![image](https://user-images.githubusercontent.com/33383857/97709529-ca960280-1aba-11eb-82d4-e95edca936df.png)
---

menu order can now be set in the config file:

```jsx
   "language": {
      "menu":[ "bo", "en", "zh" ],
      /* ... */ 
   }
```

**Comment by berger-n** [comment]
there it is: https://github.com/buda-base/public-digital-library/commit/5097ab14c02ef0ebbd6775175beb846cd0c1fece

**Comment by eroux** [comment]
perfect, thanks!
