### ISSUE TITLE
small changes in the search results design

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#322]
Now that we have the open access by default, I think we could have the following:
- not displaying the image icon (as it's obvious with the thumbnail)
- instead, having an icon signifying that there are no images, maybe either a barred image icon or something evoking a catalog record...?
- displaying the provider icon as it's done in the version list of works ([ex](http://library.bdrc.io/show/bdr:WA4CZ16799) with the icon in the thumbnail)
- not displaying the open access icon (but keep displaying the other access icons)
- if it doesn't eat up too much room, displaying the (non-open) access icon in the thumbnail box

Note that if we do all of that we'll have no icons under the thumbnails anymore, which means we can lower the min-height of the block.

@JannTibetan what do you think of these changes?

**Comment by JannTibetan** [comment]
Let's drop the image icon when there is a thumbnail present.
We need a better way to indicate a record lacks images. A barred image icon would communicate this well, I think. Google Books doesn't use an icon:
<img width="626" alt="Screen Shot 2020-10-30 at 12 42 04 PM" src="https://user-images.githubusercontent.com/44705185/97732865-83554500-1aad-11eb-9ebe-51c8532ee709.png">
Displaying the provider icon is a good idea
The open access icon is superfluous at this point
I like your last suggestion (thumbnail place closed-lock icon)

**Comment by berger-n** [comment]
some of the changes made so far:
- http://library-dev.bdrc.io/search?q=%22saddharmapu%E1%B9%87%E1%B8%8Darika%22&lg=inc-x-ndia&t=Instance&f=asset,inc,tmp:hasOpen

![image](https://user-images.githubusercontent.com/33383857/102067873-016e7080-3dfc-11eb-8ad7-a139bbf53c43.png)

- http://library-dev.bdrc.io/search?q=%22spyod%20%27jug%22&lg=bo-x-ewts&t=Instance&pg=1&f=asset,exc,tmp:hasOpen&f=provider,exc,bda:CP049&s=title

![image](https://user-images.githubusercontent.com/33383857/102067600-9e7cd980-3dfb-11eb-9a90-d8350ff790c9.png)

note that in the latter search [query results](http://purl.bdrc.io/lib/instanceFacetGraph?LG_NAME=bo-x-ewts&L_NAME=%22spyod%20%27jug%22), both bdr:MW8LS22437 and bdr:MWEAP105-2-3-77 have `hasImage:false` whereas latter one do have [available scans](http://library-dev.bdrc.io/show/bdr:WEAP105-2-3-77)

**Comment by eroux** [comment]
This looks perfect, thanks a lot! I also noticed that some thumbnails were missing for some IIIF works that we have (from EAP mostly)... I'll take a look

**Comment by eroux** [comment]
Regarding W8LS22437 it doesn't really have images, it's quite normal... maybe for these we could have a barred image icon?

**Comment by berger-n** [comment]
ok thanks! 
done: http://library-dev.bdrc.io/search?q=%22spyod%20%27jug%22&lg=bo-x-ewts&t=Instance&f=asset,exc,tmp:hasImage

![image](https://user-images.githubusercontent.com/33383857/102101799-5f667c80-3e2b-11eb-9db4-58fd96face28.png)

**Comment by berger-n** [comment]
now with custom icon:

![image](https://user-images.githubusercontent.com/33383857/102105775-1533ca00-3e30-11eb-8097-a3e3863ccb66.png)

**Comment by berger-n** [comment]
with modified icon:

![image](https://user-images.githubusercontent.com/33383857/102109976-ecfa9a00-3e34-11eb-8ccf-f6aacb2cd650.png)

**Comment by eroux** [comment]
if it's not pushed already let's push it and close the issue

**Comment by berger-n** [comment]
ok! now it is: https://library.bdrc.io/search?q=%22spyod%20%27jug%22&lg=bo-x-ewts&t=Instance&pg=1&f=asset,exc,tmp:hasOpen

**Comment by eroux** [comment]
great, thanks a lot!
