### ISSUE TITLE
css for tabs in Tibetan

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#324]
see (under latest Firefox)

![Capture d’écran de 2020-10-31 18-59-29](https://user-images.githubusercontent.com/60868/97788094-812add80-1bb6-11eb-9d67-fe36b3dcd586.png)

it's not very legible... the IDs should be a bit lower

**Comment by berger-n** [comment]
fixed: http://library-dev.bdrc.io/show/bdr:MW4CZ302233?uilang=bo

![image](https://user-images.githubusercontent.com/33383857/97867190-aaaa4d00-1d0d-11eb-8539-41857ee41915.png)

**Comment by eroux** [comment]
great, thanks!
