### ISSUE TITLE
Not able to view the image

### ISSUE THREAD

**Issue by jeehuajian** [buda-base/public-digital-library#325]
1) Cant see the Larger view of the image. [Link](http://buda.zju.edu.cn/show/bdr:MW1KG12986_B2C959?s=%2Fshow%2Fbdr%3AMW1KG12986%3Fpart%3Dbdr%3AMW1KG12986_B2C959%26s%3Dq%253D%252522%2525E0%2525BD%2525A3%2525E0%2525BE%2525B7%2525E0%2525BC%25258B%2525E0%2525BD%2525A3%2525E0%2525BD%2525B4%2525E0%2525BD%252584%2525E0%2525BC%25258B%2525E0%2525BD%252591%2525E0%2525BD%252594%2525E0%2525BD%2525A3%2525E0%2525BC%25258B%2525E0%2525BD%252582%2525E0%2525BE%2525B1%2525E0%2525BD%2525B2%2525E0%2525BC%25258B%2525E0%2525BD%2525A2%2525E0%2525BE%2525A1%2525E0%2525BD%2525BC%2525E0%2525BC%25258B%2525E0%2525BD%2525A2%2525E0%2525BE%252597%2525E0%2525BD%2525BA%2525E0%2525BC%25258B%252522%2526lg%253Dbo%2526t%253DInstance%2526s%253Dclosest%252520matches%252520forced%2526n%253D7#open-viewer) 

![Capture](https://user-images.githubusercontent.com/42564256/97839298-de40a380-1d1c-11eb-906d-989561b5d2f2.PNG)

2) Cant view the smaller view of the image [Link](https://library.bdrc.io/show/bdr:W30526)
![002](https://user-images.githubusercontent.com/42564256/97840371-d1bd4a80-1d1e-11eb-9190-818647bf271e.PNG)

**Comment by eroux** [comment]
Thanks! This is an error in the iiif server in China, it should be fixed soon

**Comment by eroux** [comment]
it works now, thanks for the report!
