### ISSUE TITLE
css bug with very long titles in etext viewer header

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#326]
see https://library.bdrc.io/show/bdr:UT3JT13307_001_0000#open-viewer

![Capture d’écran de 2020-11-02 16-36-20](https://user-images.githubusercontent.com/60868/97887095-b73c9e80-1d29-11eb-9d26-b7b809d0ec62.png)

**Comment by berger-n** [comment]
much better now:

![image](https://user-images.githubusercontent.com/33383857/97903913-0d1c4100-1d40-11eb-8b06-55c6bb06e29e.png)

**Comment by eroux** [comment]
much better indeed, thanks!
