### ISSUE TITLE
strange "role" display

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#328]
In https://library.bdrc.io/show/bdr:P2CZ8011 : 

![Capture d’écran de 2020-11-03 10-38-21](https://user-images.githubusercontent.com/60868/97969811-dcc8b700-1dc0-11eb-938e-5fe0884425e8.png)

**Comment by berger-n** [comment]
fixed: 

![image](https://user-images.githubusercontent.com/33383857/97993353-3c848980-1de4-11eb-9de7-8e0e9e7b87e4.png)

**Comment by eroux** [comment]
thanks!
