### ISSUE TITLE
missing source for some information

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#329]
On https://library.bdrc.io/show/bdr:P2CZ8011 all the information about students come from the DILA database but it's not acknowledged

**Comment by berger-n** [comment]
it's fixed now:

![image](https://user-images.githubusercontent.com/33383857/98005789-bbcc8a00-1df1-11eb-8dde-f6caecefbe14.png)

**Comment by eroux** [comment]
great, thanks!
