### ISSUE TITLE
search called twice in some contexts

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#33]
steps to reproduce:
- go to [this search](library.bdrc.io/search?q="bka bstan"&lg=bo-x-ewts&t=Any) with the network analyzer open (everything goes fine)
- search `bka' bstan`
- see the search being called twice in the network analyzer

**Comment by berger-n** [comment]
for now there seem to be a problem with `lds-pdi` ?
![image](https://user-images.githubusercontent.com/33383857/47351461-4c771800-d6b8-11e8-96e0-60d917b3fde1.png)

**Comment by berger-n** [comment]
(I was expecting search results to display immediately... no problem with `ldspdi` I think, but I'll first check this, it should at least show "no results" on loading the page)

**Comment by eroux** [comment]
weird, I don't have that... the URL I get to is 

http://purl.bdrc.io/lib/rootSearchGraph?LG_NAME=bo-x-ewts&I_LIM=500&L_NAME=%22bka%27%20bstan%22

which gives me some results

**Comment by berger-n** [comment]
the ' seem of importance here

**Comment by berger-n** [comment]
some kind of bonus/combo bug... ^^

but what you're suggesting here is that `rootSearchGraph` should not be called if it already has returned results for a given query ?

**Comment by berger-n** [comment]
(here it is for the no result part)
now I get what you mean I think:
![image](https://user-images.githubusercontent.com/33383857/47352673-a8db3700-d6ba-11e8-9e7f-e98eae50d913.png)

**Comment by berger-n** [comment]
+1 talking about combo bugs:
![image](https://user-images.githubusercontent.com/33383857/47353102-be9d2c00-d6bb-11e8-96f4-ac76d8796767.png)
![image](https://user-images.githubusercontent.com/33383857/47353130-ca88ee00-d6bb-11e8-9cc4-6ab7f947a7f9.png)
![image](https://user-images.githubusercontent.com/33383857/47353159-e096ae80-d6bb-11e8-9565-bb96f61d9349.png)

**Comment by berger-n** [comment]
I agree
this should not be

BTW do this highlight tagging make sense to you:
![image](https://user-images.githubusercontent.com/33383857/47354871-28b7d000-d6c0-11e8-9afa-5db8d2c35930.png)

**Comment by eroux** [comment]
you already reported it, it's recorded in https://github.com/BuddhistDigitalResourceCenter/lucene-bo/issues/15#issuecomment-430259673
