### ISSUE TITLE
etext "outline"

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#330]
It's not really an outline (yet!) but here's a query that returns the information necessary to display the etext intances in a nice way:

http://ldspdi.bdrc.io/query/graph/etextrefs?R_RES=bdr:IE3JT13307

the data model is the following:

```
bdr:IE3JT13307
   :instanceHasVolume (a volume)
       :volumeHasEtext (etext ref, with a seqNum to sort them)
           :eTextResource (the actual etext)
```

There's always only one etext by etext ref, the only use of etextref is the seqnum property to have the etexts in a certain order. We don't want to display the etext refs in the UI.

In some cases, one volume will have several etexts (like in bdr:IE1KG14), but most of the time it won't... so I think we should have two separate displays:

When a volume has just one etext(/ref), then don't expand more, let's actually skip the volume and only display the corresponding etext (title, etc.), preceded by "volume 1"

When a volume has several etexts, let's display "volume 1" and then below the different etexts.

It should work just like the outlines, in the sense that clicking on the title should only expand / fold the outline, not go anywhere else. In terms of data we display it would be very basic:
- open record (a link to the resource of the etext)
- open etext
- download etext

**Comment by berger-n** [comment]
it's almost there: http://library-dev.bdrc.io/show/bdr:IE30037

![image](https://user-images.githubusercontent.com/33383857/98279459-4223d000-1f9a-11eb-9781-469b2587583f.png)
---

same with multiple volumes : http://library-dev.bdrc.io/show/bdr:IE3JT13307

![image](https://user-images.githubusercontent.com/33383857/98282821-0dfede00-1f9f-11eb-852d-dc6356072518.png)
---

multiple texts inside multiple volumes: http://library-dev.bdrc.io/show/bdr:IE1KG14

![image](https://user-images.githubusercontent.com/33383857/98282947-3b4b8c00-1f9f-11eb-9fc0-19cbab717f30.png)
---

there is an issue with the last one though
i've updated the query to return the texts titles but it's slooow: http://ldspdi.bdrc.io/query/graph/etextrefs?R_RES=bdr:IE1KG14

**Comment by eroux** [comment]
ah excellent, thanks! Yes,`OPTIONAL` is (almost) always a bad idea in SPARQL, I'll take a look

**Comment by eroux** [comment]
Well, actually it's not (only) a problem of query, it's just that the data is very big... I didn't think it would be necessary but I'm affraid we'll have to do like the outlines and fetch level by level... I'll transform the query into something that fetches the volumes if called on an etext instance, and fetches the resources if called with a volume

**Comment by berger-n** [comment]
now with links when title is clicked: http://library-dev.bdrc.io/show/bdr:IE3JT13307

![image](https://user-images.githubusercontent.com/33383857/98372533-2ffb6d80-203e-11eb-9574-5aa4405581c1.png)
---

when there is only one volume/text it's visible when page is loaded: http://library-dev.bdrc.io/show/bdr:IE30037

![image](https://user-images.githubusercontent.com/33383857/98372622-591bfe00-203e-11eb-8f79-d3c37e6eb37d.png)

**Comment by eroux** [comment]
wow, this is great, thanks!

**Comment by eroux** [comment]
I think the main missing features is to replace `[no title]` with `volume x` in the outline when the volume or the etext have no title, like in http://library-dev.bdrc.io/show/bdr:IE0OPP008105 . Also let's remove the search bar for now, we can implement it later on. Once it's done we can merge
