### ISSUE TITLE
? as title for etexts results

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#332]
For instance 

https://library.bdrc.io/search?q=%22gso%20ba%20rig%20pa%27i%20bstan%20bcos%20sman%20bla%27i%20dgongs%20rgyan%20rgyud%20bzhi%22&lg=bo-x-ewts&t=Etext

**Comment by berger-n** [comment]
this is because there are no `prefLabel` for these in query results ([link](https://purl.bdrc.io/lib/etextContentFacetGraph?LG_NAME=bo-x-ewts&L_NAME=%22gso%20ba%20rig%20pa%27i%20bstan%20bcos%20sman%20bla%27i%20dgongs%20rgyan%20rgyud%20bzhi%22)): 

![image](https://user-images.githubusercontent.com/33383857/98242356-a334af00-1f6c-11eb-82db-112204240b9d.png)

**Comment by eroux** [comment]
So, here's a new logic:
- let's not display the work label in the result
- let's add an instance facet on the left (should be straightforward as it works like all others)
- let's display "In: "+the label of the instance, just like we do for outline nodes
- when there's no label for the etext resource, let's not display the "In: "... as the main title

Also, the query now accepts an optional `R_EINST` argument that restricts the results to an etext instance, so that https://github.com/buda-base/public-digital-library/issues/333 can be implemented. See for instance the difference between 

https://purl.bdrc.io/lib/etextContentFacetGraph?LG_NAME=bo&L_NAME=%22%E0%BD%90%E0%BD%96%E0%BD%A6%E0%BC%8B%E0%BD%86%E0%BD%BA%E0%BD%93%E0%BC%8B%E0%BD%94%E0%BD%BC%E0%BC%8B%E0%BD%A1%E0%BD%B2%E0%BC%8B%E0%BD%A2%E0%BD%84%E0%BC%8B%E0%BD%96%E0%BD%9E%E0%BD%B2%E0%BD%93%E0%BC%8B%E0%BD%85%E0%BD%93%E0%BC%8D%20%E0%BC%8D%E0%BD%A0%E0%BD%91%E0%BD%B2%E0%BC%8B%E0%BD%93%E0%BD%B2%E0%BC%8B%E0%BD%91%E0%BD%BA%E0%BC%8B%E0%BD%96%E0%BD%9E%E0%BD%B2%E0%BD%93%E0%BC%8B%E0%BD%82%E0%BD%A4%E0%BD%BA%E0%BD%82%E0%BD%A6%E0%BC%8B%E0%BD%94%E0%BD%A0%E0%BD%B2%E0%BC%8B%E0%BD%A2%E0%BD%B2%E0%BD%82%E0%BD%A6%22&R_EINST=bdr:IE23703

and 

https://purl.bdrc.io/lib/etextContentFacetGraph?LG_NAME=bo&L_NAME=%22%E0%BD%90%E0%BD%96%E0%BD%A6%E0%BC%8B%E0%BD%86%E0%BD%BA%E0%BD%93%E0%BC%8B%E0%BD%94%E0%BD%BC%E0%BC%8B%E0%BD%A1%E0%BD%B2%E0%BC%8B%E0%BD%A2%E0%BD%84%E0%BC%8B%E0%BD%96%E0%BD%9E%E0%BD%B2%E0%BD%93%E0%BC%8B%E0%BD%85%E0%BD%93%E0%BC%8D%20%E0%BC%8D%E0%BD%A0%E0%BD%91%E0%BD%B2%E0%BC%8B%E0%BD%93%E0%BD%B2%E0%BC%8B%E0%BD%91%E0%BD%BA%E0%BC%8B%E0%BD%96%E0%BD%9E%E0%BD%B2%E0%BD%93%E0%BC%8B%E0%BD%82%E0%BD%A4%E0%BD%BA%E0%BD%82%E0%BD%A6%E0%BC%8B%E0%BD%94%E0%BD%A0%E0%BD%B2%E0%BC%8B%E0%BD%A2%E0%BD%B2%E0%BD%82%E0%BD%A6%22

To restrict to a specific etext resource there's actually a more clever query to make, let's do that later

**Comment by berger-n** [comment]
wonderful! thanks

**Comment by eroux** [comment]
once the current state of https://github.com/buda-base/public-digital-library/issues/330 has been merged, this will be the most urgent... if we can implement this for Monday 5pm that will be wonderful!
