### ISSUE TITLE
searching in an etext instance content

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#333]
A user's request, for something that used to exist on tbrc.org : it would be good to have a search bar in an etext resource and in an etext instance (and probably later in a normal instance if it has at least one etext reproduction). I think we already have a request for an etext resource, but not yet for the etext instance, I'll create that. I'm not really sure yet how to display that in a good way... I'll create the queries first, and let's think of a good way to display the results.

**Comment by berger-n** [comment]
regarding search in etext I think this will perfectly fit into https://github.com/buda-base/public-digital-library/issues/330

https://library.bdrc.io/show/bdr:MW12827?osearch=%22dri%20med%20%27od%20zer%22~1@bo-x-ewts

![image](https://user-images.githubusercontent.com/33383857/98242502-df680f80-1f6c-11eb-953f-ce82fef9ad9d.png)

BTW do we keep the word "Outline" for etext table of content or do you already think of a better one?

**Comment by eroux** [comment]
ah, good point yes! we can use "Browse etexts", it's a bit generic but I think it would fit well

**Comment by eroux** [comment]
For UX / performance / engineering reasons, it's much better to keep the search in instance separate from the general etext search... I've just added the query ([example](http://purl.bdrc.io/lib/etextContentFacetGraphInInstance?L_NAME=%22%E0%BD%82%E0%BD%A3%E0%BC%8B%E0%BD%8F%E0%BD%BA%E0%BC%8B%E0%BD%96%E0%BE%B1%E0%BD%84%E0%BC%8B%E0%BD%86%E0%BD%B4%E0%BD%96%E0%BC%8B%E0%BD%A6%E0%BD%BA%E0%BD%98%E0%BD%A6%E0%BC%8B%E0%BD%91%E0%BD%94%E0%BD%A0%E0%BD%A6%E0%BD%BA%E0%BD%98%E0%BD%A6%E0%BC%8B%E0%BD%91%E0%BD%94%E0%BD%A0%E0%BC%8B%E0%BD%86%E0%BD%BA%E0%BD%93%E0%BC%8B%E0%BD%94%E0%BD%BC%E0%BD%A6%E0%BC%8B%E0%BD%A0%E0%BD%81%E0%BE%B2%E0%BD%B4%E0%BD%82%E0%BD%99%E0%BD%84%E0%BC%8B%E0%BD%93%E0%BD%BA%E0%BD%98%E0%BC%8B%E0%BD%93%E0%BD%B4%E0%BD%A2%E0%BC%8B%E0%BD%98%E0%BD%81%E0%BE%B1%E0%BD%BA%E0%BD%A2%E0%BC%8D%22&LG_NAME=bo&R_EINST=bdr:IE0OPP008105)).

The UI should be very similar to the general etext search, with a few differences:
- the title should be something along the lines of "results for X in Y" where X is the search and Y is the instance label (returned by the query)
- the etext type should be selected, and no other type selectable
- the instance shouldn't be a facet (as all results will be in the same instance anyways), nor a filter that can be unselected
- the results are still sorted by etext, that doesn't change, but if there are matches only in one etext, it should be unfolded (as if the user clicked on "see other matches"
- results have a `etextInVolume` or `etextIsVolume` property that could be used as a facet

This will be the next priority once the small things and bugs have been dealt with

**Comment by berger-n** [comment]
I'm not sure about which direction to take here
I thought we were going to use kind of same UI we made for outlines/search: https://library.bdrc.io/show/bdr:MW1PD107937?osearch=%22drin%20can%20rtsa%20ba%27i%20bla%20ma%20ngag%20dbang%22~1@bo-x-ewts

![image](https://user-images.githubusercontent.com/33383857/100992237-3a812800-3554-11eb-97fb-c8d2501f077c.png)

do you prefer we use main search page here?
if so how do we handle having to input both a resource and keywords?
this needs some thinking

**Comment by eroux** [comment]
well, there are two things really: 
- one is to search in the etext titles, which would be good with the outline search bar, but it would only be useful for a few etexts (like the Paltsek ones, or the Rinchen Terdzo), but this is a different issue, I'll open it for clarity
- another (which is what I meant in this issue) is to search in the content of all the etexts of an instance, which can returns 100s of results in the same format as the general etext search. They would also have all the features of the current etext search, like link to the etext viewer with highlight, expand context, etc.

**Comment by berger-n** [comment]
ok it's clear now thanks!
the most straightforward is to start search from the etext page
(regarding the difference title/text search we could/will add some checkbox to tell which to call)

**Comment by eroux** [comment]
yes, or maybe the same kind of select as the main search bar (where *instance*, *work*, *person*, etc. would be replaced by *etext titles* and *etext contents*)... but we can deal with that later on

**Comment by berger-n** [comment]
why not indeed! good idea

**Comment by berger-n** [comment]
a first step: http://library-dev.bdrc.io/search?q=%22གལ་ཏེ་བྱང་ཆུབ་སེམས་དཔའསེམས་དཔའ་%22&lg=bo&t=Etext&r=bdr:IE0OPP008105&s=volume%20number%20reverse

![image](https://user-images.githubusercontent.com/33383857/101069617-8bb40a80-359a-11eb-8b8f-cfca245d6ced.png)

next step is to plug http://library-dev.bdrc.io/show/bdr:IE0OPP008105

BTW about:
>if there are matches only in one etext, it should be unfolded

do you mean one volume of etext resource? like in http://library-dev.bdrc.io/search?q=%22གལ་ཏེ་བྱང་ཆུབ་སེམས་དཔའསེམས་དཔའ་ཆེན་པོས་འཁྲུགཙང་ནེམ་ནུར་མཁྱེར།%22&lg=bo&t=Etext&r=bdr:IE0OPP008105 if there were "other matches" in the only result?

**Comment by eroux** [comment]
Great, thanks! Yes, that's what I mean

When you plug the thing, maybe the best thing would be to have a main title (the same level as "browse") that says "search in the content of this etext", and then just the search bar, then Browse, and then the outline... otherwise I'm afraid it won't be very clear for users. I think in the end we can live with two search bars once we implement https://github.com/buda-base/public-digital-library/issues/388, that will be fine and probably clearer

**Comment by berger-n** [comment]
not far from done here: http://library-dev.bdrc.io/show/bdr:IE0OPP008105

![image](https://user-images.githubusercontent.com/33383857/101178591-7cd86100-3649-11eb-826f-c1e0a54c35d1.png)

note that in results page you can now keep on searching in the same etext
(unless you remove the `bdr:IExyz` filter below searchbar - but for now there's a bug that prevents new results to be displayed you'll have to click on a facet to see them - working on it)

**Comment by berger-n** [comment]
fixed the navigation bug: http://library-dev.bdrc.io/search?q=%22dri%20med%20%27od%20zer%22&lg=bo-x-ewts&r=bdr:IE0OPP008105&t=Etext

![Kazam_screencast_00003 mp4](https://user-images.githubusercontent.com/33383857/101194827-caab9400-365e-11eb-89c8-551002f0197c.gif)

---

regarding that [context of match](http://purl.bdrc.io/query/graph/chunkContext?R_UT=bdr%3AUTIE0OPP008105_v038&I_START=372693&I_END=376628) I wonder how to interpret `tmp:inInstancePart` though:

![image](https://user-images.githubusercontent.com/33383857/101194990-0e9e9900-365f-11eb-9fec-f5d399edc3e6.png)

resulting in that display:

![image](https://user-images.githubusercontent.com/33383857/101195069-2f66ee80-365f-11eb-9e05-072644947917.png)

**Comment by eroux** [comment]
wow, really cool, thanks a lot! I'll take a look at the context thing, it's not really supposed to be that way. Probably an error in the data in that case. I think we can close this, unless perhaps there are a few things to polish?

**Comment by eroux** [comment]
https://github.com/buda-base/lds-queries/issues/60

**Comment by berger-n** [comment]
ok thanks! 
indeed it seems to be fully working now (no bug in mind)
let's close this!
