### ISSUE TITLE
[design] display the sort by value

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#334]
the selected value of sortby should be displayed all the time, with the little arrow on the right. When the user clicks the list should be displayed below the value, not on the right and vertically centered in the middle as it is now

**Comment by berger-n** [comment]
done: https://library.bdrc.io/search?q=%22spyod%20%27jug%22&lg=bo-x-ewts&t=Instance&f=asset,inc,tmp:hasOpen&s=title%20reverse

![image](https://user-images.githubusercontent.com/33383857/98377306-f417d680-2044-11eb-81a9-fd44d02904bb.png)

**Comment by eroux** [comment]
great, thanks!

**Comment by berger-n** [comment]
now with popup below:

![image](https://user-images.githubusercontent.com/33383857/98377743-786a5980-2045-11eb-9093-b5112fc673c2.png)

**Comment by eroux** [comment]
ah, even better!
