### ISSUE TITLE
adding sort icon

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#337]
left of the "sort by" block we could have an icon drawing the attention on the feature, maybe something like [this](https://material.io/resources/icons/?search=up&icon=import_export&style=baseline) ?

**Comment by berger-n** [comment]
done something like that:

![image](https://user-images.githubusercontent.com/33383857/99065412-a56bbe80-25a7-11eb-968b-74650091bbaa.png)

**Comment by eroux** [comment]
great, thanks!
