### ISSUE TITLE
return to BUDA in Mirador goes too far in the past

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#338]
- search Saddharmapundarika in Indic ([here](https://library.bdrc.io/search?q=%22saddharmapundarika%22&lg=inc-x-ndia&t=Instance&f=asset,inc,tmp:hasOpen)) (step 1)
- select the first result
- go to the work tab
- select the tibetan parallel work (step 4)
- click on the thumbnail of the one in the Derge Parphud (or any)
- open the viewer (sometimes it doesn't automatically for some reason)
- click on "return to BUDA" and instead of going back to step 4, you go back to step 1

**Comment by berger-n** [comment]
seems to be fine now
BTW clicking on version thumbnail from a work does not opens viewer but record
do you want to it to?

**Comment by eroux** [comment]
I think it's fine
thanks a lot!
