### ISSUE TITLE
bugs in etext results

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#339]
When on [this search page](https://library.bdrc.io/search?q=%22thang%20zing%22&lg=bo-x-ewts&t=Etext&s=closest%20matches):
- [x] for the other matches in the same etext, all titles are "@undefined~undefined" which is not really great
- [x] let's not display the character range in the search results
- [x] the "open in viewer" link doesn't open the etext at the place of the match
- [x] the "open in viewer" link doesn't highlight anything
- [x] when looking at other matches in the same etext, there should also be an "expand context" and "open in viewer"
- [ ] the highlighting is lost when the context is expanded
- [x] are results really sorted by highest Lucene score? it's the same as the number of results per etext it seems
- [x] removing the "etext" type for each result (or maybe replace it by "match"?)
- [x] removing the permalink
- [x] removing the ID of the etext (bdr:UTIE0OPP...) for the matches
- [x] replace "open etext" by "open in etext"

**Comment by berger-n** [comment]
- links/matches are fixed: http://library-dev.bdrc.io/search?q=%22thang%20zing%22&lg=bo-x-ewts&t=Etext&s=closest%20matches

![image](https://user-images.githubusercontent.com/33383857/98535364-46940580-2286-11eb-8d12-9459337fe5d6.png)

- regarding highlighting it seems that the query used to return match markers like "↦...↤" but doesn't anymore ([example](http://purl.bdrc.io/lib/Chunks?R_RES=bdr%3AUTIE0OPP005548_v001&I_START=0&I_END=10000))

- regarding expand/context the query seems not to return any text ([example](http://purl.bdrc.io/query/graph/chunkContext?R_UT=bdr%3AUTIE0OPP005548_v001&I_START=127407&I_END=130854))

**Comment by berger-n** [comment]
(not sure about the highligting... I think there used to be some fallback/js mechanism, i'll check)

**Comment by eroux** [comment]
Ah thanks! A few ideas:
- let's not display the character coordinates in the matches, I'm not sure users can really relate to that
- if "text match:" is the only property, let's remove it and just display the text

I'll look at the queries now

**Comment by eroux** [comment]
regarding the first query (Chunks) there's no way it ever returned highlights, for that there would need to be a search string passed to it...

**Comment by eroux** [comment]
ok, regarding the second one I can add a few surrounding chunks in the query, I'll do that later this week

**Comment by eroux** [comment]
I've updated the initial comment to keep track of things

**Comment by berger-n** [comment]
no coordinates/'text match':

![image](https://user-images.githubusercontent.com/33383857/98539891-56fbae80-228d-11eb-9ea6-558e4a33a75e.png)

**Comment by eroux** [comment]
Yes, that's good! What about also:
- removing the "etext" type for each result (or maybe replace it by "match"?)
- removing the permalink
- removing the ID of the etext (`bdr:UTIE0OPP...`) for the matches
- replace "open etext" by "open in etext"

**Comment by berger-n** [comment]
done:

![image](https://user-images.githubusercontent.com/33383857/98542395-2584e200-2291-11eb-83af-3c09f2dfa03d.png)
---

simple highlight is ok now: http://library-dev.bdrc.io/show/bdr:UTIE0OPP005548_v001?startChar=128407&keyword=%22thang%20zing%22@bo-x-ewts#open-viewer

![image](https://user-images.githubusercontent.com/33383857/98542465-42b9b080-2291-11eb-919a-071f2796967c.png)

**Comment by berger-n** [comment]
i'll check sorting now

**Comment by berger-n** [comment]
now there is a difference between nbChunks & closet match

**Comment by eroux** [comment]
ok, I've fixed the query so now [this example](https://purl.bdrc.io/query/graph/chunkContext?R_UT=bdr%3AUTIE0OPP000301_v010&I_START=222114&I_END=225089) returns the data. The problem now is that the highlighting is lost when the context is expanded. Ideally we should keep the chunk that was returned with highlighting and complete it with the new chunks returned by the query, instead of replacing it

**Comment by berger-n** [comment]
this is strange because it already works when running locally!

![image](https://user-images.githubusercontent.com/33383857/98653591-80741300-233d-11eb-804b-6d02f60da397.png)

I'll fix that

**Comment by berger-n** [comment]
finally fixed everything I think: https://library.bdrc.io/search?q=%22thang%20zing%22&lg=bo-x-ewts&t=Etext
(finds bo in bo-x-ewts and reciprocally)

![image](https://user-images.githubusercontent.com/33383857/98692400-5e938400-236f-11eb-9b4b-84232c296e32.png)

![image](https://user-images.githubusercontent.com/33383857/98692340-4b80b400-236f-11eb-939c-8cab36c6aa8d.png)

![image](https://user-images.githubusercontent.com/33383857/98692245-3146d600-236f-11eb-8b2a-5c5b77440270.png)

![image](https://user-images.githubusercontent.com/33383857/98692202-23915080-236f-11eb-9a6e-903a89c7e040.png)

**Comment by eroux** [comment]
thanks a lot!
