### ISSUE TITLE
auth routes

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#34]
Two new routes should be handled in `library.bdrc.io`:
- `/iiiftoken`
- `/logout`

the second one is relatively obvious, it just logs the user out.

The first one corresponds to [this part](https://iiif.io/api/auth/1.0/#interaction-for-browser-based-client-applications) of the iiif auth spec (it would not handle [this part](https://iiif.io/api/auth/1.0/#interaction-for-non-browser-client-applications)), so basically, to sum up, it would:
- read the url arguments
- if the user is already logged it, it would send the token through postmessage and close the window
- if the user is not logged, it would show a login button and follow the login workflow until the user is logged in, and send the resulting token through postmessage, then close the window

**Comment by eroux** [comment]
and finally a last one: `/iiifcookielogin`, implementing [this part](https://iiif.io/api/auth/1.0/#access-cookie-service) of the spec. It would be quite similar to `/iiiftoken` but instead of communicating the token to the parent window by postmessage, it:
- records the token in a cookie (I'm not actually sure it's necessary but let's do it and we can comment it later if it wasn't)
- closes the window (so that it triggers the next steps of the workflow)

**Comment by eroux** [comment]
Ok, I now have a much clearer understanding of what the `/iiifcookielogin` should do (sorry for the changes). It doesn't need to set a cookie itself, but instead, once the user is logged in, it should make a request to a url with the access token in the headers. The url needs to be configurable but would currently be `http://images.bdrc.io/setcookie`. The result of that request is irrelevant except for the http status code, in case it's not 200, then there's an error.

**Comment by eroux** [comment]
(sorry, the url would currently be configured to `null`, in that case there's no request (and no error))

**Comment by eroux** [comment]
a last thing to take care of: the logout process should send a request to the iiif cookie url with no token so that the cookie is discarded

**Comment by MarcAgate** [comment]
see that implementation on iiif server : https://github.com/buda-base/buda-iiif-server/blob/master/src/main/java/de/digitalcollections/iiif/hymir/image/frontend/IIIFImageApiController.java#L108
