### ISSUE TITLE
clicking on "img. xxx" in the etext viewer doesn't work sometimes

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#344]
I'm not sure what triggers that but in some cases the image just doesn't load, for instance when I click on an image on https://library.bdrc.io/show/bdr:UTIE0OPP000301_v010?startChar=246671&keyword=%22stong%20pa%27i%20ngang%20las%20hU~M%20las%20byung%22~1@bo-x-ewts#open-viewer

**Comment by berger-n** [comment]
I can't reproduce this
my guess would be it has to do with opening/closing mirador multiple times in a row without reloading (I think I've already fixed that though)
something useful here will be that "Return to BUDA" in Mirador when openend from Etext viewer returns to Etext viewer and not resource page as it does now

**Comment by eroux** [comment]
hmm indeed, it works fine now! Let's forget about it, I'll reopen it if it does it again
