### ISSUE TITLE
[Design] highlight selected element in mirador outline

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#345]
Currently if you're in a list of leaves in the outline tree, if you click on one of the leaves, it displays the corresponding manifests on the right panel, but it doesn't highlight the selected element on the left, example:

![Capture d’écran de 2020-11-10 15-50-17](https://user-images.githubusercontent.com/60868/98689805-9220df00-236c-11eb-80c8-eb15466b0293.png)

**Comment by berger-n** [comment]
done:

![image](https://user-images.githubusercontent.com/33383857/99705225-bb8ee880-2a99-11eb-9778-aafb987d35de.png)

not sure about the style, WDYT:

![image](https://user-images.githubusercontent.com/33383857/99705339-e1b48880-2a99-11eb-9adf-daa8b57c14c8.png)

I have also reduced font size a bit in collection tree when not in tibetan unicode

**Comment by eroux** [comment]
excellent thanks! reducing the font is a good idea yes. I think I prefer the first (bold) one...
