### ISSUE TITLE
accepting anther apostrophe as ewts

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#346]
`Snyan-brgyud Rin-po-che Rdo-rje-zam-pa’i Gdams-ngag` is recognized as English because of the `’`, but it should be part of the characters allowed in ewts in the language detection

**Comment by berger-n** [comment]
fixed:

![image](https://user-images.githubusercontent.com/33383857/98952879-41d88700-24fc-11eb-893d-edf9606e712e.png)

**Comment by eroux** [comment]
great, thanks!
