### ISSUE TITLE
corporation usability

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#347]
https://library.bdrc.io/show/bdr:C38 is not very usable, there should be a list of the famous persons associated with the corporations, and then the usual link to the associated persons

**Comment by eroux** [comment]
I think this is good, thanks!

**Comment by eroux** [comment]
ah, it's actually not ok, now the bar with the members works but when clicking instead of going to the person it goes to the intermediate `bdr:CM...` thing

**Comment by berger-n** [comment]
I've made some fixes here, I think we're good now
you can try 
- https://library.bdrc.io/show/bdr:C38 (direct link to person record)
- https://library.bdrc.io/show/bdr:C12 (more than 4 members --> link to query)
- https://library.bdrc.io/show/bdr:C35 (only members no works)

**Comment by eroux** [comment]
excellent, thanks a lot! In the last one can we put the note after the related resources? (that's quite a note!)

**Comment by berger-n** [comment]
indeed!
done: 

![image](https://user-images.githubusercontent.com/33383857/99698674-58995380-2a91-11eb-8b80-816c0b8c5236.png)
