### ISSUE TITLE
zoom out a bit by default for places

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#348]
In most cases our GIS data is not that good and the visual isn't super interesting anyways, for instance https://library.bdrc.io/show/bdr:G1PD96170 looks like it's on the Moon... something like this would be more compelling:

![Capture d’écran de 2020-11-12 20-18-21](https://user-images.githubusercontent.com/60868/98985739-49138b00-2524-11eb-915f-8847bdf789be.png)

(so let's zoom out a lot by default)

**Comment by berger-n** [comment]
done:

![image](https://user-images.githubusercontent.com/33383857/99057974-d1ce0d80-259c-11eb-82c8-ead4eccc89d4.png)

**Comment by eroux** [comment]
thanks, excellent!
