### ISSUE TITLE
outline bar in mirador too narrow

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#349]
This is a combination of two issues:
- the outline bar in the collection view of Mirador is too narrow by defaut, for instance on my screen:

![Capture d’écran de 2020-11-13 09-11-00](https://user-images.githubusercontent.com/60868/99044693-75fd8780-2590-11eb-92cc-6929fab0647b.png)

- when I resize it so that I can browse the outline, when I click on a volume and then click on the collection in the breadcrumbs, the bar is back to being tiny

**Comment by berger-n** [comment]
it seems to be fixed now

**Comment by eroux** [comment]
yes, excellent!!
