### ISSUE TITLE
match context

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#350]
there's a facet on tbrc.org that we haven't implemented on BUDA. It's the "context" facet, which indicates if the string match occurs in the title / name or elsewhere (in the notes, publisher name, etc.).

I think by default there should be nothing checked and we could name the facets like this:
- title (in the context of bibliographical entities)
- name (in other contexts)
- secondary data

(note that there can be matches in both for the same thing) 

The distinction should be relatively easy to make I think in the javascript with the current data right?

It's not very urgent

**Comment by eroux** [comment]
This has been requested during the demo today

**Comment by berger-n** [comment]
seems to be working fine: http://library-dev.bdrc.io/search?q=%22dri%20med%20%27od%20zer%22~1&lg=bo-x-ewts&t=Instance&pg=1&f=context,inc,tmp:noteMatch

![image](https://user-images.githubusercontent.com/33383857/117283316-f5945100-ae65-11eb-83f4-a7ef5101255e.png)

**Comment by eroux** [comment]
looks perfect, this is really great! thanks!
