### ISSUE TITLE
missing topic icon in SRC results

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#352]
see https://library.bdrc.io/search?q=%22Mah%C4%81y%C4%81na%22&lg=inc-x-ndia&t=Topic for instance

**Comment by berger-n** [comment]
works fine now:

![image](https://user-images.githubusercontent.com/33383857/99262920-d30e6d00-281e-11eb-8e40-79b9a6ebaed8.png)

not sure which of our types we should use for records of these types though:
- `https://sakyaresearch.org/deities/ `: `Person` I guess?
- `https://sakyaresearch.org/literary_forms/`: `Work` ?

**Comment by eroux** [comment]
ah thanks! both are topics

**Comment by berger-n** [comment]
ok thanks!
