### ISSUE TITLE
etext with pages that cannot be linked to images

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#353]
in etexts such as https://library.bdrc.io/show/bdr:UT1KG4884_001_0001#open-viewer the images can't be linked to images (at all) even if they have `bdo:seqNum`s. The way to differentiate these etexts from the others is that these have `rdf:type bdo:EtextNonPaginated`. In that case instead of `img. 1` with a link, we should have `p. 1` with no link, and perhaps a message "the pages of this etext may correspond to page in the original edition, but we cannot provide the exact mapping".

**Comment by berger-n** [comment]
added the message both at the top and when hovering page number (but not sure this is what you meant):

![image](https://user-images.githubusercontent.com/33383857/99549088-99be3480-29b9-11eb-85d8-521abf37f073.png)

**Comment by eroux** [comment]
yes, perfect!

**Comment by eroux** [comment]
oops sorry, the conditional doesn't seem to be good because https://library.bdrc.io/show/bdr:UTIE0OPP001673_v001#open-viewer doesn't display the images anymore while it should

**Comment by berger-n** [comment]
thanks for reporting that! it was a mistake of mine
images are back here https://library-dev.bdrc.io/show/bdr:UTIE0OPP001673_v001#open-viewer
and nothing to show here: http://library-dev.bdrc.io/show/bdr:UT1KG4884_001_0001#open-viewer

**Comment by eroux** [comment]
perfect, thanks!
