### ISSUE TITLE
persons associated with a corporation

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#354]
The query for persons associated with a corporation should return the results and allow a facet on the type of membership (which is in the `bdr:CM...` thing), I'll make the query work and then there will need to be a facet on `tmp:membershipType` (the labels of the possible values are already in the ontology)

**Comment by eroux** [comment]
ok, the query works now, there are two changed needed on https://library.bdrc.io/search?r=bdr:C38&t=Person&s=title%20forced :
- adding the facet for `tmp:membershipType`
- removing the facet for is creator (I wonder how it got there?)

**Comment by eroux** [comment]
actually make that 3, let's add the facet for centuries

**Comment by eroux** [comment]
ok, a lot of twists on this issue... I've put the membership type in the existing relation type so no need for an additional facet for that, but the other changes are still necessary

**Comment by eroux** [comment]
also the label of the types of membership is not the one from the ontology, I'm not sure why?

**Comment by berger-n** [comment]
this is what we have now:

![image](https://user-images.githubusercontent.com/33383857/99429952-f6ade200-2908-11eb-9575-4285ca08b11b.png)
---

- I removed the widget for is creator here (according to the condition that there is a result having value true for this property - which is false in that case)
- regarding the Corporation Member Unknown label, it seems that the ontology has a http://purl.bdrc.io/ontology/core/CorporationMemberNotSpecified but no `bdo:CoporationMemberUnknown` so the default label is used (remove property path and insert a space before capital letters)

**Comment by eroux** [comment]
thanks a lot! Oooooh ok, let me fix that for the label

**Comment by eroux** [comment]
Ah, now the problem is different: the left bar now displays

```
Facet
 |   Corporation Member
```

as I think what it tries to do is present something like in the ontology:

```
Corporation Member
|  by blood
|  by marriage
etc.
```

which is a good intent, but in that case the type is the top type and not a subtype... so maybe the UI should check that it doesn't display "facet" as the top thing?

**Comment by berger-n** [comment]
it's better now: https://library.bdrc.io/search?r=bdr:C44&t=Person

![image](https://user-images.githubusercontent.com/33383857/99540575-f9174700-29af-11eb-9b6d-e6f76c533497.png)

(`bdo:CorporationMemberMarriage` and `bdo:CorporationMemberBlood` are `bdo:CorporationMemberByMarriage` and `bdo:CorporationMemberByBlood` in the ontology)

**Comment by eroux** [comment]
thanks! another error in the migration indeed, sorry for that! it should be ok tomorrow

**Comment by eroux** [comment]
FYI, the issue with the migration has been solved and the display is good now

**Comment by berger-n** [comment]
great! thanks
