### ISSUE TITLE
missing matching property in some results

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#355]
such as https://library.bdrc.io/search?q=%22A%20rA%20ga%22~1&lg=bo-x-ewts&t=Instance

**Comment by berger-n** [comment]
fixed: https://library.bdrc.io/search?q=%22A%20rA%20ga%22~1&lg=bo-x-ewts&t=Instance&s=closest%20matches%20forced

![image](https://user-images.githubusercontent.com/33383857/99423065-784d4200-2900-11eb-99e7-fff112623187.png)

**Comment by eroux** [comment]
excellent, thanks!
