### ISSUE TITLE
missing facets in associated instances

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#356]
For instance in https://library.bdrc.io/search?r=bdr:T548&s=title%20forced&t=Instance the facet for access is not present in the left bar, despite the open access filter being there by default. I think it's just a matter of configuration

**Comment by berger-n** [comment]
it seems that [query](https://purl.bdrc.io/lib/associatedInstances?R_RES=bdr%3AT548&format=json) does not have data about access `tmp:hasOpen/Image/Etext`
(contrary to this [keyword search query](https://purl.bdrc.io/lib/instanceFacetGraph?LG_NAME=bo-x-ewts&L_NAME=%22spyod%20%27jug%22) for example)

**Comment by eroux** [comment]
ok, I've added the missing data, it now appears in the UI, thanks!
