### ISSUE TITLE
hiding hasVolume property on etexts

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#357]
for instance on https://library.bdrc.io/show/bdr:IE0OPP001673, it's not necessary with the outline. Actually tell me if we can remove them from the query, we could do that

**Comment by berger-n** [comment]
now the volumes are not displayed anymore when there is an outline to display
if it's always the case in the data, we could remove them from query, yes

**Comment by eroux** [comment]
excellent, thanks!
