### ISSUE TITLE
handling IDP content provider

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#358]
There's a new provider to handle: IDP. It has no icon (yet), the URLs start with `http://idp.bl.uk`.

- [ ] there should be an indication in the search results ([ex](https://library.bdrc.io/search?q=%22%27phags%20pa%20rgyal%20bu%20don%20grub%20kyi%20mdo%22~1&lg=bo-x-ewts&t=Instance&pg=1)) (currently there's only one provider strangely)
- [ ] in the main records ([ex](https://library.bdrc.io/show/bdr:MW0IDP0002_2)) there should be the metadata block, the icon in the yellow header and the permalink block, and the link to the original record, which is in the `adm:canonicalHtml` property

the behavior should be similar to the EAP records

**Comment by berger-n** [comment]
regarding the first point it seems that there is no provider in `IDPxyz` records 
[query](https://purl.bdrc.io/lib/instanceFacetGraph?LG_NAME=bo-x-ewts&L_NAME=%22%27phags%20pa%20rgyal%20bu%20don%20grub%20kyi%20mdo%22~1) looks quite empty actually:

![image](https://user-images.githubusercontent.com/33383857/99431348-eac31f80-290a-11eb-9496-4b9036bb77d8.png)

**Comment by eroux** [comment]
hmm... right, I'll fix that tomorrow thanks!

**Comment by eroux** [comment]
ok, the query works now, the provider is present in the left bar, but we should add a small icon like we do on https://library.bdrc.io/search?q=%22saddharmapundarika%22&lg=inc-x-ndia&t=Instance&pg=1&f=asset,inc,tmp:hasOpen&f=provider,inc,bda:CP026

**Comment by berger-n** [comment]
almost done: https://library.bdrc.io/search?q=%22%27phags%20pa%20rgyal%20bu%20don%20grub%20kyi%20mdo%22~1&lg=bo-x-ewts&t=Instance&pg=1&f=provider,inc,bda:CP052

![image](https://user-images.githubusercontent.com/33383857/99520236-29042180-2993-11eb-98a4-1e9106f8f1c7.png)

---

https://library.bdrc.io/show/bdr:MW0IDP0002?part=bdr:MW0IDP0002_2

![image](https://user-images.githubusercontent.com/33383857/99520375-4df89480-2993-11eb-830c-d4336246bd33.png)

![image](https://user-images.githubusercontent.com/33383857/99520414-58b32980-2993-11eb-85bb-f5efe4384a06.png)

---

note that if we open https://library.bdrc.io/show/bdr:MW0IDP0002_2 there is no `originalRecord` [here](https://purl.bdrc.io/query/graph/ResInfo-SameAs?R_RES=bdr%3AWA0RK0351&format=json) so the permalink/header are not set: 

![image](https://user-images.githubusercontent.com/33383857/99520736-c52e2880-2993-11eb-995a-df6f8b65df85.png)

**Comment by eroux** [comment]
thanks!
