### ISSUE TITLE
crash on IDP work

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#359]
https://library.bdrc.io/show/bdr:WA0IDP0002_3?tabs=bdr:MW0IDP0002_3

**Comment by berger-n** [comment]
can't reproduce neither in chrome nor firefox... 
is there an error message in the console?

**Comment by eroux** [comment]
it seems that it happens after a few clicks: if you go there, click on version, click on "In: ...." and it crashes

**Comment by eroux** [comment]
another bug: if you go on https://library.bdrc.io/show/bdr:PR0IDP001 and click on "Stein Collection", then go to to the record but the main label of the record is the same as the label of the instance instead of being the label of the Stein collectin

**Comment by berger-n** [comment]
crash is fixed on https://library.bdrc.io/show/bdr:MW0IDP0002
and title of collection is the good one:

![Kazam_screencast_00002 mp4](https://user-images.githubusercontent.com/33383857/99561874-bcefe080-29c7-11eb-83f4-2419e42191cb.gif)

**Comment by eroux** [comment]
great, thanks!
