### ISSUE TITLE
search within a work

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#36]
there should be a way to search inside a text, two use cases are obvious:
- search inside one etext only
- search in the titles of works contained in a work

This could be done by adding a little syntax in the search bar, something like `in::bdr:W23703`, so searching `in::bdr:W23703 byang chub sems dpa` would find `bdr:W23703_3871` (among other things possibly). It would require a new query in lds-query I think, but nothing insurmountable...

**Comment by berger-n** [comment]
great idea!
