### ISSUE TITLE
language for ontology properties

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#360]
The object of some properties should be considered part of the UI, that's the case for resources that are given in the ontology model. For instance on https://library.bdrc.io/show/bdr:MW0IDP0002 this should be the case for the object of print method, binding, etc. which currently appear in Tibetan but should be in English (and also probably shouldn't be links, just like print method)

**Comment by berger-n** [comment]
now when url is found in ontology we don't put a link but instead add any comment in menu:

![image](https://user-images.githubusercontent.com/33383857/99666623-8075c080-2a6b-11eb-875c-1d6ee0996c6d.png)

**Comment by eroux** [comment]
excellent, thanks a lot!
