### ISSUE TITLE
link to associated resources

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#363]
Let's create a link to associated resources in every entity, even when there is nothing returned by ResInfo-sameAs. The type should probably be version by default... The most urgent is to implement this on https://library.bdrc.io/show/bdr:PR0IDP001 so that we can demo it.

an idea would be that when no associated resource is returned by ResInfo-sameAs, the app calls `countAssociatedTypes` and links to the search results of the first available type.

another idea related to https://github.com/buda-base/public-digital-library/issues/362 (also not urgent): instead of opening the associated versions by default, we could run the associated persons in auto type

**Comment by berger-n** [comment]
done
when there is nothing related it fetches `countAssociatedTypes` and uses type with the maximum numbers of results (version being used as a fallback)
ex:
https://library.bdrc.io/show/bdr:PR0IDP001 (**3 instances**)
https://library.bdrc.io/show/bdr:WA0IDP0001?tabs=bdr:MW0IDP0001 (**1 topic** / 1 instance)
https://library.bdrc.io/show/bdr:W12827 (**12 versions** / 1 topic)
https://library.bdrc.io/show/bdr:W22084 (n/a, anchor to related works)

on the last one there is no link because there are only 2 (less than 5) works
but query has other results to show: https://library.bdrc.io/search?r=bdr:WA22084&t=Work 
shouldn't we find something to put it on the resource page?

**Comment by eroux** [comment]
Ah excellent! I can't see it on library nor library-dev though, are you sure you deployed?

**Comment by eroux** [comment]
Here's an idea:
- in addition to all other tabs of associated resources, there should be an additional one with the title "All (X)" where X is the sum of all the hits by type in countAssociatedTypes (so it's not present by default, only if the query is triggered)
- when there's nothing in the other tabs (or when in a type with no other tab), this one should be open by default
- when the tab is open, the query is triggered and the display is like in the other tabs except:
   * each item is a type, with the corresponding icon
   * the title of each item is just the type, with the number of hits in parenthese (ex: "Versions (2)")
   * the items are sorted by number of hits
   * when clicking on each item, there's a link to the search page, with the corresponding type open
- If there's no hit returned by the query, we should display "no associated resources found"
- when clicking on the "browse all" button, it goes to the type with the largest number of hits

**Comment by berger-n** [comment]
not far from finished here: http://library-dev.bdrc.io/show/bdr:PR0IDP001

![image](https://user-images.githubusercontent.com/33383857/100103632-6f5ef200-2e65-11eb-8601-46470fd54ea3.png)

you can also have a look at:
http://library-dev.bdrc.io/show/bdr:C35
http://library-dev.bdrc.io/show/bdr:WA22084
http://library-dev.bdrc.io/show/bdr:G3466
http://library-dev.bdrc.io/show/bdr:P4956
http://library-dev.bdrc.io/show/bdr:C38

one last thing to do is finding a resource which associated types returns nothing

**Comment by eroux** [comment]
excellent, thanks a lot!

http://library-dev.bdrc.io/show/bdr:PR0IDP001

is also good! I'm wondering if the "Show all" is necessary though, I think in my initial description I just meant that when clicking on the already existing "see all" button, it goes on the type with the most hits

**Comment by berger-n** [comment]
I've replaced "Show all" by "See result/s"
(the idea is to have quite the same display as on other tabs)

I've also found some unrelated resources like http://library-dev.bdrc.io/show/bdr:T607 :

![image](https://user-images.githubusercontent.com/33383857/100129822-5153ba80-2e82-11eb-9943-5b0ed990d049.png)

**Comment by eroux** [comment]
ah the no associated resources found looks good, thanks! I don't think I fully realized that we had these "read more", "see result, "show all", etc. below the yellow squares... I don't think they bring any kind of information... maybe we could remove them entirely?

**Comment by berger-n** [comment]
ok why not!
done:

![image](https://user-images.githubusercontent.com/33383857/100134176-194f7600-2e88-11eb-8fe7-1cfe9306d507.png)

**Comment by eroux** [comment]
great, even better :) I think we can deploy and close the issue!

**Comment by berger-n** [comment]
done: https://library.bdrc.io/show/bdr:P1583

**Comment by eroux** [comment]
thanks!
