### ISSUE TITLE
display extended properties like normal ones

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#364]
Currently extended properties can be folded, which leads to their display being different from the normal properties. Let's change that and display them in the same way as the normal ones (keeping the gray background)

**Comment by berger-n** [comment]
I think we're good here: 
- https://library.bdrc.io/show/bdr:MW22084?tabs=bdr:W22084#ext-info

![image](https://user-images.githubusercontent.com/33383857/100360784-b2ea6500-2ff9-11eb-8baa-403a6365f099.png)
--

- https://library.bdrc.io/show/bdr:P1583#ext-info

![image](https://user-images.githubusercontent.com/33383857/100360864-c990bc00-2ff9-11eb-9dd1-f337182a2197.png)
--

**Comment by eroux** [comment]
Yay, excellent! thanks!
