### ISSUE TITLE
original record shouldn't be displayed in the search results

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#366]
or at least not in the way they are on

https://library.bdrc.io/search?r=bdr:PR0IDP001&t=Instance&s=title%20forced

note that on

https://library.bdrc.io/search?q=%22saddharmapundarika%22&lg=inc-x-ndia&t=Instance&f=asset,inc,tmp:hasOpen

it's fine, they're not displayed. We could think of adding links in the bottom right corner like the TOL links on

https://library.bdrc.io/search?q=%22gampopa%22&lg=en&t=Person

though, that would probably be best

**Comment by eroux** [comment]
also, "relation type" shouldn't be displayed neither I think... it's already in the facets and it takes some room, let's try to hide it too

**Comment by berger-n** [comment]
done: https://library.bdrc.io/search?r=bdr:PR0IDP001&t=Instance&s=title

![image](https://user-images.githubusercontent.com/33383857/99983477-30b93100-2dac-11eb-98b5-c9cffe24b941.png)

(it seems that there is no `originalRecord` in [query](https://purl.bdrc.io/lib/instanceFacetGraph?LG_NAME=inc-x-ndia&L_NAME=%22saddharmapundarika%22) called on https://library.bdrc.io/search?q=%22saddharmapundarika%22&lg=inc-x-ndia&t=Instance&f=asset,inc,tmp:hasOpen
if there were, the link would be displayed there as well now)

**Comment by eroux** [comment]
excellent, thanks a lot!
