### ISSUE TITLE
links to BuddhaNexus

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#367]
I've imported some links to [BuddhaNexus](https://buddhanexus.net), they're on canonical works such as https://library.bdrc.io/show/bdr:WA0RK0024 (occasionally there are multiple links like in this example but it's rare). The property is `rdfs:seeAlso` but if there's a more usual one I can use it too.

The icon they have on their website has a good resolution, we could use it

**Comment by berger-n** [comment]
what about using `sameAs` instead of `seeAlso`?
if it's ok everything should work out of the box (icon excepted of course)
if not I'll make use of the `seeAlso`

**Comment by eroux** [comment]
I think it's fine, I've just changed the links to sameAs and indeed, it works except for the icon!

**Comment by eroux** [comment]
excellent, thanks!

**Comment by berger-n** [comment]
I've found a icon of the tree with no background, it seems a bit more readable, wdyt?

![image](https://user-images.githubusercontent.com/33383857/100246011-f4670b80-2f38-11eb-8670-12c2ac9b8fef.png)

![image](https://user-images.githubusercontent.com/33383857/100246053-021c9100-2f39-11eb-8f39-19ef2f182d24.png)

**Comment by eroux** [comment]
ah yes, much better, thanks!

**Comment by eroux** [comment]
so, I've had a chat with the people at BuddhaNexus and they'd rather have another one, with the frame and the name, even if it's small... can we change it to https://buddhanexus.net/src/assets/img/buddhanexus_logo.png but with a `6d5f47` background so that it looks like the home page of https://buddhanexus.net/ ?

**Comment by berger-n** [comment]
done:

![image](https://user-images.githubusercontent.com/33383857/100597526-da914400-32fd-11eb-81a6-6204535e2943.png)

![image](https://user-images.githubusercontent.com/33383857/100597580-ebda5080-32fd-11eb-877c-d884190e6ead.png)

**Comment by eroux** [comment]
Thanks! It's really tiny but well... let's see what they say!
