### ISSUE TITLE
ability to copy some text

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#368]
I've been wanting to copy the note at the bottom of

http://library-dev.bdrc.io/show/bdr:MW8LS16354

twice but I don't think it's possible right? If I try to select some text, as soon as I select it the popup appears and my text is not selected anymore so I can't copy it, and if I try to select the text of the popup, the popup disappears with the text so I can't select it neither...

I'm sure there are solutions for that, in case there's nothing obvious, we could make the popup so that clicking on the initial text doesn't close the popup but lets it open... wdyt?

**Comment by berger-n** [comment]
fixed
(popup doesn't close when clicking on it now: "copy made available from the collection of skye dgu zhang 'gu dgon a gro")

**Comment by eroux** [comment]
great, that's a relief, thanks!
