### ISSUE TITLE
viewer artifact when no images to display

### ISSUE THREAD

**Issue by xristy** [buda-base/public-digital-library#37]
When showing a [Work with no images to display](http://library.bdrc.io/show/bdr:W23702_1524) there is an artifact where the image viewer selection would be displayed:

![screen shot 2018-11-27 at 9 48 22 am](https://user-images.githubusercontent.com/3542294/49093647-2221f880-f22a-11e8-979f-bced2283b740.png)

The artifact disappears when leaving and returning to the page but reappears on reloading

**Comment by berger-n** [comment]
what browser/version are you using ?
I can't reproduce this bug

**Comment by xristy** [comment]
Safari 12.0.1 on Mac OS X 10.13.6. I don't see it on Chrome or FF so it's a corner case, but it seems to me to indicate that the client is ready to display the initial image and viewer selection prior to "knowing" whether there are images to display. I.e., it appears that the waiting spinner is momentarily replaced by an empty frame when there are no images. Something like that perhaps could wait until it is known whether there are images or not. It might surface as an issue on future versions of browsers
