### ISSUE TITLE
handling cases where there's no volume 1

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#370]
In some cases such as https://library.bdrc.io/show/bdr:W3CN23000 there's a thumbnail but no volume 1 (the manifest is a 404). In these cases nothing happens when I click on the image (mirador doesn't open). In this case mirador should open on the collection manifest

**Comment by berger-n** [comment]
fixed:

![image](https://user-images.githubusercontent.com/33383857/100263652-1454fa00-2f4e-11eb-8ffe-a7434c557df8.png)

**Comment by eroux** [comment]
great, thanks!
