### ISSUE TITLE
[design] highlight links a bit more

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#371]
I think the links to our partners could be highlighted a bit more, here are 3 proposals:
- remove the BDRC logo when there's no link (so that what's in there has a meaning that's easier to understand)
- add "Links: " on the left of the icons (when there are some)
- add a little design highlight on the area of the permalink bar that has the links, perhaps a separator and / or a different background...

**Comment by berger-n** [comment]
done this, wdyt? 
- https://library.bdrc.io/show/bdr:P4956

![image](https://user-images.githubusercontent.com/33383857/100376304-8fcab000-300f-11eb-9c49-55d28e0f6da7.png)
--

- https://library.bdrc.io/show/bdr:WA4CZ16799

![image](https://user-images.githubusercontent.com/33383857/100376345-a96bf780-300f-11eb-97a7-5d496c38e70b.png)
--

- https://library.bdrc.io/show/bdr:WA12827

![image](https://user-images.githubusercontent.com/33383857/100376431-ca344d00-300f-11eb-9452-7ce8e5259393.png)

![image](https://user-images.githubusercontent.com/33383857/100376464-dcae8680-300f-11eb-92e4-ae41742bbd2c.png)

**Comment by eroux** [comment]
ah, this is very good indeed! Perfect, thanks a lot!
