### ISSUE TITLE
collection view of Wanli Kangyur broken

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#372]
When I open mirador on

https://library.bdrc.io/show/bdr:WSBB_WKG

I see:

![Capture d’écran de 2020-11-27 08-15-38](https://user-images.githubusercontent.com/60868/100421614-fe981f80-3088-11eb-9503-852b8be8deaf.png)

(after the veeeery slow manifests of the Stabi eventually load)

**Comment by berger-n** [comment]
there seem to be a problem with their logo which is not available from the url in the manifest: https://ngcs-beta.staatsbibliothek-berlin.de/dc/logo-small ("connection timeout")
I'll try to replace it on the fly with https://www.facebook.com/349741960101/photos/10150978030560102/ (unless you have another logo in mind?)
other images seem to load pretty fast: https://content.staatsbibliothek-berlin.de/dc/3376911134-0011/full/full/0/default.jpg

now let's fix thumbnails and volume opening

**Comment by berger-n** [comment]
https://content.staatsbibliothek-berlin.de/dc/logo-small works ...

**Comment by eroux** [comment]
arf indeed... yes, let's replace it on the fly for now :( The Facebook image will be good for https://github.com/buda-base/public-digital-library/issues/373 though (better than the other I think

**Comment by berger-n** [comment]
it works now: https://library.bdrc.io/view/bdr:WSBB_WKG

![image](https://user-images.githubusercontent.com/33383857/100456116-2191f600-30c0-11eb-8ca2-09c217c5611f.png)

**Comment by eroux** [comment]
great!
