### ISSUE TITLE
add Stabi icon

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#373]
we're in the process of importing an interesting collection frome the Stabi and we should add the proper icon so that it displays nicely. The new collection is not imported yet but we already have one item from another collection:

https://library.bdrc.io/show/bdr:MWSBB_WKG

https://library.bdrc.io/search?q=%22bka%27%20%27gyur%20wan%20li%22&lg=bo-x-ewts&t=Instance&n=1

**Comment by eroux** [comment]
I think we could take the one with the eagle (which is... what it is), the one in https://digital.staatsbibliothek-berlin.de/images/SBB_Logo_White_DIN_A6.png .

The URLs typically start with http://resolver.staatsbibliothek-berlin.de/

**Comment by berger-n** [comment]
done:

![image](https://user-images.githubusercontent.com/33383857/100472146-f5846e00-30db-11eb-8680-95afafd2557c.png)

![image](https://user-images.githubusercontent.com/33383857/100472166-03d28a00-30dc-11eb-9c8c-1294d1fc3a06.png)

![image](https://user-images.githubusercontent.com/33383857/100472197-0f25b580-30dc-11eb-9e06-fa708be05c86.png)

**Comment by eroux** [comment]
perfect, thanks!
