### ISSUE TITLE
isAbout shouldn't remove links

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#375]
for instance on https://library.bdrc.io/show/bdr:WA0XL41C2D829881B the links should stay. Also, I think when we remove the links such as for gender, material, etc. we should display the links in the popup box

**Comment by berger-n** [comment]
regarding  `isAbout` the links are still here:

![image](https://user-images.githubusercontent.com/33383857/100458179-9fa3cc00-30c3-11eb-872c-eeecb20d3b75.png)

![image](https://user-images.githubusercontent.com/33383857/100458202-aa5e6100-30c3-11eb-85a3-efd4291d7c2e.png)

(link is removed only when url is to be found in ontology - should be easy to add it back in popup)

**Comment by eroux** [comment]
great, thanks!

**Comment by berger-n** [comment]
done: 

![image](https://user-images.githubusercontent.com/33383857/100475617-dee21500-30e3-11eb-8efd-a4eb011210dc.png)

![image](https://user-images.githubusercontent.com/33383857/100475672-03d68800-30e4-11eb-8372-625b470aefe8.png)

now we still have to handle #281++:

![image](https://user-images.githubusercontent.com/33383857/100475758-35e7ea00-30e4-11eb-939b-3929292497a0.png)

**Comment by eroux** [comment]
ah, neat, thanks a lot! yes 281 would be good, but no emergency
