### ISSUE TITLE
[user report] message indicating reason for no PDF download

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#378]
Some IIIF providers don't provide PDF download, that's the case for EAP for instance. In that case we gray out the "download" button in Mirador (in https://library.bdrc.io/show/bdr:WEAP039-1-4-259 for instance), which is good. I think in addition to that we should also have a small `?` in a disc icon that can be clicked and would display a small popup saying something like:

```
The provider of these images does not provide PDF download functionality. BDRC does not have a copy of these images and thus cannot provide a PDF export either.
``` 

(or maybe just a hover with that message would be enough actually, that's more simple to implement)

**Comment by berger-n** [comment]
done: http://library-dev.bdrc.io/view/bdr:WEAP039-1-4-259

![image](https://user-images.githubusercontent.com/33383857/102241426-3c0a0300-3ef9-11eb-8511-786e72b262ce.png)

**Comment by eroux** [comment]
great, thanks!
