### ISSUE TITLE
some dates not appearing in the query results

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#379]
most of the time it works but in some cases it doesn't, for instance:

https://library.bdrc.io/search?q=%22padma%20dkar%20po%22&lg=bo-x-ewts&t=Person&n=1

should display dates for the first result. This may be a problem in the query, I haven't checked yet

**Comment by berger-n** [comment]
it seems that [query](http://purl.bdrc.io/lib/personGraph?LG_NAME=bo-x-ewts&L_NAME=%22padma%20dkar%20po%22) contains century indication ("16") but no precise date

**Comment by eroux** [comment]
ok thanks! I'll take care of it

**Comment by eroux** [comment]
so, it appears that the two results of this query are from TOL and SRC, but there's no match in BDRC's database. This is a bit counter-intuitive but at its core this issue is https://github.com/buda-base/lucene-bo/issues/29 so let's close this one
