### ISSUE TITLE
can't see language selection when the title is too long

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#380]
for instance if you type `byang gter phur pa'i sri chung bcu gsum gyis mnan pa'i lhan thabs rab gsal me long zhes bya ba bzhugs so` in the search bar I see

![Capture d’écran de 2020-11-29 15-34-21](https://user-images.githubusercontent.com/60868/100544792-6fd9fd00-3258-11eb-8214-64a5e8439769.png)

which is not very helpful... so we should cut the title in the dropdown list so that the languages are always visible

**Comment by berger-n** [comment]
done
not sure of which variant to choose though:

![image](https://user-images.githubusercontent.com/33383857/100646154-f3b9e500-333d-11eb-9611-2d1b9c727ec7.png)

--

![image](https://user-images.githubusercontent.com/33383857/100646336-32e83600-333e-11eb-9163-2ab5ae776bef.png)

**Comment by eroux** [comment]
ah excellent! I think the second one is clearer

**Comment by berger-n** [comment]
ok thanks! done

**Comment by eroux** [comment]
perfect, thanks!
