### ISSUE TITLE
not using https all the time

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#381]
Some of our partners don't have https, that's the case for rKTs, so links on BUDA don't work, for instance

https://library.bdrc.io/show/bdr:WA0RK0024

has a link to rKTs in https but it doesn't work, while the http version does... it's quite unfortunate but let's only convert to https for domains in `*.bdrc.io`

**Comment by berger-n** [comment]
rKTs link works now
I also fixed the case when there are multiple resource from one provider
now it looks exactly the same as in results:
- https://library.bdrc.io/show/bdr:WA0RK0024

![image](https://user-images.githubusercontent.com/33383857/100638946-e3e9d300-3334-11eb-89ac-62509496914c.png)
--

- https://library.bdrc.io/show/bdr:P4956

![image](https://user-images.githubusercontent.com/33383857/100639270-3f1bc580-3335-11eb-9697-66a8e4af85a0.png)

--

yet note that in the latter case it seems that the Himalayan Art link is not returned by [query](https://purl.bdrc.io/lib/associatedPersons?R_RES=bdr%3AP8205):

![image](https://user-images.githubusercontent.com/33383857/100639683-c9fcc000-3335-11eb-9790-df1cd75faac8.png)

**Comment by eroux** [comment]
ah excellent, thanks! For the HAR link, IIRC it's only in the TOL record so it's not really returned by the search results which don't fully merge the sameAs records like the resource page does
