### ISSUE TITLE
collection members should be assumed versions, not works

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#382]
When looking at https://library.bdrc.io/show/bdr:PR0IDP001 the icon for the collection members should be the version icon, not the works one. We could imagine having collections of works but we don't have any and I don't think we envision having one any time soon...

**Comment by berger-n** [comment]
fixed:

![image](https://user-images.githubusercontent.com/33383857/100598530-242e5e80-32ff-11eb-915e-040b39d27dfa.png)

**Comment by eroux** [comment]
perfect, thanks!
