### ISSUE TITLE
stop spinning when manifest is 404

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#383]
for instance in https://library.bdrc.io/show/bdr:MW1KG1680_0FB602 the manifest is not a 200 code, it should display a barred images logo (or nothing in a first time)

**Comment by berger-n** [comment]
fixed:

![image](https://user-images.githubusercontent.com/33383857/100627638-83a06480-3327-11eb-821a-4f51b1a81ae6.png)

**Comment by eroux** [comment]
perfect!
