### ISSUE TITLE
location display broken in some cases

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#384]
in https://library.bdrc.io/show/bdr:MW1KG1680_0FB602 the "Location: " line is broken, it's just a link to the W record, while I think we have a nice display in other cases, with "image X to Y in volume Z"

**Comment by berger-n** [comment]
fixed:

![image](https://user-images.githubusercontent.com/33383857/100627683-93b84400-3327-11eb-8b19-b6128a9d71f0.png)

**Comment by eroux** [comment]
great, thanks a lot!
