### ISSUE TITLE
in absence of prefLabel, an instance or work should have [no title]

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#385]
for instance in https://library.bdrc.io/show/bdr:MW0IDP0002_1 the `bdr:MW0IDP0002_1` should be replaced by `[no title]`

**Comment by berger-n** [comment]
done:

![image](https://user-images.githubusercontent.com/33383857/100623485-85b3f480-3322-11eb-8a4c-9069a7d22c47.png)

**Comment by eroux** [comment]
great, thanks!
