### ISSUE TITLE
spurious "other label" in associated resources

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#386]
see https://library.bdrc.io/search?r=bdr:PR0SBB001&t=Scan&s=title%20forced&pg=1

but the [query](https://purl.bdrc.io/lib/associatedIInstances?R_TYPE=bdo%3AScan&R_RES=bdr%3APR0SBB001&format=json) only returns one label... Is it because the label is in Tibetan Unicode?

It doesn't do that in other cases such as

https://library.bdrc.io/search?r=bdr:PR1VIENNA00&t=Scan&s=title%20forced

**Comment by berger-n** [comment]
the issue was indeed caused by tibetan unicode
it's fixed:

![image](https://user-images.githubusercontent.com/33383857/100620749-0f61c300-331f-11eb-987d-8582f5bd1760.png)

**Comment by eroux** [comment]
perfect, thanks!
