### ISSUE TITLE
Leiden University Library logo

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#389]
For records such as https://library.bdrc.io/show/bdr:W0LULDC1646858 we would need the University library logo, I think taking the left part of https://www.universiteitleiden.nl/ul2common/images/zegel.png would be good (not the test). There are still some errors in the records, it's WIP sorry!

**Comment by eroux** [comment]
also it seems some adjustments in the reading view are needed, it seems to request images that are too big... (and there's also a very weird first canvas?)

**Comment by berger-n** [comment]
for the logo there is https://iiifviewer.universiteitleiden.nl/logo/ in their manifest which seems perfect!
the scans are grouped by four, first one excepted:

- https://iiif.universiteitleiden.nl/iiif/2/hdl%3A1887.1%2Fitem%3A1646861/full/3162,/0/default.jpg:
![image](https://user-images.githubusercontent.com/33383857/101071539-09791580-359d-11eb-9a9b-5615813ec9f2.png)
- https://iiif.universiteitleiden.nl/iiif/2/hdl%3A1887.1%2Fitem%3A1646859/full/712,/0/default.jpg
![image](https://user-images.githubusercontent.com/33383857/101071608-21e93000-359d-11eb-893d-3a97a60b1ad2.png)

and these are the url from the manifest: https://digitalcollections.universiteitleiden.nl/iiif_manifest/item:1646858/manifest

**Comment by eroux** [comment]
Indeed they didn't crop their images, it's not very convenient to read but well... but when I open the reading view I see

![Capture d’écran de 2020-12-03 19-43-05](https://user-images.githubusercontent.com/60868/101073623-0895b300-35a0-11eb-8b61-0c14a8d16c14.png)

and I get a 403 on 

https://iiif.universiteitleiden.nl/iiif/2/hdl%3A1887.1%2Fitem%3A1646861/full/4845,/0/default.jpg

which blocks the loading of the first image... do you see that too? no rush, we can deal with that later

**Comment by eroux** [comment]
P.S.: yes, this logo is perfect indeed!

**Comment by berger-n** [comment]
added the logo: 
- http://library-dev.bdrc.io/search?r=bdr:WA0LULDC1646858&t=Instance

![image](https://user-images.githubusercontent.com/33383857/101166489-a63cc100-3638-11eb-8adb-942bf664f323.png)

- http://library-dev.bdrc.io/show/bdr:WA0LULDC1646858

![image](https://user-images.githubusercontent.com/33383857/101167490-40513900-363a-11eb-9a9a-165e6ff0b975.png)

![image](https://user-images.githubusercontent.com/33383857/101167601-74c4f500-363a-11eb-925a-01f9dc8ee8ae.png)

**Comment by eroux** [comment]
looks perfect, thanks a lot!

**Comment by berger-n** [comment]
images look better now: http://library-dev.bdrc.io/view/bdr:W0LULDC1646858

![image](https://user-images.githubusercontent.com/33383857/101200775-0f3b2d80-3667-11eb-9b42-b390b47a6022.png)

BTW I've added the 3500 max limit, compare http://library-dev.bdrc.io/view/bdr:I1CZ5005 with previous version https://library.bdrc.io/view/bdr:I1CZ5005 (especially thumbnails in page view)

**Comment by eroux** [comment]
oh this is really good, thanks! Maybe we can deploy in prod?

**Comment by berger-n** [comment]
indeed! done

**Comment by eroux** [comment]
great, thanks!
