### ISSUE TITLE
changing type is buggy

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#391]
to reproduce:
- go to https://library.bdrc.io/search?q=%22Performance%22&lg=en&t=Instance&f=asset,inc,tmp:hasOpen (instance selected)
- click on topics on the left
- experience disappointment as there is no result despite the fact that the count on the left says 4
- go back to instances
- go back to topics
- topics have appeared

**Comment by berger-n** [comment]
this is odd! let's fix that

**Comment by berger-n** [comment]
fixed:

![Kazam_screencast_00004 mp4](https://user-images.githubusercontent.com/33383857/101381477-135d8a00-38b7-11eb-95cb-86a1f241e6d8.gif)

`[off-topic]` 
isn't it a bit strange that [countTypes](https://purl.bdrc.io/query/table/countTypes?LG_NAME=en&I_LIM=500&LI_NAME=700&L_NAME=%22Performance%22) returns 288 whereas actual [query](https://purl.bdrc.io/lib/workFacetGraph?LG_NAME=en&L_NAME=%22Performance%22) 9? 
reminds me of https://github.com/buda-base/lds-queries/issues/17 
`[/off-topic]`

**Comment by eroux** [comment]
ah thanks a lot! It's strange indeed... I'll take a look

**Comment by berger-n** [comment]
same bug here:
https://library.bdrc.io/search?q=%22leiden%22&lg=en&t=Person
