### ISSUE TITLE
small highlight bug on publishername

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#392]
In this search: https://library.bdrc.io/search?q=%22bkra%20shis%20lhun%20grub%22~1&lg=bo-x-ewts&t=Instance&f=asset,inc,tmp:hasOpen one of the matches is in the publisher name but the highlight doesn't work and keeps the `↦↤`

**Comment by berger-n** [comment]
works better now: 

![image](https://user-images.githubusercontent.com/33383857/101485347-507b5800-395b-11eb-9b70-aefda9742ed0.png)

---

however there are a few things still to be fixed:
- [ ] publisher in result 2 above should be highlighted 
- [ ] highlighting transliterated matches seem to fail in result title: https://library.bdrc.io/search?q=%22bkra%20shis%20lhun%20grub%22~1&lg=bo-x-ewts&t=Instance&f=asset,inc,tmp:hasOpen&uilang=bo

![image](https://user-images.githubusercontent.com/33383857/101485521-90423f80-395b-11eb-8ef2-b6627957a52a.png)

**Comment by eroux** [comment]
Yes, this is a data problem, not really a technical one, see https://github.com/buda-base/xmltoldmigration/issues/158

**Comment by eroux** [comment]
anyways, thanks a lot!
