### ISSUE TITLE
extended matches shouldn't be displayed as the main title of the work matches

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#393]
For instance in https://library.bdrc.io/search?q=%22performance%22&lg=en&t=Work i've just added the extended matches, and most of them are in the `catalogInfo` field but they appear as the main label

**Comment by eroux** [comment]
oh, note that the same bug appears on the Versions results too

**Comment by berger-n** [comment]
I've added `catalogInfo` to results for Work so as [this](http://library-dev.bdrc.io/search?q=%22rituals%20for%20the%20performance%22&lg=en&t=Work) becomes [that](https://library.bdrc.io/search?q=%22rituals%20for%20the%20performance%22&lg=en&t=Work):

![image](https://user-images.githubusercontent.com/33383857/101395344-1c0b8b80-38ca-11eb-9b27-cf2ba5b84856.png)



but are sure what you're reporting is a bug?
to me these are matching `altLabels`, at least regarding these [four leading results](https://library.bdrc.io/search?q=%22for%20the%20performance%22&lg=en&t=Work) having a match in their main title:

![image](https://user-images.githubusercontent.com/33383857/101395524-5ecd6380-38ca-11eb-9639-3ce14630f783.png)

there also seems to have duplicate catalogInfo in [query for versions](http://purl.bdrc.io/lib/instanceFacetGraph?LG_NAME=en&L_NAME=%22rituals%20for%20the%20performance%22):

![image](https://user-images.githubusercontent.com/33383857/101396135-2f6b2680-38cb-11eb-9f29-b330887d41bc.png)

resulting in duplicate display:

![image](https://user-images.githubusercontent.com/33383857/101396259-575a8a00-38cb-11eb-96c1-926e780b79e7.png)

(but I guess I'll have to handle these client-side)

**Comment by eroux** [comment]
Ah thanks! I'll have a look at the duplicates in catalogInfo tomorrow. Matches in altLabels are interesting... Do we have another place to display them? maybe a Other title? The ideal would be to always display the prefLabel as the main label for the item (not the altLabel, even when there's a match)... would that be complex to represent?

**Comment by eroux** [comment]
Ah, well, actually the duplicate catalogInfo (one with highlight, one without) should be handled on the client indeed, like the prefLabel

**Comment by eroux** [comment]
actually never mind: https://github.com/buda-base/xmltoldmigration/issues/156

**Comment by eroux** [comment]
duplicates have disappeared! also, related: https://github.com/buda-base/lds-queries/issues/61

**Comment by berger-n** [comment]
well done, thanks! 
I've noticed that highlighting has disappeared in matching note here: https://library.bdrc.io/search?q=%22rituals%20for%20the%20performance%22&lg=en&t=Instance&f=asset,inc,tmp:hasOpen
I can put in back using case insensitive search for keyword but it will use keyword instead of original string in highlighted property value (capital letters might disappear), is that ok?

![image](https://user-images.githubusercontent.com/33383857/101472508-fbcee180-3948-11eb-8785-8378bf6754d6.png)

**Comment by eroux** [comment]
hmmm... it's more or less intended as it's a field that comes from the work and the search actually doesn't search on this field (it's a coincidence that there's a match here)... so, maybe let's not do that, at least not now

**Comment by berger-n** [comment]
nevermind I managed to keep the original string:

![image](https://user-images.githubusercontent.com/33383857/101473321-f8882580-3949-11eb-93c2-8ea73e3f042a.png)

this is the default behaviour to look for keyword and highlight it when found
do you want to disable it in this "catalogInfo of version" special case?

**Comment by eroux** [comment]
ah no never mind, if it's already in place let's keep it!

**Comment by berger-n** [comment]
`altLabels` are not used in result title anymore: https://library.bdrc.io/search?q=%22for%20the%20performance%22&lg=en&t=Work

![image](https://user-images.githubusercontent.com/33383857/101474650-bf50b500-394b-11eb-8ba8-6ee515ce3927.png)

**Comment by eroux** [comment]
great, thanks a lot!

**Comment by berger-n** [comment]
just fixed missing highlighting here: http://library-dev.bdrc.io/search?q=%22Mar%20me%20smon%20lam%22~1&lg=bo-x-ewts&t=Instance

![image](https://user-images.githubusercontent.com/33383857/105980904-bbacf500-6095-11eb-8c1a-838898dc0b2e.png)

not using matching `altLabel` as result title as expected here: http://library-dev.bdrc.io/search?q=%22for%20the%20performance%22&lg=en&t=Work

![image](https://user-images.githubusercontent.com/33383857/105981550-7e953280-6096-11eb-98b0-a2aed0546db1.png)
