### ISSUE TITLE
[user request] new facet: know roles for persons

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#395]
This will require a change in the query so I need to implement that first, but I'm tracking it here

**Comment by eroux** [comment]
I've implemented a new property for persons (that is automatically generated through a cache) called `tmp:hasRole` and it's not returned by the query ([example](https://purl.bdrc.io/lib/personGraph?LG_NAME=bo-x-ewts&L_NAME=%22%27jigs%20med%20gling%20pa%22)). As it's an elaboration on the previous tmp:isCreator property, I've removed this one. So I think it's ready for implementation, it can be just another regular facet


Note that the property now appears on the records but it's fine... maybe we should just localize the name of the property

**Comment by berger-n** [comment]
thanks! I've just added Has Role facet: http://library-dev.bdrc.io/search?q=%22%27jigs%20med%20gling%20pa%22~1&lg=bo-x-ewts&t=Person&pg=1&f=role,inc,bdr:R0ER0025

![image](https://user-images.githubusercontent.com/33383857/102116188-e2440300-3e3c-11eb-89da-81a5a53bff93.png)

**Comment by eroux** [comment]
perfect, thanks!
