### ISSUE TITLE
more info in extended outline information

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#398]
We should have more info in the outline nodes, for instance the colophon:

https://library.bdrc.io/show/bdr:MW4CZ1042?part=bdr:MW4CZ1042_21C17B

has one but it's not displayed. creators, authorship statement, contentLocationStatement, incipit and explicit would also be good candidates

**Comment by berger-n** [comment]
[colophon](https://library.bdrc.io/show/bdr:MW4CZ1042_21C17B) is not returned by [query](http://purl.bdrc.io/query/graph/Outline_root?R_RES=bdr%3AMW4CZ1042_21C17B):

![image](https://user-images.githubusercontent.com/33383857/101656117-a414a100-3a42-11eb-85f4-5c86316db73b.png)

`contentLocationStatement` is already displayed, should it be moved to hidden/extended information?

![image](https://user-images.githubusercontent.com/33383857/101656328-dc1be400-3a42-11eb-8d1b-27fca50b7dae.png)

**Comment by eroux** [comment]
ok, it's added now! Note that authors have also been added (although not in that example, see [this node](https://library.bdrc.io/show/bdr:MW4PD3076?part=bdr:MW4PD3076_A47E91), from [this query](https://purl.bdrc.io/query/graph/Outline_root?R_RES=bdr%3AMW4PD3076_A47E91))

**Comment by berger-n** [comment]
thanks! 
almost done: http://library.bdrc.io/show/bdr:MW4CZ1042?part=bdr:MW4CZ1042_5A3A48

![image](https://user-images.githubusercontent.com/33383857/101665359-2efa9900-3a4d-11eb-8608-515fb50e72d7.png)

**Comment by berger-n** [comment]
added more properties:
- https://library.bdrc.io/show/bdr:MW0IDP0002?part=bdr:MW0IDP0002_7

![image](https://user-images.githubusercontent.com/33383857/101666648-c3193000-3a4e-11eb-97e0-2a8f59d421bf.png)

- https://library.bdrc.io/show/bdr:MW4PD3076?part=bdr:MW4PD3076_A47E91

![image](https://user-images.githubusercontent.com/33383857/101666708-d62c0000-3a4e-11eb-9c31-660d5b5c9073.png)

**Comment by eroux** [comment]
excellent!! thanks
