### ISSUE TITLE
crash in Safari

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#400]
report from Guli:

Safari 62.0+:

![image_2020_12_11T10_49_04_434Z](https://user-images.githubusercontent.com/60868/101895311-a80e0380-3ba7-11eb-8108-a9e580b32ee8.png)

and Safari 87.0+:

![image_2020_12_11T10_52_04_198Z](https://user-images.githubusercontent.com/60868/101895335-b2c89880-3ba7-11eb-86ad-c8493c8e1f4a.png)

**Comment by berger-n** [comment]
version numbers don't make sens for Safari https://en.wikipedia.org/wiki/Safari_version_history
still I can't reproduce neither in Safari 14/MacOS BigSur nor 13/Catalina and 13/High Sierra
I guess the url is http://buda.zju.edu.cn/show/bdr:W22084?

**Comment by eroux** [comment]
hmm I guess yes... do these version numbers make sense for Chrome?

**Comment by berger-n** [comment]
ok it is indeed a Safari output and I can finally reproduce in Safari 12
where `Intl.PluralRules` fails as expected https://caniuse.com/intl-pluralrules
(it was introduced with century facet [here](https://github.com/buda-base/public-digital-library/commit/6a33ddf71edfadfbef7cd74783ff5ad7f1da975e#diff-99acca0e99f2c9762a8880aa24af09136368b0b55234a1971e17963d6c4c07fe))
it seems there is a working polyfill for `Intl.PluralRules`: https://github.com/Financial-Times/polyfill-library/issues/227
should I try to use it?

**Comment by eroux** [comment]
arf ok... sure, let's try to use that. Otherwise there are only 21 values, we can hardcode it

**Comment by berger-n** [comment]
https://github.com/eemeli/intl-pluralrules works out of the box
no more crash here with the updated build: http://library-dev.bdrc.io/search?q=%22spyod%20%27jug%22&lg=bo-x-ewts&t=Instance&f=asset,inc,tmp:hasOpen 

![image](https://user-images.githubusercontent.com/33383857/101915128-7a37b780-3bc5-11eb-8155-ebf3fbc33e19.png)

whearas n-1 build still crashes here: http://library.bdrc.io/search?q=%22spyod%20%27jug%22&lg=bo-x-ewts&t=Instance&f=asset,inc,tmp:hasOpen

![image](https://user-images.githubusercontent.com/33383857/101915255-a7846580-3bc5-11eb-8656-7621226dd522.png)

**Comment by eroux** [comment]
that works, thanks!
