### ISSUE TITLE
wrong fallback mechanism on faulty thumbnail

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#402]
In https://library.bdrc.io/show/bdr:W0IA_HOD68  the thumbnail is indicated (with the `tmp:thumbnailIIIFService` property) as https://iiif.archivelab.org/iiif/rashodgson68$1 (which is good), and then the UI tries to load https://iiif.archivelab.org/iiif/rashodgson68$1/full/!1000,500/0/default.jpg . It fails but then instead of trying the same image with another dimension: https://iiif.archivelab.org/iiif/rashodgson68$1/full/,600/0/default.jpg , it tries the first images of the manifest which in the case of the archive.org manifest is the gray thing, which is quite ugly. So maybe when the thumbnail fetching fails the fallback should keep the same image?

**Comment by berger-n** [comment]
fixed it: http://library-dev.bdrc.io/show/bdr:W0IA_HOD68

![image](https://user-images.githubusercontent.com/33383857/102088585-68e7e880-3e1b-11eb-87cc-a6b4feb926fc.png)

**Comment by eroux** [comment]
excellent, thanks!
