### ISSUE TITLE
more labels in UI language

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#403]
Looking at https://library.bdrc.io/show/bdr:P314 the objects of two properties should be displayed in English and not Tibetan: "Has Role" and "Tradition"

**Comment by berger-n** [comment]
done: http://library-dev.bdrc.io/show/bdr:P314

![image](https://user-images.githubusercontent.com/33383857/102113643-8f1c8100-3e39-11eb-8659-6f972c791321.png)

**Comment by eroux** [comment]
great, thanks!
