### ISSUE TITLE
outline / independent record navigation

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#404]
The main problem that we have now (in the user feedback that I'm getting) is the navigation between the outline and the independent record (ex: https://library.bdrc.io/show/bdr:MW22084_0829 vs https://library.bdrc.io/show/bdr:MW22084?part=bdr:MW22084_0829 ). Here are a few things we can start with:

- [ ] when a result is in an outline, we should have two buttons:
   * open in outline (with the icon of the collection view in mirador: https://library.bdrc.io/scripts/mirador/images/collecR.svg )
   * open record (I'm not sure what icon we could use here... it would be useful to find one... perhaps something that looks like the page of the records, like 
![Drawing](https://user-images.githubusercontent.com/60868/102244758-036c2880-3efd-11eb-8a71-6daed8fabcba.png)

- [ ] in the record there should be a "view in outline" button, with the icon

**Comment by berger-n** [comment]
a first attempt on this:
- in results like http://library-dev.bdrc.io/search?q=%22kun%20%27dus%20rig%20pa%27i%20mdo%22&lg=bo-x-ewts&t=Instance&pg=1&f=asset,inc,tmp:hasOpen&f=asset,inc,tmp:hasEtext&f=asset,inc,tmp:hasImage&n=1

![image](https://user-images.githubusercontent.com/33383857/102894780-eb982580-4463-11eb-8300-c69639bce8bf.png)

- in node page like http://library-dev.bdrc.io/show/bdr:MW22084_0829

![image](https://user-images.githubusercontent.com/33383857/102894949-27cb8600-4464-11eb-8475-bf5d01995775.png)

**Comment by eroux** [comment]
Great! I imagined it pretty much like that!

**Comment by berger-n** [comment]
now deployed on library: https://library.bdrc.io/show/bdr:MW22084_0829
