### ISSUE TITLE
image viewer on mobile

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#405]
This is just to track it down as it's already been discussed and some templates have been produced. The image viewer (and particularly `public/embed-iframe.html`) should be working well on mobile, at least in landscape mode. We already have some mockups by Tania, here are a few considerations:
- it will certainly be difficult to display the outline + the volume list at the same time, I have a few ideas how to handle that, we can discuss it
- it's fine if some features disappear on small screens, I'm thinking of the image manipulation tools, etext display, image label display, etc.

**Comment by berger-n** [comment]
thumbnails now closed when opening OSD
+buttons to toggle menu bars
http://library-dev.bdrc.io/scripts/embed-iframe.html?work=bdr:I0886&origin=BDRCLibApp&uilang=en&lang=bo-x-ewts

![Kazam_screencast_00007 mp4](https://user-images.githubusercontent.com/33383857/103638528-5316a080-4f4d-11eb-8d56-73fc0e228905.gif)

next step will be to fix collection view

**Comment by eroux** [comment]
great, thanks a lot, this looks good!

**Comment by eroux** [comment]
I think something we could also try would be to have a next / previous page system in the page view that's linked to the swipe movement. It would be both vertically and horizontally: next page on swipe down or right, previous page on up or left (maybe with the exception of right to left direction where the horizontal axis would be inverted). It's probably challenging as the swipe movement is already associated with an action (moving the image when zoomed in)... I think it's worth exploring but if it's too complex we can keep it for later

**Comment by berger-n** [comment]
what I get in Chrome now (this is desktop version, but it's quite the same on mobile):

![Kazam_screencast_00008 mp4](https://user-images.githubusercontent.com/33383857/103804581-a7f00f00-5052-11eb-847f-397fd225da85.gif)

unfortunately it lags a lot more in Firefox on my mobile...

**Comment by eroux** [comment]
oh that looks better! On my firefox it's working fine but the speed of the movement is too fast I think and there seems to be no way to cancel (if I start to swipe, I can't stop turning the page, while on most systems if the page won't turn if I swipe back in the same movement)

**Comment by berger-n** [comment]
now you can "hold back" the image while it's going left/right before it leaves screen:

![Kazam_screencast_00001 mp4](https://user-images.githubusercontent.com/33383857/103928512-3a101a00-511c-11eb-9e87-1709ffdcb670.gif)

**Comment by berger-n** [comment]
this was kind of epic but I think I've managed to use the default browser "show/hide address bar on scroll up/down" behavior!

![Kazam_screencast_00002 mp4](https://user-images.githubusercontent.com/33383857/104050421-e7e7fb00-51e6-11eb-8310-2be1fb212bc0.gif)
http://library-dev.bdrc.io/scripts/embed-iframe.html?work=bdr:I4CZ75258&origin=BDRCLibApp&lang=bo-x-ewts&uilang=en

now there are issues with image re/loading, which seems to be off unless you make browser top menu appear/disappear (which triggers the resize event and force reloading) 

also I was thinking of using smaller images in reading view so as to make loading faster
+zoom UI in reading view needs some fixes/improvements as well

**Comment by berger-n** [comment]
fixed image re/loading bugs + improved collection view for LibApp:

![Kazam_screencast_00003 mp4](https://user-images.githubusercontent.com/33383857/104220788-49ef6d00-5440-11eb-8eaa-1bc52c106168.gif)

not far from good here!

**Comment by berger-n** [comment]
to fix: 
- [ ] scans should fit screen when opening reading view here http://library-dev.bdrc.io/scripts/embed-iframe.html?work=bdr:W1KG4884&origin=BDRCLibApp&lang=bo-x-ewts&uilang=en (compare with http://library-dev.bdrc.io/scripts/embed-iframe.html?work=bdr:W1PD95844&origin=BDRCLibApp&lang=bo-x-ewts&uilang=en where it sort of works because of the "copyrighted work" page in landscape)

**Comment by eroux** [comment]
also in the collection view:
- [ ] hide the white header if the screen is small
- [ ] close the left panel by default (or actually hide it completely) if it contains no sub-section (just the main thing), also only if the screen is small

**Comment by berger-n** [comment]
done hiding the topbar in collection view + viewing full portrait image when opening reading view

![image](https://user-images.githubusercontent.com/33383857/104356028-bf743f80-550b-11eb-997c-e78e8c50f0ab.png)

![image](https://user-images.githubusercontent.com/33383857/104356183-ed598400-550b-11eb-9c4b-110e8e40b198.png)


one (last?) more to do:
- [ ] enable popup for downloading pdf/zip in collection view


> close the left panel by default (or actually hide it completely) if it contains no sub-section (just the main thing), also only if the screen is small

it would help to find a resource where it's needed

**Comment by eroux** [comment]
yes good idea. Example resources are multi-volume ones without an outline, for instance bdr:MW28949

**Comment by berger-n** [comment]
made scrolling in collection view show/hide browser topmenu as well (not sure it's 100% functional yet... some weird bugs there!!)
+panel is now closed by default on library-dev.bdrc.io/scripts/embed-iframe.html?work=bdr:MW28949&origin=BDRCLibApp&uilang=en&lang=bo-x-ewts: 

![image](https://user-images.githubusercontent.com/33383857/104504598-fbc69f00-55e2-11eb-95e0-324bedd942dc.png)

**Comment by eroux** [comment]
nice, it's on good tracks!

**Comment by berger-n** [comment]
scrolling is now 100% bug-free in collection view 
(found out the custom scrollbar was the culprit while adding open/close tree view with swipe left/right, which is more user-friendly than the thin red button I think)

two more bugs to go though:
- [ ] when opening reading view the initial scroll offset seem to be related in some way with scroll offset in collection view (it might open at the last page in some cases!)
- [ ] lazy loading manifests in collection view is not working anymore

**Comment by eroux** [comment]
great, thanks!

**Comment by berger-n** [comment]
added pdf/zip download popup ([example](http://library-dev.bdrc.io/scripts/embed-iframe.html?work=bdr:MW28949&origin=BDRCLibApp&uilang=en&lang=bo-x-ewts)):
![image](https://user-images.githubusercontent.com/33383857/104761995-f2187500-5763-11eb-9820-d92adc90586f.png)
(note to self: there is a minor popup positioning bug to fix [here](http://library-dev.bdrc.io/scripts/embed-iframe.html?work=bdr:W1KG4884&origin=BDRCLibApp&lang=bo-x-ewts&uilang=en) due to portrait images)

regarding lazy loading, I thought I fixed it earlier but I had to disable it again because I found out a few minutes ago that the scrolling adaptions to mobile browsers break the `imageIsOnScreen` test (resulting in all manifest loaded at once and displayed in the wrong order)

**Comment by eroux** [comment]
ok! thanks a lot!

**Comment by berger-n** [comment]
lazy loading is ok now
(for the record this is close to the weirdest bug ever I've ever fixed in HTML...
it was using `<li>` elements for pdf/zip menu entries in popup that was making everything fail
using `<span>` elements instead fixed everything)

**Comment by berger-n** [comment]
viewer is in "app mode" on library-dev now: http://library-dev.bdrc.io/view/bdr:W1FPL4316
- just added a small "< BUDA" link in topbar so as to close viewer or go back to `/show` route:

![image](https://user-images.githubusercontent.com/33383857/105392149-2d5eec00-5c1b-11eb-84f9-7330da34bbc6.png)

---

- zoom on pinch in/out works (though a minor issue makes scroll offset change, I'll fix it)

- BTW I finally created a [`mobile`](https://github.com/buda-base/public-digital-library/tree/mobile) branch for work soon to come 
which sure will be helpful in case unrelated bug happen and have to be handled & deployed fast

**Comment by berger-n** [comment]
a few more bugs here:
- [ ] something's wrong when rotating screen back to portrait mode in reading view ([example](http://library-dev.bdrc.io/view/bdr:W8LS20894))
- [ ] when scrolling up in reading view, the showing-mobile-browser-topbar-resize-event triggers some sort of current image centering, which makes it uneasy to keep track of where you were reading ([modern print in English example](http://library-dev.bdrc.io/view/bdr:W8LS20887))

I'm also thinking of a reading view in portrait mode, which clearly seems missing for modern books from a user point of view, even if we keep top/bottom menus as they are, in landscape mode, for the sake of simplicity ([same example](http://library-dev.bdrc.io/view/bdr:W8LS20887))

**Comment by berger-n** [comment]
fixed a few things here regarding orientation changing
now you can use both reading/page views in portrait mode: http://library-dev.bdrc.io/view/bdr:W8LS20887

![image](https://user-images.githubusercontent.com/33383857/106037266-bde37380-60d6-11eb-9838-7cbb7dec27d0.png)

(there might be something different to do with menu bars yet it works as is for now)

- [ ] lazy loading needs to be fixed in that case
- [ ] something in the zoom level when switching orientation needs to be finalized
- [ ] check collection view in portrait (did not try it yet)

**Comment by berger-n** [comment]
fixed lazy loading and zoom in/out in portrait mode 

next : 
- [ ] scroll offset is still moved a bit when zooming in portrait, I'll fix that
- [ ] keeping current page when switching orientation is also buggy
(actually I was struggling to make that work in responsive mode of desktop browser without managing to at all,
but it almost works on a real device! sometimes it doesn't though, I'll check that)

**Comment by berger-n** [comment]
fixed case of fair use works in portrait mode using "copyrighted work" landscape image thus computing wrong default zoom:

![image](https://user-images.githubusercontent.com/33383857/106312622-3da04800-6267-11eb-919e-41c4f177d6c7.png)

the zoom is now perfect for reading but the "copyrighted work" image maybe isn't visible enough:

![image](https://user-images.githubusercontent.com/33383857/106312758-76402180-6267-11eb-9c0c-a4dc5a52e619.png)

I also managed to fix keeping scroll offset both when zooming and changing orientation

- [ ] yet there still is a little "jump" in scroll when switching from landscape to portrait when browser topbar is visible
- [ ] at least in chrome... in firefox it also appears that orientation change still breaks scroll offset

**Comment by berger-n** [comment]
I thought I was done here (with chrome it works 100%, with firefox it's a bit more... random sometimes but I'm not sure it's not because I am biased against it... ^^)
- [ ] yet scroll breaks when changing orientation after opening OSD

**Comment by berger-n** [comment]
everything's fine now with orientation switching (in both firefox and chrome as far as I've tested)
one *last* thing (hurray!) to do now is to check collection view

**Comment by eroux** [comment]
excellent, thanks!

**Comment by berger-n** [comment]
collection view in portrait seems to work fine
- [ ] found a random bug with image resizing when opening a volume though:
![image](https://user-images.githubusercontent.com/33383857/106791076-bf6fe700-6654-11eb-94f5-2c400b728b6b.png)

**Comment by berger-n** [comment]
I think we are finally ok here! both on chrome & firefox
a good time to merge (then work on something else... ^^)

**Comment by berger-n** [comment]
+one last fix for OSD menu bar: http://library-dev.bdrc.io/view/bdr:W2KG210311

![image](https://user-images.githubusercontent.com/33383857/107025024-1d154800-67a9-11eb-9cd5-eccb8e66bb07.png)

**Comment by eroux** [comment]
let's close this, we've made some good progress and we can track the rest in separate issues
