### ISSUE TITLE
search by ID

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#408]
This one is quite similar to #407 but has a slightly higher priority (as it's been requested a few times, unlike 407), I think they could be done at the same time as they modify essentially the same code. Here the idea is:
- whatever the user writes in the search box, "identifier" will be proposed
- it uses the [count](http://purl.bdrc.io/query/table/countIdTypes?L_ID=D1)
- and then there are only works and instance ([ex](http://purl.bdrc.io/lib/idInstances?L_ID=D1))

**Comment by eroux** [comment]
just to record a use case, this should also allow search by NGMPP reel number, for instance "L667/3"

**Comment by berger-n** [comment]
seems to be working fine too: http://library-dev.bdrc.io/search?id=%22D1%22&t=Instance&s=title

![image](https://user-images.githubusercontent.com/33383857/107962309-18217700-6fa7-11eb-90d5-e4d139501664.png)

there might be something to fix in queries targetting NGMPP ids though:
- searching "[NGMPP E/797/2](http://library-dev.bdrc.io/show/bdr:MW0NGMCP69090)" (or "E/797/2") no result: http://purl.bdrc.io/lib/idInstances?L_ID=NGMPP%20E%2F797%2F2&format=json
- yet one result in datatypes when searching "NGMPP E/797/2": http://purl.bdrc.io/query/table/countIdTypes?L_ID=NGMPP%20E%2F797%2F2

**Comment by eroux** [comment]
Looks perfect, thanks a lot!! The problem with NGMPP is probably an artefact in the data, I'll confirm that tomorrow

**Comment by eroux** [comment]
ok, the NGMPP data has been fixed. Everything seems to work fine, let's merge this!
