### ISSUE TITLE
list of the lds-queries used by pdl

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#41]
I'll be rewriting some of the queries in lds-pdi, focusing on those that are actually used, @berger-n can you make a list of all the queries used in pdl? Maybe if they're all listed as constants that will be easy for me to catch up

**Comment by berger-n** [comment]
* generic/ontology: 
http://purl.bdrc.io/ontology/core.json

* on resource page:
http://purl.bdrc.io/graph/Resgraph?I_LIM=500&R_RES=bdr%3AG418
http://purl.bdrc.io/lib/allAssocResource?R_RES=bdr:G418
http://purl.bdrc.io/graph/AnnCollection-forResource?I_LIM=500&R_RES=bdr%3AWCBC2237
http://purl.bdrc.io/anncollection/ANCWCBC2237_C001.jsonld
(iiif)
http://iiifpres.bdrc.io/2.1.1/collection/i:bdr:I22084
http://presentation.bdrc.io/2.1.1/v:bdr:V22084_I0886/manifest

* on search page
http://purl.bdrc.io/lib/rootSearchGraph?LG_NAME=bo-x-ewts&I_LIM=500&L_NAME=%22%27od%20zer%22
http://purl.bdrc.io/lib/workFacetGraph?LG_NAME=bo-x-ewts&I_LIM=500&L_NAME=%22%27od%20zer%22
http://purl.bdrc.io/lib/personFacetGraph?LG_NAME=bo-x-ewts&I_LIM=500&L_NAME=%22%27od%20zer%22
http://purl.bdrc.io/lib/chunksFacetGraph?LG_NAME=bo-x-ewts&I_LIM=500&L_NAME=%22%27od%20zer%22
(related resource search)
http://purl.bdrc.io/lib/placeAllAssociations?I_LIM=500&R_RES=bdr%3AG418
http://purl.bdrc.io/lib/workAllAssociations?I_LIM=500&R_RES=bdr%3AW22084
http://purl.bdrc.io/lib/personAllAssociations?I_LIM=500&R_RES=bdr%3AP1583
http://purl.bdrc.io/lib/topicAllAssociations?I_LIM=500&R_RES=bdr%3AT2423

**Comment by eroux** [comment]
thanks, that's very useful!

**Comment by berger-n** [comment]
I almost forgot that one (for the editor): http://purl.bdrc.io/query/BLMP?LG_NAME=bo-x-ewts&I_LIM=500&L_NAME=%22%27od%20zer%22&format=json
