### ISSUE TITLE
perturbation / error warning

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#418]
we will make some changes in the Lucene analyzer and we need to make sure users are aware that the search (and only the search hopefully) can be a bit disturbed for a few hours. I'm thinking of the following in the config.json:

```json
...
"msg": [
{
    "severity": "warning",
    "text": [
        { "@value": "the search will be disturbed today between 9 am to 12am", "@language": "en"}
    ],
    "display": ["home", "search"]
}
]
```

(note that there cat be several messages). For the "home" display, the message would be displayed above the search bar on the home page, for the "search" display, it would be at the top of the search results area

**Comment by berger-n** [comment]
added this to config file:
```
   "msg": [
      {
         "severity": "info",
         "text": [
             { "@value": "Information message on home & resource page", "@language": "en" }
         ],
         "display": [ "home", "resource" ]
      },
      {
          "severity": "warning",
          "text": [
              { "@value": "The search will be disturbed today between 9 am to 12am", "@language": "en" }
          ],
          "display": ["home", "search"]
      }
   ]
```
resulting in this:
- on home (not sure what you meant by "there can be several messages" but this is how this case is handled): http://library-dev.bdrc.io/

![image](https://user-images.githubusercontent.com/33383857/105050793-6efe6400-5a6e-11eb-8787-527d672e396d.png)

---

- on results page: http://library-dev.bdrc.io/search?r=bdr:WA8LS20912&t=Instance&s=title

![image](https://user-images.githubusercontent.com/33383857/105050986-9fde9900-5a6e-11eb-8b03-488282db784d.png)

---

- on resource page: http://library-dev.bdrc.io/show/bdr:MW8LS20912?s=r%3Dbdr%3AWA8LS20912%26t%3DInstance%26s%3Dtitle%26n%3D1

![image](https://user-images.githubusercontent.com/33383857/105051189-d1effb00-5a6e-11eb-9d78-a61f10954def.png)

**Comment by eroux** [comment]
(almost) perfect, thanks a lot! can we adjust the color with the severity level?
- red for error
- orange for warning
- green for info
? If green is too ugly maybe yellow?

**Comment by berger-n** [comment]
actually I was using an icon to differenciate severity level
(I don't think any color other that this red will fit here... but we can try at least in inspector... let me take some screenshots)

**Comment by eroux** [comment]
(if we keep only the icons, let's put a circled i icon for information)

**Comment by eroux** [comment]
oh I just realized a requirement: the message I'm thinking of will have a link in it, so we should allow html markers in the text of the message

**Comment by berger-n** [comment]
is it better with icons before and after message?

![image](https://user-images.githubusercontent.com/33383857/105053523-504d9c80-5a71-11eb-89b9-87a5491c4096.png)

- in case of an error:

![image](https://user-images.githubusercontent.com/33383857/105057871-f26f8380-5a75-11eb-8c36-689bde2618bd.png)

- just an information:

![image](https://user-images.githubusercontent.com/33383857/105058017-16cb6000-5a76-11eb-98bd-0ee7718cddf5.png)

**Comment by eroux** [comment]
well, I'm not sure I like it better... let's keep it this way (no other color is fine), without the icon on the right. Thanks!

**Comment by berger-n** [comment]
ok!
now you can insert a link using markdown syntax: http://library-dev.bdrc.io/


```
     {
          "severity": "warning",
          "text": [
              { "@value": "The search will be disturbed today between 9 am to 12am ([more information](https://bdrc.io/))", "@language": "en" }
          ],
          "display": ["home", "search"]
      },
```


![image](https://user-images.githubusercontent.com/33383857/105061609-ff8e7180-5a79-11eb-9aa9-87e088d21650.png)

**Comment by eroux** [comment]
oh, very cool, perfect! Thanks a lot!
