### ISSUE TITLE
display login identity

### ISSUE THREAD

**Issue by xristy** [buda-base/public-digital-library#419]
It would be helpful to display the identity one is logged in as.

Currently:

![Screen Shot 2021-01-25 at 11 31 14 AM](https://user-images.githubusercontent.com/3542294/105742434-1fea8000-5f01-11eb-8477-fe5bd9d8db46.png)

versus

![Screen Shot 2021-01-25 at 11 32 30 AM](https://user-images.githubusercontent.com/3542294/105742465-2842bb00-5f01-11eb-9403-3583569bb3c1.png)

or have the logged in be a drop-down for example:

![Screen Shot 2021-01-25 at 11 34 31 AM](https://user-images.githubusercontent.com/3542294/105742799-938c8d00-5f01-11eb-8d1b-24c71c958198.png)

**Comment by eroux** [comment]
This is a duplicate of https://github.com/buda-base/public-digital-library/issues/220

**Comment by xristy** [comment]
Oh I didn't find #220. I thought I'd opened an issue on this before.
