### ISSUE TITLE
creator labels in the UI again

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#420]
I think this happened before, but the role labels are appearing the UI where they shouldn't, see for instance

https://library.bdrc.io/show/bdr:P1428

**Comment by berger-n** [comment]
fixed:
![image](https://user-images.githubusercontent.com/33383857/106440009-a14d8f80-6478-11eb-9d12-d5a4adf16567.png)

(this was indeed partially fixed in #328 
and still is)

**Comment by eroux** [comment]
excellent, thanks a lot!
