### ISSUE TITLE
small display bug in extended properties

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#421]
Here's what I see on https://library.bdrc.io/show/bdr:G165 on FIrefox:

![Capture d’écran de 2021-02-02 09-47-13](https://user-images.githubusercontent.com/60868/106574843-b4756380-653b-11eb-89e0-f0d19eaedc22.png)

moved from https://github.com/buda-base/library-issues/issues/330

**Comment by berger-n** [comment]
fixed:

![image](https://user-images.githubusercontent.com/33383857/106627930-90387780-6579-11eb-959f-fa35d41a5003.png)

**Comment by eroux** [comment]
thanks!
