### ISSUE TITLE
missing topics in assocated image instances

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#422]
see for instance

https://library.bdrc.io/search?t=Scan&r=bdr:PR0LULDC001&s=title%20forced&pg=1

there should be many more topics (ex: T247 has 27 matches in the [request](https://purl.bdrc.io/lib/associatedIInstances?R_TYPE=bdo%3AScan&R_RES=bdr%3APR0LULDC001&format=json) but doesn't appear in the UI)

**Comment by berger-n** [comment]
fixed: https://library.bdrc.io/search?r=bdr:PR0LULDC001&t=Scan&s=title%20forced&pg=1&f=tree,inc,bdr:T247

![image](https://user-images.githubusercontent.com/33383857/106753098-7eafa800-662b-11eb-98ce-99f9eb8674d8.png)
