### ISSUE TITLE
library.bdrc.io not loading

### ISSUE THREAD

**Issue by TBRC-Travis** [buda-base/public-digital-library#424]
Have tried loading library.bdrc.io on multiple browsers and the website flashes by and then shows a gray screen.

![image](https://user-images.githubusercontent.com/19354126/107149996-9cca2080-6929-11eb-9078-7d1e3205d3ae.png)

**Comment by berger-n** [comment]
this is now fixed: https://library.bdrc.io/
(for the record it was because some of the current syncs have no `prefLabel`, see for example https://library.bdrc.io/show/bdr:MW1FPL2409)

**Comment by TBRC-Travis** [comment]
a bit concerning that it caused the entire site not to load, but I'm glad it's fixed now!  thanks.

**Comment by eroux** [comment]
Thanks!
