### ISSUE TITLE
improve open / hide context in etext results

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#425]
When on https://library.bdrc.io/search?q=%22brgya%20rtsa%27i%20TI%20ka%22~1&lg=bo-x-ewts&t=Etext , look at result number 3 and click on "open context" and then scroll down and click "hide context". It works but it doesn't scroll back to result number 2, which is quite confusing

**Comment by berger-n** [comment]
fixed: https://library.bdrc.io/search?q=%22brgya%20rtsa%27i%20TI%20ka%22~1&lg=bo-x-ewts&t=Etext 

![Kazam_screencast_00004 mp4](https://user-images.githubusercontent.com/33383857/107365131-ad6ec800-6adc-11eb-8ae4-ad4d9649a080.gif)

**Comment by eroux** [comment]
great, thanks!

**Comment by berger-n** [comment]
(from https://github.com/buda-base/public-digital-library/issues/390)

scrolling back seems to fail [here](http://library-dev.bdrc.io/search?q=(%22zhi%22%20AND%20%22ba%22%20AND%20%22lha%22)&lg=bo-x-ewts&t=Etext)

**Comment by berger-n** [comment]
fixed 
scrolling back work [here](http://library-dev.bdrc.io/search?q=(%22zhi%22%20AND%20%22ba%22%20AND%20%22lha%22)&lg=bo-x-ewts&t=Etext) as well

**Comment by eroux** [comment]
oh, I tried with one of the other matches of the first result and it didn't really work... is it supposed to?

**Comment by berger-n** [comment]
oops, no it's not
I'll fix that

**Comment by berger-n** [comment]
works better now: https://library.bdrc.io/search?q=(%22zhi%20ba%22%20AND%20%22lha%22)&lg=bo-x-ewts&t=Etext

**Comment by eroux** [comment]
yes, perfect, thanks!
