### ISSUE TITLE
crash in etext outline

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#430]
Going to https://library.bdrc.io/show/bdr:IE23703 and clicking on Volume 1 crashes the website

**Comment by berger-n** [comment]
fixed:

![image](https://user-images.githubusercontent.com/33383857/107649113-69ff8f80-6c7d-11eb-82dd-14c1b43108d4.png)

**Comment by eroux** [comment]
thanks! the data is a bit bizarre but still... crashes are never good!
