### ISSUE TITLE
bogus message when no result

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#432]
In https://library.bdrc.io/search?r=bdr:P8277&t=Person there's no result (in person) but the message says:

![Capture d’écran de 2021-02-20 12-36-30](https://user-images.githubusercontent.com/60868/108594122-5688ae80-7378-11eb-8321-2a1a7e2c89c9.png)

**Comment by berger-n** [comment]
fixed:

![image](https://user-images.githubusercontent.com/33383857/108704261-0d696380-750c-11eb-8027-3d0656969beb.png)

**Comment by eroux** [comment]
excellent, thanks!
