### ISSUE TITLE
broken display in some records

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#433]
for instance https://library.bdrc.io/show/bdr:P8224

**Comment by berger-n** [comment]
issue comes from P8224 being its own student and its own teacher: http://purl.bdrc.io/query/graph/ResInfo-SameAs?R_RES=bdr%3AP8224&format=json
seems not straightforward to fix display nonetheless but let's give it a try!

**Comment by eroux** [comment]
wow, that's veeery weird... don't bother, thanks for investigating!
