### ISSUE TITLE
display Sanskrit (IAST, LOC, etc.) in title case

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#434]
for instance on https://library.bdrc.io/show/bdr:P8228 , `surendrabodhi` should be transformed into `Surendrabodhi` for display (and also in the html title). The IAST transliteration is case-insensitive so we can do that.... don't do it for `sa-x-ewts` though, EWTS is case-sensitive

**Comment by berger-n** [comment]
do you have another potential resource with `sa-x-iast` labels in mind?
in this example labels are mainly `bo-x-ewts`:
https://purl.bdrc.io/query/graph/ResInfo-SameAs?R_RES=bdr%3AP8228&format=jsonld
there is one `sa-alalc97` though, should I capitalize it?

**Comment by eroux** [comment]
Yes, alalc97 in title case works for Sanskrit (not really for Tibetan)

**Comment by berger-n** [comment]
seems ok now:

![image](https://user-images.githubusercontent.com/33383857/109522594-bbe24b00-7aae-11eb-9085-443803806f00.png)

is this restricted to property like title/name? 
or is it generic to any value in transliterated sanskrit, ewts excepted
(for now it is generic)

**Comment by eroux** [comment]
Looks good (considering the less than ideal data)! it's generic yes. Thanks a a lot!
