### ISSUE TITLE
remove "public digital library" from HTML title

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#435]
let's make it something like 

XXX - Buddhist Digital Archives (BUDA)

it will look better in the Google search results: https://www.google.com/search?client=firefox-b-d&q=surendrabodhi

**Comment by berger-n** [comment]
I've updated title to: XXX - Buddhist Digital Archives
regarding display in Google there might be something else to do in Search Console I think
(don't know where the extra " - BUDA" comes from actualy:
![image](https://user-images.githubusercontent.com/33383857/109489593-634b8780-7a87-11eb-8409-2278c5900c64.png)
)

**Comment by eroux** [comment]
oh, interesting... thanks, I think it's a good step already, closing!
