### ISSUE TITLE
not able to scroll laterally in a zoomed image on mobile in page view

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#436]
When on mirador on Firefox mobile, if you open an image in page view and zoom in, then you can't scroll in the image laterally because the swapping gesture is bound to the mechanism that moves to previous / next image

**Comment by berger-n** [comment]
I've disabled swipe listener and added prev/next buttons: https://library.bdrc.io/view/bdr:I4CZ75258

![image](https://user-images.githubusercontent.com/33383857/109823112-ed3a5280-7c37-11eb-9adc-8673f46d5e2e.png)

**Comment by eroux** [comment]
excellent, thanks!! One remark though: in landscape mode on Firefox they get hidden under the address bar

**Comment by berger-n** [comment]
ok ! now they stay just on top of address bar (like the bottom right button)
