### ISSUE TITLE
Remove "beta" from the welcome box

### ISSUE THREAD

**Issue by JannTibetan** [buda-base/public-digital-library#437]
"WELCOME TO THE BETA VERSION OF BUDA" - I think it's time to remove the beta label.

**Comment by JannTibetan** [comment]
But that's just my opinion. How do other people feel about this?

**Comment by eroux** [comment]
I'm not opposed to removing it, no problem. There are different styles to versioning: some projects have a 1.0 version that's not feature ready and unstable but that's released soon, some projects never leave beta... I tend to lean on the prudent side of things but I'm a bit too aware of all the bugs and limitations so I'm not really neutral.
