### ISSUE TITLE
strange prefLabel displayed on entity pages

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#438]
see https://library.bdrc.io/show/bdr:P1583 : the prefLabel is "klong chen pa", but it seems to come from one of the sameAs (the Wikidata one). We should only display prefLabels from the BDRC entity here

**Comment by eroux** [comment]
related issues: https://github.com/buda-base/public-digital-library/issues/439 https://github.com/buda-base/xmltoldmigration/issues/170

**Comment by berger-n** [comment]
done: https://library.bdrc.io/show/bdr:P1583

![image](https://user-images.githubusercontent.com/33383857/110953571-d1296600-8347-11eb-964b-13e8a71eb49a.png)

note yet that this was intended as to help provide a label in the reader language preference
switch language to chinese on https://library.bdrc.io/show/bdr:P4956 you get:

![image](https://user-images.githubusercontent.com/33383857/110953072-3d579a00-8347-11eb-9bac-49542a7c26c6.png)

should I implement some fallback mechanism so as we can keep displaying the chinese name when it's requested and available from a `sameAs` resource? like this: http://library-dev.bdrc.io/show/bdr:P4956

![image](https://user-images.githubusercontent.com/33383857/110953240-6a0bb180-8347-11eb-8ebf-6ee201491cd1.png)

**Comment by eroux** [comment]
great, thanks! well, that's a good question... well... I'm tempted to say yes, but we can do that at a later point, let's pause this for now
