### ISSUE TITLE
allow search in image instances (through URL only)

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#440]
I created a new query ([example](https://purl.bdrc.io/lib/iinstanceFacetGraph?L_NAME=%22mi%20la%20ras%20pa%20rnam%20thar%22&LG_NAME=bo-x-ewts)) that searches in the scans. We don't need to wire it in the UI now but we should at least make the search available through URLs (like 

https://library.bdrc.io/search?q=%22mi%20la%20ras%20pa%20rnam%20thar%22~1&lg=bo-x-ewts&t=ImageInstance

), so that we can use this in the editor (for `bdo:contentLocationInstance`)

**Comment by berger-n** [comment]
done: http://library-dev.bdrc.io/search?q=%22mi%20la%20ras%20pa%20rnam%20thar%22~1&lg=bo-x-ewts&t=Scan

(there seem to be missing something like `tmp:hasReproAccess` data though:

![image](https://user-images.githubusercontent.com/33383857/112337983-b5667e00-8cbe-11eb-980d-29cbfc68fa9d.png)
)

**Comment by berger-n** [comment]
oops there is an `adm:access` property
I can use it I think

**Comment by eroux** [comment]
ah yes, great, thanks!

**Comment by berger-n** [comment]
better now:

![image](https://user-images.githubusercontent.com/33383857/112339067-9fa58880-8cbf-11eb-936f-fd9ffb419a8f.png)

**Comment by eroux** [comment]
perfect, thanks!
