### ISSUE TITLE
issue in etext / image relationship

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#441]
(from a user report) I'm opening it here but it could be that the error is somewhere else. The problem is that on

https://library.bdrc.io/show/bdr:UT23703_1319_0000?backToEtext=bdr:IE23703#open-viewer

there's an offset of 2 on the images

**Comment by berger-n** [comment]
it seems that page with lowest `seqNum` returned by [`Chunks` query](http://purl.bdrc.io/lib/Chunks?R_RES=bdr%3AUT23703_1319_0000&I_START=0&I_END=10000) is page 6:

![image](https://user-images.githubusercontent.com/33383857/112808120-f2dd5980-9078-11eb-946b-437c490e850a.png)

which corresponds to image [13190006.tif](http://iiif.bdrc.io/bdr:I1319::13190006.tif/full/max/0/default.jpg) according to [image list](http://iiifpres.bdrc.io/il/v:bdr:I1319):

![image](https://user-images.githubusercontent.com/33383857/112808492-4fd90f80-9079-11eb-9146-540f37ca128c.png)

yet actual first image seems to be [13190004.tif](https://iiif.bdrc.io/bdr:I1319::13190004.tif/full/max/0/default.png):

![](https://iiif.bdrc.io/bdr:I1319::13190004.tif/full/max/0/default.png)
