### ISSUE TITLE
mobile: bug in Chrome on Android (from the app)

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#442]
https://library.bdrc.io/scripts/embed-iframe.html?work=bdr:MW29701_80DDDF&origin=BDRCLibApp1.2.0&lang=bo-x-ewts&uilang=en

is unusable on Chrome on Android, there's a big "add item" with a little part of an image and nothing works

**Comment by berger-n** [comment]
could reproduce and fix the problem
everything's fine now I think

**Comment by eroux** [comment]
@ngawangtrinley what say you?
