### ISSUE TITLE
[mirador] back to the left in the image view

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#445]
when users read a very long (palm leaf) manuscript, they have to zoom in and only see a small portion of the image, and when they reach the right end of the image (at the end of a line), going back to the left of the image (to start reading the next line) is a bit tedious and requires a lot of clicks and movements. We could have a "go to the left" button towards the right of the image (or maybe it could always be there? or perhaps a keyboard shortcut too?)

**Comment by eroux** [comment]
Here's a proposal for some shortcuts in the page view:
- `n`: next image
- `p`: previous image
- `page down`: next image
- `page up`: previous image
- `home` (the button that usually goes at the beginning of a line): go back to the left of the image, not changing the vertical position
- `end` (the button that usually goes at the end of a line): go to the right of the image, not changing the vertical position
- `+`: zoom in
- `-`: zoom out
- `arrow (left, up, right, down)`: move in the image
- `space` move right in horizontal images, move down in vertical images

**Comment by eroux** [comment]
ah, now that I think about here, here are two obvious ones I totally forgot about:
- `esc` should close the viewer and bring the user back to buda (although this is probably the case already?)
- `v` (for volume), `r` (for reading view) and `backspace` should bring the user back to reading view

**Comment by berger-n** [comment]
deployed a new version here: http://library-dev.bdrc.io/show/bdr:W1FPL1783

![image](https://user-images.githubusercontent.com/33383857/116905395-352d2400-ac3f-11eb-8a05-da22936622e5.png)

- implemented all shortcuts
- you can go to begin/end in any direction of image by double-clicking the corresponding arrow in bottom menu

**Comment by eroux** [comment]
very excellent, thanks a lot!
