### ISSUE TITLE
small css glitch in collections search

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#447]
in https://library.bdrc.io/search?q=%22berlin%22&lg=en&t=Product&s=closest%20matches%20forced in Firefox, the gray bar gets above the RID:

![Capture d’écran de 2021-04-13 15-36-29](https://user-images.githubusercontent.com/60868/114561784-2b328980-9c6e-11eb-8549-ee9d81591718.png)

**Comment by berger-n** [comment]
looks better now:

![image](https://user-images.githubusercontent.com/33383857/114564422-97ae8800-9c70-11eb-9259-55dcfe50937a.png)

**Comment by eroux** [comment]
perfect, thanks!
