### ISSUE TITLE
getting stucked on "id" in the search bar

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#448]
If I go on https://library.bdrc.io/search?id=%22Leiden%20University%20Library%22&t=Product on Firefox, if I select "id" again, wait for the search to happen, then click in the search input bar, then select English, a new search is done but as if id was still selected

**Comment by berger-n** [comment]
seems fixed to me:

![Kazam_screencast_00015 mp4](https://user-images.githubusercontent.com/33383857/114571327-df381280-9c76-11eb-85ba-91e1674197d5.gif)

**Comment by berger-n** [comment]
something seems wrong with `idProducts` query though: https://purl.bdrc.io/lib/idProducts?I_LIM=700&L_ID=Leiden%20University%20Library&format=json
```
"status": 500,
"code": 5011,
"message": "Query template parsing failed for: idProducts.arq",
"link": null,
"developerMessage": null
```

**Comment by eroux** [comment]
yes, it's just that it doesn't exist, only idWorks and idInstances do

**Comment by eroux** [comment]
thanks!
