### ISSUE TITLE
double underlining in some links

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#450]
on https://library.bdrc.io/show/bdr:WA1KG18407 on Firefox when i put my mouse on the author's name I get this display:

![Capture d’écran de 2021-04-14 19-27-13](https://user-images.githubusercontent.com/60868/114753385-b176ca80-9d57-11eb-937d-7141835fec62.png)

**Comment by berger-n** [comment]
fixed:

![image](https://user-images.githubusercontent.com/33383857/114874329-85f9eb80-9dfc-11eb-9a19-223abd9906d1.png)

**Comment by eroux** [comment]
excellent, thanks!
