### ISSUE TITLE
bug in the search bar behavior

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#451]
- go on https://library.bdrc.io/search?q=%22mi%20la%20ras%20pa%27i%20rnam%20thar%22~1&lg=bo-x-ewts&t=Instance&f=asset,inc,tmp:hasOpen&n=1
- replace the content of the search bar with "sgam po pa"
- don't select a language
- select the "Persons" type
- click in the content of the search bar to open the list of languages
- click on EWTS

you reach this bogus state:

![Capture d’écran de 2021-04-14 19-31-34](https://user-images.githubusercontent.com/60868/114753876-3f52b580-9d58-11eb-8f66-e1c6d9c36126.png)

which has:
- persons in the URL and in the search bar
- versions selected on the left and seemingly in the results
- displays no results while there are many results in the versions, see https://library.bdrc.io/search?q=%22sgam%20po%20pa%22~1&lg=bo-x-ewts&t=Instance&f=asset,inc,tmp:hasOpen

**Comment by berger-n** [comment]
fixed:

![Kazam_screencast_00016 mp4](https://user-images.githubusercontent.com/33383857/114864043-ceaba780-9df0-11eb-9ef1-2a3f2b279ddc.gif)

also fixed the multiple "No results" bug with results displayed, from homepage:

![Kazam_screencast_00017 mp4](https://user-images.githubusercontent.com/33383857/114864275-15999d00-9df1-11eb-887f-1958e8c7f9e0.gif)

**Comment by eroux** [comment]
excellent, thanks!
