### ISSUE TITLE
upper casing identifiers

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#454]
the search on identifiers is case sensitive and not all IDs are in one case or another, but most are upper case. One important case is the Tohoku identifiers (starting with D), I just witnessed a user searching an identifier `d42` which returns no results while `D42` does. So I'm thinking perhaps we could automatically upper case some identifiers... perhaps starting with everything that starts with D and then a number (there can be anything after the first number) should be upper cased automatically.

**Comment by berger-n** [comment]
done:

![image](https://user-images.githubusercontent.com/33383857/115224192-dc24a280-a10c-11eb-82fe-71f611a58591.png)

**Comment by eroux** [comment]
excellent, thanks!
