### ISSUE TITLE
sticky search option

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#456]
steps to reproduce:
- type P4308 in the search bar
- select "search as identifier"
- (see there are no results)
- click in the search bar to see the options
- click on the first one "find resource with this rid"
- see the results as if you selected the second one instead of the first

**Comment by berger-n** [comment]
fixed (#455 as well):

![Kazam_screencast_00019 mp4](https://user-images.githubusercontent.com/33383857/115554616-f26a6400-a2ae-11eb-9461-ebee531328db.gif)

**Comment by eroux** [comment]
excellent, thanks!
