### ISSUE TITLE
wording change for copyright restricted works

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#457]
This is quite important not to do that right now, but on a certain day in May (I'll keep you updated), the idea is to change the wording of the message displayed on copyrighted works to:

```
This work is copyright restricted and BDRC can only make available the first and last 20 pages. The full text is viewable on Internet Archive, a close partner of ours, through their lending library: https://archive.org/details/bdrc-{wrid}
```

where `{wrid}` is the local name of the scan IDs, so the link would be something like https://archive.org/details/bdrc-W8LS25030

**Comment by eroux** [comment]
Ah, here's the final message:

```
This work is copyrighted. As a result, BDRC can only make very limited portions available for private research and study. The full text of the work is viewable on Internet Archive, a close partner of ours, through their Open Library program. [Click here]
```

Perhaps the link could be "Access this work on Internet Archives", on a separate line, with an IA icon on the right of the link... @JannTibetan do you think that could work?

Also, importantly, this would only be displayed for scans that have `bdo:digitalLendingPossible true` or no property `bdo:digitalLendingPossible`.  For the other works, we would keep the same message as the one we have now. Alsooooo, this new message shouldn't be displayed on the Chinese server.

Example of a work where the message should be shown: W8LS66789, example of a work where we would keep the old message (because it's not on IA): W1KG18414

**Comment by berger-n** [comment]
done: http://library-dev.bdrc.io/show/bdr:W8LS66789

![image](https://user-images.githubusercontent.com/33383857/126186282-127be183-7fe5-4105-9150-26ec990c0b31.png)

old message kept here: http://library-dev.bdrc.io/show/bdr:W1KG18414

**Comment by eroux** [comment]
Excellent, thanks! Let's perhaps highlight the link a little more... let's put the IA icon on the left, a little bit smaller, and put the external link icon on the right. Also, perhaps let's not use underlining in the text (these look like links), perhaps using italic for "copyrighted", and no underlining for the two others

**Comment by berger-n** [comment]
reduced IA icon size and added the link icon, but let the text underlined:

![image](https://user-images.githubusercontent.com/33383857/126198248-69469e70-0df8-4173-a7cb-cb85ed0b011b.png)

not sure about the italic, I think we've already tried (it was supposed to be bold/black at first)
here's a screenshot from a try in the inspector:

![image](https://user-images.githubusercontent.com/33383857/126198636-8fca503a-3833-4a2a-8fab-7e3a50839c4a.png)

note that it has been underlined like this for long here: http://library-dev.bdrc.io/show/bdr:W1KG18414

![image](https://user-images.githubusercontent.com/33383857/126198444-2b2170ce-de50-4be6-8267-6e00aa93c0bf.png)

**Comment by eroux** [comment]
Looks perfect, thanks! Let's deploy all that!
