### ISSUE TITLE
crash when searching with parenthesis

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#458]
https://library.bdrc.io/search?q=%22bka%27%20%27gyur%2F%20(pe%20cing%20%2F)%22~1&lg=bo-x-ewts&t=Instance&f=asset,inc,tmp:hasOpen makes the app crash

**Comment by berger-n** [comment]
fixed:

![image](https://user-images.githubusercontent.com/33383857/116373957-26dda300-a80e-11eb-8679-4d02f21d41f9.png)

- [ ] there's a missing parenthesis at the end of keyword in search box though

**Comment by eroux** [comment]
thanks! the missing parenthesis is less of an issue, we can focus on other things now
