### ISSUE TITLE
bug in EAP collections

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#459]
https://library.bdrc.io/show/bdr:WEAP570-4-1 when clicking on the image and getting into mirador, I get a list of volumes but there's no thumbnails and I can't click on anything

**Comment by berger-n** [comment]
fixed: https://library.bdrc.io/view/bdr:WEAP570-4-1

![Kazam_screencast_00022 mp4](https://user-images.githubusercontent.com/33383857/116374587-b5522480-a80e-11eb-9439-08ed18fd31f6.gif)

**Comment by eroux** [comment]
excellent, thanks a lot!
