### ISSUE TITLE
unable to access images of WEAP039-1-4-65

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#460]
unable to view images of https://library.bdrc.io/show/bdr:WEAP039-1-4-65

I think that when it wants to display the thumbnail it goes to https://iiifpres.bdrc.io/wv:bdr:WEAP039-1-4-259/manifest which is kind of odd... I think it should go to https://iiifpres.bdrc.io/wv:bdr:IEAP039-1-4-259/manifest right? (for a very stupid reason this one also doesn't work but it should be fixed later today)

**Comment by eroux** [comment]
sorry, I meant https://eap.bl.uk/archive-file/EAP039-1-4-259/manifest which now works! few

**Comment by berger-n** [comment]
yes it seems you got this working:

![image](https://user-images.githubusercontent.com/33383857/116374972-1b3eac00-a80f-11eb-8daa-8a57f8c4e36f.png)

**Comment by eroux** [comment]
indeed, thanks!
