### ISSUE TITLE
removing BDRC logo in mirador when on bdrc.io on mobile

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#464]
it should be fairly obvious from the title: when on bdrc.io, on mobile, the BDRC logo shouldn't be displayed in mirador. Perhaps for other logos we could find a way to make it more discrete so that it doesn't hide the text?

**Comment by eroux** [comment]
here's an example:

![pasted image 0](https://user-images.githubusercontent.com/60868/116570364-81f4c000-a90a-11eb-895f-79e851537754.png)

**Comment by berger-n** [comment]
I've tried to move logo to upper right corner (and remove it if it's BDRC's):

- https://library.bdrc.io/view/bdr:WEAP676-12-2

![image](https://user-images.githubusercontent.com/33383857/116717143-df574280-a9d8-11eb-9930-5eda6cdf7765.png)
---

- https://library.bdrc.io/view/bdr:W22084

![image](https://user-images.githubusercontent.com/33383857/116717831-9fdd2600-a9d9-11eb-8bcb-ee6278009521.png)

**Comment by eroux** [comment]
when I visit https://library.bdrc.io/view/bdr:WEAP676-12-2 with a small Firefox window, I'm getting the collection view, I then click on the manifest but then I have a black screen and nothing happens... the console doesn't show any error

**Comment by berger-n** [comment]
I can reproduce, in Chrome too, with window width between 769px and 799px
must be some faulty edge case in responsive activation

**Comment by berger-n** [comment]
same kind of issue here:

![Capture d’écran de 2021-04-30 18-24-47](https://user-images.githubusercontent.com/33383857/117153585-6c284480-adbb-11eb-9ace-b9e7635adcfb.png)

**Comment by berger-n** [comment]
no more black screen at ~777px width in https://library.bdrc.io/view/bdr:WEAP676-12-2

![image](https://user-images.githubusercontent.com/33383857/117171671-5f135180-adcb-11eb-935e-2749ff736f25.png)

now let's see what we can do about the top menu when width is a bit wider:

![image](https://user-images.githubusercontent.com/33383857/117172003-adc0eb80-adcb-11eb-9744-21c0007da8f4.png)

**Comment by eroux** [comment]
Excellent!! i think this state is satisfying enough, thanks! closing
