### ISSUE TITLE
going back from page view to reading view on mobile

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#465]
users tend to be stuck in page view and don't understand how to go back to the reading view, perhaps we could have a back arrow somewhere on the left?

**Comment by berger-n** [comment]
what about the Reading View icon between the navigation arrows at the bottom: https://library.bdrc.io/view/bdr:I1KG9127

![image](https://user-images.githubusercontent.com/33383857/116718271-1548f680-a9da-11eb-9f08-c7f53907cc91.png)

**Comment by eroux** [comment]
excellent idea!
