### ISSUE TITLE
etext stub appearing on mobile

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#466]
here's what happens:

![pasted image 0](https://user-images.githubusercontent.com/60868/116570933-ed3e9200-a90a-11eb-8da3-fd39ac361fff.png)

apparently this happens in some cases even when there are no associated etexts... I need to investigate further and get the specific url, but even without this info, we could dramatically reduce the space this takes on mobile, or even not display this at all when there's no etext

**Comment by berger-n** [comment]
could not reproduce, but the whole block that is shown above is now only rendered if not on mobile
so I think the bug should not happen anymore

**Comment by eroux** [comment]
great, thanks!

**Comment by eroux** [comment]
just for reference, it was on https://library.bdrc.io/scripts/embed-iframe.html?work=bdr:MW29701_80DDDF&origin=BDRCLibApp1.2.0&lang=bo&uilang=bo
