### ISSUE TITLE
simplifying the page view

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#468]
I think the page view on mobile could be radically simplified:
- no thumbnails on the left (they're less useful with the reading view + mechanism to move from one page to the next)
- no button in the bottom right corner (there's nothing really crucial for mobile)
- no button in the top left corner, or maybe replacing it with an arrow to the left that goes back to the reading view

(also when I visit the image view of an image of W1FPL1 on my mobile Firefox I can't zoom with the gesture, but i can report that in another issue)

**Comment by berger-n** [comment]
regarding the issue with zoom in Firefox I couldn't reproduce it... but I could notice some "oddities" (like having to double-click to open a item in collection view right panel??) so maybe we'll have to check that in a separate issue yes

**Comment by eroux** [comment]
excellent, thanks!!
