### ISSUE TITLE
misbehaving "go to page" on mobile

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#470]
original issue https://github.com/buda-base/BDRC-Lib-App/issues/77

related to https://github.com/buda-base/public-digital-library/issues/468

**Comment by berger-n** [comment]
fixed: http://library-dev.bdrc.io/view/bdr:I1KG13171?uilang=bo

![image](https://user-images.githubusercontent.com/33383857/117033712-eea0fd80-ad02-11eb-9215-d4d7a930086f.png)

now you can also find page by inputing tibetan numbers in unicode 
(more testing of that feature might be a good idea though, as I can't read tibetan myself)

**Comment by eroux** [comment]
excellent, thanks a lot!
