### ISSUE TITLE
reduce font size of page numbers on mobile

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#471]
see https://github.com/buda-base/BDRC-Lib-App/issues/80

**Comment by eroux** [comment]
sort of duplicate: https://github.com/buda-base/BDRC-Lib-App/issues/76

**Comment by berger-n** [comment]
this is what we have now: https://library.bdrc.io/view/bdr:W1NLM1?uilang=bo

![image](https://user-images.githubusercontent.com/33383857/117148102-35036480-adb6-11eb-95f4-f82aa289abbe.png)

with captions in English: https://library.bdrc.io/view/bdr:W1NLM1?uilang=en

![image](https://user-images.githubusercontent.com/33383857/117148242-595f4100-adb6-11eb-99a9-690ec2e51f96.png)

**Comment by eroux** [comment]
thanks! this looks better! 

I'm actually starting to wonder if we could remove these page numbers altogether... let's see what the feedback will be
