### ISSUE TITLE
simplifying reading view

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#472]
see https://github.com/buda-base/BDRC-Lib-App/issues/78

let's change the behavior on mobile and do something similar to https://github.com/buda-base/public-digital-library/issues/468 , in the top right corner let's just have two buttons:
- one going back to the collection view when there is one (with the collection view icon), and let's not display this button when there's no collection view
- one for closing the viewer

**Comment by berger-n** [comment]
removed disabled collection link in header:

![image](https://user-images.githubusercontent.com/33383857/117850627-c591e700-b285-11eb-9adb-d0e18dee0794.png)


regarding https://github.com/buda-base/BDRC-Lib-App/issues/78 there can't be someting like a Close button as it's in the embedded viewer: http://library-dev.bdrc.io/scripts/embed-iframe.html?work=bdr:W1NLM1&origin=BDRCLibApp1.2.0&lang=bo-x-ewts&uilang=en

![image](https://user-images.githubusercontent.com/33383857/117851135-4ea91e00-b286-11eb-935b-f1304781ab31.png)

**Comment by eroux** [comment]
ah yes good! I'm thinking perhaps in the case of the app, if there's no collection button nor close button... then we can just not display the header at all (as it will be empty)? (I'm actually a bit confused how the app closes the viewer..? I'll send you the Android thingy)

**Comment by berger-n** [comment]
removed header in app when not in a collection: http://library-dev.bdrc.io/scripts/embed-iframe.html?work=bdr:W1FPL1&origin=BDRCLibApp1.2.0&lang=bo-x-ewts&uilang=en

![image](https://user-images.githubusercontent.com/33383857/117958594-78605480-b31b-11eb-800e-75e0c38c9c44.png)

regarding the browser frame header in the app's "view" mode, I guess we don't have much choice, do we? wdyt?

**Comment by eroux** [comment]
Thanks! I'm not sure what you mean wrt the app? What is our only choice?

**Comment by berger-n** [comment]
my bad, I might have misunderstood what you were saying about closing the viewer in the app, I thought it was about removing the frame header which has the close button:

![Screenshot_20210512-134413_Chrome](https://user-images.githubusercontent.com/33383857/117969918-502b2280-b328-11eb-8e62-4a2be341d611.jpg)

**Comment by eroux** [comment]
oh I see! let's keep the app header yes, no problem, but in the specific case we discussed (no collection view), let's not display the top left hamburger button in the reading view in the app

**Comment by berger-n** [comment]
ok thanks! then it's done: http://library-dev.bdrc.io/scripts/embed-iframe.html?work=bdr:W1FPL1&origin=BDRCLibApp1.2.0&lang=bo-x-ewts&uilang=en

![image](https://user-images.githubusercontent.com/33383857/117983650-70161280-b337-11eb-99e7-270ba05dd056.png)

let's update library now

**Comment by eroux** [comment]
excellent, thanks!
