### ISSUE TITLE
open access filter displays copyrighted material

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#473]
for instance https://library.bdrc.io/search?q=%22%E0%BD%91%E0%BD%BA%E0%BD%96%E0%BC%8B%E0%BD%90%E0%BD%BA%E0%BD%A2%E0%BC%8B%E0%BD%A6%E0%BE%94%E0%BD%BC%E0%BD%93%E0%BC%8B%E0%BD%94%E0%BD%BC%22~1&lg=bo&t=Instance&f=asset,inc,tmp:hasOpen

(maybe a data issue?)

**Comment by berger-n** [comment]
it seems to come frome data indeed, where some results have both `AccessOpen` and another `hasReproAccess` like `AccessRestrictedByTbrc`, see [query](https://purl.bdrc.io/lib/instanceFacetGraph?LG_NAME=bo&L_NAME=%22%E0%BD%91%E0%BD%BA%E0%BD%96%E0%BC%8B%E0%BD%90%E0%BD%BA%E0%BD%A2%E0%BC%8B%E0%BD%A6%E0%BE%94%E0%BD%BC%E0%BD%93%E0%BC%8B%E0%BD%94%E0%BD%BC%22~1):

![image](https://user-images.githubusercontent.com/33383857/117011723-687abc00-acee-11eb-8231-75e1b69c6221.png)

![image](https://user-images.githubusercontent.com/33383857/117011875-9c55e180-acee-11eb-98a2-8f569372073d.png)

**Comment by eroux** [comment]
ah yes thanks! fixed (it's actually a sort of bug in openpecha... but we can deal with that later on)
