### ISSUE TITLE
part type facet

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#476]
this is an improvement over the "version type" facet (like on https://library.bdrc.io/search?q=%22%E0%BD%91%E0%BD%BA%E0%BD%96%E0%BC%8B%E0%BD%90%E0%BD%BA%E0%BD%A2%E0%BC%8B%E0%BD%A6%E0%BE%94%E0%BD%BC%E0%BD%93%E0%BC%8B%E0%BD%94%E0%BD%BC%E0%BC%8B%22~1&lg=bo&t=Instance&f=asset,inc,tmp:hasOpen ), we would keep the "standalone" thing, the other would be renamed "part" and have sub items, one per value of the partType property, which is already returned by the query

**Comment by eroux** [comment]
also the part type (when there's one) should replace "version" there:

![Uploading Capture d’écran de 2021-05-05 18-53-37.png…]()

**Comment by berger-n** [comment]
done: http://library-dev.bdrc.io/search?q=%22%E0%BD%91%E0%BD%BA%E0%BD%96%E0%BC%8B%E0%BD%90%E0%BD%BA%E0%BD%A2%E0%BC%8B%E0%BD%A6%E0%BE%94%E0%BD%BC%E0%BD%93%E0%BC%8B%E0%BD%94%E0%BD%BC%E0%BC%8B%22~1&lg=bo&t=Instance&pg=1&f=versionType,inc,tmp:standalone&n=3

![image](https://user-images.githubusercontent.com/33383857/117462702-35833300-af4f-11eb-8a4b-18b33af5c2a4.png)

**Comment by eroux** [comment]
Perfect, thanks!
