### ISSUE TITLE
display map of the results in the place search

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#478]
This is the least priority among the new features and it's more an exploration at this point (if it's too complex we can give up), but we could display a map with a pin for each of the results displayed on a page. Each pin should be associated with the prefLabel, and perhaps also the type? (type is optional)

Optional feature: it be synchronized with the results (à la Google Maps search), in the sense of when some pins are not visible on the maps, the results disappear from the list... but I'm not sure it's even that convenient... so let's not focus on that

see also https://github.com/buda-base/lds-queries/issues/68

**Comment by berger-n** [comment]
work in progress here: http://library-dev.bdrc.io/search?q=%22lha%20sa%22~1&lg=bo-x-ewts&t=Place

![image](https://user-images.githubusercontent.com/33383857/118272919-9963a980-b4c3-11eb-9fdd-0ada797bb33a.png)

**Comment by eroux** [comment]
wow this is really great!! I think the main thing that's missing to put that in prod is a link to the record in the popup that appears on a map when we click a pin

**Comment by berger-n** [comment]
fixed a few things regarding pagination and added links/CSS: http://library-dev.bdrc.io/search?q=%22lha%22~1&lg=bo-x-ewts&t=Place&uilang=bo-x-ewts&pg=1&n=1

![Kazam_screencast_00024 mp4](https://user-images.githubusercontent.com/33383857/118287170-7b9e4080-b4d3-11eb-8b31-dbe7fd664a6d.gif)

![image](https://user-images.githubusercontent.com/33383857/118287016-59a4be00-b4d3-11eb-8784-ca967944ab0a.png)

**Comment by eroux** [comment]
Great! You can put it into prod if you have the opportunity

**Comment by berger-n** [comment]
there it is: https://library.bdrc.io/search?r=bdr:G2800&t=Place

**Comment by eroux** [comment]
fantastic, thanks a lot!! I'm thinking perhaps we should hide it on mobile?

**Comment by berger-n** [comment]
just tried something like that on mobile: https://library.bdrc.io/search?r=bdr:G2800&t=Place
(smaller height + use two fingers to scroll to prevent conflict with scrolling results)

![image](https://user-images.githubusercontent.com/33383857/118470089-a6bca600-b706-11eb-9f68-15890a434b27.png)

**Comment by eroux** [comment]
yes, excellent!! thanks a lot!
