### ISSUE TITLE
add bdo:associatedTradition facet

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#479]
It's pretty much everywhere now, in person search, place search, instance search, etc. [example](https://purl.bdrc.io/lib/personGraph?LG_NAME=bo-x-ewts&L_NAME=%22%27jigs%20med%20gling%20pa%22~1)

**Comment by berger-n** [comment]
seems to be already working fine indeed: http://library-dev.bdrc.io/search?r=bdr:P1583&t=Person&pg=1&f=tradition,inc,bdr:TraditionNyingma

![image](https://user-images.githubusercontent.com/33383857/117325734-49685f80-ae91-11eb-8325-89d981b15fb4.png)

---

note that [work query](https://purl.bdrc.io/lib/workFacetGraph?LG_NAME=bo-x-ewts&L_NAME=%22%27jigs%20med%20gling%20pa%22~1) does not have that kind of data though
actually it does but there's a typo preventing it to be used:

![image](https://user-images.githubusercontent.com/33383857/117325661-3b1a4380-ae91-11eb-959c-02bb2d4305d2.png)

**Comment by eroux** [comment]
great!! I've fixed the work query and added the tradition facet to the etext query too

**Comment by berger-n** [comment]
thanks, perfect! now deployed on library: https://library.bdrc.io/search?r=bdr:P1583&t=Work&pg=1&f=tradition,inc,bdr:TraditionNyingma

regarding https://purl.bdrc.io/lib/workFacetGraph?LG_NAME=bo-x-ewts&L_NAME=%22%27jigs%20med%20gling%20pa%22~1
I guess that according to ontology `tmp:associatedTradition` should be `bdo:associatedTradition`:

![image](https://user-images.githubusercontent.com/33383857/117329759-43747d80-ae95-11eb-94a9-9f9b0140cddd.png)

**Comment by eroux** [comment]
woops, fixed again, sorry! Thanks a lot!
