### ISSUE TITLE
"NEW" indicator on new filters

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#480]
The filters that are not present on tbrc.org could have a "NEW!" indication, in small, next to their title, that would include:
- associated century
- associated role
- associated tradition

**Comment by berger-n** [comment]
added a config parameter:
```
   "facets-new":[ 
      "century", "role", "tradition"
   ]
```
resulting in this display: http://library-dev.bdrc.io/search?q=%22%E0%BD%91%E0%BD%BA%E0%BD%96%E0%BC%8B%E0%BD%90%E0%BD%BA%E0%BD%A2%E0%BC%8B%E0%BD%A6%E0%BE%94%E0%BD%BC%E0%BD%93%E0%BC%8B%E0%BD%94%E0%BD%BC%E0%BC%8B%22~1&lg=bo&t=Person

![image](https://user-images.githubusercontent.com/33383857/117478204-24422280-af5f-11eb-8feb-9ada23450834.png)

**Comment by eroux** [comment]
Excellent, thanks a lot!
