### ISSUE TITLE
back button misbehaving in mirador

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#484]
steps to reproduce:
- go to https://library.bdrc.io/show/bdr:W1KG10253
- click on the image to open the viewer (this opens the viewer but doesn't change the URL)
- the back button gets one step too far and goes the page before you went to the original page

**Comment by berger-n** [comment]
fixed: 

![Kazam_screencast_00025 mp4](https://user-images.githubusercontent.com/33383857/118294007-90320700-b4da-11eb-83be-c869eda0a0c4.gif)

**Comment by eroux** [comment]
Excellent, thanks!
