### ISSUE TITLE
tiny fix for filter label

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#485]
in https://library.bdrc.io/search?q=%22%E0%BD%91%E0%BD%BA%E0%BD%96%E0%BC%8B%E0%BD%90%E0%BD%BA%E0%BD%A2%E0%BC%8B%E0%BD%A6%E0%BE%94%E0%BD%BC%E0%BD%93%E0%BC%8B%E0%BD%94%E0%BD%BC%E0%BC%8B%22~1&lg=bo&t=Instance&pg=1&f=versionType,inc,tmp:standalone&n=3 in the "Match Context" filters, "Note Match" should be "Note"

**Comment by berger-n** [comment]
[fixed](https://library.bdrc.io/search?q=%22%E0%BD%91%E0%BD%BA%E0%BD%96%E0%BC%8B%E0%BD%90%E0%BD%BA%E0%BD%A2%E0%BC%8B%E0%BD%A6%E0%BE%94%E0%BD%BC%E0%BD%93%E0%BC%8B%E0%BD%94%E0%BD%BC%E0%BC%8B%22~1&lg=bo&t=Instance&pg=1&f=versionType,inc,tmp:standalone):

![image](https://user-images.githubusercontent.com/33383857/118487643-39ffd680-b71b-11eb-8884-d9c447d452ea.png)

**Comment by eroux** [comment]
perfect thanks!
