### ISSUE TITLE
restricted by quality -> low quality

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#490]
Instead of the *restricted by quality* mechanism, we're going to implement a new one where we just indicate the low quality. I'll update this with some details about the new data but here are a few UI things to implement:
- use an icon on the thumbnails to indicate low quality, something like https://icons8.com/icons/set/low-rate ? (perhaps with the upper wave blurred?)
- in the Scans tab, add a message (at the same level as the fairuse / copyright one), saying something like "We acknowledge the poor quality of these scans and apologize for it. We think these might still be useful for scholarship and make them available, while searching for higher quality ones."
- in Mirador I think there could be a message? but I'm not sure where and this seems a bit cumbersome so perhaps not...

So, the meaning of the data is now:
- if the scans (ex: bdr:W8238) or etext (or anything actually) have `bdo:qualityGrade 0` then we should display the aforementioned warning

**Comment by berger-n** [comment]
thanks for the changes in the data!
for the record images at https://library.bdrc.io/show/bdr:W3CN3014 return a 401 error, I'm not sure why?

**Comment by eroux** [comment]
ok, [this query](https://purl.bdrc.io/lib/instanceFacetGraph?LG_NAME=bo-x-ewts&L_NAME=%22%27gro%20kun%20dad%20pa%27i%20zhing%20sar%20bden%20don%20chos%20char%20%27bebs%20pa%27i%20sngon%22~1) on [this page](https://library.bdrc.io/search?q=%22%27gro%20kun%20dad%20pa%27i%20zhing%20sar%20bden%20don%20chos%20char%20%27bebs%20pa%27i%20sngon%22~1&lg=bo-x-ewts&t=Instance&f=asset,inc,tmp:hasOpen)

now contains `tmp:hasReproQuality 0`, (because it's the quality of the reproduction), and [this query](https://purl.bdrc.io/lib/iinstanceFacetGraph?LG_NAME=bo-x-ewts&L_NAME=%22%27gro%20kun%20dad%20pa%27i%20zhing%20sar%20bden%20don%20chos%20char%20%27bebs%20pa%27i%20sngon%22~1) has `bdo:qualityGrade 0` (because it's a direct property)

**Comment by berger-n** [comment]
added icon with tooltip in results for [Scans](https://library.bdrc.io/search?q=%22%27gro%20kun%20dad%20pa%27i%20zhing%20sar%20bden%20don%20chos%20char%20%27bebs%20pa%27i%20sngon%22~1&lg=bo-x-ewts&t=Scan) & [Versions](https://library.bdrc.io/search?q=%22%27gro%20kun%20dad%20pa%27i%20zhing%20sar%20bden%20don%20chos%20char%20%27bebs%20pa%27i%20sngon%22~1&lg=bo-x-ewts&t=Instance&f=asset,inc,tmp:hasOpen):

![image](https://user-images.githubusercontent.com/33383857/119517063-92685100-bd77-11eb-8b48-69f9e1a268dc.png)
---

\+ message on resource page: https://library.bdrc.io/show/bdr:W8238

![image](https://user-images.githubusercontent.com/33383857/119517344-d3606580-bd77-11eb-94dd-ecbf8bba9984.png)
---

regarding Mirador I guess we can do something like when images are not avilable to download (icon+tooltip): https://library.bdrc.io/view/bdr:WEAP676-12-2

![image](https://user-images.githubusercontent.com/33383857/119517634-128eb680-bd78-11eb-9200-edac740c2716.png)

**Comment by eroux** [comment]
looks perfect, thanks!! Good idea about Mirador yes, let's do that!

**Comment by berger-n** [comment]
finally made it: https://library.bdrc.io/view/bdr:W8238

![image](https://user-images.githubusercontent.com/33383857/119660404-83dd7080-be2f-11eb-8734-8dabf3aad1fd.png)

**Comment by eroux** [comment]
oh excellent, thanks a lot!!

**Comment by eroux** [comment]
Let's reformulate the warning to:

```
We acknowledge the poor quality of these scans (which might be difficult to read or in the wrong order, and we apologize for it. We think these might still be useful for scholarship and make them available, while searching for higher quality ones.
```

**Comment by berger-n** [comment]
done: https://library.bdrc.io/show/bdr:W8238

![image](https://user-images.githubusercontent.com/33383857/119700305-53a7c900-be53-11eb-8087-091fbf8d8772.png)

---

![image](https://user-images.githubusercontent.com/33383857/119700383-6e7a3d80-be53-11eb-9d57-cde2d5029702.png)

**Comment by eroux** [comment]
great, thanks!
