### ISSUE TITLE
handling 401 code on PDF generation

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#492]
I'm almost ready to deploy a new policy for PDF generation where users need to be logged in to request PDFs. The main change will be that the server can now return HTTP code 401 when the user requests a PDF and is not logged in. I think there are two aspects to this issue:
- code 401 for PDFs should be handled by both the main web UI and mirador, and display an error message like "you must be logged in to download PDFs"
- the interface (and mirador?) could detect that the user is not logged in and display the links to the PDF in gray, with a hover saying "you must be logged in to download PDFs". Note that this should be behind an option as the Chinese version won't have this requirement (yet)

**Comment by eroux** [comment]
Sorry, forget about the second point actually, it's more complex than that and in some cases non-logged in users can downliad PDFs, so let's jyst stick with the first action

**Comment by berger-n** [comment]
almost good here:
- added message in popup when requesting pdf/zip download and not logged in: http://library-dev.bdrc.io/show/bdr:W8LS25425
(it's an active link that triggers authentication process when clicked)

![image](https://user-images.githubusercontent.com/33383857/120216091-d905f180-c236-11eb-8e63-34ed84201c36.png)

---

- works from mirador as well: http://library-dev.bdrc.io/view/bdr:W22084

![image](https://user-images.githubusercontent.com/33383857/120216338-2eda9980-c237-11eb-887c-ae47dc6fec0f.png)

![image](https://user-images.githubusercontent.com/33383857/120216403-42860000-c237-11eb-8921-c3d8b0c32d9e.png)

---

- then there is an issue with iiifpres-dev which returns 500 when user is logged which prevents testing download is ok after authentication:

![image](https://user-images.githubusercontent.com/33383857/120217036-0f903c00-c238-11eb-8114-3e1326776a3f.png)

- regarding your comment https://github.com/buda-base/public-digital-library/commit/d7608d7a805e8f737cb6a3fcd40e42c1ca63f6a4#r51535399 does it mean that there is a bypass mechanism that allows some IP-selected users to request downloads without having to log in?

**Comment by eroux** [comment]
Thanks, this looks good!

http://iiifpres-dev.bdrc.io/collection/wio:bdr:MW22084 seems to work again (I've updated the code and config)

Yes, there's a mechanism based on the IP address, see https://github.com/buda-base/public-digital-library/issues/492#issuecomment-851270358, so the primary thing is to handle the HTTP error code (401 vs. 403 vs. 200 vs. other)

**Comment by berger-n** [comment]
ok thanks, I get it I think: we must check error code to determine if user has to login first, instead of asking any user to log before showing the download links
will do

**Comment by eroux** [comment]
Yes exactly! Thanks!

**Comment by eroux** [comment]
exactly yes, thanks! It would be convenient at some point to allow the UI to know in advance (before actually trying to download a PDF) is the user can access it or not... but it's not that straightforward conceptually so... let's not dive into that!

**Comment by berger-n** [comment]
should be ok now: http://library-dev.bdrc.io/show/bdr:W22084

![Kazam_screencast_00029 mp4](https://user-images.githubusercontent.com/33383857/120298115-123b7180-c2ca-11eb-867c-1b8d2e826fec.gif)

**Comment by eroux** [comment]
Excellent, thanks a lot!
