### ISSUE TITLE
error appearing from time to time

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#494]
Not the first time I'm getting this error:

```
uncaught at Yt at Yt 
 at Yt 
 at f 
 at  
 It@https://library.bdrc.io/static/js/main.baf6285a.chunk.js:1:195006
475/g[l.a.gotOutline]@https://library.bdrc.io/static/js/main.baf6285a.chunk.js:1:401546
256/t.a/<@https://library.bdrc.io/static/js/main.baf6285a.chunk.js:1:88451
T/<@https://library.bdrc.io/static/js/2.6c7900b6.chunk.js:1:472879
h@https://library.bdrc.io/static/js/2.6c7900b6.chunk.js:1:470756
l/</<@https://library.bdrc.io/static/js/2.6c7900b6.chunk.js:1:676846
l/</<@https://library.bdrc.io/static/js/2.6c7900b6.chunk.js:1:676846
e/<@https://library.bdrc.io/static/js/main.baf6285a.chunk.js:1:371616
x@https://library.bdrc.io/static/js/2.6c7900b6.chunk.js:1:1075721
w/o._invoke</<@https://library.bdrc.io/static/js/2.6c7900b6.chunk.js:1:1075510
O/</e[t]@https://library.bdrc.io/static/js/2.6c7900b6.chunk.js:1:1075900
r@https://library.bdrc.io/static/js/2.6c7900b6.chunk.js:1:46918
s@https://library.bdrc.io/static/js/2.6c7900b6.chunk.js:1:47121
```

to reproduce:
- search "’das log" in wylie
- click on the second result, MW1KG1400
- click on scans
- click on the breadcrumbs to get back to the search results

**Comment by eroux** [comment]
possibly related: https://share.getcloudapp.com/WnuxdlQm

**Comment by berger-n** [comment]
I think we're finally good here:
- ["'das log" / MW1KG1400](https://library.bdrc.io/show/bdr:W1KG1400?s=q%3D%2522%25E2%2580%2599das%2520log%2522~1%26lg%3Dbo-x-ewts%26t%3DInstance%26f%3Dasset%2Cinc%2Ctmp%3AhasOpen%26n%3D2)
- ["lam rim" / MW1EE32](https://library.bdrc.io/search?q=%22lam%20rim%22~1&lg=bo-x-ewts&t=Instance&f=asset,inc,tmp:hasOpen&n=1)
- outlines with sections having `bf:identifiedBy`
  - https://library.bdrc.io/show/bdr:MW22084?part=bdr:MW22084_S0001
    ![image](https://user-images.githubusercontent.com/33383857/120672118-4e213300-c492-11eb-8e2f-2038af679b5e.png)
  - https://library.bdrc.io/show/bdr:MW0TT0000?part=bdr:MW0TS001
    ![image](https://user-images.githubusercontent.com/33383857/120672245-6bee9800-c492-11eb-9c2e-97ddb013a66c.png)
- outline search results: 
  https://library.bdrc.io/show/bdr:MW12827?osearch=%22dri%20med%20%27od%20zer%22~1@bo-x-ewts
  ![image](https://user-images.githubusercontent.com/33383857/120672734-da335a80-c492-11eb-9a64-5af3c5cde880.png)
- outline nodes with multiple authors:
  https://library.bdrc.io/show/bdr:MW1PD107937?part=bdr:MW1PD107937_0C30BD
  ![image](https://user-images.githubusercontent.com/33383857/120674670-9d686300-c494-11eb-9eb7-74c6736cc4f7.png)

**Comment by eroux** [comment]
excellent, thanks! @TBRC-pmench can you test if you're still getting the error you got yesterday?

**Comment by TBRC-pmench** [comment]
The error I got yesterday appears to be fixed.

**Comment by eroux** [comment]
ok, thanks!

**Comment by berger-n** [comment]
just keeping track of things here
- fixed etext outline crash: https://library.bdrc.io/show/bdr:IE0OPP002915
  ![image](https://user-images.githubusercontent.com/33383857/121332874-8e603580-c918-11eb-9120-4317858281c7.png)
- fixed loading match context crash: https://library.bdrc.io/search?q=%22dri%20med%20%27od%20zer%22&lg=bo-x-ewts&t=Etext
  ![image](https://user-images.githubusercontent.com/33383857/121333159-d67f5800-c918-11eb-99c7-9f3867e4bdb1.png)
