### ISSUE TITLE
Some NLM works not loading on website

### ISSUE THREAD

**Issue by TBRC-Travis** [buda-base/public-digital-library#495]
@eroux for some reason https://library.bdrc.io/show/bdr:W1NLM2232 is not loading.  I see this strange icon when trying to load the scans:

<img width="193" alt="Screen Shot 2021-06-02 at 4 15 19 PM" src="https://user-images.githubusercontent.com/19354126/120546389-c9fd7b80-c3bd-11eb-9d77-9731a715ae71.png">

all the images and json files appear to be properly synced to s3.

it also appears that W1NLM2226 - W1NLM2309 load on BUDA but not on tbrc.org which is strange.

**Comment by eroux** [comment]
see https://github.com/buda-base/buda-iiif-server/issues/80
