### ISSUE TITLE
Wrong pdf volume download link

### ISSUE THREAD

**Issue by MarcAgate** [buda-base/public-digital-library#496]
On this page: https://library.bdrc.io/show/bdr:W3PD1100
When using the dropdown list to generate then download volume 4 of W3PD1100, the link created actually corresponds to the first volume (https://iiif.bdrc.io/download/file/pdf/bdr:I4PD487:1-502) but it should be  I4PD490_1-822 

This is the only location where this problem occurs

if I go down on this same page and click on the link to the individual volume page (https://library.bdrc.io/show/bdr:I4PD490) then download is ok

Same thing from within the viewer here: https://library.bdrc.io/show/bdr:W3PD1100?s=%2Fshow%2Fbdr%3AMW3PD1100%3Ftabs%3Dbdr%3AW3PD1100#open-viewer

**Comment by eroux** [comment]
ah good to hear from you @MarcAgate 

thanks! This is actually entirely in the hands of the IIIF server so I moved this issue to https://github.com/buda-base/buda-iiif-server/issues/81

you can even look at it if you want ;)
