### ISSUE TITLE
publication date missing in search results display

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#499]
For instance in https://library.bdrc.io/search?q=%22Du%20ku%20la%22~1&lg=bo-x-ewts&t=Instance&pg=1&f=asset,inc,tmp:hasOpen&f=author,inc,bdr:P37 

for instance MW1AC371 (hit number 3) was published in 2013 (it's indicated in the data)

**Comment by eroux** [comment]
ok, the data is now available and the display is ok:

https://library.bdrc.io/search?q=%22Du%20ku%20la%22~1&lg=bo-x-ewts&t=Instance&pg=1&f=asset,inc,tmp:hasOpen&f=author,inc,bdr:P37

but I think it could be a bit better... what about displaying 

```
{tmp:yearStart}-{tmp:yearEnd}
```

right below the publisher location (in the same block)?

**Comment by berger-n** [comment]
done: https://library.bdrc.io/search?q=%22Du%20ku%20la%22~1&lg=bo-x-ewts&t=Instance&pg=1&f=asset,inc,tmp:hasOpen&f=author,inc,bdr:P37

 ![image](https://user-images.githubusercontent.com/33383857/121360672-ea38b780-c934-11eb-8eeb-c074c7531c0a.png)

in Versions associated with Work search as well: https://library.bdrc.io/search?i=bdr:WA23956&t=Work&w=q%3D%2522rgyal%2520dbang%2520lnga%2520pa%2527i%2520rang%2520rnam%2520du%2520kU%2520la%2527i%2520gos%2520bzang%2522~1%26lg%3Dbo-x-ewts%26t%3DWork%26n%3D1

 ![image](https://user-images.githubusercontent.com/33383857/121360915-1f450a00-c935-11eb-8310-c87ee503ad11.png)

(BTW note that it seems that in the latter some Author and Note information are not returned by [query](https://purl.bdrc.io/lib/workInstancesGraph?R_RES=bdr%3AWA23956&format=json))

**Comment by eroux** [comment]
looks perfect, thanks! I've reported the issue on https://github.com/buda-base/lds-queries/issues/74
