### ISSUE TITLE
inpiration from other UIs

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#5]
There's an interesting UI for topics on:

https://eric.ed.gov/?qt=brain

click on one of the results, then "Search collection using this descriptor", ex: https://eric.ed.gov/?q=%22%22&ff1=subBrain then you can click on other tags on the left, they will be added in the list of labels towards the top, and you can still run a text query in it.

I think it's a very nice example... we don't have to do that now, it's just to share and to get some inspiration for future versions!

**Comment by berger-n** [comment]
I agree 
exactly what we need here
