### ISSUE TITLE
impossible to open mirador when first volume is missing

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#500]
for instance on https://library.bdrc.io/show/bdr:W8LS25567

**Comment by berger-n** [comment]
fixed: https://library.bdrc.io/show/bdr:W8LS25567#open-viewer (https://library.bdrc.io/view/bdr:W8LS25567)

![image](https://user-images.githubusercontent.com/33383857/121332612-52c56b80-c918-11eb-866b-bc66ea4739ea.png)

**Comment by eroux** [comment]
excellent, thanks!
