### ISSUE TITLE
add unAPI information

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#504]
The first step of https://github.com/buda-base/public-digital-library/issues/498 should be relatively easy and should make Zotero work directly: the unAPI connector. On the client it consists in two parts:

```
<link rel="unapi-server" type="application/xml" title="unAPI" href="https://ldspdi.bdrc.io/UNAPI" />
```

in the header (that can be for all the pages), plus in the instance tab and in the scans tab:

```
<abbr class="unapi-id" title="bdr:XXX"></abbr>
```

where `XXX` is for instance `MW22084` in the instance tab and `W22084` in the scans tab. There's a demo of the desired output [here](http://eroux.fr/testunapi.html) (note that the `abbr` is not empty in the demo but it shouldn't matter). Once Zotero and the connector for the browser are installed, it should display something like that:

![Capture d’écran de 2021-06-16 14-07-46](https://user-images.githubusercontent.com/60868/122216134-51fa7f80-ceac-11eb-9ec3-71209469629f.png)

**Comment by eroux** [comment]
(note that it won't work for outline nodes / instance parts, but should in the near future)

**Comment by eroux** [comment]
server-side: https://github.com/buda-base/lds-pdi/issues/215

**Comment by berger-n** [comment]
done: http://library-dev.bdrc.io/show/bdr:W22084

![image](https://user-images.githubusercontent.com/33383857/122583109-2ff23000-d059-11eb-92e5-07739b82c042.png)

**Comment by eroux** [comment]
wow, amazing, thanks a lot!

**Comment by eroux** [comment]
the Zotero doesn't seem to be working on https://library.bdrc.io/show/bdr:MW1PD159441

**Comment by berger-n** [comment]
was not deployed on library until now: https://library.bdrc.io/show/bdr:W1PD159441
there is an issue with unAPI though 
the plugin icon is not highlighted here and its context menu doesnt not contain unAPI option:

![image](https://user-images.githubusercontent.com/33383857/122726490-55a85080-d276-11eb-85e9-24c0246f5195.png)

yet the code is there:

![image](https://user-images.githubusercontent.com/33383857/122726898-bfc0f580-d276-11eb-9205-8abf7a6675d1.png)

![image](https://user-images.githubusercontent.com/33383857/122726973-d2d3c580-d276-11eb-9351-529689eaa308.png)

**Comment by eroux** [comment]
ah thanks! This seems linked to https://github.com/buda-base/lds-pdi/issues/217 , the plugin works on https://library.bdrc.io/show/bdr:W22084

**Comment by eroux** [comment]
for reference: https://github.com/zotero/translators/issues/2472
