### ISSUE TITLE
cant open info.json in OSD from volume record

### ISSUE THREAD

**Issue by berger-n** [buda-base/public-digital-library#506]
see https://library.bdrc.io/show/bdr:I2PD20017#open-viewer

![image](https://user-images.githubusercontent.com/33383857/122792638-a477d980-d2ba-11eb-8ebf-a5010cf1062d.png)

it works from https://library.bdrc.io/show/bdr:W2PD19896#open-viewer though...

**Comment by berger-n** [comment]
`ResInfo-SameAs` for [`bdr:I2PD20017`](http://purl.bdrc.io/query/graph/ResInfo-SameAs?R_RES=bdr%3AI2PD20017&format=json) does not return `adm:access` property whereas it does for [`bdr:W2PD19896`](https://purl.bdrc.io/query/graph/ResInfo-SameAs?R_RES=bdr%3AW2PD19896&format=json)
which is why the former does not send token and gets a 401 and the latter not
(I guess it's not the most urgent but let's keep track of it here)

**Comment by eroux** [comment]
hmmm, interesting... can you describe the logic here? Who is calling `ResInfo-SameAs` (pdl or mirador)? how does it use the result?

**Comment by berger-n** [comment]
query is the one called in pdl resource page
then if needed it gives a boolean parameter to mirador:
https://github.com/buda-base/public-digital-library/blob/56b8fac0275da359682c22a634d562e4134afb4e/src/components/ResourceViewer.js#L3844-L3848

parameter is then propagated to osd which sets the xhr header accordingly:
https://github.com/openseadragon/openseadragon/blob/cac0e5c9bd64460b8d1e5ab97052751d13f0d7a5/src/openseadragon.js#L2247-L2274

**Comment by eroux** [comment]
Ah ok I understand. I have to say I'm not 100% sure why we're distinguishing the two cases instead of just having `withCredentials = true` all the time... but I'm thinking perhaps when we don't have the access thing, perhaps we can consider that withCredentials = true?

**Comment by berger-n** [comment]
you were right, thanks! it's 100% working to always set it to true: https://library.bdrc.io/show/bdr:I2PD20017#open-viewer

![image](https://user-images.githubusercontent.com/33383857/123073619-dc942f00-d416-11eb-9add-a8ea3c11c2b9.png)

it seems to me that ["back in the days"](https://github.com/buda-base/public-digital-library/commit/f1df936096e81b18d1ddc65f8601760eccb9b042) sending credentials stuff when not needed would trigger an error, but that's not longer the case, so I'm closing the issue
