### ISSUE TITLE
add Khmer and Burmese to the list of languages

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#509]
the data is currently made in such a way that selecting the "Indic" search is required to find Burmese and Khmer manuscripts, while these two languages are not Indic. This not ideal but there are reasons for that (most titles and texts are in Pali, which is an Indic language). So I'm thinking we should allow users to understand that and select the language they want.

I initially thought we could add two entries in the list:
- `Burmese or Pali (transliterated)`
- `Khmer or Pali (transliterated)`

that would both map to `inc-x-ndia`. But I don't think this is a very good option as one lang tag would be associated with multiple labels...

So here's an idea adding a new `Pali / Burmese / Khmer (transliterated)` lang tag, mapping to `pi-x-ndia`... I think that would work well

**Comment by berger-n** [comment]
done: http://library-dev.bdrc.io/search?q=%22dhammapada%22&lg=pi-x-ndia&t=Instance&f=asset,inc,tmp:hasOpen

![image](https://user-images.githubusercontent.com/33383857/126136062-8e5d288d-ba43-49da-a1f8-d1a59d9f048c.png)

**Comment by eroux** [comment]
perfect, thanks!
