### ISSUE TITLE
use place type above icon

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#515]
just like we display the part type instead of just "version" for versions, let's display the place type instead of "place" in the search results

**Comment by berger-n** [comment]
done: http://library-dev.bdrc.io/search?q=%22lha%20sa%22~1&lg=bo-x-ewts&t=Place&pg=1&f=placeType,inc,bdr:PT0074&f=placeType,inc,bdr:PT0037

![image](https://user-images.githubusercontent.com/33383857/126158107-4e2eb62c-e49f-46f7-9eb5-a49af27722a6.png)

**Comment by eroux** [comment]
perfect, thanks!
