### ISSUE TITLE
hide future features

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#519]
namely these:

![Capture d’écran de 2021-07-20 18-34-06](https://user-images.githubusercontent.com/60868/126361990-8ebd2857-9657-4980-ac39-b85474701105.png)

**Comment by berger-n** [comment]
done: https://library.bdrc.io/

![image](https://user-images.githubusercontent.com/33383857/126483251-06226c2c-9990-4409-b60b-a56b21702508.png)

**Comment by eroux** [comment]
perfect, thanks!
