### ISSUE TITLE
cannot logout

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#520]
- go to https://library.bdrc.io/ while logged in
- click on log out
- wait for the log out to fully finish
- close the tab
- open https://library.bdrc.io/
- you are still logged in, which shouldn't happen

**Comment by eroux** [comment]
(note: clicking on logout should summon a spinning thingy while waiting for the logout to happen)

**Comment by berger-n** [comment]
fixed using auth0 logout call: https://library.bdrc.io/show/bdr:W8LS26212
now once you're logged out it won't silently log you in

**Comment by eroux** [comment]
perfect, thanks!
