### ISSUE TITLE
making more versions visible by default in the search

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#521]
currently the search on versions automatically turns on the "open access" filter, which selects the following results:

released versions with at least 1 set of scans or etexts that is open access

Now that we have links to IA for (most) copyrighted works, it would make sense to at least list them, but it seems we want to show everything. Here are the categories of works that would be appear if we remove all filters:
- copyrigted works: ~3,800, including ~750 not accessible on IA
- works restricted by tradition + temporarily + by BDRC:  124 + 269 + 133 = 526
- works for which the images have not been synced yet: 10,992 (mostly FPL and FEMC I suspect)
- works that are just catalog records (no planned image sync): ~37,000 (just counting the NGMCP catalog)

@JannTibetan are we sure we want all of these to appear in the search by default? Or perhaps just the ones with images or etexts?

**Comment by JannTibetan** [comment]
I possible, I would like the default search setting to return:
> - copyrigted works: ~3,800, including ~750 not accessible on IA
> - works restricted by tradition 
> - works that are just catalog records (no planned image sync): ~37,000 (just counting the NGMCP catalog)

**Comment by eroux** [comment]
oh ok! so:
- not those restricted temporarily or by BDRC
- not those whose images are not synced yet

ok, let me see how to best do that... thanks!

**Comment by eroux** [comment]
in order for this to be implemented in a way that's selectable by the users, we need to:
- rename the "open access" filter into "Possibly accessible" (I can't find a better term... that will select open access + copyrighted + restricted by tradition"
- add a "catalog only" filter in the "asset availability" menu

both would be selected by default, and that will create a "or" that will result in the requested filtering... I'll create two new properties:
- `tmp:catalogOnly` that will be `true` in the case of catalog only records, and absent by default for regular records
- `tmp:possibleAccess` that will behave like `tmp:hasOpen`

I think the best is that I add these now and then we can adjust the UI... @berger-n does that sound reasonable?

**Comment by JannTibetan** [comment]
copyrighted works: ~3,800, including ~750 not accessible on IA
works restricted by tradition
works that are just catalog records (no planned image sync): ~37,000 (just counting the NGMCP catalog)
-- Including these in default search results will increase the number of results that come back but without inundating the user with results whose lack of images is time-consuming to explain (when will the images be synced? why is this restricted? can you make an exception for me?)

**Comment by JannTibetan** [comment]
Thanks you guys.

**Comment by eroux** [comment]
so, I made a few experiments and I have a solution that mostly works... but there are some cases in our database that I don't really know how to classify and that would fall in the "catalog only" category, one such example is W00KG0615 : because we have no volume information at all in our database, there's no set of scans associated with it, and thus it's in the same category as the NGMCP instances... I think it's fine but I have to say I don't really understand this case... @karmagongde can you tell us a bit about the status of W00KG0615? Is this something that we catalogued because it's useful, are there some images that we might have, or did you catalog it based on a physical edition in the office?

**Comment by karmagongde** [comment]
@eroux W00KG0615 does not have images. It has never been scanned. Probably the book is given to GEBIS. BDRC gave several boxes of books that are not scanned and they agreed to scan them at the time. 

When we get images for W00KG0615 and another with the same status then I will generate a scan request.

**Comment by eroux** [comment]
ok thanks for the explanation, that's really helpful! I think it's fine if it appears as "catalog only" then... @JannTibetan do you confirm?

**Comment by JannTibetan** [comment]
To me W00KG0615 is the kind of record we don't want to include (because people will ask, When will it be ready??). 
The types of I records I selected yesterday seemed good to me because we either have the images (including copyrighted and restricted by tradition) or will never have the images (NGMPP). It's the third category of "maybe someday we'll get the images" that I think are frustrating to users.  BUT if these GEBIS books are one-of-a-kind then we should include the records just so people can know that such books exist.

**Comment by eroux** [comment]
well, the issue here is that we don't make the distinction between the two types in the data (and we might well have the images from NGMPP before we have those of W00KG0615, who knows)... But here's an idea: on https://library.bdrc.io/show/bdr:MW00KG0615 (and https://library.bdrc.io/show/bdr:MW0NGMCP52429) we could display a grayed out "scans" tab, with a message like "BDRC does not have associated images, the record is purely for reference"? This would contrast with the likes of https://github.com/buda-base/public-digital-library/issues/525 which have a scan tab and will display a message like "Images not yet available" (once #525 is done). wdyt?

**Comment by JannTibetan** [comment]
I think  "BDRC does not have associated images, the record is purely for reference" is a good. Maybe we can tweak it to say, "BDRC does not have images of this text, the record is purely for reference"

**Comment by JannTibetan** [comment]
"Images not yet available" is also a good message to add to records for which the images truly are forthcoming.

**Comment by eroux** [comment]
ok excellent, let's do that! I'll deploy a change in the queries early next week so that we can implement that

**Comment by berger-n** [comment]
deployed: https://library.bdrc.io/search?q=%22spyod%20%27jug%22~1&lg=bo-x-ewts&t=Instance&f=asset,inc,tmp:possibleAccess&f=asset,inc,tmp:catalogOnly
