### ISSUE TITLE
hide non-released items for admins too

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#522]
it seems it's not very useful... perhaps there could be a special filter for admins in the asset availability thing, where non-released things would be filtered by default... that's a bit more complex and that can be done in a second time, in a first time we can just make these disappear

**Comment by eroux** [comment]
@berger-n what about a filter "show non-released" only visible for admins (and desactivated by default)? it would be a bit weird as it would be a sort of "negative" filter... wdyt?  example https://library.bdrc.io/search?q=%22mes%20po%27i%20shul%20bzhag%22~1&lg=bo-x-ewts&t=Work

**Comment by berger-n** [comment]
seems not too difficult to add an admin-only facet and hide those results when it's not checked

**Comment by berger-n** [comment]
(oops)

**Comment by berger-n** [comment]
done: http://library-dev.bdrc.io/search?q=%22mes%20po%27i%20shul%20bzhag%22~1&lg=bo-x-ewts&t=Work&s=closest%20matches%20forced

- when you are logged and admin, if you check "Non-released items / Show" in the facet widgets:

![image](https://user-images.githubusercontent.com/33383857/127532334-42d23cd5-6621-41fb-9bd5-7e58222b539a.png)


- when you are not logged or logged but not admin:

![image](https://user-images.githubusercontent.com/33383857/127531946-72b755cc-1672-4bd7-ab42-5d868a19a1ac.png)


(note the difference in the number of Works, 1 if not logged, 2 if admin)

**Comment by eroux** [comment]
Perfect, thanks!
