### ISSUE TITLE
Change language of download menu

### ISSUE THREAD

**Issue by JannTibetan** [buda-base/public-digital-library#524]
Can we change this to say something like "generate text as PDF", "generate text as images files." The latter case is the one that is perhaps confusing for users. PDF and ZIP are not commonly opposed to one another and so people may not understand what the difference is between the two options.

<img width="206" alt="Screen Shot 2021-07-22 at 10 19 55 AM" src="https://user-images.githubusercontent.com/44705185/126661610-d0a3b30e-655c-49da-9c56-8ee8134ace02.png">

**Comment by eroux** [comment]
ah, good point yes. What about "Get image files"? (I'm personally very confused by "text as PDF", to me this sounds like a PDF with some actual text and not images... but perhaps it's just me)

**Comment by JannTibetan** [comment]
Get PDF and Get Image Files is preferable. 
Should was say “Get Image Files (TIFF)”?

**Comment by eroux** [comment]
ok yes, images can be tiff or jpeg so perhaps `(TIFF)` can be confusing

**Comment by eroux** [comment]
@berger-n for next week

**Comment by JannTibetan** [comment]
Thanks guys

**Comment by berger-n** [comment]
so I've updated menus in mirador and in resource view as well
here's a preview:

- http://library-dev.bdrc.io/view/bdr:W3CN9692

![image](https://user-images.githubusercontent.com/33383857/127632668-30c9faff-658a-4ac1-9348-0a0db8c0bce1.png)

![image](https://user-images.githubusercontent.com/33383857/127632780-c362800b-a6b6-4514-b28e-7d1dc6484464.png)

![image](https://user-images.githubusercontent.com/33383857/127632827-0dae0f05-6646-48d0-954d-ce9f402788fd.png)



- http://library-dev.bdrc.io/show/bdr:W3CN9692:

![image](https://user-images.githubusercontent.com/33383857/127633660-0dc5afc2-33f1-4481-a1c0-01e5c9c8bb01.png)

![image](https://user-images.githubusercontent.com/33383857/127633599-a5716bd8-f24c-44ee-bb1b-e68a3e2b442a.png)

![image](https://user-images.githubusercontent.com/33383857/127633970-6cdb0c22-76c3-4014-88f1-2c39288ef3f0.png)

![image](https://user-images.githubusercontent.com/33383857/127634013-178b5477-e07c-4b89-8866-421c7635b048.png)

---

- regarding the latter, should we update the top-level popup menu as well? not sure how to rephrase it though:

![image](https://user-images.githubusercontent.com/33383857/127634661-2ed0e030-260a-4db8-8115-08e789bef850.png)

**Comment by eroux** [comment]
maybe "Get images or PDF"? What do you think @JannTibetan ?

**Comment by JannTibetan** [comment]
> maybe "Get images or PDF"? What do you think @JannTibetan ?

Thank you. I just tried it and it and it works very well. We'll update the user guide to explain this handy feature. So much better than download on tbrc.org!
