### ISSUE TITLE
fix display when no images are available

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#525]
In the case of https://library.bdrc.io/show/bdr:W2KG210295 we should display a message like "Images not available yet". Here I think this is a normal case where the manifest returns a 404

**Comment by berger-n** [comment]
when not logged collection returns 401 so there's an error message:

![image](https://user-images.githubusercontent.com/33383857/126675447-d19f0fa5-cea2-40c1-b362-b2c85ccfcd3d.png)

once logged it seems that fixes for #370 & #383 prevent the code to throw the 404 exception:

https://github.com/buda-base/public-digital-library/blob/18a97bff1410447dbf5a4ed9302c84711fe57f84/src/state/sagas/index.js#L1014-L1020

not sure how to handle that for now... need to think about it

**Comment by eroux** [comment]
oh I see... hmm.... I think there's some interference between different things... I think for instance

https://library.bdrc.io/show/bdr:W3CN23000

works because the W records had a thumbnail attached in the data, so even if the manifest is 404 it works anyways... so here we area dealing with a case where there is no thumbnail and no volume 1. I think all these cases can lead to an error like in https://github.com/buda-base/public-digital-library/issues/383 . That should be relatively easy to implement right?

**Comment by berger-n** [comment]
done: http://library-dev.bdrc.io/show/bdr:W2KG210295

![image](https://user-images.githubusercontent.com/33383857/127357469-dca429e7-3ee6-4e6e-945c-286726d5a066.png)

**Comment by eroux** [comment]
excellent, thanks!
