### ISSUE TITLE
add icons next to messages in the scan tab

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#528]
In the message of the scans tab:
- left of the "images not available" message there should be the appropriate icon (the same as in the search results)
- left of all the different fair use messages (IA link or not), there should be the fair use icon
- left of the message for restricted texts, there should be the appropriate icon too

**Comment by berger-n** [comment]
done:
- http://library-dev.bdrc.io/show/bdr:W3CN8302

![image](https://user-images.githubusercontent.com/33383857/127677844-7fb620dc-4052-4698-b15c-9d0c93d77636.png)
---

- http://library-dev.bdrc.io/show/bdr:W1KG18414

![image](https://user-images.githubusercontent.com/33383857/127677882-a96fd222-a99c-4172-8865-07f0e1f61c82.png)
---

- http://library-dev.bdrc.io/show/bdr:W3CN6498

![image](https://user-images.githubusercontent.com/33383857/127677926-640ce180-3c37-4a3a-9be7-4e4001823a14.png)
---

- http://library-dev.bdrc.io/show/bdr:W8LS18997

![image](https://user-images.githubusercontent.com/33383857/127677995-d198bf57-0134-454f-aa27-c9f747949ed0.png)

**Comment by eroux** [comment]
Perfect, thanks!
