### ISSUE TITLE
app crashes when searching an instance from the editor

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#529]
see following screenshot when searching "sgam po pa gsung 'bum" in the source property of notes:

![Capture d’écran de 2021-07-23 11-14-01](https://user-images.githubusercontent.com/60868/126762054-fa56af1d-1e6b-4724-ba00-b4548a5c72b2.png)

**Comment by eroux** [comment]
URL: https://library.bdrc.io/simplesearch?q=%22sgam%20po%20pa%20gsung%20%27bum%22~1&lg=bo-x-ewts&t=ImageInstance&for=bdr:NTVU58DRAWbds:NoteShape-noteSource0

**Comment by eroux** [comment]
(if possible, let's use the full qname for types, like `bdo:ImageInstance`, and map it to what's used internally on pdl)

**Comment by berger-n** [comment]
quickfixed it: 

![Kazam_screencast_00050 mp4](https://user-images.githubusercontent.com/33383857/126766363-8e2ebe43-4c1d-4a30-90f3-31af8e4077e5.gif)

note that I had to use incognito mode to make iframe refreshed at first

**Comment by eroux** [comment]
hmmm ok... what URL does it lead to? https://library.bdrc.io/simplesearch?q=%22sgam%20po%20pa%20gsung%20%27bum%22~1&lg=bo-x-ewts&t=bdo:ImageInstance&for=bdr:NTVU58DRAWbds:NoteShape-noteSource0 doesn't seem to be working for me... (or is it another case of cache not going away?)

**Comment by berger-n** [comment]
sorry I can't fix search datatype in a minute :-)
`bdo:ImageInstance`  is currently not allowed

I think the way we thought of it is to use `Instance` type with `hasImage` facet: https://library.bdrc.io/search?q=%22sgam%20po%20pa%20gsung%20%27bum%22~1&lg=bo-x-ewts&t=Instance&pg=1&f=asset,inc,tmp:hasImage

**Comment by eroux** [comment]
oh ok, that's what I was looking for https://library.bdrc.io/search?q=%22gsung%20%27bum%20sgam%20po%20pa%22~1&lg=bo-x-ewts&t=Scan (the search I initially used wasn't very good)
