### ISSUE TITLE
Increased visibility of image group IDs for admins

### ISSUE THREAD

**Issue by TBRC-Travis** [buda-base/public-digital-library#530]
I still go to tbrc.org quite often to review image group numbers for a given work.  On the old site it's quite easy to see the corresponding image group numbers associated with a work which is quite helpful for our archival operations.

For example:

<img width="483" alt="Screen Shot 2021-07-27 at 11 52 49 AM" src="https://user-images.githubusercontent.com/19354126/127186241-ab1ea622-7438-4ced-983a-e78757e9fa78.png">

It's also helpful to be able to see the image group number for a work that has been cataloged but not synced yet.  For example:

<img width="677" alt="Screen Shot 2021-07-27 at 11 54 29 AM" src="https://user-images.githubusercontent.com/19354126/127186592-5340f526-433b-4c9e-9a1b-f9b879ceb7d3.png">

If the librarians update an image group number for a given work only the latest image group number is reflected on tbrc.org which is helpful.

Could we please add this kind of visibility of image group numbers for BUDA?

**Comment by eroux** [comment]
Thanks! This is really a feature specific for admin, I don't think regular users were really understanding what these IDs were... let me think of ways we could display something like that for admins... one way that's currently possible is by clicking on the different volumes (in https://library.bdrc.io/show/bdr:W22084 for instance) and looking at their ID... are there use cases that require much more speed?

**Comment by TBRC-Travis** [comment]
Having drill down into each volume to see the image group number is really time-consuming.  On the old site it's very easy to load a work and be able to see at a glance what the associated image group numbers are.  

On BUDA there's a good volume listing under Scans tab --> Extended Properties --> Has Volume.  Perhaps adding the image group number in parentheses next to the Volume # is a good option?

![scan-volumes](https://user-images.githubusercontent.com/19354126/127712196-1bdf83dc-f240-4240-93a1-09120633eb0f.gif)

I personally think it's useful to have the image group numbers more visible to be able to link specific volumes back to their corresponding archival elements if needed.  It's helpful when we need to fix issues on the site.

A suppose a quick LDS query would work too if there's one available.

**Comment by eroux** [comment]
here's an idea:
- we don't display the "has volume" property for non-admins (who, in my experience, tend to get confused when they land on the page of a volume)
- when we display it for admins, we display the image group next to the link, à la tbrc.org

A LDS query already exists, see for instance https://purl.bdrc.io/query/table/volumesForInstance?R_RES=bdr:W23703

**Comment by TBRC-Travis** [comment]
Yes, I like that idea.  That'll work!

Thanks for the query.  I'll keep that one in my back pocket.  :)

**Comment by berger-n** [comment]
added image group numbers to volume list, which is now visible only if logged and admin: http://library-dev.bdrc.io/show/bdr:W2PD16865

![image](https://user-images.githubusercontent.com/33383857/127882053-e8e86da1-a6ac-4e67-a565-28d8dab14cdf.png)

**Comment by eroux** [comment]
looks perfect, thanks!

**Comment by berger-n** [comment]
need to clean these empty square brackets in etext outline: http://library-dev.bdrc.io/show/bdr:IE0OPP005472

![image](https://user-images.githubusercontent.com/33383857/128715885-de173ed2-ba4a-4511-b7dd-fb55f29a351c.png)

**Comment by berger-n** [comment]
done: http://library-dev.bdrc.io/show/bdr:IE0OPP005472

![image](https://user-images.githubusercontent.com/33383857/128717438-0c2d99e3-e2d3-44fc-b2d6-3782df3678d5.png)
