### ISSUE TITLE
Adding integration to the Vimala Treasures printing service 

### ISSUE THREAD

**Issue by JannTibetan** [buda-base/public-digital-library#531]
Vimala Treasures's print-on-demand service is used by dozens of users every year. We should continue to provide a convenient way to order prints directly from a work record, as we have been doing on tbrc.org for years ([see here](https://www.tbrc.org/#!footer/about/print)). Perhaps we could add a button for Vimala here:
<img width="832" alt="Screen Shot 2021-07-28 at 4 08 09 PM" src="https://user-images.githubusercontent.com/44705185/127388717-b4a96479-f792-480c-93b4-606245d25855.png">

**Comment by eroux** [comment]
Oh ok, we decided to discontinue it a few years ago, but maybe that was before your time, I can't remember... It's not a big deal to bring it on again. I think adding a fourth button here (permalink, download, cite this item, order print) is perhaps a little bit overkill... perhaps it could be in the download button? Were we to bring this back, it would also need to appear in the outlines (as it does on tbrc.org). Out of curiosity, where do your statistics (dozens of users per year) come from?

**Comment by JannTibetan** [comment]
I just looked at their recent receipts and they seem to process several dozen orders a year. Most orders are for individual volumes but a couple orders are for a large number of prints (10-15 volumes).

**Comment by JannTibetan** [comment]
We might think about adding a small print icon and the words "print on demand"

**Comment by eroux** [comment]
ok yes. @berger-n this should be quite straightforward as it's just a popup / popin with some text and an link to the current item... (it can be the permalink). Wdyt?

**Comment by berger-n** [comment]
done: http://library-dev.bdrc.io/show/bdr:W12827

![image](https://user-images.githubusercontent.com/33383857/128216567-b5c3b67a-0834-4de2-b151-fdd5ca481046.png)

![image](https://user-images.githubusercontent.com/33383857/128216659-40011707-063e-4c9f-b6ba-d6ef3596c8f2.png)
---

in the outline as well (whenever images are available):

![image](https://user-images.githubusercontent.com/33383857/128217005-d3c8d6b4-ae20-4c85-be04-03f25e59504f.png)

**Comment by JannTibetan** [comment]
Thank you. It works very well and doesn't take up value real estate.

**Comment by eroux** [comment]
@berger-n I updated pdl on buda1 but I can't see anything on https://library.bdrc.io/show/bdr:W12827... can you check?

**Comment by JannTibetan** [comment]
The print on demand link is now working on the public site (at least for me).

**Comment by JannTibetan** [comment]
![image](https://user-images.githubusercontent.com/44705185/133319063-42f042a4-cdb6-403f-9960-4167130f2a2d.jpeg)
