### ISSUE TITLE
i18next files in json

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#532]
It would be easier for translators if the i18next files were in json instead of js. @berger-n is that easy to do?

cc @ngawangtrinley

**Comment by berger-n** [comment]
done:

https://github.com/buda-base/public-digital-library/blob/3aaba32eef4b9f31c4fa1d1364df9cb3fbf5e884/src/translations/en.json#L1-L10

**Comment by eroux** [comment]
ah wonderful, thanks a lot!
