### ISSUE TITLE
"open etext" link no longer displaying on versions tab

### ISSUE THREAD

**Issue by JannTibetan** [buda-base/public-digital-library#534]
This morning I've encountered this problem on multiple records. Because people aren't familiar with our etext icon it's important to display the "open etext viewer" link and not just the bdr: number. 
<img width="799" alt="Screen Shot 2021-08-09 at 7 34 10 AM" src="https://user-images.githubusercontent.com/44705185/128700394-cec70ac8-089f-49cb-93a9-dd6868ff628b.png">

**Comment by berger-n** [comment]
done, you can preview it here: http://library-dev.bdrc.io/show/bdr:MW28942

![image](https://user-images.githubusercontent.com/33383857/128869911-3ab83be5-2476-49ee-aac0-011224bf7987.png)

a few side issues though:

- [ ] in this case [link for first etext](http://library-dev.bdrc.io/show/bdr:IE0OPP009519?backToEtext=bdr:MW28942#open-reader) won't open viewer as already reported here: https://github.com/buda-base/public-digital-library/issues/483

- [ ] regarding second etext here, it's unclear why [first volume](http://library-dev.bdrc.io/show/bdr:UT28942_002_0000?backToEtext=bdr:IE28942#open-viewer) doesn't display scans but [volume 2](http://library-dev.bdrc.io/show/bdr:UT28942_002_0000?backToEtext=bdr:IE28942#open-viewer) does, I'll check that

**Comment by berger-n** [comment]
> regarding [second etext](http://library-dev.bdrc.io/show/bdr:IE28942) here, it's unclear why [first volume](http://library-dev.bdrc.io/show/bdr:UT28942_002_0000?backToEtext=bdr:IE28942#open-viewer) doesn't display scans but [volume 2](http://library-dev.bdrc.io/show/bdr:UT28942_002_0000?backToEtext=bdr:IE28942#open-viewer) does, I'll check that

found the needle in the haystack, long story short these volumes are all of  `NonPaginated` type so we dont display scans but a warning, preview here: https://library-dev.bdrc.io/show/bdr:IE28942#open-reader

![Screenshot_20210811_141024](https://user-images.githubusercontent.com/33383857/129026199-3fbc56ff-3e3e-4cae-ad2c-70e1458a0b47.png)

**Comment by JannTibetan** [comment]
Ah ok, so this was a non-typical case. Sorry for the wild goose chase.
