### ISSUE TITLE
Related Resources section for G337 might be acting inconsistently 

### ISSUE THREAD

**Issue by JannTibetan** [buda-base/public-digital-library#535]
The record for Ganden Monastery G337 has at least 4 types of "related resources." When you first open up this work record, the Related Resources section defaults to showing the titles of the related Works and not the "All" tab. On other place records it seems that "All" is the default view. Perhaps G337 is acting inconsistently because of the relatively large number of different related data types.
Sakya Monastery G880 - which also has 4 types of related data - also has this same issue.

**Comment by eroux** [comment]
ah yes, the philosophy (if I may say so) of this UI is the following:
- if there are related works, they have their own tab, if there isn't any, there's no tab
- if there are related versions, they have their own tab, if there isn't any, there's no tab
- if there is any related resource (including works and versions, but also persons, places, topics, etc.), the number of related resource per type will appear in the "all" tab

so depending on the place, there might be one, two or three tabs, with the one open by default changing according to the availability of associated resources... this isn't perfect and we could imagine either
- have an "associated works" (and versions) tab always present but grayed out if there's no associated resources of this type (I'm not sure what the default tab would be though in this case... maybe "all"?)
- always defaulting to "all" even when there are associated works or versions...

I think the first option is better... wdyt?

**Comment by JannTibetan** [comment]
I think the ALL is a better default because sometimes people are searching for associated persons rather than works, and if a texts tab is open by default then they might not know that related persons and places are also available for this record. 
Also now I see that the interface has two "all"s and the difference between them might not be clear to newer users:
<img width="818" alt="Screen Shot 2021-08-09 at 11 22 17 AM" src="https://user-images.githubusercontent.com/44705185/128731742-47c1e770-95ea-4b1d-b188-a5a3a47cc5cf.png">

Perhaps change the "all" to "all related resources"?

**Comment by eroux** [comment]
hmmm ok yes, sure, a few questions if we go that route:
- should the All be always the first one?
- since it will be the default, I'm wondering if the other tabs are really relevant... the initial idea was to have a nice little excerpt of the most relevant related works and instances, with a thumbnail, etc. but they now seem a little bit redundant... wdyt?
   * if we drop them, we can remove the tabs and have the content directly, that way we'll have only one "all" (if I understand correctly)
   * if we don't, perhaps we can just remove the "see all" link? it seems redundant (in general, but especially if the "all" tab is the default)
- I suppose this applies to all types and not just places? (it would make an inconsistent UI otherwise) ex: https://library.bdrc.io/show/bdr:P1583

**Comment by eroux** [comment]
so, the conclusion of the last discussion was to remove the "see all" button at the top. One issue that has been pointed out by a board member is that it's not very clear how to see all the works by an author when the work we're looking for is not in the short list on the record... perhaps there should be a more visible button on the right of the list?

**Comment by berger-n** [comment]
done: http://library-dev.bdrc.io/show/bdr:P1583

![Screenshot_20210908_174620](https://user-images.githubusercontent.com/33383857/132541837-0bdc6db0-752d-4525-b9f0-770b4a88cd45.png)

did something similar with each type of resource & related resource (taken from #363, #269):
http://library-dev.bdrc.io/show/bdr:G1657
http://library-dev.bdrc.io/show/bdr:PR01DOR0
http://library-dev.bdrc.io/show/bdr:C35

regarding http://library-dev.bdrc.io/show/bdr:WAS00KG09211 it seems that [query](http://purl.bdrc.io/query/graph/ResInfo-SameAs?R_RES=bdr%3AWAS00KG09211&format=json) does not return `serialHasMember` anymore
reopening #269

**Comment by eroux** [comment]
I think we can close this
