### ISSUE TITLE
performance issue

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#537]
when opening https://library.bdrc.io/show/bdr:MW1FEMC030001?tabs=bdr:W1FEMC030001 the page gets super slow, to the point where the browser has to stop the JS and the fan of the processor turns on...

**Comment by berger-n** [comment]
that seems to be a weird cache issue because in incognito navigation everything is fine...
yet using normal navigation queries won't load which make the UI hang
 
![image](https://user-images.githubusercontent.com/33383857/129028106-4bb5f87d-0155-4564-916d-47948a99f8b7.png)

**Comment by eroux** [comment]
still encountering this, I'll try to debug it next week

**Comment by berger-n** [comment]
same here
https://purl.bdrc.io/query/graph/ResInfo-SameAs?R_RES=bdr%3AMW1FEMC030001&format=json has a lot of log entries (3.5MB)

**Comment by eroux** [comment]
oooh nice! I'll fix that this afternoon

**Comment by eroux** [comment]
fixed, works wonderfully now!
