### ISSUE TITLE
more visible image references when location statement is available

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#542]
We received a suggestion from a user: in cases where there are location statements, example in MW21506 :

![Screen Shot 2021-08-18 at 4 55 51 PM](https://user-images.githubusercontent.com/60868/130039689-d2e27001-2556-4d24-bc10-14312a299f76.png)

users find the information (image xx to yy in volume zz) quite useful. I think we should display it in the following way:

> ff. 11v-13v (v. 4, img. 382-387)

**Comment by berger-n** [comment]
done: http://library-dev.bdrc.io/show/bdr:MW21506?part=bdr:MW21506_AF8D27

![Screenshot_20210909_162332](https://user-images.githubusercontent.com/33383857/132703925-1f6a9eda-ce6c-401d-af5c-c4daa73e352b.png)
---

no volume: http://library-dev.bdrc.io/show/bdr:MW25995?part=bdr:MW25995_B50420

![Screenshot_20210909_162406](https://user-images.githubusercontent.com/33383857/132704016-74e99bee-4003-4e6a-adb4-18c57c222089.png)
---

one page: http://library-dev.bdrc.io/show/bdr:MW1KG3381?part=bdr:MW1KG3381_8945CA

![Screenshot_20210909_162438](https://user-images.githubusercontent.com/33383857/132704104-99649b79-39be-4852-ad23-a7eaf7170ec7.png)
---

nothing changed on http://library-dev.bdrc.io/show/bdr:MW7477?part=bdr:MW7477_334ADF and its multiple statements: 

![Screenshot_20210909_162500](https://user-images.githubusercontent.com/33383857/132704154-f6659c09-2dab-4ebd-8d1e-12ba47f4fd5a.png)

**Comment by eroux** [comment]
this is perfect, thanks a lot! the multiple statements are a bit odd... I'll report that elsewhere
