### ISSUE TITLE
crash in etext search

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#543]
When searching `ཆོས་ཉིད་བདེན་པ་བསྟན་པས་གྲོལ` in the etexts:

https://library.bdrc.io/search?q=%22%E0%BD%86%E0%BD%BC%E0%BD%A6%E0%BC%8B%E0%BD%89%E0%BD%B2%E0%BD%91%E0%BC%8B%E0%BD%96%E0%BD%91%E0%BD%BA%E0%BD%93%E0%BC%8B%E0%BD%94%E0%BC%8B%E0%BD%96%E0%BD%A6%E0%BE%9F%E0%BD%93%E0%BC%8B%E0%BD%94%E0%BD%A6%E0%BC%8B%E0%BD%82%E0%BE%B2%E0%BD%BC%E0%BD%A3%22~1&lg=bo&t=Etext

the app crashes

**Comment by berger-n** [comment]
fixed: https://library.bdrc.io/search?q=%22%E0%BD%86%E0%BD%BC%E0%BD%A6%E0%BC%8B%E0%BD%89%E0%BD%B2%E0%BD%91%E0%BC%8B%E0%BD%96%E0%BD%91%E0%BD%BA%E0%BD%93%E0%BC%8B%E0%BD%94%E0%BC%8B%E0%BD%96%E0%BD%A6%E0%BE%9F%E0%BD%93%E0%BC%8B%E0%BD%94%E0%BD%A6%E0%BC%8B%E0%BD%82%E0%BE%B2%E0%BD%BC%E0%BD%A3%22~1&lg=bo&t=Etext

from what I see problem is that the matching chunk for this result is not returned by [query](http://purl.bdrc.io/lib/etextContentFacetGraph?LG_NAME=bo&L_NAME=%22%E0%BD%86%E0%BD%BC%E0%BD%A6%E0%BC%8B%E0%BD%89%E0%BD%B2%E0%BD%91%E0%BC%8B%E0%BD%96%E0%BD%91%E0%BD%BA%E0%BD%93%E0%BC%8B%E0%BD%94%E0%BC%8B%E0%BD%96%E0%BD%A6%E0%BE%9F%E0%BD%93%E0%BC%8B%E0%BD%94%E0%BD%A6%E0%BC%8B%E0%BD%82%E0%BE%B2%E0%BD%BC%E0%BD%A3%22~1):

![Screenshot_20210823_180032](https://user-images.githubusercontent.com/33383857/130479465-3bbd303b-5ebb-458d-b093-bdbfaf69a293.png)

![Screenshot_20210823_175528](https://user-images.githubusercontent.com/33383857/130478632-9bcc6f53-1f35-4c6f-a9de-d25e8cb85995.png)

**Comment by eroux** [comment]
Oh I see... this is kind of a strange case that involves a few different parts... step 1: https://github.com/buda-base/library-issues/issues/378

**Comment by eroux** [comment]
also partly related: https://github.com/buda-base/xmltoldmigration/commit/372d3b93ae47f357debad9f0f66f4c2cc7b9cca4

closing here since it's not really a pdl issue anymore
