### ISSUE TITLE
remove creator UI noise

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#544]
creator now has some seealso, but it shouldn't appear in the UI: https://library.bdrc.io/show/bdr:P1KG21914

**Comment by berger-n** [comment]
fixed: https://library.bdrc.io/show/bdr:P1KG21914

![Screenshot_20210824_104931](https://user-images.githubusercontent.com/33383857/130587080-e2117a15-c950-4061-80fa-3a8a23f4aaf3.png)

**Comment by eroux** [comment]
Great, thanks!
