### ISSUE TITLE
have an actual Wylie / Unicode switch in etext viewer

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#545]
Currently the way to change the display in the etext viewer is to change the language through the button at the bottom:

![Capture d’écran de 2021-08-24 15-49-57](https://user-images.githubusercontent.com/60868/130633752-e096cda6-4f67-4edb-ba11-0b1c115ccfb7.png)

but some users are confused since English / Tibetan is not really an indication of a change in the transliteration... perhaps we could just have a switch and keep the value in localstorage?

**Comment by berger-n** [comment]
done: http://library-dev.bdrc.io/show/bdr:UTIE0OPP000301_v010?startChar=666269&keyword=%22%E0%BD%A6%E0%BE%9F%E0%BD%BC%E0%BD%84%E0%BC%8B%E0%BD%94%E0%BD%A0%E0%BD%B2%E0%BC%8B%E0%BD%84%E0%BD%84%E0%BC%8B%E0%BD%A3%E0%BD%A6%E0%BC%8B%E0%BD%A7%E0%BD%B5%E0%BE%83%E0%BC%8B%E0%BD%A3%E0%BD%A6%E0%BC%8B%E0%BD%96%E0%BE%B1%E0%BD%B4%E0%BD%84%E0%BC%8B%22@bo#open-viewer

![Screenshot_20210825_122220](https://user-images.githubusercontent.com/33383857/130773814-3832d946-9a7b-4894-bf3c-4e73ea5eb1e1.png)

have to fix https://github.com/buda-base/public-digital-library/issues/343 now

BTW all the etexts are in `bo/bo-x-ewts` I guess
nothing in chinese? yet?

**Comment by eroux** [comment]
excellent, thanks! Nothing in Chinese no... but we wouldn't have a transliteration switch for Chinese anyway. Can you deploy in production? (CC @TBRC-pmench FYI, it could be worth updating the user guide?)

**Comment by berger-n** [comment]
ok thanks! 
deployed: https://library.bdrc.io/show/bdr:UTIE0OPP000301_v010?startChar=666269&keyword=%22%E0%BD%A6%E0%BE%9F%E0%BD%BC%E0%BD%84%E0%BC%8B%E0%BD%94%E0%BD%A0%E0%BD%B2%E0%BC%8B%E0%BD%84%E0%BD%84%E0%BC%8B%E0%BD%A3%E0%BD%A6%E0%BC%8B%E0%BD%A7%E0%BD%B5%E0%BE%83%E0%BC%8B%E0%BD%A3%E0%BD%A6%E0%BC%8B%E0%BD%96%E0%BE%B1%E0%BD%B4%E0%BD%84%E0%BC%8B%22@bo#open-viewer
