### ISSUE TITLE
crash in the app when clicking on a result

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#546]
- go to https://library.bdrc.io/search?q=%22dag%20yig%20thon%20mi%27i%20dgongs%20rgyan%22~1&lg=bo-x-ewts&t=Instance&f=asset,inc,tmp:possibleAccess&f=asset,inc,tmp:catalogOnly 
- click on the last result, this leads to the outline
- click on "view scans", the app crashes

**Comment by berger-n** [comment]
fixed: https://library.bdrc.io/search?q=%22dag%20yig%20thon%20mi%27i%20dgongs%20rgyan%22~1&lg=bo-x-ewts&t=Instance&f=asset,inc,tmp:possibleAccess&f=asset,inc,tmp:catalogOnly

![Screenshot_20210830_110439](https://user-images.githubusercontent.com/33383857/131315144-376c9aa6-9f92-4e9c-8d0d-cc7d145f1d94.png)

**Comment by eroux** [comment]
thanks!
