### ISSUE TITLE
mirador crashes in some cases

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#547]
This seems to happen only when I'm logged in, on https://library.bdrc.io/view/bdr:W8LS26111 :+1: 

![Capture d’écran de 2021-08-30 10-17-59](https://user-images.githubusercontent.com/60868/131308985-02c543d3-a80c-4641-8532-e2c05c3d9bd9.png)

**Comment by berger-n** [comment]
I've added an exception that will display the token which made the parser crash:

![Screenshot_20210830_122756](https://user-images.githubusercontent.com/33383857/131325876-216200e5-8850-491f-9ff3-e441abebb032.png)

**Comment by berger-n** [comment]
deployed version with new `parseJwt`: https://library.bdrc.io/view/bdr:W8LS26111

**Comment by eroux** [comment]
that works now, thanks a lot!
