### ISSUE TITLE
using resized image in some cases

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#55]
For some works (eg http://library-dev.bdrc.io/show/bdr:W1KG4941), the preview image (before we open the viewer) should be smaller. Most of the time it makes sense to take the max size image (as it's faster to encode), but sometimes it's just too big. There should be a limit to the number of pixels (width x heigth) above which a resized image is asked.

**Comment by berger-n** [comment]
should be better now

**Comment by berger-n** [comment]
yet we'll need a way to know and adapt when the canonical image is 60Mb
for now reading view uses them
(opening mirador on this work won't show 1st image before long in reading view)

**Comment by berger-n** [comment]
(BTW it is unclear to me why reading view won't show zoom slider ?? images are more than 6000px wide... I'll check it out)

**Comment by eroux** [comment]
yes, I realized that the problem is not really the definition but the compression (it's uncompressed on S3). I'm trying to find ways to mitigate that. I've asked AO (archive operations? jim and Travis) what should be done in that case, but a quick way to avoid the problem is to provide the iiif-presentation service with the S3 size information. In case it's too big, it could take the decision not to include it in the manifest, so that it doesn't degrade the user experience

**Comment by berger-n** [comment]
ok
