### ISSUE TITLE
add a "browse all works by ..." button at the top of the person records

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#551]
it's a very common use case so it should be highlighted in the record. I'll ask Tania to design it

**Comment by berger-n** [comment]
not sure about the button next to the title:

![Screenshot_20210907_181631](https://user-images.githubusercontent.com/33383857/132378027-75137dec-6598-4d1c-9988-18a32213ad83.png)

below title looks better to me: http://library-dev.bdrc.io/show/bdr:P1583

![Screenshot_20210907_184834](https://user-images.githubusercontent.com/33383857/132381952-19e0cb9f-d554-401b-83a8-dd8593337f57.png)

case of a woman: http://library-dev.bdrc.io/show/bdr:P9639

![Screenshot_20210907_184556](https://user-images.githubusercontent.com/33383857/132381617-25c47746-acce-48af-b1a3-61e75bd097fe.png)

**Comment by eroux** [comment]
Excellent, thanks! Perhaps we could reword it a little bit:
- the work icon on the left side of the button, in white
- text "browse associated works"

**Comment by berger-n** [comment]
ok good idea! done: http://library-dev.bdrc.io/show/bdr:P796

![Screenshot_20210908_104151](https://user-images.githubusercontent.com/33383857/132476587-d7db99ec-121b-44e4-91fa-bff8a85a0349.png)

**Comment by eroux** [comment]
great! almost perfect: can the icon be a bit smaller, and feel more centered between the left limit of the button and the left of the B?

**Comment by berger-n** [comment]
done, but as Tania said these svg are made for a specific width, here we can't go much below this size:  http://library-dev.bdrc.io/show/bdr:P783

![Screenshot_20210908_105653](https://user-images.githubusercontent.com/33383857/132479113-ed2a7edf-ddbe-419c-80da-519d1b32606b.png)

or it'll just get blurry:

![Screenshot_20210908_105735](https://user-images.githubusercontent.com/33383857/132479221-51d8e1ff-7268-482b-8636-ae3b894fd5d8.png)

**Comment by berger-n** [comment]
deployed: https://library.bdrc.io/show/bdr:P653

![Screenshot_20210908_114933](https://user-images.githubusercontent.com/33383857/132487608-fb913b5e-1f00-4370-8672-146fb24be19a.png)

**Comment by eroux** [comment]
perfect, thanks!
