### ISSUE TITLE
add genre taxonomy

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#552]
This will work just like the topic taxonomy, there will be different services involved in this issue (xmltold, the migration repo, lds-pdi, etc.), but I'll keep it as one issue here so that we can track everything down

**Comment by eroux** [comment]
genre taxonomy: https://www.tbrc.org/xmldoc?rid=O3JW5309

**Comment by eroux** [comment]
@berger-n this is now ready, see this query: https://ldspdi-dev.bdrc.io/lib/associatedWorks?R_RES=bdr%3AP252&format=json

basically the're now a new "genres" alongside the "topics" facets. It works in exactly the same way except it has `O3JW5309` as its root. Instead of having `Genre / Topic` in one title of the filters on the left, we should have `Genre` (open by default, unlike topics) and `Topic`.

**Comment by berger-n** [comment]
seems to be already working fine! http://library-dev.bdrc.io/search?r=bdr:P252&t=Work
(though not thoroughly tested yet)

![Screenshot_20210909_180928](https://user-images.githubusercontent.com/33383857/132722419-6afb9097-a7fb-4d35-b5c5-af95794897c8.png)
---

works with both topic and genre selected: http://library-dev.bdrc.io/search?r=bdr:P252&t=Work&pg=1&f=genres,inc,bdr:T140&f=tree,inc,bdr:T26

![Screenshot_20210909_180814](https://user-images.githubusercontent.com/33383857/132722209-4b04b17e-6299-446f-98c9-e9f944651aad.png)

**Comment by eroux** [comment]
Excellent, thanks!! @karmagongde @JannTibetan is that satisfactory?

**Comment by xristy** [comment]
I think it looks very good. I did notice that there are 5 be'ui bum (w/ 1 version each) and 1 Collected Works (w/ 5 versions).  Is this a case where version grouping is needed?

**Comment by karmagongde** [comment]
@eroux I cleared the caches and cookies of the web browser and Iooked for P252. The display of BUDA looks the same as before on my machine. Maybe I have to wait till tomorrow to see the changes.
![Screen Shot 2021-09-09 at 4 01 21 PM](https://user-images.githubusercontent.com/19337852/132755011-3618c2c3-62dc-4f8b-aaaa-abd732bcc714.png)

**Comment by eroux** [comment]
@karmagongde the trick is to go to the development website (`library-dev` instead of `library`), for instance http://library-dev.bdrc.io/search?r=bdr:P252&t=Work
