### ISSUE TITLE
indicating unaccessible images in etext viewer

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#553]
We have a few etexts from copyrighted material, for instance:

https://library.bdrc.io/show/bdr:UTIE0OPP000008_v001?startChar=525889&keyword=%22dag%20la%20ni%20dbyen%20gyi%20nyer%20bsdogs%20las%22~1@bo-x-ewts#open-viewer

in that case the images are copyrighted and will return a 401 / 403. It would be best if the etext viewer could handle these codes and display a little error message with an explanation

**Comment by berger-n** [comment]
now when you click on an image or the Show Images button,  here's what you see if current image is 401/403: http://library-dev.bdrc.io/show/bdr:UTIE0OPP000008_v001?startChar=525889&keyword=%22dag%20la%20ni%20dbyen%20gyi%20nyer%20bsdogs%20las%22~1@bo-x-ewts#open-viewer

![Screenshot_20210906_161434](https://user-images.githubusercontent.com/33383857/132230315-9818072d-e11b-4e55-a7c9-f91ed3fed81b.png)

message is not perfect I guess though, wdyt?

**Comment by eroux** [comment]
Looks perfect, thanks!
