### ISSUE TITLE
missing translations ?

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#554]
I wasn't able to find these two strings for translation in Chinese / Tibetan:

![image_2021_09_05T13_42_12_459Z](https://user-images.githubusercontent.com/60868/132129205-8b05a2d0-8947-4503-886f-466c2bcc7f90.png)

@berger-n do you know where they are?

cc @ngawangtrinley

**Comment by berger-n** [comment]
those are here, in `/buda-base/mirador`: https://github.com/buda-base/mirador/tree/2.7.0-bdrc/locales

**Comment by berger-n** [comment]
(note that they only are in the `2.7.0-bdrc` branch which need to be explicitly checked out first)
