### ISSUE TITLE
improve display of birth / death dates of persons

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#557]
There are 2 places where dates are displayed for persons: search results and main record (just below the name). The current display has all the information but it's not very convenient. Let's have a system that's a little more complex but better:

- when we only have birth date: dispaly "b. " then the birth date (or range, see below)
- when we only have death date, display "d. " then the death date
- when we only have floruit dates (no instance in the database for now), display "fl. " then floruit date

Now, when a date is a range (not before / not after), keep the current display unless the first ends with 00 and the second with 99, in that case display the century (ex: 12th century for 1100-1199). Let's also keep in mind that there are sometimes multiple centuries (ex: 700-899 --> 8th-9th century). I'll comment with the Tibetan and Chinese localizations, but they will be a little tricky (not just substitutions of the English). I can make the function that does the computation of the final string, but I'll need a little help to start it

**Comment by eroux** [comment]
in Tibetan:
- 12th century: དུས་རབས་༡༢
- 12-13th century: དུས་རབས་༡༢ ནས་ ༡༣ བར།

**Comment by berger-n** [comment]
found out some weird things in results sorted by year of birth: https://library.bdrc.io/search?q=%22lama%22&lg=en&t=Person&s=year%20of%20birth%20reverse

![Screenshot_20210916_182836](https://user-images.githubusercontent.com/33383857/133649988-53df14db-7624-4fd3-9235-3d08548dcb23.png)
---

some improvement here but more still to be done: http://library-dev.bdrc.io/search?q=%22lama%22&lg=en&t=Person&s=year%20of%20birth%20reverse

- [ ] not related but interesting typo in id here https://library.bdrc.io/show/bdr:p1019
- [ ] case of [bdr:P2AG27](bdr:P2AG27) suggests improving handling different birth dates from sources (+ a typo 2005 as both birth & death)
  why about making a range from available dates?

**Comment by eroux** [comment]
I've fixed P2AG27 on tbrc.org, it should be fixed on BUDA tomorrow. I'm not sure where you saw the typo in the ID of P1019 but it's correct in our data: http://purl.bdrc.io/resource/P1019.ttl . Maybe a reference from Wikidata or TOL?

**Comment by berger-n** [comment]
ok thanks! not sure what think about https://purl.bdrc.io/resource/p1019.ttl:

![Screenshot_20210917_112531](https://user-images.githubusercontent.com/33383857/133760875-ff728531-1f18-4d01-b43d-74e9438ef991.png)

but it's what causes this I think: http://library-dev.bdrc.io/search?q=%22wonpo%20lama%20rinchen%22&lg=en&t=Person

![Screenshot_20210917_113208](https://user-images.githubusercontent.com/33383857/133760969-d3095b85-045a-4857-a361-a47489336d27.png)

regarding discrepancy in birth date like in https://library.bdrc.io/show/bdr:P7430:

![Screenshot_20210917_103523](https://user-images.githubusercontent.com/33383857/133751922-040cf628-31eb-4acc-b850-688308eb4d3c.png)

in results instead of displaying this which is a bit confusing w.r.t previous/next element birth dates:

![Screenshot_20210917_103255](https://user-images.githubusercontent.com/33383857/133751712-ac164d07-0e52-4d8a-89f3-cd7e91d04bf2.png)

I guess something like 1905~1938 - 1964 could be better
or do we prefer to "filter" bogus date like 1938 using `notAfter`?

**Comment by eroux** [comment]
hmmm, good question... I think something like `1905~1938 - 1964` is best. I'll fix the tol import

**Comment by eroux** [comment]
the p1019 issue is fixed: http://library-dev.bdrc.io/search?q=%22wonpo%20lama%20rinchen%22&lg=en&t=Person&s=closest%20matches%20forced

**Comment by berger-n** [comment]
perfect! thanks

**Comment by berger-n** [comment]
search results look better now: http://library-dev.bdrc.io/search?q=%22lama%22&lg=en&t=Person&s=year%20of%20birth%20reverse

![Screenshot_20210917_155433](https://user-images.githubusercontent.com/33383857/133794370-3bf963e6-51f4-402a-9926-8f56649e549a.png)
---
a strange issue with data imported from TOL [in query](http://ldspdi-dev.bdrc.io/lib/personGraph?LG_NAME=en&L_NAME=%22Tsentrangwa%22) on https://library-dev.bdrc.io/search?q=%22Tsentrangwa%22&lg=en&t=Person though: 


![Screenshot_20210917_160043](https://user-images.githubusercontent.com/33383857/133795396-b8a749b0-b787-4155-8b14-8159c9dca8a0.png)


![Screenshot_20210917_155649](https://user-images.githubusercontent.com/33383857/133794731-27c11efd-36ce-4b33-8a13-4c9ffe1e8526.png)

(supposed to be 13th century on https://treasuryoflives.org/biographies/view/Lama-Tsentrangwa/13438)

\+ I'm investigating why the TOL result isn't merged with BDRC record here

**Comment by berger-n** [comment]
> \+ I'm investigating why the TOL result isn't merged with BDRC record here

data doesn't mention any BDRC record here: http://ldspdi-dev.bdrc.io/lib/personGraph?LG_NAME=en&L_NAME=%22Tsentrangwa%22

![Screenshot_20210917_160417](https://user-images.githubusercontent.com/33383857/133795902-82452cf9-925d-4cd3-b0a9-d93cf578a26f.png)

though the inverse is true: 

![Screenshot_20210917_160539](https://user-images.githubusercontent.com/33383857/133796128-389fe2bd-3c62-4d29-b07b-eb0747eb15d8.png)

do I try to update client code to handle it?

**Comment by eroux** [comment]
oops, that was an error in the fix I made for the lower case IDs, both ways of the owl:sameAs should be there now. As for the `13` date, I'll fix that in the import too... sigh... I hope their new data is ready soon

**Comment by eroux** [comment]
done

**Comment by eroux** [comment]
otherwise it's a good improvement, thanks!

**Comment by berger-n** [comment]
thanks for the data!
not far from good here about the localized dates/century in search results: http://library-dev.bdrc.io/search?q=%22lama%22&lg=en&t=Person&uilang=en&s=year%20of%20birth

![Screenshot_20210917_175028](https://user-images.githubusercontent.com/33383857/133817420-17860edf-2c50-402e-a79e-e2642fa0ce1d.png)
---

same in Tibetan:

![Screenshot_20210917_175052](https://user-images.githubusercontent.com/33383857/133817488-e2e5629c-af84-4465-b82a-a3f02da4ef93.png)

**Comment by eroux** [comment]
This is great!! I'll make a few little changes on the Tibetan but other than that this is excellent, thanks! Can you just add the `fl.` thing before we forget? (For the floruit event)

**Comment by eroux** [comment]
I fixed the Tibetan translations but I realize that on tbrc.org the display is as follows in search result with the UI in Tibetan:

![Capture d’écran de 2021-09-17 19-07-28](https://user-images.githubusercontent.com/60868/133827386-65332cd6-7e0d-43cc-b92c-617355b47eb4.png)

so it's all spelled out ("born in xxxx, died in yyyy") instead of being abbreviated ("xxxx-yyyy"). @JannTibetan do you think we should spell it out in full on BUDA too or is it ok to abbreviate it?

(cc @karmagongde @ngawangtrinley )

**Comment by ngawangtrinley** [comment]
("xxxx-yyyy") is good! I think most people will get it.   
  
When working on the localization I remember someone proposed ("ལོ་ཚིགས། xxxx-yyyyy") which is equivalent to ("dates: xxxx-yyyy"), I think this could work too.

**Comment by eroux** [comment]
thanks! we can give it a try if we get feedback of Tibetan users who are confused by the display

**Comment by JannTibetan** [comment]
How will it display when we only have one date (either birth date or death date)?

**Comment by eroux** [comment]
when we have one date:

- in English it will be "b. xxx" / "d. yyy" for birth / death
- in Tibetan "འཁྲུངས་དུས། xxx" / "འདས་དུས། yyy"

**Comment by karmagongde** [comment]
"in Tibetan "འཁྲུངས་ལོ། xxx" / "འདས་ལོ། yyy" would be a more precise term.

**Comment by eroux** [comment]
ah thanks! 

does it also apply when we indicate a century? In that case what we have now is "འཁྲུངས་དུས། དུས་རབས་xx"

**Comment by karmagongde** [comment]
"དུས་རབས།" or "བརྒྱ་ཕྲག" for a century.  But more people use "དུས་རབས།" term.
To make a century, it needs "དུས་རབས།".
"དུས་" is a time and འཁྲུངས་དུས་ the time of birth.
"ལོ"   is a year.
I am also fine with "འཁྲུངས་དུས།" it is broad that used​ ​at​ tbrc.org.
The displays on tbrc.org and bdrc.io are different.
See the screenshot below:
![Screen Shot 2021-09-20 at 11 44 47 AM](https://user-images.githubusercontent.com/19337852/134033794-d48245f4-1051-46bb-8b04-25e1821a7733.png)
![Screen Shot 2021-09-20 at 11 44 26 AM](https://user-images.githubusercontent.com/19337852/134033798-2987ba50-1646-455b-b3e3-53a6e3254927.png)

**Comment by eroux** [comment]
yes, we're working on the display of dates on BUDA (hence this issue), it will change soon. @berger-n can we make a special case for the translation of "b."  in Tibetan when it's years (and not century)?

**Comment by berger-n** [comment]
same display now used on records: http://library-dev.bdrc.io/show/bdr:P2KG229170

![Screenshot_20210923_093619](https://user-images.githubusercontent.com/33383857/134470222-530ead32-639b-415d-898d-c2cf4cafa817.png)

@eroux not sure what you mean, can you give an example?

**Comment by eroux** [comment]
great, thanks!

Here's an example:
- `b. 1956` in Tibetan: `འཁྲུངས་ལོ། ༡༩༥༦`
- `b. 20th c.` in Tibetan: `འཁྲུངས་དུས། དུས་རབས་༢༠`
(note the `ལོ` vs. `དུས`)

**Comment by berger-n** [comment]
done:
- http://library-dev.bdrc.io/show/bdr:P8LS75361

![Screenshot_20210923_103734](https://user-images.githubusercontent.com/33383857/134477525-1b8e7ffb-acad-4ff6-9e05-f6f8374f775a.png)
---

- http://library-dev.bdrc.io/show/bdr:P9569

![Screenshot_20210923_103808](https://user-images.githubusercontent.com/33383857/134477588-b85caf3d-2ebb-4ba7-8c24-8884de1d6afe.png)

**Comment by eroux** [comment]
thanks! @ngawangtrinley @karmagongde is that satisfactory? if so we can deploy on the production site. Also, perhaps this would be a good opportunity to translate "associated works"

**Comment by eroux** [comment]
@karmagongde we're deploying, if you see something off please tell us!
