### ISSUE TITLE
Adding phonetics when the data from other sources in non-standard or incomplete

### ISSUE THREAD

**Issue by JannTibetan** [buda-base/public-digital-library#558]
It seems to me that all of our phonetics for [Mipham](http://purl.bdrc.io/resource/P252) come from Treasury of Lives. This is a problem because ToL has an idiosyncratic phonetic system that in this case is different from the phonetics for mi pham in almost all English language publications. ToL uses Mipam and everyone else writes Mipham. Our users are going to search on the dominant spelling and not get the desired result. 
What should we do in cases like this? Update our own metadata? Thanks!

**Comment by eroux** [comment]
In that case there are two ways:
- manually we can add the English phonetic(s) we want in our record yes, that's the most straightforward path
- but more generally I should import more names from Wikidata, which in that case does have [Mipham](https://www.wikidata.org/wiki/Q613140). I currently only import the main name but I'll import the rest too (actually I thought this was already the case... I'll fix that tomorrow, it's a small change)

**Comment by JannTibetan** [comment]
Wonderful. Thanks!

**Comment by eroux** [comment]
done, the search on "Mipham" in English seems satisfying:

https://library.bdrc.io/search?q=%22mipham%22&lg=en&t=Person

**Comment by JannTibetan** [comment]
Thanks!

Did you import the "Mipham" names from Wikidata?

**Comment by eroux** [comment]
yes, I updates the Wikidata import script so that the "Mipham" names are imported too. That must also have imported a Chinese name for Mipham that's the most common in the PRC and that we didn't have in our data (麥彭仁波切 I think)... or at least that's the theory. Perhaps at some point this data can also reach the Chinese miror but... let's see!
