### ISSUE TITLE
image not loading in page view for CUDL manuscripts

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#559]
for instance https://library.bdrc.io/show/bdr:W0CDL0MS-OR-00728-00008 (only in page view, the volume view works)

from https://github.com/buda-base/library-issues/issues/386

**Comment by eroux** [comment]
(looks like the CORS issue with the token)

**Comment by berger-n** [comment]
fixed: https://library.bdrc.io/view/bdr:W0CDL0MS-OR-00728-00008

![Screenshot_20210914_161823](https://user-images.githubusercontent.com/33383857/133274780-e3498908-47e6-48e1-b36e-75190f0e680e.png)

(related to https://github.com/buda-base/public-digital-library/issues/506)

**Comment by eroux** [comment]
excellent, thanks!
