### ISSUE TITLE
mirador improvements

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#56]
in the collection view, the search bar should be removed

also, we should just remove the link to the page view in the list of volumes, that just looses everyone. clicking on the thumbnail image of the volume should lead to the reading view

make sure keyboard commands work
**Edit:** I think part of it is to `.focus()` the reading room, the focus seems to be on the background (the library page) that's invisible

**Comment by eroux** [comment]
we can also remove the UV and Diva buttons

**Comment by xristy** [comment]
Perhaps retain a discreet dropdown for the UV and Diva viewers on library-dev for testing purpose

**Comment by eroux** [comment]
Also, Mirador doesn't display the renderings in PDF and ZIP, for instance on the first volume of W22084, the [manifest](http://presentation.bdrc.io/2.1.1/v:bdr:V22084_I0888/manifest).

**Comment by eroux** [comment]
Another thing that's not urgent but that we should start thinking about now: when embedding our viewer, there should be an argument somewhere that our partners use that triggers the addition of an http header in all the requests to the iiif server and presentation. For instance if the viewer is embedded with `?origin=ACIP`, then each request should contain the http header:

```
X-iiif-origin: ACIP
```

**Comment by eroux** [comment]
Sorry for this seemingly never-ending litany of feature requests, but it would be nice to have a little documentation with a complete example of how to integrate the viewer on a website... A partner would like to do that this week

**Comment by eroux** [comment]
Aaaand finally, I think it would be reasonable, when integrating, to have a query argument or a configuration option to set up the language preferences. Currently I think `en` is preferred over `bo`, it's a good setup for some partners, but some would prefer `bo` over `en`. Maybe it could be given as a coma-separated list or something like that?

**Comment by eroux** [comment]
for keyboard navigation, maybe [this plugin](https://github.com/dbmdz/mirador-plugins) could be used

**Comment by berger-n** [comment]
+use language preference to display titles

**Comment by berger-n** [comment]
- [ ] resizable collection tree panel

**Comment by eroux** [comment]
- [ ] make the item records display images like the work record
- [ ] try to display the images for works restricted in China
- [ ] put the PDF icon  right of the thumbnail of the volumes

**Comment by eroux** [comment]
- [ ] In [this URI](http://library.bdrc.io/scripts/embed-iframe.html?work=bdr:W0CJ001&origin=jonangdharma.org&lang=bo-x-ewts) the labels should be displayed in ewts, most of them are except when you select a text and look on the right side of the outline view, which displays "Volume 1" whereas the manifest ([example](http://presentation.bdrc.io/2.1.1/v:bdr:V21208_I3492::3-4/manifest)) has a ewts label
