### ISSUE TITLE
put "unspecified" at the end for filters

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#560]
(for instance in genres and topics), even when they are the value with the most data

**Comment by berger-n** [comment]
done: https://library.bdrc.io/search?q=%22spyod%20%27jug%22~1&lg=bo-x-ewts&t=Instance&f=asset,inc,tmp:possibleAccess&f=asset,inc,tmp:catalogOnly

![Screenshot_20210914_164349](https://user-images.githubusercontent.com/33383857/133279402-1a502963-450c-4346-bd8f-766655855273.png)

**Comment by eroux** [comment]
perfect, thanks a lot!
