### ISSUE TITLE
sorting results according to context

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#563]
I think most users will expect results from matches in the titles of versions to come before results from matches only in non-title fields (notes, colophons, etc.). We should order them in that way (I think it's more or less the case on tbrc.org)

**Comment by berger-n** [comment]
should be ok like this: http://library-dev.bdrc.io/search?q=%22spyod%20%27jug%22~1&lg=bo-x-ewts&t=Instance&f=asset,inc,tmp:possibleAccess&f=asset,inc,tmp:catalogOnly

don't know what to think of this years of publication though: http://library-dev.bdrc.io/search?q=%22spyod%20%27jug%22~1&lg=bo-x-ewts&t=Instance&f=asset,inc,tmp:possibleAccess&f=asset,inc,tmp:catalogOnly&s=year%20of%20publication

![Screenshot_20210923_173037](https://user-images.githubusercontent.com/33383857/134537527-e18d9152-30c3-4eed-9d22-c4bd80dc917e.png)

**Comment by eroux** [comment]
excellent, thanks!! yes this data is weird... see https://github.com/buda-base/xmltoldmigration/issues/193

does it also work for person names ?

**Comment by berger-n** [comment]
no it doesn't work for person names / work titles yet (sort function is a bit different from others)

**Comment by berger-n** [comment]
done for sort by title / name as well: https://library-dev.bdrc.io/search?q=%22spyod%20%27jug%22~1&lg=bo-x-ewts&t=Instance&f=asset,inc,tmp:possibleAccess&f=asset,inc,tmp:catalogOnly&s=title

example for persons: http://library-dev.bdrc.io/search?q=%22dalai%20lama%22&lg=en&t=Person&s=person%20name

**Comment by eroux** [comment]
excellent, thanks!
