### ISSUE TITLE
performance issue in big collections

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#565]
I think it's kind of unavoidable with the way we fetch the data (all at once), but I'm wondering if there are some optimizations we might do to speed up the display of https://library.bdrc.io/search?r=bdr:PR1FPL01&t=Scan ? I think there were some good optimizations for the outline that we made recently so that made me a bit more optimistic about displaying big collections...

**Comment by berger-n** [comment]
interesting preliminary tests here
on a total time of 17.7s we have:
```
rewriteAuxMain: 9351
getDerivedState: 4767
loadResults: 1068
render: 703
loadDatatypes: 170 
```
let's dive into the first two

**Comment by eroux** [comment]
yes, if we can make it 14s shorter that will be enough :) thanks, let's look into this, I'm sure there's a lot we can do

**Comment by berger-n** [comment]
> if we can make it 14s shorter that will be enough

so be it :smile:
total time 4.2s:
```
rewriteAuxMain: 243
getDerivedState: 58
```

can't believe it myself that `.reduce` was such a waste of time in this use case!
see for yourself: https://library-dev.bdrc.io/search?r=bdr:PR1FPL01&t=Scan&s=title

**Comment by eroux** [comment]
wow, that's such a huge improvement, thanks a lot! many people will notice
