### ISSUE TITLE
missing sanskrit labels

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#566]
on https://library.bdrc.io/search?q=%22Mah%C4%81bh%C4%81rata%22&lg=inc-x-ndia&t=Work&s=closest%20matches%20forced

**Comment by berger-n** [comment]
no labels in query indeed: https://purl.bdrc.io/lib/workFacetGraph?LG_NAME=inc-x-ndia&L_NAME=%22Mah%C4%81bh%C4%81rata%22

**Comment by eroux** [comment]
right, should be better tomorrow
