### ISSUE TITLE
version IDs not recognized in the search bar

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#567]
`MW1KG8584` is not recognized as a resource id in the search bar while `mw1KG8584` is (it has the "find resource with this id" first)

**Comment by berger-n** [comment]
fixed: http://library-dev.bdrc.io/

![Screenshot_20210929_121737](https://user-images.githubusercontent.com/33383857/135250223-22856f90-5e68-4d70-aa29-a0020df67e2b.png)

**Comment by eroux** [comment]
perfect, thanks! maybe we can deploy?

**Comment by berger-n** [comment]
> maybe we can deploy?

depends on https://github.com/buda-base/public-digital-library/issues/557
can we?

**Comment by eroux** [comment]
ok yes, let's!

**Comment by berger-n** [comment]
done: https://library.bdrc.io/
