### ISSUE TITLE
start loading spinner at the beginning of the network requests

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#569]
For instance on https://library.bdrc.io/search?r=bdr:PR1FPL01&t=Scan my understanding is that:
- at the beginning of the (pretty long) network request, the interface freezes on a gray empty space
- when the network request finishes, the spinner is displayed while the UI is computed
- once the UI is computed it is displayed

it would be best if the spinner could start at the beginning of the network request instead

**Comment by berger-n** [comment]
seems better now: http://library-dev.bdrc.io/search?r=bdr:PR1FPL01&t=Scan&s=title

![Kazam_screencast_00052 mkv](https://user-images.githubusercontent.com/33383857/135250020-1c79ff57-677b-4351-a5f4-89a9f41ba474.gif)

**Comment by eroux** [comment]
yes, perfect, thanks!
