### ISSUE TITLE
ZJU server uses iiifpres with the app

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#574]
[this line](https://github.com/buda-base/public-digital-library/blob/5185be1d679eba752ed71a7e6a6a0573a2b7ba87/src/lib/miradorSetup.js#L4) hardcodes the url of iiifpres, but the URL is different in China and in the US... there should be no url at all hardcoded in the data, they should all come from the configuration

**Comment by berger-n** [comment]
to me it's only a default/initialisation value that is replaced later on by value from config file, see: https://github.com/buda-base/public-digital-library/blob/5185be1d679eba752ed71a7e6a6a0573a2b7ba87/src/lib/miradorSetup.js#L1110-L1117

**Comment by eroux** [comment]
hmmm ok... let's find the source of http://buda.zju.edu.cn/scripts/embed-iframe.html?work=bdr:W22084&lang=en&origin=BDRCLibApp1.2.0 calling presentation.bdrc.io then

**Comment by eroux** [comment]
oddly enough it calls presentation.bdrc.io instead of iiifpres.bdrc.io...

**Comment by berger-n** [comment]
ok let's check that

**Comment by berger-n** [comment]
something goes wrong so it loads http://buda.zju.edu.cn/tibcolldemo2.json instead (where the presentation.bdrc.io comes from)

**Comment by berger-n** [comment]
found the problem but know what it comes from...
here just after `iiifpres` url initialization: https://github.com/buda-base/public-digital-library/blob/5185be1d679eba752ed71a7e6a6a0573a2b7ba87/src/lib/miradorSetup.js#L1124-L1133
interestingly enough, with exact same data received chinese server seems to fail to enter the second else:

![Screenshot_20211006_143133](https://user-images.githubusercontent.com/33383857/136202494-c89b3b71-87fb-4dd1-b35c-527166409860.png)

while at https://library.bdrc.io/scripts/embed-iframe.html?work=bdr:W12827&lang=en&origin=BDRCLibApp1.2.0:

![Screenshot_20211006_143407](https://user-images.githubusercontent.com/33383857/136202982-9af2ad8d-ac21-4210-b694-7d01a4041936.png)

does it make sense to you?
I'll add more debug output

**Comment by berger-n** [comment]
deployed here: http://library-dev.bdrc.io/scripts/embed-iframe.html?work=bdr:W12827&lang=en&origin=BDRCLibApp1.2.0

![Screenshot_20211006_145032](https://user-images.githubusercontent.com/33383857/136205567-ed1a49f4-d965-4196-8f32-f445a1d93aad.png)

**Comment by eroux** [comment]
fixed (was mostly a data / config issue)
