### ISSUE TITLE
download function on the resource pages doesn't work

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#575]
it might be because of https://github.com/buda-base/xmltoldmigration/commit/bb5608bdf2df00e616884a2c02b64fd253457aa8 but I can't see why... example from @TBRC-pmench : https://library.bdrc.io/show/bdr:W1NLM1952

**Comment by eroux** [comment]
hmm no, the cache seems clean:

![Capture d’écran de 2021-10-08 12-10-38](https://user-images.githubusercontent.com/60868/136539006-ec421c3d-d647-4a40-bf99-0690bed09f14.png)

no message in the console... I'll try to investigate

**Comment by berger-n** [comment]
now the bug has disappeared! weird... investigating

**Comment by berger-n** [comment]
deployed then found out how to reproduce (not Firefox related) using another work, at east when first clicking "Get PDF"  and before pdf is actually generated on server: https://library.bdrc.io/show/bdr:W1NLM1954
should be possible to fix now, having a look

**Comment by berger-n** [comment]
seems to be ok now, you can try this one: https://library.bdrc.io/show/bdr:W1NLM1975

![Screenshot_20211008_153352](https://user-images.githubusercontent.com/33383857/136566433-235c0080-1f37-4bda-94f5-62097085034e.png)

**Comment by eroux** [comment]
excellent, thanks!
