### ISSUE TITLE
login change for proxied instances of the website

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#577]
Many subscriber institutions are using [EZproxy](https://help.oclc.org/Library_Management/EZproxy/Get_started/About_EZproxy?sl=en) to access the website so that their users don't need to register / login in order to access the PDFs the institution subscribed to.

For instance in NW university, students are using https://library-bdrc-io.turing.library.northwestern.edu/ (the link won't work outside of the University). This has a side effect with the auth though: because the redirect URL is not on library.bdrc.io, auth0 won't allow users to log in on this website.

This is fine since the description of EZproxy linked above indicates that login on proxied instanes is not necessary. I propose that when the website detects that it's not on the usual domain (from the config?), the login and register buttons should be grayed out, with a message on hover saying something like "This is a proxied version, login is disabled. If you are part of a subscribing institution, you can download PDFs of texts in the subscribed collections." (@TBRC-pmench if you think this should be reworded don't hesitate)

**Comment by TBRC-pmench** [comment]
Small change:

>This is a proxied version provided by your institution's library subscription; login is disabled. If you are part of a subscribing institution, you can download PDFs of texts in the subscribed collections.

**Comment by eroux** [comment]
great, thanks! Looking at it I think there could be some little improvements: what about ending the message with "If you have an account and wish to use it, please go to https://library.bdrc.io" (with a link)?

**Comment by berger-n** [comment]
done: http://library-dev.bdrc.io/

![Screenshot_20211013_151613](https://user-images.githubusercontent.com/33383857/137140044-f35c0175-3a93-4bb7-a2cc-9f113b4c64c7.png)
