### ISSUE TITLE
ontology download URL

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#579]
it would be good to have a config for the ontology url in the config, so that the Chinese server can use a specific one

**Comment by berger-n** [comment]
fixed as of https://github.com/buda-base/public-digital-library/commit/538fc1e60118afda319ef0a4bf753bc3d1b5a194: http://buda.zju.edu.cn/

![Screenshot_20211018_112153](https://user-images.githubusercontent.com/33383857/137704308-caaeca3d-2c6b-4c02-bfad-04b4e45c9501.png)
---

see also: https://github.com/buda-base/public-digital-library/blob/cd5a07f01b65bffec70634a6e2944e4ed1bf8e7d/src/lib/api.js#L1175-L1178

is that ok or do we need something else?
