### ISSUE TITLE
Additional metadata field for Waddell Collection

### ISSUE THREAD

**Issue by JannTibetan** [buda-base/public-digital-library#583]
It seems like we're not displaying the "Alternativer Titel" field on Waddell Collection texts. What should we do when a field like this contains useful information in a non-English European language? Examples are the Alternativer Titels of Waddell 142 and Waddell 161. They are almanacs (lo tho) and the SBB metadata gives their dates. One example:
<img width="818" alt="Screen Shot 2021-10-18 at 9 45 59 PM" src="https://user-images.githubusercontent.com/44705185/137831126-c8667c51-a242-4e07-a112-750c04a107f9.png">

Can this field be left in German but converted to a notes or comment field on BUDA? Without this it could take a scholar hours and hours to figure out the years of these almanacs. This is probably the case for all of the nameless Waddell texts as well. 

On a related note it seems that the descriptive Titel and Alternativer Titel data for many Waddell texts is being translated into English and placed in the comment field. Is that being done by us? For ex.

<img width="818" alt="Screen Shot 2021-10-18 at 9 55 26 PM" src="https://user-images.githubusercontent.com/44705185/137831470-a65cd143-76d9-4fe5-b6e9-a7c3c439738c.png">

**Comment by eroux** [comment]
ah yes, that was a small glitch in the import, just fixed it. I think I did the translations myself, I started out of curiosity about the content I think... I can remove them if you want
