### ISSUE TITLE
add properties / class links

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#6]
It would be good if when in the UI, it was possible to click either on the properties themselves or on a (very discreet) icon next to them, and open the link to the property in another tab. For instance when on

http://library.bdrc.io/show/bdr:P6161

we could click on `Gender:` and get to http://purl.bdrc.io/ontology/core/personGender

**Comment by berger-n** [comment]
(in progress)

two points:
- http://purl.bdrc.io/ontology/core/sameAs (eg in http://purl.bdrc.io/resource/P6161.ttl) does not seem to exist: http://purl.bdrc.io/ontology/
- what dto do with "external" properties such as https://www.w3.org/2000/01/rdf-schema#seeAlso ? we need a more user-friendly page for non-BDRC ontology properties, eg https://www.infowebml.ws/rdf-owl/seeAlso.htm

**Comment by eroux** [comment]
The first seems to be a mistake, for the second I think we can just take the normal url for now
