### ISSUE TITLE
use disclosure view on long lists

### ISSUE THREAD

**Issue by xristy** [buda-base/public-digital-library#60]
When there are long lists of items such as **Has Part** of a Work or lists of teacher or lists of students  for Persons and so on these can be displayed with disclosure view in the initially closed state. This will make it easier to see the entire picture of a resource without lots of scrolling.

**Comment by eroux** [comment]
I think it would be better to show a few entries and then `...` that can be expanded, in the current state the property is almost invisible and it almost looks like a bug

**Comment by xristy** [comment]
thx
