### ISSUE TITLE
Works in other language shouldn't appear in Tibetan.

### ISSUE THREAD

**Issue by tadhondup** [buda-base/public-digital-library#602]
Can we use the language of the work for the default title? Right now we have multiple works of the same text with the same title in Tibetan [like here.](https://library.bdrc.io/search?q=%22%E0%BD%96%E0%BE%B1%E0%BD%84%E0%BC%8B%E0%BD%86%E0%BD%B4%E0%BD%96%E0%BC%8B%E0%BD%A6%E0%BD%BA%E0%BD%98%E0%BD%A6%E0%BC%8B%E0%BD%91%E0%BD%94%E0%BD%A0%E0%BD%B2%E0%BC%8B%E0%BD%A6%E0%BE%A4%E0%BE%B1%E0%BD%BC%E0%BD%91%E0%BC%8B%E0%BD%94%E0%BC%8B%E0%BD%A3%E0%BC%8B%E0%BD%A0%E0%BD%87%E0%BD%B4%E0%BD%82%E0%BC%8B%E0%BD%94%22~1&lg=bo&t=Work&s=closest%20matches)

For example [this Work](https://library.bdrc.io/show/bdr:WA1EE17?tabs=bdr:MW1EE17,bdr:W1EE17) is actually in mongolian but appear in Tibetan.
Another option would be to merge all instances of the same work together regardless of the language. What can be done to improve that?

**Comment by eroux** [comment]
(well, actually the initial place was the right place, moving it again ;) )
