### ISSUE TITLE
wrong link for associated works

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#605]
- go to https://library.bdrc.io/show/bdr:P2075
- go to the tab "created by ..."
- click on "see more"
- arrive on https://library.bdrc.io/search?r=bdr:P2075&t=Work&f=relation,inc,bdo:creator which is invalid because there's no bdo:creator facet

it should go to https://library.bdrc.io/search?r=bdr:P2075&t=Work&pg=1&f=relation,exc,bdo:workIsAbout instead

**Comment by berger-n** [comment]
right, thanks for noticing!
fixed: https://library.bdrc.io/show/bdr:P2075

**Comment by eroux** [comment]
excellent, thanks!
