### ISSUE TITLE
link to IA in the case of parts in outlines

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#609]
on https://library.bdrc.io/show/bdr:MW30465_4152EB the link to Internet archives is an invalid https://archive.org/details/bdrc-MW30465_4152EB , it should be https://archive.org/details/bdrc-W30465 (based on the local name of the root instance minus the `M`)

**Comment by eroux** [comment]
@berger-n could you take a look?

**Comment by berger-n** [comment]
fixed: https://library.bdrc.io/show/bdr:MW30465_4152EB

![image](https://user-images.githubusercontent.com/33383857/151371851-2650e333-87f0-4e83-8451-683bfc23ac28.png)

**Comment by eroux** [comment]
thanks!
