### ISSUE TITLE
TOC displayed instead of text

### ISSUE THREAD

**Issue by ngawangtrinley** [buda-base/public-digital-library#612]
Not sure if it's a data issue or a website issue, so I post it here. The following title should point to a text (page 423-446), not this one page in the table of contents:  
  
[https://library.bdrc.io/show/bdr:MW1KG17605_6E55AC](https://library.bdrc.io/show/bdr:MW1KG17605_6E55AC)  
 

![](https://user-images.githubusercontent.com/17675331/142598391-a70cedf7-d91c-48ca-a329-aeadbbb32c9e.png)

**Comment by berger-n** [comment]
is this the right link, where "page 423-446" come from? 
seems ok with data for this record: https://library.bdrc.io/show/bdr:MW1KG17605_6E55AC

![Screenshot_20211119_103735](https://user-images.githubusercontent.com/33383857/142600454-296e17d1-77d8-4199-9128-0a64a1cc4ae5.png)
---

same in the outline: https://library.bdrc.io/show/bdr:MW1KG17605?part=bdr:MW1KG17605_6E55AC


![Screenshot_20211119_103917](https://user-images.githubusercontent.com/33383857/142600724-e38d0cd6-a49d-46f1-acc6-6ea3d6531485.png)

**Comment by berger-n** [comment]
(ok I get it sorry, morning here :smile: )

@eroux not sure where it comes from but surprising indeed, same unique page for different versions of works?

![Screenshot_20211119_104255](https://user-images.githubusercontent.com/33383857/142601247-624fd918-90f0-4eb4-9882-6bf33e389d7c.png)

**Comment by eroux** [comment]
it's an issue in the data (one way to quickly test that is to look at tbrc.org, which has the same issue in that case) @ngawangtrinley  feel free to open an issue on https://github.com/buda-base/library-issues/issues/ about that
