### ISSUE TITLE
Can't find strings to translate

### ISSUE THREAD

**Issue by ngawangtrinley** [buda-base/public-digital-library#613]
Can't find the following strings [seen here](https://library.bdrc.io/show/bdr:MW3CN3408?tabs=bdr:IE0OPP001829&uilang=bo), in the [translation json](https://github.com/buda-base/public-digital-library/blob/master/src/translations/en.json). Do they live somewhere else?

*   [x] Alt Label
*   [x] Work Extent Statement
*   [ ] Content Method

**Comment by eroux** [comment]
hmm these are actually bugs... the translation for `skos:altLabel` is in https://github.com/buda-base/owl-schema/blob/master/translations/third_party_labels.ttl but it doesn't get into https://purl.bdrc.io/ontology/data/json ... I'll fix that. The other two are deprecated properties that haven't been mapped correctly, I'll fix that in a separate issue in xmltold

**Comment by eroux** [comment]
https://github.com/buda-base/xmltoldmigration/issues/205

**Comment by eroux** [comment]
first issue fixed by https://github.com/buda-base/owl-schema/commit/99481aa24d0a482b642e9ee3fdd1593fb1b0d085

**Comment by eroux** [comment]
second one in https://github.com/buda-base/xmltoldmigration/commit/2633867ffe263495ad7d0f30ce83c5589cdce659

I'm going to need a translation for the third one NT, it's something that can have the following values: computer input, OCR, typeset, facsimile

**Comment by ngawangtrinley** [comment]
ཡི་གེ་གཏག་ཐབས།
