### ISSUE TITLE
language in tooltips

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#614]
when there are tooltips on properties, the languages are a bit off, see for instance on https://library.bdrc.io/show/bdr:MW3CN3408?tabs=bdr:IE0OPP001829&uilang=bo

![Capture d’écran de 2021-11-19 11-18-05](https://user-images.githubusercontent.com/60868/142606894-30f616fb-1ad3-4d78-8686-562e2d39e440.png)

which should:
- have the Tibetan in Unicode instead of ewts
- should not have the English (it should only when Tibetan is not available)

**Comment by eroux** [comment]
also below on the same page, "modern" should be in Tibetan, the label is available:

![Capture d’écran de 2021-11-19 11-23-17](https://user-images.githubusercontent.com/60868/142607247-08235bec-25f7-434e-a0c8-d1c1e3425813.png)

**Comment by berger-n** [comment]
fixed: https://library.bdrc.io/show/bdr:MW3CN3408?tabs=bdr:IE0OPP001829&uilang=bo

![Screenshot_20211119_124814](https://user-images.githubusercontent.com/33383857/142617930-b6b9fe2d-6c37-43f5-ab46-f21f75463840.png)

---

regarding `printMethod` specifically, I can't see any other label in ontology:

![Screenshot_20211119_124936](https://user-images.githubusercontent.com/33383857/142618319-b9a37532-f258-4dae-b3e7-d6cd80c1117d.png)

which seems consistent with what would be displayed if there were, see Script property example:

![Screenshot_20211119_125047](https://user-images.githubusercontent.com/33383857/142618430-a12a09da-7127-4b31-8df0-2788b5716c55.png)

![Screenshot_20211119_125428](https://user-images.githubusercontent.com/33383857/142618869-1d044d9e-25ca-42a9-af0a-5ef668086543.png)

**Comment by eroux** [comment]
Thanks for the tooltips! oh you're right, the translation for "modern print method" is not there... @ngawangtrinley what do you think it should be?

**Comment by ngawangtrinley** [comment]
ལྕགས་པར་གཏབ་ཚུལ།
