### ISSUE TITLE
strange display

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#618]
in https://library.bdrc.io/search?q=%22rhinoceros%22&lg=en&t=Place&s=closest%20matches%20forced&pg=1&f=context,inc,tmp:nameContext I'm getting (logged in with an admin account)

![Capture d’écran de 2021-11-23 22-24-34](https://user-images.githubusercontent.com/60868/143131575-9a7dc4d9-1fbe-467c-9575-402b0b38abfe.png)

**Comment by berger-n** [comment]
(thought it was something else, so I had a look)
seems better now anyway : https://library.bdrc.io/search?q=%22rhinoceros%22&lg=en&t=Place&s=closest%20matches%20forced&pg=1&f=context,inc,tmp:nameContext&f=nonReleased,inc,tmp:show

![Uploading Screenshot_20211124_103715.png…]()

**Comment by eroux** [comment]
excellent, thanks!
