### ISSUE TITLE
improvements to worksInInstance

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#619]
In http://library-dev.bdrc.io/search?i=bdr:WA1FEMC010070&t=Work&w=t%3DWork%26r%3Dbdr%3APR1KDPP00%26n%3D1 we should have:
- the ID displayed like a regular property (for instance something like **Femc Manuscript Code:** XXX)
- the "isComplete" property displayed in the results when it's false: **Incomplete**
- the "isComplete" property in the filters on the left (as a separate "completion" filter category)

**Comment by eroux** [comment]
oh, and also:
- displaying the `hasFascicles` property in the results (and maybe a filter too?)
- material should be in the filters on the left
- when it's > 1, display `tmp:nbImageReproductions X` as **X scans** (this might change but I think it will be a good start)

maybe the scans could also be displayed (when there are multiple ones) like the instances in the work search (through a separate request I think)... but that will be for another issue

**Comment by berger-n** [comment]
done: http://library-dev.bdrc.io/search?i=bdr:WA1FEMC010070&t=Work&w=t%3DWork%26r%3Dbdr%3APR1KDPP00%26n%3D1

![Screenshot_20211124_164436](https://user-images.githubusercontent.com/33383857/143269916-0573c979-77ba-4c91-b4d5-d91299c087d6.png)

---

- note that currently on http://library-dev.bdrc.io/show/bdr:WA1FEMC010070 the link to related versions at the bottom of page leads to another results page using another query, having with half as many results as given on Work page BTW: http://library-dev.bdrc.io/search?r=bdr:WA1FEMC010070&t=Instance&s=title%20forced
 wdyt? 
 should there always be a distinct, dedicated link in Has Version property? limit to display it is currently 20

- about fascicles in side menu here: http://library-dev.bdrc.io/search?i=bdr:WA1FEMC040001&t=Work
 not sure how it's supposed to be sorted (nor why it is so for now) but I guess something needs to be done:

 ![Screenshot_20211124_171737](https://user-images.githubusercontent.com/33383857/143275525-77e40da5-fba1-4997-890c-d4144a544e66.png)

**Comment by eroux** [comment]
thanks a lot, I think this is really good!
- the fascicle filter is indeed not very useful in its current form, let's remove it
- yes the link from work to associated versions at the bottom is a bit unfortunate... perhaps we can remove it? the count is twice the real count because we count the image versions too
- I think if there are more than 2 versions we can add the button (in many cases people will want to filter by completeness), I think the limit of 20 is good. Ideally there would be some sorting so that the ones that appear correspond to some criteria, but that can be to another day

**Comment by berger-n** [comment]
removed fascicle filter, hidden instances from related resources on work page and made link to versions of work visible if there are more than 2 of them: http://library-dev.bdrc.io/show/bdr:WA1FEMC010070

![Screenshot_20211125_113110](https://user-images.githubusercontent.com/33383857/143425220-cec058f6-504d-40ef-a571-7fa1581180bc.png)

**Comment by eroux** [comment]
Thanks a lot! a few small things:
- http://library-dev.bdrc.io/show/bdr:MW1FEMC022267?s=i%3Dbdr%3AWA1FEMC010070%26t%3DWork%26n%3D2 has "browse all 4" on titles, which looks like a bug
- the empty "related resources" thing is taking all the room, we should either make it much smaller or replace the big "all" tab (with the empty space below) with just one line "no associated resources found"

**Comment by berger-n** [comment]
fixed bogus link and reduced empty related resources block: http://library-dev.bdrc.io/show/bdr:WA1FEMC010070

![Screenshot_20211125_141834](https://user-images.githubusercontent.com/33383857/143448603-9a47a69c-129c-48d6-adcd-73a8a6d3b5fa.png)
---

now a few more things to fix:
- [ ] related resources needs to be fixed when opening a work after related search results using back button:

![Screenshot_20211125_142309](https://user-images.githubusercontent.com/33383857/143449218-eb66f8d8-5461-4484-b73a-0ca9716e2cf3.png)


- [ ] top link missing something when opening version from work related results: http://library-dev.bdrc.io/show/bdr:MW1FEMC022267?s=i%3Dbdr%3AWA1FEMC010070%26t%3DWork%26n%3D2
 
![Screenshot_20211125_142551](https://user-images.githubusercontent.com/33383857/143449602-e5e89a62-8384-4d6a-977a-4b5941592a9f.png)

**Comment by eroux** [comment]
excellent, thanks!

**Comment by berger-n** [comment]
done, everything's fine now: http://library-dev.bdrc.io/show/bdr:MW1FEMC022267?s=i%3Dbdr%3AWA1FEMC010070%26t%3DWork%26n%3D2

![Screenshot_20211125_192121](https://user-images.githubusercontent.com/33383857/143487543-60d6383d-ccb8-4a04-af4c-c0b34fe27919.png)

**Comment by eroux** [comment]
perfect, thanks!
