### ISSUE TITLE
showing reproductions in work instances

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#621]
(this should actually work everywhere, even in instance search, or in the preview of instances in the work search, but if possible, let's first test it in this query only)

in http://library-dev.bdrc.io/search?i=bdr:WA1FEMC010070&t=Work we have one instance with mutiple scans. For this case it would be best to have something similar than what we have for works:

![Capture d’écran de 2021-11-26 13-41-51](https://user-images.githubusercontent.com/60868/143582783-5f067ffa-b9d2-42da-9b94-fea6e7cb2320.png)

except more simple (everything would always be inline like preview is now, no preview / browse all) the displayed property wouldn't be many, mostly the thumbnail and some buttons to open the viewer or record

**Comment by eroux** [comment]
almost forgot, the associated query is http://purl.bdrc.io/lib/instanceReproductionsGraph?R_RES=bdr:MW1FEMC040198

**Comment by eroux** [comment]
oh, when there's only one reproduction, no need to display this, let's limit it to cases with at least 2

**Comment by berger-n** [comment]
done: http://library-dev.bdrc.io/search?i=bdr:WA1FEMC010070&t=Work&pg=1&f=printMethod,inc,bdr:PrintMethod_Manuscript&pg=1&n=5

![Screenshot_20211126_172234](https://user-images.githubusercontent.com/33383857/143609032-53a9044a-8602-4b6f-afc3-12a5fb5ba29e.png)

---

note that by default it's already in use in work query as well: http://library-dev.bdrc.io/search?t=Work&r=bdr:PR1KDPP00&n=24


![Screenshot_20211126_172319](https://user-images.githubusercontent.com/33383857/143609137-a3a91af8-33a3-46c3-bcd3-bda12bdb27f4.png)

**Comment by eroux** [comment]
excellent, thanks!!

a little change: it would be best to hide it by default and have a button "show 2 reproductions". It's my fault though, I realize my choices of words were a bit unfortunate, sorry.

Other than that this is great!!

**Comment by berger-n** [comment]
ok thanks! no problem, added back the toggle button: http://library-dev.bdrc.io/search?i=bdr:WA1FEMC010070&t=Work&pg=1&f=printMethod,inc,bdr:PrintMethod_Manuscript&pg=1&n=5

![Kazam_screencast_00057 mp4](https://user-images.githubusercontent.com/33383857/143614295-a227510b-888a-4adf-813f-0c3092fd77ec.gif)

**Comment by eroux** [comment]
yes, this is perfect! thanks a lot!
