### ISSUE TITLE
configure order of proposed languages in the search bar for latin strings

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#623]
when typing `trai lok` in the search bar of the Khmer website (and the Khmer website only), the default should be `Pali / Burmese / Khmer (transliterated)`, not `Tibetan (Wylie)`

**Comment by eroux** [comment]
oh I think it's best this way yes, thanks!

**Comment by berger-n** [comment]
ok! done: http://library-dev.bdrc.io/

![Screenshot_20211201_153635](https://user-images.githubusercontent.com/33383857/144253802-83ebce46-dd53-4365-ad83-2c36a9a3ce68.png)

**Comment by eroux** [comment]
perfect, thanks!
