### ISSUE TITLE
more flexible preview/browse limit in work results

### ISSUE THREAD

**Issue by berger-n** [buda-base/public-digital-library#625]
> I wonder what would be an acceptable cut-off point for previewing all from a user perspective (and the webpage)? For myself, 5 or 6 seems too few. What about 10? But it's always going to be tricky to set an exact number... what if it is set at 10 and there are only 11 or 12? Is it possible to have some flexibility so that you might get up to 12, say, but if there are more than 12 only 8 are available in preview? OR maybe just keep the preview very small? I don't have an answer, but I do think the issue is valid. I'm seeing too many with 'browse all 4 or preview 3' which looks unreasonable. I guess that what is used at present is based on an assessment of the frequency of the versions?

**Comment by eroux** [comment]
thanks! the algorithm would be:

```
maxpreviews=10
normalpreviews=6

if (nbinstances < maxpreviews):
    showeverythinginline()
else:
    showninstances(n = normalpreviews)
```

**Comment by berger-n** [comment]
done: http://library-dev.bdrc.io/search?t=Work&r=bdr:PR1KDPP00&&s=title%20forced&pg=1&n=33

![Screenshot_20211129_185035](https://user-images.githubusercontent.com/33383857/143918016-31983ccd-b4e1-42a3-a37a-fef660b0d91d.png)

**Comment by eroux** [comment]
perfect thanks!
