### ISSUE TITLE
map not displayed in search results

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#627]
for instance in  https://library.bdrc.io/search?q=%22sa%20skya%22~1&lg=bo-x-ewts&t=Place (quite urgent)

**Comment by berger-n** [comment]
fixed: https://library.bdrc.io/search?q=%22sa%20skya%22~1&lg=bo-x-ewts&t=Place

![Screenshot_20211129_153744](https://user-images.githubusercontent.com/33383857/143887265-a5958b2a-eccd-4a8a-b671-68c0f1343920.png)

**Comment by eroux** [comment]
thanks!
