### ISSUE TITLE
missing titles in query

### ISSUE THREAD

**Issue by berger-n** [buda-base/public-digital-library#628]
see http://library-dev.bdrc.io/search?q=%22dhamma%22&lg=pi-x-ndia&t=Work

[query](http://purl.bdrc.io/lib/workFacetGraph?LG_NAME=pi-x-ndia&L_NAME=%22dhamma%22) doesn't return titles though Works seem to have one ([example](http://library-dev.bdrc.io/show/bdr:WA1FPL10688))

**Comment by eroux** [comment]
ok, I think it's good now! Two things though:
- in the language of each result (above the title), Burmese is not well handled (it's an empty square)
- when searching on the Khmer website, the facet collection = FEMC should be checked by default (users can uncheck it, it's fine). This should be configurable

**Comment by berger-n** [comment]
perfect, thanks! 
fixed the burmese language tag: http://library-dev.bdrc.io/search?q=%22dhamma%22&lg=pi-x-ndia&t=Work

![Screenshot_20211130_174925](https://user-images.githubusercontent.com/33383857/144090977-f5f58c9e-983b-4097-8bb9-5308dbdb5349.png)
---

regarding the collection facet, I'm not sure how to handle it, doesn't [query](http://purl.bdrc.io/lib/workFacetGraph?LG_NAME=pi-x-ndia&L_NAME=%22dhamma%22) need more information like `inCollection` property?

**Comment by eroux** [comment]
Thanks!

hmmm, right... good point... let me think about that...
