### ISSUE TITLE
duplicate info in results

### ISSUE THREAD

**Issue by berger-n** [buda-base/public-digital-library#629]
see http://library-dev.bdrc.io/search?q=%22test%22&lg=en&t=Work

![Screenshot_20211130_142038](https://user-images.githubusercontent.com/33383857/144054809-6d63efb0-3cf6-4fb4-ba24-2b3b3fc7bf10.png)
---

some matching fields seem to be returned twice: http://purl.bdrc.io/lib/workFacetGraph?LG_NAME=en&L_NAME=%22test%22

![Screenshot_20211130_142241](https://user-images.githubusercontent.com/33383857/144055102-9e539048-6941-4987-8ed8-d11e3e52cea8.png)

**Comment by eroux** [comment]
fixed, thanks for reporting!
