### ISSUE TITLE
Display preferences option for EWTS/Devanagari needs a change

### ISSUE THREAD

**Issue by xristy** [buda-base/public-digital-library#63]
The display preference for this data language priority should be:

```
Tibetan(EWTS)/Sanskrit(IAST)
```
as this will conform to the common scholar choices (even better would perhaps be Hackett's Scholars' Tibetan Transliteration)

**Comment by eroux** [comment]
I think there should be an option to position the English too, proably first... I think most people are interested in the English labels for topics for instance

**Comment by xristy** [comment]
thx
