### ISSUE TITLE
matches not converted to Unicode in some cases

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#630]
in https://library.bdrc.io/show/bdr:MW2DB4571?osearch=%22%E0%BD%93%E0%BD%BC%E0%BD%A2%E0%BC%8B%E0%BD%96%E0%BD%B4%E0%BC%8B%E0%BD%95%E0%BE%B2%E0%BD%BA%E0%BD%84%E0%BC%8B%E0%BD%96%22~1@bo when the UI is set in Unicode, the colophon match is not transliterated:

<img width="1356" alt="Screen Shot 2021-11-30 at 2 58 42 PM" src="https://user-images.githubusercontent.com/60868/144201797-a72feee0-4c6d-44b9-8e35-606f7c6fcba8.png">

(also colophon match should be in the json files of the strings that can be translated)

**Comment by berger-n** [comment]
fixed: https://library.bdrc.io/show/bdr:MW2DB4571?osearch=%22%E0%BD%93%E0%BD%BC%E0%BD%A2%E0%BC%8B%E0%BD%96%E0%BD%B4%E0%BC%8B%E0%BD%95%E0%BE%B2%E0%BD%BA%E0%BD%84%E0%BC%8B%E0%BD%96%22~1@bo

![Screenshot_20211201_120023](https://user-images.githubusercontent.com/33383857/144222867-d8780b9e-9ae8-44c0-ac51-68276128dde2.png)
---

\+ added string to translation file: https://github.com/buda-base/public-digital-library/blob/3a15d99bda674f7eb1505f77cf0d84a1a83b58e6/src/translations/bo.json#L216-L221

**Comment by eroux** [comment]
excellent, thanks!
