### ISSUE TITLE
loading images from wrong manifest?

### ISSUE THREAD

**Issue by berger-n** [buda-base/public-digital-library#633]
see http://library-dev.bdrc.io/show/bdr:W1FEMC046178
it seems that there are two Scans for one Version and it's loading the wrong one (I guess it should show http://library-dev.bdrc.io/show/bdr:I1FEMC046178)

**Comment by eroux** [comment]
hmm yes, I think it's exactly the same problem as the one we worked on the other day (I can't find it), namely instead of calling http://iiifpres.bdrc.io/collection/wio:bdr:MW1FEMC046178 pdl should call http://iiifpres.bdrc.io/collection/wio:bdr:MW1FEMC046178::bdr:W1FEMC046178

**Comment by berger-n** [comment]
ok thanks! I'll check #572 and #615 as well

**Comment by eroux** [comment]
ah yes, #615 is what I was thinking of

**Comment by berger-n** [comment]
turns out these changes were commited to master branch and not khmer branch
https://library.bdrc.io/show/bdr:W1FEMC046178#open-viewer is fine

**Comment by berger-n** [comment]
merging master indeed fixed http://library-dev.bdrc.io/show/bdr:W1FEMC046178#open-viewer
closing
