### ISSUE TITLE
new property for preferred formats

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#64]
See [this comment](https://github.com/IIIF/api/issues/1786#issuecomment-483354805): the iiif spec editors added the property `preferredFormats` that does the same as our `formatHints`. We should use it instead.

In order to get a good transition period, we should first handle both `preferredFormats` and `formatHints` in Javascript, then change the iiif server and presentation.

**Comment by eroux** [comment]
do we have the new mirador integrating this in the pdl? If so let's close this

**Comment by berger-n** [comment]
yes we do

**Comment by eroux** [comment]
@berger-n something's not working in that regard. If I go on

http://library.bdrc.io/scripts/embed-iframe.html?work=bdr:W22084&origin=githubissue&lang=bo-x-ewts

the jpg are used instead of the png. The property is correctly set in the [info.json](http://iiif.bdrc.io/bdr:V22084_I0887::08870003.tif/info.json) so it should work
