### ISSUE TITLE
wrong label for author in associated search results

### ISSUE THREAD

**Issue by berger-n** [buda-base/public-digital-library#640]
not for now because it does not happen on https://library.bdrc.io/search?r=bdr:P252&t=Work&pg=1&f=tree,inc,bdr:O9TAXTBRC201605_1835&f=tree,inc,bdr:O9TAXTBRC201605_1598&f=tree,inc,bdr:T808&f=tree,inc,bdr:T471&f=tree,inc,bdr:T1082&f=tree,inc,bdr:T1193&f=tree,inc,bdr:T1PD181203 

![Screenshot_20211209_162348](https://user-images.githubusercontent.com/33383857/145424573-ab53523f-4da3-4e01-98fc-f0cec6b5f688.png)
---

but see http://library-dev.bdrc.io/search?r=bdr:P252&t=Work&pg=1&f=tree,inc,bdr:O9TAXTBRC201605_1835&f=tree,inc,bdr:O9TAXTBRC201605_1598&f=tree,inc,bdr:T808&f=tree,inc,bdr:T471&f=tree,inc,bdr:T1082&f=tree,inc,bdr:T1193&f=tree,inc,bdr:T1PD181203

![Screenshot_20211209_162222](https://user-images.githubusercontent.com/33383857/145424294-0e3c9d47-f927-4853-97c6-09dc7f158e9a.png)

**Comment by eroux** [comment]
isn't it just the different language settings of the Khmer website ?

**Comment by berger-n** [comment]
indeed! thanks, adding "bo-x-ewts" as last choice for user language preference fixed it
closing
