### ISSUE TITLE
outline by volume at the root level

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#641]
This is a follow up on the work that has already been done on the outlines by volume. This time this would be required at the root level, on https://library.bdrc.io/show/bdr:MW3CN27014 . I probably need to change the initial resource query a little bit?

**Comment by berger-n** [comment]
I guess having a `
tmp:hasNonVolumeParts: true` in http://purl.bdrc.io/query/graph/ResInfo-SameAs?R_RES=bdr%3AMW3CN27014&format=json will help prevent calling the default full outline query on root node, yes, thanks
then it should be quite straighforward to fix it client-side

**Comment by eroux** [comment]
would that be ok to remove the `bdo:hasPart` property and replace them with a `tmp:hasPartB` which would be `true` of `false`? that way the page would load more quickly and even the first level of the outline can be queried asynchronously

**Comment by berger-n** [comment]
yes why not indeed!

**Comment by eroux** [comment]
here it is: http://ldspdi-dev.bdrc.io/query/graph/ResInfo-SameAs?R_RES=bdr%3AMW3CN27014&format=json (on ldspdi-dev only so that we don't break the website in the meantime). Once the client is ready we can deploy it on ldspdi too

**Comment by berger-n** [comment]
done: http://library-dev.bdrc.io/show/bdr:MW3CN27014

![Screenshot_20211210_093306](https://user-images.githubusercontent.com/33383857/145542640-931bc215-4bca-4077-b0fa-e2c3942d9d7c.png)
---

not sure what to think about this text which is present in both http://ldspdi-dev.bdrc.io/query/graph/Outline_root_pervolume?R_RES=bdr%3AMW3CN27014&I_VNUM=1 and http://ldspdi-dev.bdrc.io/query/graph/Outline_root_pervolume?R_RES=bdr%3AMW3CN27014&I_VNUM=8 (BTW is it ok that there is nothing before v. 1 img. 137? nor nothing after  v. 65 img. 527 in a 80 volumes version?) 

![Kazam_screencast_00059 mp4](https://user-images.githubusercontent.com/33383857/145545190-4fc4dcbb-f083-4d96-83de-888a953a0dca.gif)
---

\+ needs to fix case when loading from subnode page though: http://library-dev.bdrc.io/show/bdr:MW3CN27014?part=bdr:MW3CN27014_K0001

![Screenshot_20211210_095126](https://user-images.githubusercontent.com/33383857/145545349-39f3112f-e6c2-4e87-8bd8-99a9650e3faa.png)

**Comment by eroux** [comment]
Great, thanks!

the first text spans from volume 1 to the middle of volume 8 and then the second text starts in volume 8. The current query is not really ideal, I agree... but at least all the information is there

the outline is not fully finished yet, so it's normal that the end isn't there yet

**Comment by berger-n** [comment]
fixed: http://library-dev.bdrc.io/show/bdr:MW3CN27014?part=bdr:MW3CN27014_K0001

![Screenshot_20211210_145215](https://user-images.githubusercontent.com/33383857/145584396-0ed0d011-539f-4ef5-9633-e58ae397dc49.png)

now search needs to be fixed too: http://library-dev.bdrc.io/show/bdr:MW3CN27014?osearch=%22%E8%88%AC%E8%8B%A5%E6%B3%A2%E7%BE%85%E8%9C%9C%E5%A4%9A%E7%B6%93%22@zh-hant

![Screenshot_20211210_145705](https://user-images.githubusercontent.com/33383857/145585108-1ad1f847-91b6-41f7-b46c-4b05984ff9dd.png)

**Comment by berger-n** [comment]
actually it appears that query does not return any match information: http://ldspdi-dev.bdrc.io/query/graph/Outline_search?LG_NAME=zh-hant&R_RES=bdr%3AMW3CN27014&L_NAME=%22%E8%88%AC%E8%8B%A5%E6%B3%A2%E7%BE%85%E8%9C%9C%E5%A4%9A%E7%B6%93%22

**Comment by berger-n** [comment]
search is ok now: http://library-dev.bdrc.io/show/bdr:MW3CN27014?osearch=%22%E8%88%AC%E8%8B%A5%E6%B3%A2%E7%BE%85%E8%9C%9C%E5%A4%9A%E7%B6%93%22@zh-hant

![Screenshot_20211210_165403](https://user-images.githubusercontent.com/33383857/145602684-3e2c6428-41a9-440c-819c-60969cdadbd8.png)
 
deployed: https://library.bdrc.io/show/bdr:MW3CN27014?part=bdr:MW3CN27014_K0001

**Comment by berger-n** [comment]
even better with Volumes/load siblings in outline search: :smile: 
https://library.bdrc.io/show/bdr:MW3CN27014?osearch=%22%E8%88%AC%E8%8B%A5%E6%B3%A2%E7%BE%85%E8%9C%9C%E5%A4%9A%E7%B6%93%22@zh-hant

![Screenshot_20211210_174849](https://user-images.githubusercontent.com/33383857/145610731-e9acd15d-1ba5-45f9-9ff1-89c4bdb4d4e3.png)

**Comment by eroux** [comment]
how wonderful :) thanks a lot!

**Comment by berger-n** [comment]
sorry reopening, I've just found a few more minor bugs:
- [ ] this node won't open in outline: https://library.bdrc.io/show/bdr:MW3CN27014?part=bdr:MW3CN27014_K0022-1

- [ ] (related) its parent node won't show its children when clicked: https://library.bdrc.io/show/bdr:MW3CN27014?part=bdr:MW3CN27014_K0021
  ![Kazam_screencast_00060 mp4](https://user-images.githubusercontent.com/33383857/145611818-ed50a444-12d3-42fd-bb0e-d6c4c3cda6b3.gif)

- [ ] its behaviour in search results is to check as well: https://library.bdrc.io/show/bdr:MW3CN27014?osearch=%22%E8%88%AC%E8%8B%A5%E6%B3%A2%E7%BE%85%E8%9C%9C%E5%A4%9A%E7%B6%93%22@zh-hant
![Kazam_screencast_00061 mp4](https://user-images.githubusercontent.com/33383857/145612291-3712b291-eda3-4ed2-b4c0-0ca4e329bf49.gif)

**Comment by berger-n** [comment]
fixed last of all items above: https://library.bdrc.io/show/bdr:MW3CN27014?part=bdr:MW3CN27014_K0022-1

![Screenshot_20211213_122134](https://user-images.githubusercontent.com/33383857/145803597-90ce2004-503c-4ff8-8d84-df9cfb010633.png)

**Comment by eroux** [comment]
great, thanks!
