### ISSUE TITLE
empty image reproductions in versions associated to work search

### ISSUE THREAD

**Issue by berger-n** [buda-base/public-digital-library#642]
see http://library-dev.bdrc.io/search?i=bdr:WA0XLE120E730D9AA&t=Work

![Kazam_screencast_00058 mp4](https://user-images.githubusercontent.com/33383857/145443640-7437c3f4-47da-4a43-ab21-6b2176e4bc26.gif)
---

main query returns `nbImageReproductions=2`: http://purl.bdrc.io/lib/workInstancesGraph?R_RES=bdr%3AWA0XLE120E730D9AA&format=json

![Screenshot_20211209_181801](https://user-images.githubusercontent.com/33383857/145444460-59cdb9c6-f474-4e48-ba7c-6c9a137d27d0.png)
---

but subquery returns nothing: http://purl.bdrc.io/lib/instanceReproductionsGraph?R_RES=bdr%3AMW1KG14_0AC578&format=json

![Screenshot_20211209_181717](https://user-images.githubusercontent.com/33383857/145444324-8836b362-7620-4b49-8b9e-8852dad4d2b3.png)

**Comment by eroux** [comment]
fixed. I'm not sure it's fixed in the best possible way... but at least it's coherent. Let's have a look later if needed

**Comment by berger-n** [comment]
perfect! thanks
