### ISSUE TITLE
tweak guided search categories

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#644]
this is kind of cheating but in

https://khmer-manuscripts.bdrc.io/guidedsearch

the leporello and long/short palm leaf should be in the same category (in the versions tab)

**Comment by berger-n** [comment]
quite straightforward from a technical point-of-view, but as we actually can't have both binding:leporello and any format, checking leporello and anything else in format won't yield any result (not the expected OR behaviour like everywhere else): http://library-dev.bdrc.io/guidedsearch

![Screenshot_20220104_190155](https://user-images.githubusercontent.com/33383857/148103339-359efa51-7b43-44e8-8369-a889ffe27102.png)

wouldn't it be better if leporello was a format, not a binding?

**Comment by eroux** [comment]
well, it would make things more simple in this page yes, but the data is what it is... yes, that makes the UI a bit clucky... let's embrace that kind of cluckiness for now. Thanks!
