### ISSUE TITLE
error message priority

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#645]
On https://library.bdrc.io/show/bdr:W3CN7697 there are two "errors":
- the images are not yet available
- the text is restricted

When I'm logged in (with admin credentials) I see only the restriction error message. Is it possible to also always show the "images not yet available" message?

**Comment by berger-n** [comment]
need to clarify a bit, not sure what should be done here... 

first, what I see is the opposite, when I'm logged as admin I get the message "*images not yet available*":

![Screenshot_20220106_164133](https://user-images.githubusercontent.com/33383857/148409051-643d2aa1-333f-4667-aaa9-2ad45e5b7a32.png)

---

when I'm not (or logged with non admin account) I see "*BDRC has restricted access*" :

![Screenshot_20220106_164009](https://user-images.githubusercontent.com/33383857/148408800-8207f2ac-310b-495b-bcb5-7a137a929c6e.png)

---

then, which message is shown depends on what is returned both by [collection](http://iiifpres.bdrc.io/collection/wio:bdr:MW3CN7697::bdr:W3CN7697) (403 if not admin, thus "*restricted*" message) and by first [manifest](https://iiifpres.bdrc.io/vo:bdr:I3CN7699/manifest) if collection was able to be fetched (in this case, 404 if admin, 403 if not)

but I can also check `access` value to display restricted message even if user has credentials, is that what you want me to do?

![Screenshot_20220106_165356](https://user-images.githubusercontent.com/33383857/148410941-1b94ce41-e194-4fd8-b389-9ddfcbb5fb30.png)

**Comment by eroux** [comment]
Oh I see... don't bother then, what should probably change are the codes from iiifpres, I'll move the issue there. Thanks!
