### ISSUE TITLE
accessing copyrighted outline nodes

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#647]
when accessing https://library.bdrc.io/show/bdr:MW28948_AE83CB (a copyrighted section so no image available) not logged I'm getting "Images not available" which is not particularly helpful... when logged I'm getting the correct thing though ("This work is copyrighted, as a result..."). The latter should be there also for non-logged in users

**Comment by eroux** [comment]
(I'm not sure what triggers that... @berger-n can you take a look?)

**Comment by berger-n** [comment]
actually https://iiifpres.bdrc.io/wvo:bdr:MW28948_AE83CB::bdr:I4956/manifest is ok when logged but when not it fails:

```
code: 5001
developerMessage: null
link: null
message: "manifest is empty (images are too big to be displayed)"
status: 404
```

**Comment by eroux** [comment]
ah thanks! I'll fix that

**Comment by eroux** [comment]
fixed, now there are two messages though... wdyt @berger-n ?

**Comment by berger-n** [comment]
thanks! seems better with IA message only: https://library.bdrc.io/show/bdr:MW28948_AE83CB

![Screenshot_20220111_182033](https://user-images.githubusercontent.com/33383857/148990693-67e11b49-c623-4957-95d4-c2e52f0815f6.png)

**Comment by eroux** [comment]
perfect, thanks!
