### ISSUE TITLE
redirection not working when opening non existing resource

### ISSUE THREAD

**Issue by berger-n** [buda-base/public-digital-library#649]
see for example https://library.bdrc.io/show/bdr:T11111111111111
it used to redirect to home while displaying a message
related query is not empty though: https://purl.bdrc.io/query/graph/ResInfo-SameAs?R_RES=bdr%3AT11111111111111&format=json

![image](https://user-images.githubusercontent.com/33383857/149910054-c65eac2d-0203-4409-be4e-1a62b0e60473.png)

I think it used to return a 404 error, leading to an exception thrown in client

**Comment by eroux** [comment]
hmmm... interesting problem... let me think about this

**Comment by berger-n** [comment]
perfect! thanks
