### ISSUE TITLE
NEW SEARCH behavior

### ISSUE THREAD

**Issue by ngawangtrinley** [buda-base/public-digital-library#651]
Suggested by @tadhondup. New search should lead to the home page with the focus/cursor in the search bar, so users can directly start typing after clicking.

Not having this gradually builds up frustration when you have to do a lot of consecutive searches, as you have to use your mouse to scroll, aim at the box and click.

**Current behavior**  
1\. click on NEW SEARCH  
2\. scroll and aim at search box  
3\. click to enter the box  
4\. start to type

**Improved behavior**  
1\. click on NEW SEARCH  
2\. start to type  

![image](https://user-images.githubusercontent.com/17675331/150631320-5ad23dd4-8318-4b28-93e5-9ff53b9f85d0.png)

**Comment by eroux** [comment]
very good idea! I think it should be the behavior on the home page too

**Comment by berger-n** [comment]
done: https://library.bdrc.io/search?r=bdr:PR1FPL01&t=Scan&s=title%20forced&pg=1&n=1

![Kazam_screencast_00064 mp4](https://user-images.githubusercontent.com/33383857/150778977-90970d79-b345-40fb-a155-8dc403546a5f.gif)

---

search input has now focus by default on homepage as well: https://library.bdrc.io/

![Kazam_screencast_00066 mp4](https://user-images.githubusercontent.com/33383857/150779009-09abb535-5226-4eef-b58a-9c64bdf51d6e.gif)

**Comment by eroux** [comment]
thanks! One issue though, if I go to https://library.bdrc.io/search?r=bdr:PR1FPL01&t=Scan&s=title%20forced&pg=1&n=1 and then click on "new search", the input is focused but there's a scroll down happening that goes too far down:

![Capture d’écran de 2022-01-24 13-52-22](https://user-images.githubusercontent.com/60868/150786516-bdc44cc9-3617-4b89-9737-ae4d6de494e6.png)

**Comment by berger-n** [comment]
thanks for the feedback! seems ok now in firefox as well: https://library.bdrc.io/search?r=bdr:PR1FPL01&t=Scan&s=title%20forced&pg=1&n=1

![Kazam_screencast_00068 mp4](https://user-images.githubusercontent.com/33383857/150791556-bdb38090-8c8e-4160-994a-206c330c1045.gif)

**Comment by tadhondup** [comment]
Thank you all. Now it's working well, much easier to get there.
