### ISSUE TITLE
Updating Facebook link

### ISSUE THREAD

**Issue by TBRC-pmench** [buda-base/public-digital-library#654]
I updated our Facebook identity to bdrc.io instead of tbrc.org (https://www.facebook.com/bdrc.io) and the Facebook URLs on library.bdrc.io and bdrc.io need to be updated. 

I updated the links in the footer on bdrc.io for Chinese and Tibetan but the Widget editor has changed and I can't seem to update the link on the English version of bdrc.io. The block where I would expect to edit the code just shows up blank. Can you make the updates? Thank you.

**Comment by berger-n** [comment]
I think there is was an issue with the new widget/footer editor now used by WordPress, I've installed a plugin to use the old one and then it was here, in *Footer Column 1* : https://www.bdrc.io/wp-admin/widgets.php

![image](https://user-images.githubusercontent.com/33383857/151393111-63fe7c40-3c27-47fc-837b-53219621afe9.png)

(also updated links on library.bdrc.io)

**Comment by TBRC-pmench** [comment]
Thanks. WP's promise that the legacy widgets would work seamlessly in the new system was less than fulfilled it seems...
