### ISSUE TITLE
UI glitch on user profile

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#656]
in Firefox when I open my user profile on BUDA I see

![Capture d’écran de 2022-01-28 09-35-15](https://user-images.githubusercontent.com/60868/151514101-5cad2562-2a0a-4be1-9c9f-902e6be23172.png)

**Comment by berger-n** [comment]
fixed: https://library.bdrc.io/user

![image](https://user-images.githubusercontent.com/33383857/151526405-35abfa3f-a4c8-4a15-be75-31b20ac500b2.png)

**Comment by eroux** [comment]
thanks!
