### ISSUE TITLE
download of page range as PDF

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#657]
It would be useful to some users to have a UI to download an arbitrary page range in PDF, both in mirador and on the Scans page. I'm not really sure what the best way to present it would be, there's not an awful lot of room in there... cc @TBRC-pmench

**Comment by TBRC-pmench** [comment]
Perhaps it could be added as an option in the pop up with "Download PDF" and "Download Images"

**Comment by berger-n** [comment]
indeed adding a step in popup could work:
clicking on *Get PDF* could lead to something like that:
![image](https://user-images.githubusercontent.com/33383857/152997734-5f8bdaf0-c6a5-4fc4-a5e5-c562c0a440b5.png)

---

for input errors to be handled it will require to add min/max index of pages in http://iiif.bdrc.io/download/pdf/wi:bdr:W22084::bdr:I22084 though, where they seem not to be returned when using json output:

![image](https://user-images.githubusercontent.com/33383857/152998466-fcae8bd7-a86c-4445-b393-4389e31290bb.png)

**Comment by eroux** [comment]
looks good! we can do without input correction first (after all, there's none on tbrc.org), but yes, it would be a good idea to improve the json output, I'll report that separately

**Comment by berger-n** [comment]
first version working here: http://library-dev.bdrc.io/show/bdr:W22084

![image](https://user-images.githubusercontent.com/33383857/153257403-a22e16d0-c2bf-482a-9fd3-6983d88e4d30.png)

---

error handling needed, both in input component (checking format is valid) and in network requests (do something with error return codes if any, but I see that https://iiif.bdrc.io/download/pdf/v:bdr:I0886::700-702 seems not to fail at all?)

**Comment by eroux** [comment]
Thanks a lot! I think this is good, I'll report the lack of failure on the iiif server and will fix it

**Comment by eroux** [comment]
ok, now a 404 is returned

**Comment by berger-n** [comment]
oops I forgot, we need to do the same in mirador now

**Comment by berger-n** [comment]
done the same in mirador: http://library-dev.bdrc.io/view/bdr:W22084

![image](https://user-images.githubusercontent.com/33383857/153637946-2d90c450-57a4-499d-90ea-69b0249eafed.png)

![image](https://user-images.githubusercontent.com/33383857/153638065-bc74e10e-8d22-42f9-879d-5059d57f25f8.png)

**Comment by eroux** [comment]
perfect, thanks a lot!
