### ISSUE TITLE
display sub-locations on map of place records

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#662]
On the page of place records we currently display the place of the entity, it would be useful, I think, to also display on the map places contained in it (in a different color?). That would greatly ease navigation

**Comment by eroux** [comment]
let's not do that, but instead do a system similar to the one with the works that have many instances: if there are more than X "located in" places (X=6 maybe?), we restrict the number of displayed places to X. If there are more than 1 place in the located in property, we add a red button "see all places" that goes to the URL of associated places, with a filter on locatedIn. On that page the map should be displayed

**Comment by berger-n** [comment]
done: http://library-dev.bdrc.io/show/bdr:G3186

![Kazam_screencast_00084 mp4](https://user-images.githubusercontent.com/33383857/163594226-b1542106-8f05-48e4-8618-158e4dafcd52.gif)

**Comment by eroux** [comment]
Looks perfect, thanks!
