### ISSUE TITLE
change welcome message for loggin-in people

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#669]
The message on the home page is saying "All users, including users with existing accounts on tbrc.org, will need to register for a free BDRC account for full access. Click on the register link above to create a new account." even to logged-in users, which is confusing (it was reported on help). @JannTibetan @TBRC-pmench what do you think? Should we keep it that way, remove that part of the messsage, change it?

**Comment by JannTibetan** [comment]
Can the message change (disappear) once someone is logged in?

**Comment by eroux** [comment]
sure, let's do that. @berger-n can you look into it?

**Comment by berger-n** [comment]
done, you can test it here: http://library-dev.bdrc.io/
when not logged-in:

![image](https://user-images.githubusercontent.com/33383857/154446295-e5a49703-04df-4cad-bbce-337a24c58f26.png)

**Comment by eroux** [comment]
excellent, thanks! Let's deploy

**Comment by berger-n** [comment]
ok! done: https://library.bdrc.io/

**Comment by JannTibetan** [comment]
It works great. Thanks!
