### ISSUE TITLE
Page order for etext download of W7479 is completely scrambled

### ISSUE THREAD

**Issue by JannTibetan** [buda-base/public-digital-library#670]
http://purl.bdrc.io/resource/W7479   Thanks for looking into this.

**Comment by eroux** [comment]
@JannTibetan I can't see any obvious scrambling... do you have an example?

**Comment by JannTibetan** [comment]
My computer is not with me but the pagination was totally out of order. Word by word it was alright but the pages were a mess in the download. Online is displays fine.

**Comment by JannTibetan** [comment]
Then I downloaded two other etexts to see if it was a wider problem but both of those were error free.

**Comment by eroux** [comment]
oh sorry I looked at it on my phone and I missed the "etext" part of the issue... probably the same as https://github.com/buda-base/lds-pdi/issues/226 I'll look closer

**Comment by JannTibetan** [comment]
Thanks for taking care of this. I'm sorry to be getting the notification so late.
