### ISSUE TITLE
use image number from manifest in OSD bottom bar

### ISSUE THREAD

**Issue by berger-n** [buda-base/public-digital-library#675]
see for example https://library.bdrc.io/view/bdr:I1KG16
img.7 is 5 in OSD

**Comment by eroux** [comment]
the issue is that when we display `img. X / Y`, the current meaning is:
- `X` is the index of the canvas in the current manifest
- `Y` is the total number of canvas in the current manifest

it should be replaced with just the image label `img. Z` where `img. Z` is the label of the displayed image

**Comment by berger-n** [comment]
done: http://library-dev.bdrc.io/view/bdr:I1KG16

![image](https://user-images.githubusercontent.com/33383857/157634885-d3a1dc53-c4ea-45fb-bc1c-aa2d0e3e55f4.png)

**Comment by eroux** [comment]
perfect, thanks!

**Comment by eroux** [comment]
(cc @karmagongde : is this change satisfactory?)
