### ISSUE TITLE
edtf display

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#677]
Now that we have our wonderful edtf field in the editor (and now that the editor has an impact on BUDA), we should handle it in here too, especially since I'm going to change the migration a bit to use this field. I think basically we should:
- display only the edtf field (`:eventWhen`) when it's present, not the other fields (onYear, notBefore, notAfter)
- when it's not present, we should compute it from the other fields and display it. It's relatively straightforward, see [this code](https://github.com/buda-base/editserv/blob/dev/src/main/java/io/bdrc/edit/helpers/EditServReasoner.java#L155) in Java

**Comment by berger-n** [comment]
**Edit:** not perfect for now compared to what's in the editor...

![image](https://user-images.githubusercontent.com/33383857/158388477-8eb737cb-187d-4556-852b-44c0db8332c9.png)

**Comment by berger-n** [comment]
better now: http://library-dev.bdrc.io/show/bdr:P0NB33

![image](https://user-images.githubusercontent.com/33383857/158390079-95027d5f-c979-437b-b66a-9873450b7881.png)

**Comment by eroux** [comment]
looks perfect, thanks a lot!!

**Comment by berger-n** [comment]
more to fix here: http://library-dev.bdrc.io/show/bdr:P1649

![image](https://user-images.githubusercontent.com/33383857/158403267-9bd44dbb-c4c2-4077-b71c-959a352fa577.png)

**Comment by berger-n** [comment]
- [ ] use locale hyphen

**Comment by berger-n** [comment]
fixed + use locale date format: http://library-dev.bdrc.io/show/bdr:P1649

![image](https://user-images.githubusercontent.com/33383857/158441401-05c15720-9cd2-40f2-9dda-618e775c0a9a.png)

![image](https://user-images.githubusercontent.com/33383857/158441444-1f3d8742-2f7f-432b-8184-faf22c005982.png)

![image](https://user-images.githubusercontent.com/33383857/158441526-690f3827-fe7a-4362-a704-c943ea840a3d.png)

**Comment by eroux** [comment]
perfect, thanks!!
