### ISSUE TITLE
wrong message for 403 when downloading PDF

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#686]
in mirador when downloading the images from there:

![Capture d’écran de 2022-03-20 11-59-38](https://user-images.githubusercontent.com/60868/159159134-cd6b6d6d-4038-4d8a-95d9-272f6865155e.png)

and receiving a 403, the message is wrong, it should be "access restricted" or something like that. The current message should be for 401 only

**Comment by berger-n** [comment]
done: http://library-dev.bdrc.io/view/bdr:W1PD96682

- when logged but not admin:

![image](https://user-images.githubusercontent.com/33383857/160607919-216d340c-f4a1-4858-be3f-84e23c9134c4.png)

- when not logged:

![image](https://user-images.githubusercontent.com/33383857/160608158-1d79b456-49bd-45ff-924a-406e2a35ff95.png)

---

regarding your screenshot, can a 403 be actually be returned in that specific case? when already displaying a manifest/collection entry, with thumbnail and download icon
(I have handled that case as well but could not find a way to test it)
