### ISSUE TITLE
allow khmer unicode to be selected in the language on the main website

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#687]
and not only on the Khmer-specific website

**Comment by berger-n** [comment]
I guess this is for the medium/long run, but we don't even even have a khmer translation file for now...
what's the roadmap here, if you already have any?

**Comment by eroux** [comment]
oh I just mean when users type unicode Khmer in the search bar it should be detected as Khmer, I'm not suggesting a Khmer language UI switch

**Comment by berger-n** [comment]
it works now: http://library-dev.bdrc.io/

![image](https://user-images.githubusercontent.com/33383857/160097153-f98906a5-c404-4a7c-9cf5-d081691ea69d.png)

---

I've also added `km-x-iast` as an automatic fallback for `km-x-twktt` and fixed sorting results by title (so as it does not put all `km`/`km-x-iast` first, then all `km-x-twktt`): http://library-dev.bdrc.io/latest?t=Scan&s=title&pg=1&f=language,inc,bdr:LangKm

![image](https://user-images.githubusercontent.com/33383857/160096930-bb63672b-4179-422c-98aa-a58efb5604f4.png)

---

also not sure about this label for `km-x-twktt` that was missing: [link](http://library-dev.bdrc.io/show/bdr:MW1FEMC011286?s=q%3D%2522%25E1%259E%2598%25E1%259E%25A0%25E1%259E%25B6%25E1%259E%259C%25E1%259F%2581%25E1%259E%259F%25E1%259F%2592%25E1%259E%259F%2522%26lg%3Dkm%26t%3DInstance%26f%3Dasset%2Cinc%2Ctmp%3ApossibleAccess%26f%3Dasset%2Cinc%2Ctmp%3AcatalogOnly%26n%3D1)

![image](https://user-images.githubusercontent.com/33383857/160098732-122865c9-1812-4ff8-a124-34989fcf1863.png) 

related: 

![image](https://user-images.githubusercontent.com/33383857/160098847-9f5a2974-782c-4747-ae4f-213dc3439141.png)

**Comment by eroux** [comment]
Thanks! Wow, the display of the transliteration looks terrible... I think this is because of spurious characters it in...

**Comment by berger-n** [comment]
> Thanks! Wow, the display of the transliteration looks terrible... I think this is because of spurious characters it in...

I was thinking it was because the IAST scheme is not perfect for khmer, hence the usefulness of Trent Walker's scheme?
indeed it always looks much better in comparison!
but if you say that it comes from the data in khmer...

**Comment by eroux** [comment]
oh, I see... let's not transliterate to IAST then, it doesn't really work for the type of Khmer we have

**Comment by berger-n** [comment]
ok
let's keep it an option you can enable in user profile

**Comment by berger-n** [comment]
ok so now by default `km` is not transliterated to `km-x-iast`, nor `pi-khmr` into `pi-x-iast` 
(user has to choose `IAST` transliteration for Khmer to enable both of them)

thus, as previously, results are sorted all `km-x-twktt` first, then all `km` (as they are considered different languages): 
http://library-dev.bdrc.io/latest?t=Scan&s=title&f=language,inc,bdr:LangKm&pg=4&n=190

![image](https://user-images.githubusercontent.com/33383857/160106146-c6b81f08-4893-46b1-9f7c-9d90e7959d13.png)

**Comment by eroux** [comment]
perfect, thanks!
