### ISSUE TITLE
crash on a particular URL

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#688]
I'm not sure about which browser version this is, but https://library.bdrc.io/search?r=bdr:P123&t=Work crashes for a user:

https://user-images.githubusercontent.com/60868/159731757-5aa1e553-2362-4bb9-9f21-5133e1a12e18.mov

**Comment by berger-n** [comment]
I can reproduce, seems to be in Chrome at least and related to UI in chinese

**Comment by berger-n** [comment]
fixed: https://library.bdrc.io/search?r=bdr:P123&t=Work&uilang=zh

![Kazam_screencast_00083 mp4](https://user-images.githubusercontent.com/33383857/160389257-df67e407-2ac2-4d8d-9d24-49bc185e2536.gif)

**Comment by eroux** [comment]
thanks!
