### ISSUE TITLE
outline displays too many comments in some cases

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#690]
like https://library.bdrc.io/show/bdr:MW23468 but this is probably an issue in the data, to be investigated

**Comment by berger-n** [comment]
it's in the data indeed: https://purl.bdrc.io/query/graph/Outline_root?R_RES=bdr%3AMW23468

![image](https://user-images.githubusercontent.com/33383857/160345816-a79f330e-8f08-4eb9-acb2-92a7dfab4a91.png)

**Comment by eroux** [comment]
thanks! moved to https://github.com/buda-base/library-issues/issues/425
