### ISSUE TITLE
Fix typo in title of EAP collection name

### ISSUE THREAD

**Issue by JannTibetan** [buda-base/public-digital-library#691]
http://purl.bdrc.io/resource/PR1EAP1150 Should be renamed to Endangered Archives Programme (not Project)

**Comment by eroux** [comment]
done, thanks! (it will be visible after the next migration). We don't currently have a description for this collection, perhaps we could add one in the "documenting collections" document on https://docs.google.com/document/d/1bk0_FshcA5bGB-O9w80TecJMBn1i3swdV3Pdmu7VJH0/edit# ?

**Comment by JannTibetan** [comment]
How about:
The Endangered Archives Programme funds the digital preservation of cultural heritage in many communities around the world. EAP has sponsored several projects to digitize Buddhist texts in Bhutan, India, China, Thailand, and elsewhere. The curated Endangered Archives Programme collection on BUDA features XXX volumes of Tibetan-language texts digitized in Bhutan and Amdo and XXX Sanskrit and Newari manuscripts from Nepal. EAP is based at the British Library and supported by a grant from the Arcadia Fund.

**Comment by eroux** [comment]
Oh, this should be a description of EAP#1150 only (the FPL part), sorry for the confusion

**Comment by JannTibetan** [comment]
Ah gotcha. Let me try to shorten the text on this page.

**Comment by JannTibetan** [comment]
The 300 bundles of Pali and vernacular manuscripts in Burmese script in this collection are a subset of the texts BDRC is digitizing at the Fragile Palm Leaves Foundation library. The Endangered Archive Programme supported the digitization and cataloging of these manuscripts. Over 1000 individual texts are contained within the bundles and were selected for their research value. The majority of the manuscripts date from the 18th or 19th century. The texts cover a variety of topics, including law, poetry, stories of the Buddha, grammar and religious rituals. They are the primary sources for the scholarly study of Burmese and Theravada Buddhism, Pali philology, history, literature, as well as regional codicology, premodern textual/scribal practices and manuscript culture.
