### ISSUE TITLE
display content location in notes

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#702]
Notes on BUDA can have specific content locations like outline nodes. Since there's not data like that from tbrc.org, the website doesn't display it correctly though. There's an example on https://library.bdrc.io/show/bdr:P3KG5

In a first step, the data should be fetched by the query and displayed in the same way as it is on an outline node (ex: https://library.bdrc.io/show/bdr:MW22084_0357)

In a second step, there should be a link that opens the image viewer using a special IIIF manifest. The IIIF manifest will be the subject of a separate issue, but the URL that should be used for the display of images is a little unclear... in the example case, I think https://library.bdrc.io/show/bdr:CLNTP3KG5IX3TRAUH41KI894X#open-viewer would be ok...

**Comment by berger-n** [comment]
- [x] first step: https://library.bdrc.io/show/bdr:P3KG5

![image](https://user-images.githubusercontent.com/33383857/166673300-f7cf520c-e8aa-4209-815c-67ea22eacd94.png)
