### ISSUE TITLE
access copyrighted works on IA in the app

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#705]
As I'm updating the data on the mirror, app, etc. an idea popped up in my head: in the app, we currently don't include copyrighted works in the app, but in general @JannTibetan what do you think of including the copyrighted works available on IA in the app and when the user opens the image viewer, they are presented with a popup with the same message as on https://library.bdrc.io/show/bdr:W1PD95844 ("This works is copyrighted..."), and the user can then choose between "view 20 pages on BDRC", "lend on Internet Archve" and "return to app". what do you think?

**Comment by JannTibetan** [comment]
That sounds good to me. Outside of China we feel confident about the legality of offering FairUse previews of copyrighted works. 
Would the IA site open up inside our app our would a web browser launch when people chose to view it on IA?

**Comment by eroux** [comment]
Thanks a lot, this is really good! 

hmm that's a good question... in my recollection, in app mode there's a cross in a corner to close the viewer, this should work in the same way

**Comment by berger-n** [comment]
actually it seems that to exit the viewer in the app you just have to click the back button of your mobile
I've deployed a version of [embed-iframe](https://library.bdrc.io/scripts/embed-iframe.html?work=bdr:W1PD95844&lang=bo-x-ewts&uilang=en&origin=BDRCLibApp1.2.0) with this action triggered when clicking *Return to app* 
but I have not been able to live test from the app so far (as fair use works does not seem to be available from the app for now)

**Comment by eroux** [comment]
thanks for this!

it's a bit odd that copyrighted works are not in the app, they should... are you that for instance W3CN22340 isn't there?

**Comment by berger-n** [comment]
oh sorry I had not latest version installed
I could indeed load W3CN22340 and W1PD95844
not sure how to bypass cache though?
for now app opens previously cached version

**Comment by eroux** [comment]
hmmm that's a good question... perhaps if you load the iframe page in your regular mobile browser and update it to the latest cache version, this new cache might also be used in the app? (not sure it works that way but who knows...)

**Comment by berger-n** [comment]
clearing browser history for last hour did the trick
unfortunately, going back in browser opened from app does not close it
we have to implement something with `postMessage`

**Comment by eroux** [comment]
oh ok, that's too bad... I really thought we had some sort of cross there somewhere...

**Comment by eroux** [comment]
here's an idea: why don't we remove that button and instead write a message 

to come back to the app, please use the "back" button

?

**Comment by berger-n** [comment]
good idea! see https://library.bdrc.io/scripts/embed-iframe.html?work=bdr:W1PD95844&lang=bo-x-ewts&uilang=en&origin=BDRCLibApp1.2.0

![image](https://user-images.githubusercontent.com/33383857/171017203-222616cb-f620-4748-aec0-8e3375689ab7.png)

**Comment by eroux** [comment]
I think this is perfect, thanks!

**Comment by JannTibetan** [comment]
Thank you. Let's change the language on the notification to 'To return to the record for this text, please use the "back" button'

**Comment by berger-n** [comment]
clearing browser history for last hour did the trick
unfortunately, going back in browser app opened from app does not work
we have to implement something with postMessage

**Comment by eroux** [comment]
good idea!
