### ISSUE TITLE
Searching for Collections not working as before

### ISSUE THREAD

**Issue by JannTibetan** [buda-base/public-digital-library#707]
<img width="766" alt="Screen Shot 2022-05-14 at 9 13 29 AM" src="https://user-images.githubusercontent.com/44705185/168427304-f0688b59-91ed-4227-a96e-b29c64edaa73.png">
<img width="766" alt="Screen Shot 2022-05-14 at 9 13 20 AM" src="https://user-images.githubusercontent.com/44705185/168427305-d025d64a-bb05-4ebf-b848-1f2250e27207.png">

**Comment by berger-n** [comment]
@eroux seems to be related to latest commit https://github.com/buda-base/lds-queries/commit/7c66e68b7932691667422c0e42dbca24a31d1b97
(it works on localhost using previous commit)

**Comment by JannTibetan** [comment]
Thanks!
