### ISSUE TITLE
in search results, the map should contain the results of all the pages

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#708]
(but only the filtered results). One example where this doesn't happen is https://library.bdrc.io/search?r=bdr:G603&t=Place&f=relation,inc,bdo:placeLocatedIn&s=title%20forced&pg=1&n=1 (if you got to page 2, the pins on the map are different)

**Comment by berger-n** [comment]
almost done: http://library-dev.bdrc.io/search?r=bdr:G603&t=Place&s=place%20name&pg=1&n=1
(though I can see a few markers on map toggling on/off when switching from page 1 to 2, need to fix this)

![Kazam_screencast_00091 mp4](https://user-images.githubusercontent.com/33383857/169260126-b5c5e50d-c434-4d29-af42-a30799a09fba.gif)
---

what about updating results list when moving/zooming on map? 
would be convenient I guess, and not too hard to implement from what I see

**Comment by eroux** [comment]
about the zoom, it would be great but we can keep it for later, especially since there are many places without coordinates

**Comment by berger-n** [comment]
now with clusters: http://library-dev.bdrc.io/search?r=bdr:G584&t=Place&s=place%20name&pg=1&n=1

![image](https://user-images.githubusercontent.com/33383857/169317174-5c789ac2-cf1c-4d97-a9b8-d4615b01fba8.png)

there's an issue with GoogleMaps though (I've upgraded some packages) so I've deactivated for now
do you know where I could add "localhost:3000" as allowed callers to API? would speed up debugging...

---

BTW https://ldspdi.bdrc.io/resource/G1DOMM0046.tt has a strange placetype: `   bdo:placeType  bdr: .`

**Comment by berger-n** [comment]
I've increased cluster radius by 50%: http://library-dev.bdrc.io/search?r=bdr:G584&t=Place&s=place%20name&pg=1

![image](https://user-images.githubusercontent.com/33383857/169342337-0d6666c6-a134-4447-8291-4060a5bee5f0.png)

**Comment by berger-n** [comment]
![Kazam_screencast_00094 mp4](https://user-images.githubusercontent.com/33383857/169353153-55d4052c-b436-4d81-a11b-525362367810.gif)

**Comment by eroux** [comment]
Perfect, thanks!
