### ISSUE TITLE
small improvements on place search display

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#709]
on https://library.bdrc.io/search?r=bdr:G584&t=Place&f=relation,inc,bdo:placeLocatedIn I've added a new relation type (`tmp:placeContainsDesc`) which means that the matches are located in the places located in main place. We should give it a proper UI label, something like "located in (descendents)". Also it's a bit strange to have "located in" twice, one should be "contains"

**Comment by berger-n** [comment]
> `value: "http://purl.bdrc.io/ontology/core/locatedIn"`

or maybe just a typo?

**Comment by berger-n** [comment]
done: https://library.bdrc.io/search?r=bdr:G584&t=Place&f=relation,inc,bdo:placeLocatedIn

![image](https://user-images.githubusercontent.com/33383857/169039232-1085d2c7-b182-403c-a3fd-45b7ff508e6d.png)
---

> > `value: "http://purl.bdrc.io/ontology/core/locatedIn"`
> 
> or maybe just a typo?

indeed see http://purl.bdrc.io/resource/G1DOMM0001.ttl:
```
   bdo:locatedIn  bdr:G584 ;
```
shouldn't be `bdo:placeLocatedIn`?

**Comment by eroux** [comment]
thanks! fixed

**Comment by eroux** [comment]
works perfectly!
