### ISSUE TITLE
special case for GIS coordinate conversion

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#712]
This is a in-house convention: in the database when we have only two digits after the dot in a GIS coordinate, we should consider that the GIS coordinates are not meant to be specific, but should be converted only to degree ° minute format for display, not to full degree ° minute ' seconds. One difficulty is that we should take the closest minute, not just truncate the display.

Also, we should have the original decimal in the "more information" popup

**Comment by berger-n** [comment]
done: http://library-dev.bdrc.io/show/bdr:G1DOMM0705

![image](https://user-images.githubusercontent.com/33383857/169855711-00a53ff2-af9e-47f3-bd05-f3f93f8acab2.png)

---

![image](https://user-images.githubusercontent.com/33383857/169855799-96cf258c-2f89-4762-8fd8-5dc86eae364f.png)

---

![image](https://user-images.githubusercontent.com/33383857/169855925-c3a2fe91-afaa-4d0e-9cf9-b3c8ba0bcea5.png)

---
the *unrounded* property is just temporary, to make sure rounding is fine, see code: https://github.com/buda-base/public-digital-library/blob/bcaac0a4d8a99cd162f66a7f88e8ec3255b75444/src/components/ResourceViewer.js#L1703-L1723

**Comment by eroux** [comment]
looks perfect, thanks! can you deploy?

**Comment by berger-n** [comment]
done: https://library.bdrc.io/show/bdr:G1DOMM0705

**Comment by eroux** [comment]
thanks!
