### ISSUE TITLE
crash when opening images from the outline

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#713]
When I go to https://library.bdrc.io/show/bdr:MW9848?part=bdr:MW9848_0077D0&s=q%3D%2522Kun%2520rig%2520gi%2520sgo%2520nas%2520tshe%2520%2527das%2520rjes%2520su%2520%2527dzin%2522~1%26lg%3Dbo-x-ewts%26t%3DInstance%26f%3Dasset%2Cinc%2Ctmp%3ApossibleAccess%26f%3Dasset%2Cinc%2Ctmp%3AcatalogOnly%26n%3D2

wait for everything to load and then click on "view scans" of the node in the outline, then app crashes

**Comment by JannTibetan** [comment]
I have been having the same issue for the past 24 hours, primarily (exclusively?) in Safari. When I click to view scans in Safari all I see is the background color of the web page (light gray) and the image viewer fails to load. This problem is not occurring in Chrome.

**Comment by berger-n** [comment]
fixed: https://library.bdrc.io/search?q=%22Kun%20rig%20gi%20sgo%20nas%20tshe%20%27das%20rjes%20su%20%27dzin%22~1&lg=bo-x-ewts&t=Instance&f=asset,inc,tmp:possibleAccess&f=asset,inc,tmp:catalogOnly&n=2

![Kazam_screencast_00097 mp4](https://user-images.githubusercontent.com/33383857/170957563-85b5cd20-b84f-4bdc-8911-25e04ed67cf9.gif)

**Comment by eroux** [comment]
thanks!
