### ISSUE TITLE
Khmer UI language

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#719]
It looks like the Khmer translation of the main UI elements is done on 

https://github.com/buda-base/public-digital-library/blob/master/src/translations/km.json

Perhaps we could add the Khmer language to the possible languages on the main website? (in addition to the dedicated website, which we should update with this new translation) There's also probably some translation to do for mirador?

**Comment by berger-n** [comment]
it's possible to enable khmer on main website, but from what I see translation of corresponding elements has not been completed:

 ![image](https://user-images.githubusercontent.com/33383857/172854165-22b820f5-b531-4cac-87bf-66d46ae22ee5.png)

I'll enable khmer in mirador as well, file will be there: https://github.com/buda-base/mirador/tree/2.7.0-bdrc/locales

**Comment by berger-n** [comment]
almost ready: http://library-dev.bdrc.io/

![image](https://user-images.githubusercontent.com/33383857/173104067-691fc374-5e08-40c3-8bb0-82d4b956480a.png)
---

- need to check here and there but more translations are now available here: https://github.com/buda-base/public-digital-library/blob/b3c8dca0ba20ff4dd7e2bf7f7a08bdf85f5865d2/src/translations/km.json#L260-L283
---

- facets in guided search are now loaded from ontology:

![image](https://user-images.githubusercontent.com/33383857/173105165-d7ed7921-b59c-4fda-b92d-4a09923908d9.png)
---

- regarding mirador khmer is now available and is here: https://github.com/buda-base/mirador/blob/2.7.0-bdrc/locales/km/translation.json

**Comment by eroux** [comment]
Thanks! that looks good, except on Firefox though:

![Capture d’écran de 2022-06-10 18-16-37](https://user-images.githubusercontent.com/60868/173109811-968b47b2-93e4-47d6-bbf3-f8e33498d96f.png)

but I don't think there's a lot we can do... this looks like a word segmentation issue, it's usually handled by ICU but it might not be activated for Firefox for some reason... I couldn't make it work even after installing some extensions, forcing `lang="km"` on the relevant div, etc. perhaps we could investigate that a little bit, but there's a chance it can't work at all.

I think at some point there were some discussions about creating a new topic taxonomy, but I suppose we shouldn't wait for it... @TBRC-pmench the topics are in https://github.com/buda-base/owl-schema/blob/master/schemes/taxonomy/FEMCScheme.ttl and as you can see some have a Khmer Unicode equivalent, some haven't. (some have only French / English, some have Pali, some have transliterated Khmer, etc.). Since this is very visible, perhaps we could ask Trent or Khoeun to translate / transcribe them? perhaps also the languages, etc.?

**Comment by berger-n** [comment]
found an easy way to merge mirador translation files and export them when deploying
see https://github.com/buda-base/public-digital-library/blob/master/src/translations/km.json

https://github.com/buda-base/public-digital-library/blob/dfdbb90071acd9218197938588e13b6c88e60564/src/translations/km.json#L701-L707

**Comment by berger-n** [comment]
regarding Firefox we can force linebreaks like this: 

![image](https://user-images.githubusercontent.com/33383857/173352787-aedf0b7c-86d3-428d-a848-2f8bc385c43c.png)
---

it's not perfect from a reader's point of view, but otherwise here's what Resource page looks like:

![image](https://user-images.githubusercontent.com/33383857/173352951-3a15bc49-0370-49e8-b37f-17f03aa51830.png)
---

what about about adding a small popup at the bottom on first visit? 
with link to https://bugzilla.mozilla.org/show_bug.cgi?id=1684927 or something
and/or https://www.google.com/intl/en_hk/chrome/
