### ISSUE TITLE
option to download an etext in wylie

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#720]
independently of the language choice, users should be able to choose wylie for the download of etexts, see https://github.com/buda-base/lds-pdi/issues/210 . I'm not really sure yet how to present that in the UI

**Comment by berger-n** [comment]
something like the language selector popup should be fine:

![image](https://user-images.githubusercontent.com/33383857/173067167-833e2834-5fe9-425e-a3a7-e69513a8a0d4.png)

do we have etext in other language than Tibetan? I don't think so

**Comment by eroux** [comment]
yes perfect! currently Tibetan / Wylie is the only option

**Comment by berger-n** [comment]
done: http://library-dev.bdrc.io/show/bdr:UTIE0OPP008078_v001?startChar=797770&keyword=%22dbang%20phyug%20lus%20gtogs%20dran%20pa%22~1@bo-x-ewts#open-viewer

![image](https://user-images.githubusercontent.com/33383857/173871417-a9040846-c23c-4c18-bf5a-8caae781308a.png)

**Comment by eroux** [comment]
oh that works perfectly, thanks!!

**Comment by eroux** [comment]
(let's deploy)

**Comment by eroux** [comment]
let's send a token yes, although it won't currently work

**Comment by eroux** [comment]
oh, wonderful :)
