### ISSUE TITLE
collection view improvements on mobile

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#722]
when opening the image viewer on MW22084 (or any other collection with an outline and multiple volumes), the image viewer is in portrait mode, and the red bar is about two thirds in the middle of the screen. It would be best in that case to have the outline on the left fully open with the bar on the right, and the possibility to fully fold it and have only the volume list, but there's no need to slide it (just open or close it)

**Comment by berger-n** [comment]
done: http://library-dev.bdrc.io/scripts/embed-iframe.html?work=bdr:W22084&lang=bo-x-ewts&uilang=en&origin=BDRCLibApp1.2.0

![image](https://user-images.githubusercontent.com/33383857/173404855-45113738-4eea-42dc-a912-8ac2b0bf5845.png)

![image](https://user-images.githubusercontent.com/33383857/173404904-04e6e693-140d-4434-8d27-2d421b163433.png)
---

but I think we need to add an icon or something in a corner to help switch panels
users might say "hey I keep clicking on that item but nothing happens"... wdyt?

**Comment by berger-n** [comment]
- now if you click on an item with no subpart it opens the volume list: http://library-dev.bdrc.io/scripts/embed-iframe.html?work=bdr:W22084&lang=bo-x-ewts&uilang=en&origin=BDRCLibApp1.2.0

![Kazam_screencast_00100 mp4](https://user-images.githubusercontent.com/33383857/173615402-310f683b-02a7-4a4e-8ecc-04577f474787.gif)
---

- fixed swipe to open/close panels:

![Kazam_screencast_00101 mp4](https://user-images.githubusercontent.com/33383857/173615435-2693256f-b3c0-4670-9669-9185e6a5076e.gif)
---

- if you go back to collection view and there's only one volume it automatically opens the left panel:

![Kazam_screencast_00102 mp4](https://user-images.githubusercontent.com/33383857/173615469-625b69cc-a04f-4311-8b6e-4774f3e6e60d.gif)

**Comment by eroux** [comment]
amazing, excellent job!
