### ISSUE TITLE
notification to tilt the mobile in landscape mode

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#724]
Instead of trying to force the landscape mode on mobile, we should instead have an icon that asks the user to tilt their phone

**Comment by berger-n** [comment]
(visible here: http://library-dev.bdrc.io/
currently Cambodia website)

**Comment by eroux** [comment]
wonderful, thanks a lot! I think people will be happy with that

**Comment by berger-n** [comment]
everything finally seem fine here: http://library-dev.bdrc.io/

![Kazam_screencast_00115 mp4](https://user-images.githubusercontent.com/33383857/181065122-e30321ed-594b-45ed-9719-7cced3df0aad.gif)

not sure we need the notification anymore though, wdyt?

**Comment by eroux** [comment]
amazing job, thanks a lot!! yes, let's not add the notification, and let's deploy, this is great!

**Comment by berger-n** [comment]
deployed: https://library.bdrc.io/
on Cambodia website as well: https://khmer-manuscripts.bdrc.io/

**Comment by eroux** [comment]
excellent, thanks a lot!
