### ISSUE TITLE
missing collection facet

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#725]
In https://library.bdrc.io/search?q=%22%E0%BD%96%E0%BD%A2%E0%BE%92%E0%BE%B1%E0%BD%91%E0%BC%8B%E0%BD%A6%E0%BE%9F%E0%BD%BC%E0%BD%84%E0%BC%8B%E0%BD%94%22~1&lg=bo&t=Instance&pg=1&f=asset,inc,tmp:possibleAccess&f=asset,inc,tmp:catalogOnly&f=versionType,inc,tmp:standalone the query returns the inCollection property but it doesn't appear in the facets on the left so we can't filter by collection. @berger-n can you take a look?

**Comment by berger-n** [comment]
done: https://library.bdrc.io/search?q=%22%E0%BD%96%E0%BD%A2%E0%BE%92%E0%BE%B1%E0%BD%91%E0%BC%8B%E0%BD%A6%E0%BE%9F%E0%BD%BC%E0%BD%84%E0%BC%8B%E0%BD%94%22~1&lg=bo&t=Instance&pg=1&f=asset,inc,tmp:possibleAccess&f=asset,inc,tmp:catalogOnly&f=versionType,inc,tmp:standalone&f=collection,inc,bdr:PR1NLM00

![image](https://user-images.githubusercontent.com/33383857/173626879-2f02fcfc-d283-4922-abab-60cefc843f0f.png)

**Comment by eroux** [comment]
perfect, thanks a lot!
