### ISSUE TITLE
display series number and work

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#726]
When displaying instance results, if there is a seriesnumber (`:seriesNumber`) and series work (`:serialInstanceOf`) we should display it in the results, something like:

**Number:** {seriesNumber} in {serial work preflabel}

as in https://library.bdrc.io/search?r=bdr:WAS00KG09211&t=Instance&s=title%20forced

and we should perhaps also have a mechanism to sort by series number...

**Comment by berger-n** [comment]
done: http://library-dev.bdrc.io/search?r=bdr:WAS00KG09211&t=Instance&s=title

![image](https://user-images.githubusercontent.com/33383857/174298406-3c0b4dbd-a8e3-40e3-ac93-f30322d1947d.png)
