### ISSUE TITLE
etext download from etext outline

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#727]
In the etext outline (I'm looking at https://library.bdrc.io/show/bdr:IE7479) there are two issues with etext download that could be easy fixes:
- users can't download in Wylie
- the link opens a blank tab and so the token is not sent

**Comment by berger-n** [comment]
fixed: https://library.bdrc.io/show/bdr:IE7479

![Kazam_screencast_00108 mp4](https://user-images.githubusercontent.com/33383857/174825158-722e61c7-a1f8-4fc2-9213-fc80fbc3d8a3.gif)

**Comment by eroux** [comment]
perfect, thanks!
