### ISSUE TITLE
empty "issue: in" in version results

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#728]
in https://library.bdrc.io/search?q=%22bcom%20ldan%20%E2%80%98das%20kun%20rig%20gi%20cho%20ga%20rgyud%20don%20gsal%20ba%E2%80%99i%20snying%20po%20bsdus%20pa%20yid%20bzhin%20gyi%20nor%20bu%22~1&lg=bo-x-ewts&t=Instance&f=asset,inc,tmp:possibleAccess&f=asset,inc,tmp:catalogOnly for instance, each result has an "Issue: in" line, which is unnecessary

**Comment by berger-n** [comment]
fixed: https://library.bdrc.io/search?q=%22bcom%20ldan%20%E2%80%98das%20kun%20rig%20gi%20cho%20ga%20rgyud%20don%20gsal%20ba%E2%80%99i%20snying%20po%20bsdus%20pa%20yid%20bzhin%20gyi%20nor%20bu%22~1&lg=bo-x-ewts&t=Instance&f=asset,inc,tmp:possibleAccess&f=asset,inc,tmp:catalogOnly

![image](https://user-images.githubusercontent.com/33383857/174985477-adda678b-0d54-47f4-8314-78de21c990dd.png)

still ok there: https://library.bdrc.io/search?r=bdr:WAS00KG09211&t=Instance&s=title%20forced

![image](https://user-images.githubusercontent.com/33383857/174986913-839aeff4-58db-43bd-9ca6-7b2651857fa4.png)

**Comment by eroux** [comment]
perfect, thanks!
