### ISSUE TITLE
some outlines not working

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#730]
for instance https://library.bdrc.io/show/bdr:MW22271 is it perhaps the recent change @berger-n ?

**Comment by eroux** [comment]
I'm going to fix the query in that case but there are so many delicate cases that I'm not sure I can catch them all in the query... I'm thinking perhaps the js code could detect this case (hasparts = true, hasNonVolumeParts = true, but volumes query returning nothing), and could then fall back to consider that hasNonVolumeParts = false... what do you think @berger-n ?

**Comment by berger-n** [comment]
good idea I'm gonna try this

**Comment by eroux** [comment]
thanks! (I've fixed the issue for this outline though, I'm not sure how to find another one that wouldn't work)

**Comment by berger-n** [comment]
fixed: https://library.bdrc.io/show/bdr:MW0IDP0002

![image](https://user-images.githubusercontent.com/33383857/176680179-3903c14f-9e62-46e7-aa39-338620791da1.png)

**Comment by eroux** [comment]
perfect, thanks!
