### ISSUE TITLE
scan tab by default when an image instance reproduction exists

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#732]
When a user gets to the page of an instance (ex: https://library.bdrc.io/show/bdr:MW1GS66286 ), the third tab seems to be randomly the scans or etext tab when both are available. Can we make it so that the scans have priority?

**Comment by berger-n** [comment]
done: https://library.bdrc.io/show/bdr:MW1GS66286

![image](https://user-images.githubusercontent.com/33383857/177172121-80b64fd9-1de2-4c7a-861e-c4482132dcb8.png)

---

BTW I've noticed that tabs are lost when switching to Work here 
(which is a withdrawn record that gets redirected)
I think I can fix that

**Comment by berger-n** [comment]
fixed, now it uses the `replaceWith` url if there is one: http://library-dev.bdrc.io/show/bdr:MW1GS66286

![Kazam_screencast_00022 mp4](https://user-images.githubusercontent.com/33383857/177197485-5590e499-9b24-4a3f-8fc7-32dbff3f8ade.gif)
