### ISSUE TITLE
archive file download button in mirador

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#735]
certain images will have their archival version (higher definition, sometimes uncompressed) available from the IIIF server, and we need to make these available in mirador too. This would mean a download button in the image/page view.

see

https://github.com/buda-base/archive-ops/issues/702
https://github.com/buda-base/buda-iiif-server/issues/98
https://github.com/buda-base/buda-iiif-presentation/issues/125
https://github.com/buda-base/archive-ops/issues/729

**Comment by eroux** [comment]
this manifest has the seeAlso things that should trigger the display of the button. The URL of the source file is the `"@id"` of the seeAlso (ex: `https://iiif.bdrc.io/sourcefile/bdr:I0GN010020005::I0GN010020005002.jpg`)

**Comment by eroux** [comment]
since we already have a "download images" button, let's just add one option in the dropdown when the seeAlso is present (and thus only in page view), "download original file for this image"

**Comment by berger-n** [comment]
done: http://library-dev.bdrc.io/show/bdr:W0GN010020#open-viewer

![image](https://user-images.githubusercontent.com/33383857/180776353-45730856-2350-4b89-8fc7-4325af003be8.png)

(server returns error 500 though)

to be tested but if server returns 401 (user not logged) 
it should show the same "please login" message than when downloading pdf

**Comment by eroux** [comment]
perfect, thanks! It can return a 401 indeed, thanks for anticipating

**Comment by eroux** [comment]
it seems to be working now, can you deploy in prod?

**Comment by berger-n** [comment]
deployed: https://library.bdrc.io/show/bdr:W0GN010020#open-viewer

**Comment by berger-n** [comment]
ah one bug to fix
when changing image in viewer it keeps downloading the same

**Comment by berger-n** [comment]
> when changing image in viewer it keeps downloading the same

fixed: https://library.bdrc.io/show/bdr:W0GN010020#open-viewer

![Kazam_screencast_00111 mp4](https://user-images.githubusercontent.com/33383857/180823004-7f1a1d11-7f42-4be4-b302-c3f57b2ed573.gif)

**Comment by berger-n** [comment]
deployed another version here: http://library-dev.bdrc.io/show/bdr:W0GN010020#open-viewer
with file dialog opening at once instead of having to wait until download is finished

![Kazam_screencast_00113 mp4](https://user-images.githubusercontent.com/33383857/180836766-3e17b895-ea6f-4cac-a40a-38a04cb0895e.gif)

which one do you prefer?

**Comment by eroux** [comment]
yes, I think this works better, thanks!

**Comment by berger-n** [comment]
> yes, I think this works better, thanks!

ok! now deployed in prod: https://library.bdrc.io/show/bdr:W0GN010020#open-viewer

**Comment by berger-n** [comment]
(not closely really related but keeping track here)
in image view with smaller window: https://library.bdrc.io/view/bdr:I1KG12050

![image](https://user-images.githubusercontent.com/33383857/223743315-d8f13b20-a476-449c-b5dc-54480930b55a.png)

**Comment by berger-n** [comment]
fixed: https://library-dev.bdrc.io/view/bdr:I1KG12050

![image](https://user-images.githubusercontent.com/33383857/223979008-3f403fed-4189-4fc8-bcc5-0fdf9c2a3b94.png)

**Comment by eroux** [comment]
thanks!
