### ISSUE TITLE
titles not displayed in etext instance outline

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#736]
for instance all the texts of volume 1 of https://library.bdrc.io/show/bdr:IE1KG14 and https://library.bdrc.io/show/bdr:IE0GN010020 have `[no title]` as their label

**Comment by berger-n** [comment]
fixed: https://library.bdrc.io/show/bdr:IE1KG14

![image](https://user-images.githubusercontent.com/33383857/180836049-3fecb4c4-6670-4481-9a25-7d82fd4a54bf.png)

- note the long title needing to be split
- on https://library.bdrc.io/show/bdr:IE0GN010020 there's a glitch so you have to click twice on volume to show its content

**Comment by eroux** [comment]
thanks!

**Comment by berger-n** [comment]
is that solution ok to you? 
I find hyphens a bit confusing because of the +s, but I don't know if something better is feasible...

![image](https://user-images.githubusercontent.com/33383857/180960593-ee583621-9373-4b32-aaad-542911b03039.png)

**Comment by eroux** [comment]
it's better than nothing yes.. This title is kind of an outlier, it looks more like an error, I think other titles should be fine!

**Comment by berger-n** [comment]
other solution can be to break anywhere:

![image](https://user-images.githubusercontent.com/33383857/180964992-125b1e9e-dfd1-4043-9411-c03a1f436145.png)

**Comment by eroux** [comment]
either option works

**Comment by berger-n** [comment]
> - note the long title needing to be split
> - on https://library.bdrc.io/show/bdr:IE0GN010020 there's a glitch so you have to click twice on volume to show its content

fixed, everything's fine now:
- https://library.bdrc.io/show/bdr:IE0GN010020

![Kazam_screencast_00114 mp4](https://user-images.githubusercontent.com/33383857/180980448-28349690-2dc5-4c42-b4ca-a5c19979f7e7.gif)

---

- https://library.bdrc.io/show/bdr:IE1KG14
 
![image](https://user-images.githubusercontent.com/33383857/180979261-30c2e9f8-5dff-4030-8958-cdcaf7443678.png)

**Comment by eroux** [comment]
looks perfect, thanks a lot!
