### ISSUE TITLE
horizontal repeat in thumbnails

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#737]
at least on Firefox, here's what I see on https://library.bdrc.io/show/bdr:PR0GN0001

![Capture d’écran de 2022-07-26 08-16-40](https://user-images.githubusercontent.com/60868/180936913-5878169b-6dae-4759-a8c9-534e393e6b84.png)

it would be best not to repeat the thumbnails horizontally

**Comment by berger-n** [comment]
fixed: https://library.bdrc.io/show/bdr:PR0GN0001

![image](https://user-images.githubusercontent.com/33383857/180957637-f934ec83-aede-44c2-abe1-6551752dccbc.png)

**Comment by eroux** [comment]
perfect, thanks!
