### ISSUE TITLE
AND keyword not working in etexts in Unicode

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#741]
for instance https://library.bdrc.io/search?q=(%22%E0%BD%9A%E0%BD%91%E0%BC%8B%E0%BD%98%E0%BC%8B%22%20AND%20%22%E0%BD%93%E0%BD%BC%E0%BD%A2%E0%BC%8B%E0%BD%96%E0%BD%B4%22)&lg=bo&t=Etext

**Comment by berger-n** [comment]
fixed: https://library.bdrc.io/search?q=(%22%E0%BD%9A%E0%BD%91%E0%BC%8B%E0%BD%98%E0%BC%8B%22%20AND%20%22%E0%BD%93%E0%BD%BC%E0%BD%A2%E0%BC%8B%E0%BD%96%E0%BD%B4%22)&lg=bo&t=Etext

![image](https://user-images.githubusercontent.com/33383857/182150243-763810f9-1277-4771-ab06-e1555d3896f4.png)

but need to reopen #718 to handle AND in exact match facet

**Comment by eroux** [comment]
perfect, thanks a lot!
