### ISSUE TITLE
improvement in the triangle buttons of the outlines

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#742]
Here's a report from a user:

> The outline tree triangles in the BDRC UI do not reflect the current
state of the corresponding node, but show the action that will be
taken if the triangle is clicked.  So for a closed subtree the
triangle points down ("i will open the subtree clicked") and on an
open subtree the triangle points up ("i will close the subtree when
clicked").
> 
> This is different from e.g. MacOS Finder, where the triangle indicates
the current state: a closed subtree has the triangle poiting right, an
open tree has the triangle pointing down.  The same convention is used
e.g. in VirtualBox for VM groups or VM snapshot trees.
> 
> Usually I can re-adjust mentally, but I've been using (i) icon a lot,
to get works' permalinks, and I realized it throws me off - b/c the
rectangle with the (i) stuff is below the line, is indented, and has
white background, so a closed entry with an (i) stuff shown looks
*very* strongly like something "open" under that line.  And the line
has the triangle that points down!  BDRC UI uses it to show that the
item is closed and that a click will open it.  But with the white (i)
suff open below it it looks so strongly like an open item that it
swiches my context to MacOS-like and I interpret that triangle to mean
that the item is open.
> 
> I'm not even a regular MacOS user, but I'm sure I've seen this
left/down triangles elsewhere too.  People that use MacOS a lot must
have this affecting them more strongly I guess.

I think he's right, let's change that

**Comment by berger-n** [comment]
done: 
- http://library-dev.bdrc.io/show/bdr:MW12827?tabs=bdr:W12827

![image](https://user-images.githubusercontent.com/33383857/186469168-d5c77c93-a2c2-4d6e-801b-35111aa75ca0.png)
---

- http://library-dev.bdrc.io/show/bdr:IE1KG14

![image](https://user-images.githubusercontent.com/33383857/186469256-c685ba44-e1c1-4505-929a-29e8316a81e2.png)

**Comment by eroux** [comment]
great, thanks!
