### ISSUE TITLE
An issue with the Return to BUDA link 

### ISSUE THREAD

**Issue by JannTibetan** [buda-base/public-digital-library#744]
<img width="865" alt="Screen Shot 2022-08-06 at 10 07 38 AM" src="https://user-images.githubusercontent.com/44705185/183254028-4a8ac143-814d-474c-affe-da681f8149f1.png">

The Return to BUDA link works well when one is on a record that was included in the original search results. However, if one starts to click on link after link and arrives at a scan that is unrelated to the original search, the Return to BUDA link still takes one back to the first record or to the initial search results (it seems to vary). Here's how it worked for me just now:
I searched for Taishō > opened the Taishō record > found a Chinese sutra in the Taisho outline > viewed the scans of the sutra > clicked Return to BUDA > was returned to the Taisho record > scrolled down to the Chinese sutra in the outline (that outline node is still expanded, helpfully) > click Open Record and then click on the Work tab > click on the Sanskrit edition of the sutra > click on the thumbnail of one of the Sanskrit versions > the image viewer is launched and I peruse the text > then I wish to minimize the IIIF viewer to return to the Scans tab > my only option is RETURN TO BUDA so I click it > I am transported all the way back to the the Taishō Tripitaka record. 

All that being said, a preliminary fix would be to create a button that will minimize the the IIIF viewer (see my previous issue post).

**Comment by berger-n** [comment]
ok it seems to be fixed now
users should be brought back to results only when closing a viewer directly opened from the results list
you can try it here: http://library-dev.bdrc.io/show/bdr:MW0TT0000?s=q%3D%2522taisho%2522%26lg%3Den%26t%3DInstance%26f%3Dasset%2Cinc%2Ctmp%3ApossibleAccess%26f%3Dasset%2Cinc%2Ctmp%3AcatalogOnly%26n%3D1

note that behaviour when closing a viewer opened from an outline node has also changed
now it redirects you to the node record page and not to the page of the outline you came from:

![image](https://user-images.githubusercontent.com/33383857/183709524-a161e3cd-a6cf-4e27-9513-a8ade107c3d5.png)


is it ok like this? 
from there you can directly go to work and choose another version
or click Open in outline to be redirected to the node where you came from:

![image](https://user-images.githubusercontent.com/33383857/183709755-678bccbe-9d8b-4d3f-9fa0-97885b30f69a.png)

**Comment by JannTibetan** [comment]
I just tried it and it worked very well for me. Thank you.
