### ISSUE TITLE
results display issue in outline search in some cases

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#748]
it seems to be happening solely in the Taisho outline, but 

https://library.bdrc.io/show/bdr:MW0TT0000?osearch=%22%E9%95%B7%E9%98%BF%E5%90%AB%E7%B6%93%22@zh-hant

displays all the sibling of the only search results and its ancestors, but the query seems ok:

https://ldspdi.bdrc.io/query/graph/Outline_search?LG_NAME=zh-hant&R_RES=bdr%3AMW0TT0000&L_NAME=%22%E9%95%B7%E9%98%BF%E5%90%AB%E7%B6%93%22

![Capture d’écran de 2022-08-29 12-37-46](https://user-images.githubusercontent.com/60868/187183065-ecfedcb6-5604-468c-ac55-740265458f86.png)

**Comment by berger-n** [comment]
seems better now: http://library-dev.bdrc.io/show/bdr:MW0TT0000?uilang=en&osearch=%22%E9%95%B7%E9%98%BF%E5%90%AB%E7%B6%93%22@zh-hant

![image](https://user-images.githubusercontent.com/33383857/187213738-4aba7f69-2c5a-4920-ba2a-75d981e8a464.png)
---

but something needs to be fixed on https://library.bdrc.io/show/bdr:MW22084
where outline looks empty though there's some data returned by query
(could it be related to recent changes you made? for now it's not clear to me what's happening)

![image](https://user-images.githubusercontent.com/33383857/187214879-dbbb242b-db7b-431c-9b2a-6b879ae03904.png)

**Comment by eroux** [comment]
ah yes, thanks! Let me look at that

**Comment by eroux** [comment]
fixed, thanks a lot!
