### ISSUE TITLE
display notes in outlines

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#749]
there are notes in some outlines, which are returned by the query, for instance

https://ldspdi.bdrc.io/query/graph/Outline_root_pervolume?R_RES=bdr%3AMW3CN27011&I_VNUM=20

in volume 20 of https://library.bdrc.io/show/bdr:MW3CN27011

let's display the note in the outline, or at least just the noteText for now

**Comment by berger-n** [comment]
done: http://library-dev.bdrc.io/show/bdr:MW3CN27011?part=bdr:MW3CN27011_L0026

![image](https://user-images.githubusercontent.com/33383857/187240038-bcdc1d94-eed7-4cf8-8e2c-98e9cc5dfdfb.png)

**Comment by eroux** [comment]
perfect, thanks!
