### ISSUE TITLE
BUDA sometimes not working for some users

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#752]
BUDA works in a new window or without cache, but we have some reports that it doesn't for regular users in their usual browsers. Perhaps it's due to some changes in the way localstorage is structured?

**Comment by eroux** [comment]
@berger-n do you think we could have a sort of version number in the data in localstorage, and when it doesn't match the js we just reinitialize it (logging out the users)?

**Comment by berger-n** [comment]
I'm afraid there's nothing new in localStorage at all...
actually version number is already stored there
(that's how the cache checking module works)

![image](https://user-images.githubusercontent.com/33383857/188590195-f6d7f35b-5e68-4fb1-867b-1c41c24df879.png)

![image](https://user-images.githubusercontent.com/33383857/188590290-fc82e27f-e85a-45be-af34-ba74d4bb7587.png)

**Comment by eroux** [comment]
hmm, ok.. maybe it's something in the user info ?

**Comment by berger-n** [comment]
without an error trace it's very difficult to know for sure...
what do users report? white screen? home screen but nothing happens?

**Comment by JannTibetan** [comment]
Here is a comment from help that may not be identical with the problem addresses in this issue but it's also happening now and so might be connected somehow:

_There also seem to be increasing problems with the text viewer; for
that item, the viewer is unstable, and sometimes shows pages at huge
(and thus useless) magnification. Reloading the web page occasionally
fixes the problem, but sometimes does not._

FWIW I have had this same experience recently on Safari.

**Comment by eroux** [comment]
I've never experiencee this one, can you take a screenshot next time it happens?

Nicolas made some good progress in improving our debugging capacity and I think the issue is solved but let's see, we'll be monitoring it today

**Comment by JannTibetan** [comment]
I was able to replicate the problem. It occurs when you open a volume scan > click on an image in order to call up the thumbnails > click on a thumbnail to generate the larger image of that particular page
<img width="1552" alt="Screen Shot 2022-09-09 at 8 27 44 AM" src="https://user-images.githubusercontent.com/44705185/189349771-60e897c3-6d30-410e-b792-0522ea6ca2d4.png">

**Comment by JannTibetan** [comment]
Is this related to the JSON resizing that was done a couple weeks ago?

**Comment by JannTibetan** [comment]
Video of the image viewer issue. Note the problem with the size and placement of the pages continues when one presses the "next page" button.
https://user-images.githubusercontent.com/44705185/189352728-8696acaf-5f9b-4386-9bad-00619b447545.mov

**Comment by JannTibetan** [comment]
Wonderful. Thanks for reverting to the flight my earlier version and for reporting this to the developers of the image viewer.

**Comment by berger-n** [comment]
finally turned out that the problem was not a bug here
but was rather caused by some default values for OSD configuration variables
(which seem to have recently changed)

restoring these values fixed the problem with current version of OSD: https://library.bdrc.io/show/bdr:W2EE2#open-viewer

**Comment by eroux** [comment]
Great job, thanks!!

**Comment by JannTibetan** [comment]
Bravo, thanks!
