### ISSUE TITLE
keyword with quote or parenthesis makes search fail

### ISSUE THREAD

**Issue by berger-n** [buda-base/public-digital-library#756]
search fails when using quote or an unclosed parenthesis:
- https://library.bdrc.io/search?q=%22bcom%20ldan%20%27das%20kyis%20ring%22%22~1&lg=bo-x-ewts&t=Etext
- https://library.bdrc.io/search?q=%22bka%27%20%27gyur%20(sde%20dge%22~1&lg=bo-x-ewts&t=Version

**Comment by berger-n** [comment]
RegExp related but with keyword in Unicode: [url](https://library.bdrc.io/search?q=%22%E0%BD%A6%E0%BE%90%E0%BE%B1%E0%BD%96%E0%BD%A6%E0%BC%8B%E0%BD%98%E0%BD%82%E0%BD%BC%E0%BD%93%E0%BC%8B%E0%BD%90%E0%BD%98%E0%BD%A6%E0%BC%8B%E0%BD%85%E0%BD%91%E0%BC%8B%E0%BD%98%E0%BD%81%E0%BE%B1%E0%BD%BA%E0%BD%93%E0%BC%8B%E0%BD%94%E0%BC%8B%E0%BD%96%E0%BE%B3%E0%BD%BC%E0%BC%8B%E0%BD%96%E0%BD%9F%E0%BD%84%E0%BC%8B%E0%BD%90%E0%BD%B4%E0%BD%96%E0%BC%8B%E0%BD%96%E0%BD%A6%E0%BE%9F%E0%BD%93%E0%BC%8B%E0%BD%86%E0%BD%BC%E0%BD%A6%E0%BC%8B%E0%BD%80%E0%BE%B1%E0%BD%B2%E0%BC%8B%E0%BD%89%E0%BD%B2%E0%BC%8B%E0%BD%98%E0%BC%8B%E0%BD%91%E0%BD%82%E0%BD%BA%E0%BC%8B%E0%BD%A3%E0%BD%BA%E0%BD%82%E0%BD%A6%E0%BC%8B%E0%BD%A2%E0%BE%A3%E0%BD%98%E0%BC%8B%E0%BD%A2%E0%BE%92%E0%BE%B1%E0%BD%A3%E0%BC%8B%E0%BD%91%E0%BD%94%E0%BD%A3%E0%BC%8B%E0%BD%96%E0%BD%9F%E0%BD%84%E0%BC%8B%E0%BD%94%E0%BD%BC%E0%BD%A0%E0%BD%B2%E0%BC%8B%E0%BD%9E%E0%BD%A3%E0%BC%8B%E0%BD%A6%E0%BE%94%E0%BC%8B%E0%BD%93%E0%BD%A6%E0%BC%8B%E0%BD%80%E0%BE%B1%E0%BD%B2%E0%BC%8B%E0%BD%90%E0%BD%B4%E0%BD%93%E0%BC%8B%E0%BD%98%E0%BD%BC%E0%BD%84%E0%BC%8B%E0%BD%96%E0%BD%A0%E0%BD%B2%E0%BC%8B%E0%BD%A2%E0%BE%A3%E0%BD%98%E0%BC%8B%E0%BD%94%E0%BD%A2%E0%BC%8B%E0%BD%90%E0%BD%A2%E0%BC%8B%E0%BD%94%E0%BC%8B%E0%BD%A2%E0%BD%B2%E0%BD%93%E0%BC%8B%E0%BD%86%E0%BD%BA%E0%BD%93%E0%BC%8B%E0%BD%91%E0%BD%96%E0%BD%84%E0%BC%8B%E0%BD%82%E0%BD%B2%E0%BC%8B%E0%BD%A2%E0%BE%92%E0%BE%B1%E0%BD%A3%E0%BC%8B%E0%BD%94%E0%BD%BC%E0%BD%A0%E0%BD%B2%E0%BC%8B%E0%BD%A0%E0%BD%95%E0%BE%B2%E0%BD%BA%E0%BD%84%E0%BC%8B%E0%BD%96%20%E0%BC%BC%22~1&lg=bo&t=Instance&f=asset,inc,tmp:possibleAccess&f=asset,inc,tmp:catalogOnly)

**Comment by berger-n** [comment]
fixed:
- https://library.bdrc.io/search?q=%22bcom%20ldan%20%27das%20kyis%20ring%22~1&lg=bo-x-ewts&t=Etext
- https://library.bdrc.io/search?q=%22bka%27%20%27gyur%20(sde%20dge%22~1&lg=bo-x-ewts&t=Instance
- [link](https://library.bdrc.io/search?q=%22%E0%BD%A6%E0%BE%90%E0%BE%B1%E0%BD%96%E0%BD%A6%E0%BC%8B%E0%BD%98%E0%BD%82%E0%BD%BC%E0%BD%93%E0%BC%8B%E0%BD%90%E0%BD%98%E0%BD%A6%E0%BC%8B%E0%BD%85%E0%BD%91%E0%BC%8B%E0%BD%98%E0%BD%81%E0%BE%B1%E0%BD%BA%E0%BD%93%E0%BC%8B%E0%BD%94%E0%BC%8B%E0%BD%96%E0%BE%B3%E0%BD%BC%E0%BC%8B%E0%BD%96%E0%BD%9F%E0%BD%84%E0%BC%8B%E0%BD%90%E0%BD%B4%E0%BD%96%E0%BC%8B%E0%BD%96%E0%BD%A6%E0%BE%9F%E0%BD%93%E0%BC%8B%E0%BD%86%E0%BD%BC%E0%BD%A6%E0%BC%8B%E0%BD%80%E0%BE%B1%E0%BD%B2%E0%BC%8B%E0%BD%89%E0%BD%B2%E0%BC%8B%E0%BD%98%E0%BC%8B%E0%BD%91%E0%BD%82%E0%BD%BA%E0%BC%8B%E0%BD%A3%E0%BD%BA%E0%BD%82%E0%BD%A6%E0%BC%8B%E0%BD%A2%E0%BE%A3%E0%BD%98%E0%BC%8B%E0%BD%A2%E0%BE%92%E0%BE%B1%E0%BD%A3%E0%BC%8B%E0%BD%91%E0%BD%94%E0%BD%A3%E0%BC%8B%E0%BD%96%E0%BD%9F%E0%BD%84%E0%BC%8B%E0%BD%94%E0%BD%BC%E0%BD%A0%E0%BD%B2%E0%BC%8B%E0%BD%9E%E0%BD%A3%E0%BC%8B%E0%BD%A6%E0%BE%94%E0%BC%8B%E0%BD%93%E0%BD%A6%E0%BC%8B%E0%BD%80%E0%BE%B1%E0%BD%B2%E0%BC%8B%E0%BD%90%E0%BD%B4%E0%BD%93%E0%BC%8B%E0%BD%98%E0%BD%BC%E0%BD%84%E0%BC%8B%E0%BD%96%E0%BD%A0%E0%BD%B2%E0%BC%8B%E0%BD%A2%E0%BE%A3%E0%BD%98%E0%BC%8B%E0%BD%94%E0%BD%A2%E0%BC%8B%E0%BD%90%E0%BD%A2%E0%BC%8B%E0%BD%94%E0%BC%8B%E0%BD%A2%E0%BD%B2%E0%BD%93%E0%BC%8B%E0%BD%86%E0%BD%BA%E0%BD%93%E0%BC%8B%E0%BD%91%E0%BD%96%E0%BD%84%E0%BC%8B%E0%BD%82%E0%BD%B2%E0%BC%8B%E0%BD%A2%E0%BE%92%E0%BE%B1%E0%BD%A3%E0%BC%8B%E0%BD%94%E0%BD%BC%E0%BD%A0%E0%BD%B2%E0%BC%8B%E0%BD%A0%E0%BD%95%E0%BE%B2%E0%BD%BA%E0%BD%84%E0%BC%8B%E0%BD%96%20%E0%BC%BC%22~1&lg=bo&t=Instance&f=asset,inc,tmp:possibleAccess&f=asset,inc,tmp:catalogOnly)

**Comment by berger-n** [comment]
same (parenthesis in keyword) https://library.bdrc.io/search?q=%22%E0%BD%91%E0%BD%BA%E0%BC%8B%E0%BD%93%E0%BD%A6%E0%BC%8B%E0%BD%A1%E0%BD%84%E0%BC%8B%E0%BD%96%E0%BE%B7%E0%BC%8B%E0%BD%96%E0%BE%B2%E0%BD%BC%E0%BD%98%20(%E0%BD%A0%E0%BD%96%E0%BD%A0%E0%BC%8B%E0%BD%A2%E0%BD%BC%E0%BD%98)%E0%BD%91%E0%BD%B4%E0%BC%8B%E0%BD%96%E0%BE%B1%E0%BD%BC%E0%BD%93%E0%BC%8D%22~1&lg=bo&t=Etext

**Comment by berger-n** [comment]
related https://library.bdrc.io/search?q=%22%E0%BD%91ul%20ba%20rnam%20par%20%27byed%20pa%22~1&lg=bo&t=Instance&f=asset,inc,tmp:possibleAccess&f=asset,inc,tmp:catalogOnly

BTW we should add an error message "something went wrong with your query, please try another one"

**Comment by berger-n** [comment]
> BTW we should add an error message "something went wrong with your query, please try another one"

done: https://library.bdrc.io/search?q=%22%E0%BD%91ul%20ba%20rnam%20par%20%27byed%20pa%22~1&lg=bo&t=Instance&f=asset,inc,tmp:possibleAccess&f=asset,inc,tmp:catalogOnly

![image](https://user-images.githubusercontent.com/33383857/190161895-c03aa185-77e6-431d-873d-9e3c8464adc9.png)

**Comment by berger-n** [comment]
fixed:
- https://library.bdrc.io/search?q=%22%E0%BD%91%E0%BD%BA%E0%BC%8B%E0%BD%93%E0%BD%A6%E0%BC%8B%E0%BD%A1%E0%BD%84%E0%BC%8B%E0%BD%96%E0%BE%B7%E0%BC%8B%E0%BD%96%E0%BE%B2%E0%BD%BC%E0%BD%98%20(%E0%BD%A0%E0%BD%96%E0%BD%A0%E0%BC%8B%E0%BD%A2%E0%BD%BC%E0%BD%98)%E0%BD%91%E0%BD%B4%E0%BC%8B%E0%BD%96%E0%BE%B1%E0%BD%BC%E0%BD%93%E0%BC%8D%22~1&lg=bo&t=Etext
- https://library.bdrc.io/search?q=%22%E0%BD%91ul%20ba%20rnam%20par%20%27byed%20pa%22~1&lg=bo&t=Instance&f=asset,inc,tmp:possibleAccess&f=asset,inc,tmp:catalogOnly

including the one in previous message, so see https://library.bdrc.io/search?q=%22test%22&lg=bo-x&t=Instance&f=asset,inc,tmp:possibleAccess&f=asset,inc,tmp:catalogOnly&s=closest%20matches%20forced for an example of error message (manually changed lg=bo-x-ewts to lg=bo-x-)

**Comment by berger-n** [comment]
- same here (search in English) https://library.bdrc.io/search?q=%22124)_khro%22&lg=en&t=Instance&f=asset,inc,tmp:possibleAccess&f=asset,inc,tmp:catalogOnly
- more character escaping needed here https://library.bdrc.io/search?q=%22%5Bdus%20%20rabs%20%20bdun%20%20pa%20nas%20%20%7C%20%20dus%20%20rabs%20%20bcu%20bdun%20pa%27i%20%20bar%20%20rgya%20%20gar%20%20gyi%20%20pandi%20%20ta%22&lg=en&t=Instance&f=asset,inc,tmp:possibleAccess&f=asset,inc,tmp:catalogOnly

**Comment by berger-n** [comment]
done:
- https://library.bdrc.io/search?q=%22124)_khro%22&lg=en&t=Instance&f=asset,inc,tmp:possibleAccess&f=asset,inc,tmp:catalogOnly&s=closest%20matches%20forced
- https://library.bdrc.io/search?q=%22%5Bdus%20%20rabs%20%20bdun%20%20pa%20nas%20%20%7C%20%20dus%20%20rabs%20%20bcu%20bdun%20pa%27i%20%20bar%20%20rgya%20%20gar%20%20gyi%20%20pandi%20%20ta%22&lg=en&t=Instance&f=asset,inc,tmp:possibleAccess&f=asset,inc,tmp:catalogOnly&s=closest%20matches%20forced

BTW @eroux we could improve things a bit, wdyt:
- don't take brackets etc. into account in language detection (none of keywords above should be detected as English)
- remove brackets etc. when sending query to ldspdi (here there are results: https://library.bdrc.io/search?q=%22dus%20%20rabs%20%20bdun%20%20pa%20nas%20%20%20%20dus%20%20rabs%20%20bcu%20bdun%20pa%27i%20%20bar%20%20rgya%20%20gar%20%20gyi%20%20pandi%20%20ta%22~1&lg=bo-x-ewts&t=Instance&f=asset,inc,tmp:possibleAccess&f=asset,inc,tmp:catalogOnly)

**Comment by eroux** [comment]
thanks for improving that, it's very important that the app doesn't crash on this kind of relatively trivial things!

You're right, let's not take punctuation and symbols into account in language detection

In theory it should all the best same for ldspdi though... do you have some example queries that give different results with / without parenthesis?

**Comment by berger-n** [comment]
> In theory it should all the best same for ldspdi though... do you have some example queries that give different results with / without parenthesis?

this particular case made me think so:
- [\[dus  rabs  bdun  pa nas  |  dus  rabs  bcu bdun pa'i  bar  rgya  gar  gyi  pandi  ta](https://ldspdi.bdrc.io/lib/instanceFacetGraph?LG_NAME=bo-x-ewts&L_NAME=%22%5Bdus%20%20rabs%20%20bdun%20%20pa%20nas%20%20%7C%20%20dus%20%20rabs%20%20bcu%20bdun%20pa%27i%20%20bar%20%20rgya%20%20gar%20%20gyi%20%20pandi%20%20ta%22) has no result
- [dus  rabs  bdun  pa nas  dus  rabs  bcu bdun pa'i  bar  rgya  gar  gyi  pandi  ta](https://ldspdi.bdrc.io/lib/instanceFacetGraph?LG_NAME=bo-x-ewts&L_NAME=%22dus%20%20rabs%20%20bdun%20%20pa%20nas%20%20%20%20dus%20%20rabs%20%20bcu%20bdun%20pa%27i%20%20bar%20%20rgya%20%20gar%20%20gyi%20%20pandi%20%20ta%22~1) has 4 results

**Comment by eroux** [comment]
Oh I see, in that case that's because of the `[` in ewts... ok, let's remove brackets then

**Comment by berger-n** [comment]
all done:
- https://library.bdrc.io/search?q=%22124)_khro%22~1&lg=bo-x-ewts&t=Etext
- https://library.bdrc.io/search?q=%22[dus%20%20rabs%20%20bdun%20%20pa%20nas%20%20|%20%20dus%20%20rabs%20%20bcu%20bdun%20pa%27i%20%20bar%20%20rgya%20%20gar%20%20gyi%20%20pandi%20%20ta%22~1&lg=bo-x-ewts&t=Instance&f=asset,inc,tmp:possibleAccess&f=asset,inc,tmp:catalogOnly&s=closest%20matches%20forced
- https://library.bdrc.io/show/bdr:UTIE0OPP000801_v007?startChar=365107&keyword=%22%E0%BD%91%E0%BD%BA%E0%BC%8B%E0%BD%93%E0%BD%A6%E0%BC%8B%E0%BD%A1%E0%BD%84%E0%BC%8B%E0%BD%96%E0%BE%B7%E0%BC%8B%E0%BD%96%E0%BE%B2%E0%BD%BC%E0%BD%98%20(%E0%BD%A0%E0%BD%96%E0%BD%A0%E0%BC%8B%E0%BD%A2%E0%BD%BC%E0%BD%98)%E0%BD%91%E0%BD%B4%E0%BC%8B%E0%BD%96%E0%BE%B1%E0%BD%BC%E0%BD%93%E0%BC%8D%22~1@bo#open-viewer
