### ISSUE TITLE
crash / Maximum update depth exceeded

### ISSUE THREAD

**Issue by berger-n** [buda-base/public-digital-library#759]
see https://library.bdrc.io/show/bdr:MW27401?part=bdr:MW27401_BE042D

**Comment by berger-n** [comment]
same here https://library.bdrc.io/show/bdr:MW1PD83972?part=bdr:MW1PD83972_5F6968&s=q%3D%2522%25E0%25BD%2596%25E0%25BC%258B%25E0%25BD%2598%25E0%25BD%2581%25E0%25BD%25A3%25E0%25BC%258B%25E0%25BD%25A6%25E0%25BE%25A8%25E0%25BD%25B4%25E0%25BD%2
582%25E0%25BC%258B%25E0%25BD%2594%25E0%25BD%25BC%2522~1%26lg%3Dbo%26t%3DInstance%26f%3Dasset%2Cinc%2Ctmp%3ApossibleAccess%26f%3Dasset%2Cinc%2Ctmp%3AcatalogOnly%26n%3D3#open-viewer

**Comment by berger-n** [comment]
same https://library.bdrc.io/show/bdr:MW22022?part=bdr:MW22022_2DF609&s=q%3D%2522%25E0%25BD%25A2%25E0%25BD%2584%25E0%25BC%258B%25E0%25BD%2596%25E0%25BE%25B1%25E0%25BD%25B4%25E0%25BD%2584%25E0%25BC%258B%25E0%25BD%25A2%25E0%25BE%25A1%25E0%25BD%25BC%25E0%25BC%258B%25E0%25BD%25A2%25E0%25BE%2597%25E0%25BD%25BA%25E0%25BC%258B%25E0%25BD%25A3%25E0%25BC%258B%2522~1%26lg%3Dbo%26t%3DInstance%26f%3Dasset%2Cinc%2Ctmp%3ApossibleAccess%26f%3Dasset%2Cinc%2Ctmp%3AcatalogOnly%26n%3D8"

**Comment by berger-n** [comment]
fixed the infinite loop:
https://library.bdrc.io/show/bdr:MW27401?part=bdr:MW27401_BE042D
https://library.bdrc.io/show/bdr:MW1PD83972?part=bdr:MW1PD83972_5F6968
https://library.bdrc.io/show/bdr:MW22022?part=bdr:MW22022_2DF609

but it was caused by data that is still missing in `Outline_root_pervolume` query:

1. open https://library.bdrc.io/show/bdr:MW22022 (resp. https://library.bdrc.io/show/bdr:MW0TT0000)
2. click first section, *gzhung yig* (resp. fourth section, *法華部類*) -- both have only one virtual volume than loads automatically
3. compare data returned by both queries:
- https://ldspdi.bdrc.io/query/graph/Outline_root_pervolume?R_RES=bdr%3AMW0TS004&I_VNUM=9 has `contentLocation` etc. and all subnodes of `MW0TS004` that are in volume 9
- https://ldspdi.bdrc.io/query/graph/Outline_root_pervolume?R_RES=bdr%3AMW22022_F89510&I_VNUM=1 has not

**Comment by eroux** [comment]
great, thanks! I think it's important to fix that kind of bug in the client to make it more robust so let's close this issue, can you open one with your latest comment on lds-queries?

**Comment by berger-n** [comment]
could be related, same error when opening second section: https://library.bdrc.io/show/bdr:MW2PD17098

**Comment by berger-n** [comment]
exact same here  https://library.bdrc.io/show/bdr:MW4CZ5369

**Comment by berger-n** [comment]
fixed: 
- https://library.bdrc.io/show/bdr:MW2PD17098
- https://library.bdrc.io/show/bdr:MW4CZ5369
