### ISSUE TITLE
crash on resource page

### ISSUE THREAD

**Issue by berger-n** [buda-base/public-digital-library#761]
see https://library.bdrc.io/show/bdr:MW0SBBPPN3308097257

**Comment by berger-n** [comment]
not a crash but resource page not loading properly: https://library.bdrc.io/show/bdr:P2JM169

**Comment by berger-n** [comment]
> not a crash but resource page not loading properly: https://library.bdrc.io/show/bdr:P2JM169

same https://library.bdrc.io/show/bdr:P4CZ15237

**Comment by eroux** [comment]
ah, that's great, thanks a lot!
