### ISSUE TITLE
return resource when searching permalink

### ISSUE THREAD

**Issue by berger-n** [buda-base/public-digital-library#765]
seen in logs: https://library.bdrc.io/search?p=%22http://purl.bdrc.io/resource/MW23828_68E9A5%22

**Comment by berger-n** [comment]
now https://library.bdrc.io/search?p=%22http://purl.bdrc.io/resource/MW23828_68E9A5%22 redirects to https://library.bdrc.io/show/bdr:MW23828_68E9A5

also when you type a permalink as keyword it is first shortened so it works as usual:

![simplescreenrecorder-2022-09-15_13 34 32 mkv](https://user-images.githubusercontent.com/33383857/190394127-73f1e104-271a-4208-889b-e77bd1f16e0c.gif)

**Comment by eroux** [comment]
thanks, that's great! I'm a bit scared that the automatic translation to `bdr:` in the input field might confuse users though

**Comment by berger-n** [comment]
ok! let's keep the permalink url: https://library.bdrc.io/

![image](https://user-images.githubusercontent.com/33383857/190398435-5ed65720-4aa2-46b4-baff-769a86eee5fb.png)

**Comment by eroux** [comment]
perfect, thanks!
