### ISSUE TITLE
BUDA database seems to be down. "There was an error processing your search" 

### ISSUE THREAD

**Issue by JannTibetan** [buda-base/public-digital-library#769]
Starting about 3 minutes ago (3:30pm Eastern) BUDA is pretty much down. Please look into this ASAP. 

<img width="834" alt="Screen Shot 2022-09-16 at 4 02 30 PM" src="https://user-images.githubusercontent.com/44705185/190724555-da41b975-b9a9-49e2-8487-8806931df35f.png">

<img width="874" alt="Screen Shot 2022-09-16 at 4 07 39 PM" src="https://user-images.githubusercontent.com/44705185/190724553-152c1a8e-c7e9-472d-8536-6bc3d2297b8d.png">

**Comment by eroux** [comment]
it's back online, sorry for the delay

**Comment by JannTibetan** [comment]
This problem seems to be happening again. I just received a message about it and confirmed it for myself.
The search box is just unresponsive. It doesn't get hung up on a search or return an error message.
Thanks for attending to this as soon as you can.

**Comment by eroux** [comment]
it's back again. I don't know what's going on sorry about that

**Comment by JannTibetan** [comment]
That's alright. Thanks for restoring it right away.
