### ISSUE TITLE
adjustments needed on buda4

### ISSUE THREAD

**Issue by berger-n** [buda-base/public-digital-library#771]
- [x] handle dates (use `eventWhen` instead of `onYear`, `notBefore`, `notAfter`)
  see http://library-dev.bdrc.io/search?q=%22dalai%20lama%22&lg=en&t=Person&s=year%20of%20birth) 

- [x] remove call to `etext_refs` from http://library-dev.bdrc.io/show/bdr:UTIE0OPI4D44D73F_I1KG16930

- [x] ~~check images not displayed in etext viewer for http://library-dev.bdrc.io/show/bdr:UTIE0OPI4D44D73F_I1KG16930?backToEtext=bdr:IE0OPI4D44D73F#open-viewer~~

- [x] fix title missing in outline on http://library-dev.bdrc.io/show/bdr:IE0OPI4D44D73F

note that last two may be caused by something missing in data: http://ldspdi-dev.bdrc.io/resource/IE0OPI4D44D73F.ttl
`instanceReproductionOf` has no instance only scans
(compare with https://ldspdi.bdrc.io/resource/IE0OPP000641.ttl )

**Comment by berger-n** [comment]
done for the first one:  http://library-dev.bdrc.io/search?q=%22dalai%20lama%22&lg=en&t=Person&s=year%20of%20birth

![image](https://user-images.githubusercontent.com/33383857/192003146-59ebe56f-25d8-4cdc-b20a-0340e194f6ca.png)
---

fixes were needed on resource page as well but now it's fine: http://library-dev.bdrc.io/show/bdr:P352?s=q%3D%2522dalai%2520lama%2522%26lg%3Den%26t%3DPerson%26s%3Dyear%2520of%2520birth%26n%3D6

![image](https://user-images.githubusercontent.com/33383857/192001731-eeea28dd-34ed-465e-af0f-1595d4f798a7.png)
---
noted some invalid `eventWhen` values (not sure if they're generated or not?):
- `18XX?` in http://ldspdi-dev.bdrc.io/resource/P348.ttl
  would work if written `18?` according to editor.bdrc.io
- `1762?1772` in https://ldspdi-dev.bdrc.io/resource/P4798.ttl
  already there in https://ldspdi.bdrc.io/resource/P4798.ttl

**Comment by eroux** [comment]
oh, I'm a bit surprised about `18XX?` not being valid, that's a bit annoying... but I can change that in the migration, thanks for spotting it!

`1762?1772` is already on https://legacy.tbrc.org/xmldoc?rid=P348 , it's part of the dates that cannot be parsed

**Comment by berger-n** [comment]
no more call to `etextrefs`  from here: http://library-dev.bdrc.io/show/bdr:UTIE0OPI4D44D73F_I1KG16930

I've also seen that images are now visible here, thanks: http://library-dev.bdrc.io/show/bdr:UTIE0OPI4D44D73F_I1KG16930?backToEtext=bdr:IE0OPI4D44D73F#open-viewer

---

regarding etext search, a look at https://library-dev.bdrc.io/search?q=%22spyod%20%27jug%22~1&lg=bo-x-ewts&t=Etext makes me think some data (regarding matching chunks) is missing from query http://ldspdi-dev.bdrc.io/lib/etextContentFacetGraph?LG_NAME=bo-x-ewts&L_NAME=%22spyod%20%27jug%22~1

![image](https://user-images.githubusercontent.com/33383857/192282980-45ca8b4b-8b1f-4808-b1a6-047ac95e6252.png)

**Comment by berger-n** [comment]
`18XX?` is now fine, see P4798:
- https://library-dev.bdrc.io/search?q=%22dalai%20lama%22&lg=en&t=Person&s=year%20of%20birth&pg=4&n=177
- https://library-dev.bdrc.io/show/bdr:P4798?s=q%3D%2522dalai%2520lama%2522%26lg%3Den%26t%3DPerson%26s%3Dyear%2520of%2520birth%26pg%3D4%26n%3D177

---
- [ ] shouldn't there be a question mark though? I guess so...

![image](https://user-images.githubusercontent.com/33383857/192540877-bc3bf09b-3b43-46e5-b99c-a0e7e4bcbb8f.png)
---

![image](https://user-images.githubusercontent.com/33383857/192540946-584f131c-60ec-4305-a517-2621526059d4.png)

---

- [ ] something wrong with results display here: http://library-dev.bdrc.io/search?q=%22spyod%20%27jug%22~1&lg=bo-x-ewts&t=Etext&n=3

![image](https://user-images.githubusercontent.com/33383857/192541362-19af584f-130d-4a24-a7b4-339547a8ec77.png)
---

- [ ] images not displayed in this etext: http://library-dev.bdrc.io/show/bdr:UTIE0OPI606EBA1E_I2PD20829?startChar=213194&keyword=%22spyod%20%27jug%22~1@bo-x-ewts#open-viewer

**Comment by eroux** [comment]
yes, a question mark would be good

**Comment by eroux** [comment]
oh I think there's no need to remove the syriac characters in PDL, this is an issue in OpenPecha (it should be resolved soon)

the inferred triples (onYear, notBefore, etc.) are now back in https://ldspdi-dev.bdrc.io/lib/personGraph?LG_NAME=en&L_NAME=%22dalai%20lama%22

**Comment by berger-n** [comment]
> images not displayed in this etext: http://library-dev.bdrc.io/show/bdr:UTIE0OPI606EBA1E_I2PD20829?startChar=213194&keyword=%22spyod%20%27jug%22~1@bo-x-ewts#open-viewer

there is no `imageVolumeId` in query: http://ldspdi-dev.bdrc.io/query/graph/Etext_base?I_LIM=500&R_RES=bdr%3AUTIE0OPI606EBA1E_I2PD20829&format=jsonld 
(see for example https://ldspdi.bdrc.io/query/graph/Etext_base?I_LIM=500&R_RES=bdr%3AUTIE0OPP008270_v001&format=jsonld)

might be related, note that an etext was available from here: https://library.bdrc.io/show/bdr:MW2PD20781
no more here: https://library-dev.bdrc.io/show/bdr:MW2PD20781
could this be related to etext record now being withdrawn on `ldspdi-dev` ?


---

> some images displayed in etext then others not: https://library-dev.bdrc.io/show/bdr:UTIE0OPI805AF297_I2PD17979?startChar=524264&&keyword=%22spyod%20%27jug%22~1@bo-x-ewts#open-viewer

this etext has two volumes https://library-dev.bdrc.io/show/bdr:IE0OPI805AF297
but `Etext_base` query on volume 1 returns `imageVolumeId` for volume 2: https://ldspdi-dev.bdrc.io/query/graph/Etext_base?I_LIM=500&R_RES=bdr%3AUTIE0OPI805AF297_I2PD17979&format=jsonld
- images for volume 1: https://library.bdrc.io/show/bdr:I2PD17979
- images for volume 2: https://library.bdrc.io/show/bdr:I2PD17980

![image](https://user-images.githubusercontent.com/33383857/192748683-b2538802-984b-4361-be9d-94a8446559fb.png)
---

![image](https://user-images.githubusercontent.com/33383857/192748903-ead55d87-23ff-40d2-a4d1-6c129a028d10.png)

**Comment by eroux** [comment]
for the record, the issue is https://github.com/OpenPecha/Toolkit/commit/2f87e37537a60fdbdeba431b910c63a2ab7d8976

**Comment by berger-n** [comment]
- [ ] data for `inRootInstances` are missing in [query](https://ldspdi-dev.bdrc.io/lib/etextContentFacetGraph?LG_NAME=bo-x-ewts&L_NAME=%22spyod%20%27jug%22~1) here: https://library-dev.bdrc.io/search?q=%22spyod%20%27jug%22~1&lg=bo-x-ewts&t=Etext
 \+ some matching chunks are missing as well (see 2nd result, in `bdr:IE11577`)

- [ ] data for nodes like name, events are missing in [query](http://ldspdi-dev.bdrc.io/query/graph/ResInfo-SameAs?R_RES=bdr%3AP352&format=json) here: http://library-dev.bdrc.io/show/bdr:P352

**Comment by berger-n** [comment]
- [ ] titles are missing (both property in each result and corresponding node data) in [query](https://ldspdi-dev.bdrc.io/lib/associatedWorks?R_RES=bdr%3AP179&format=json) here: http://library-dev.bdrc.io/search?r=bdr:P179&t=Work
 \+ more data missing in [query](http://ldspdi-dev.bdrc.io/lib/workInstancesGraph?R_RES=bdr%3AWA0XLB61557640746&format=json) for each individual Has Versions as well (compare with [library](http://ldspdi.bdrc.io/lib/workInstancesGraph?R_RES=bdr%3AWA0XLB61557640746&format=json))

**Comment by berger-n** [comment]
- etext is empty: https://library-dev.bdrc.io/show/bdr:UTIE0OPI805AF297_I2PD17979?backToEtext=bdr:IE0OPI805AF297#open-viewer
 [query](https://ldspdi-dev.bdrc.io/lib/Chunks?R_RES=bdr%3AUTIE0OPI805AF297_I2PD17979&I_START=0&I_END=10000) returning `Nothing found (adminAbout)`)

**Comment by berger-n** [comment]
- [ ] thumbnails and titles (both property and nodes) are missing in [query](https://ldspdi-dev.bdrc.io/lib/instanceFacetGraph?LG_NAME=bo-x-ewts&L_NAME=%22dri%20med%20%27od%20zer%22~1) here: https://library-dev.bdrc.io/search?q=%22dri%20med%20%27od%20zer%22~1&lg=bo-x-ewts&t=Instance&f=asset,inc,tmp:possibleAccess&f=asset,inc,tmp:catalogOnly

**Comment by berger-n** [comment]
- [ ] handle case when multiple languages on same etext page: http://library-dev.bdrc.io/show/bdr:UTIE0OPI4D44D73F_I1KG16930?backToEtext=bdr:UTIE0OPI4D44D73F_I1KG16930#open-viewer

**Comment by berger-n** [comment]
- [ ] query to user profile *sometimes* returns an default empty profile with name only

**Comment by berger-n** [comment]
done: http://library-dev.bdrc.io/show/bdr:UTIE0OPI4D44D73F_I1KG16930?backToEtext=bdr:UTIE0OPI4D44D73F_I1KG16930#open-viewer

![image](https://user-images.githubusercontent.com/33383857/193091979-09917b62-bac7-42fd-999e-02246896c686.png)
---

> query to user profile sometimes returns an default empty profile with name only [and a new id]

actually it seems to happen only on localhost
on library-dev everything's fine

**Comment by berger-n** [comment]
>  query to user profile ~~sometimes~~ returns an default empty profile with name only [and a new id]
> > actually it seems to happen only on localhost
> > on ~~library-dev everything's fine~~

actually library-dev is still set to use editserv-dev

**Comment by berger-n** [comment]
- [ ] outline is missing on Taisho record: https://library.bdrc.io/show/bdr:MW0TT0000?tabs=bdr:W0TT0000
 ([query](https://purl.bdrc.io/query/graph/Outline_root?R_RES=bdr%3AMW0TT0000) seems quite empty indeed)

**Comment by eroux** [comment]
outline is back!
