### ISSUE TITLE
redirection of etext pagesof openpecha

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#772]
pages like

https://library.bdrc.io/show/bdr:UTIE0OPP004139_v003

don't load anymore after OpenPecha's wonderful idea to change all the IDs (ccing @ngawangtrinley for no reason). The pages like https://library.bdrc.io/show/bdr:IE0OPP004139 are though.

Ideally, the redirection could take place using the following method:
- `UTIE0OPP004139_v003` = `UT` + `IE0OPP004139`   +   `v003`
-  `IE0OPP004139` is redirected into `IE0OPIA1BB940F`
- `IE0OPIA1BB940F` is a reproduction of `W28809`
- `v003` means `volume 3`
- volume 3 of `W28809` is `I4810`
- the id to redirect to is `UT`+ `IE0OPIA1BB940F` + `_` + `I4810` = `UTIE0OPIA1BB940F_I4810` -> https://library.bdrc.io/show/bdr:UTIE0OPIA1BB940F_I4810

I'm not sure how best to do that, but I can try to add that in the query

**Comment by eroux** [comment]
it's now in the query: https://ldspdi-dev.bdrc.io/query/graph/Etext_base?I_LIM=500&R_RES=bdr%3AUTIE0OPP004139_v003&format=json

**Comment by eroux** [comment]
https://library.bdrc.io/show/bdr:UTIE0OPP004139_v003?startChar=874969&keyword=%22%E0%BD%99%E0%BC%8B%E0%BD%A3%E0%BD%BA%E0%BC%8B%E0%BD%99%E0%BC%8B%E0%BD%A3%E0%BD%BA%E0%BC%8D%20%E0%BD%96%E0%BD%A6%E0%BE%90%E0%BE%B1%E0%BD%BC%E0%BD%91%
E0%BC%8B%E0%BD%85%E0%BD%B2%E0%BD%82%E0%BC%8B%E0%BD%96%E0%BD%A6%E0%BE%90%E0%BE%B1%E0%BD%BC%E0%BD%91%E0%BC%8B%E0%BD%85%E0%BD%B2%E0%BD%82%22~1@bo#open-viewer

now redirects to

https://library.bdrc.io/show/bdr:UTIE0OPIA1BB940F_I4810?startChar=874969&keyword=%22%E0%BD%99%E0%BC%8B%E0%BD%A3%E0%BD%BA%E0%BC%8B%E0%BD%99%E0%BC%8B%E0%BD%A3%E0%BD%BA%E0%BC%8D%20%E0%BD%96%E0%BD%A6%E0%BE%90%E0%BE%B1%E0%BD%BC%E0%BD%91%E0%BC%8B%E0%BD%85%E0%BD%B2%E0%BD%82%E0%BC%8B%E0%BD%96%E0%BD%A6%E0%BE%90%E0%BE%B1%E0%BD%BC%E0%BD%91%E0%BC%8B%E0%BD%85%E0%BD%B2%E0%BD%82%22~1@bo

which is almost perfect, only the `#open-viewer` part is missing

**Comment by berger-n** [comment]
done: https://library.bdrc.io/show/bdr:UTIE0OPP004139_v003?startChar=874969&keyword=%22%E0%BD%99%E0%BC%8B%E0%BD%A3%E0%BD%BA%E0%BC%8B%E0%BD%99%E0%BC%8B%E0%BD%A3%E0%BD%BA%E0%BC%8D%20%E0%BD%96%E0%BD%A6%E0%BE%90%E0%BE%B1%E0%BD%BC%E0%BD%91%E0%BC%8B%E0%BD%85%E0%BD%B2%E0%BD%82%E0%BC%8B%E0%BD%96%E0%BD%A6%E0%BE%90%E0%BE%B1%E0%BD%BC%E0%BD%91%E0%BC%8B%E0%BD%85%E0%BD%B2%E0%BD%82%22~1@bo#open-viewer

**Comment by eroux** [comment]
wonderful, thanks!

**Comment by berger-n** [comment]
found these 404 in logs today:
- https://library.bdrc.io/show/bdr:UTIE0OPP007010_v005 
- https://library.bdrc.io/show/bdr:IE0OPP002904
- even an etext volume https://library.bdrc.io/show/bdr:VLIE0OPP003241_v003

@eroux is there a chance everything's not redirected here? or are these users' wrong inputs ?

**Comment by berger-n** [comment]
could be related?
- https://library.bdrc.io/show/bdr:WA0XL4E0AAE76528D

**Comment by eroux** [comment]
there are a few etexts that are not currently redirected, we can live with that, that should be around 5% and they'll work later on. Some WA0XL works disappeared because of improvements in the work / version grouping. BTW, I've wanted to report this for a long time, but we shouldn't provide permalinks for these, and perhaps we should add a warning note that the IDs may change in the future
