### ISSUE TITLE
"manifest is empty" on W1GS11

### ISSUE THREAD

**Issue by berger-n** [buda-base/public-digital-library#773]
see https://iiifpres-dev.bdrc.io/vo:bdr:I1KG80359/manifest
from https://library.bdrc.io/show/bdr:W1GS11
not sure what's happening there @eroux ? 
anyway there should be a message displayed

**Comment by eroux** [comment]
the issue behind this one is https://github.com/buda-base/archive-ops/issues/775 , what's happening is that there's no images, nothing special. Yes, let's add a message that there are no images in that case (it's quite strange, in other cases it's present)

**Comment by berger-n** [comment]
ok thanks! fixed: https://library.bdrc.io/show/bdr:W1GS11

**Comment by eroux** [comment]
perfect, thanks!
