### ISSUE TITLE
two new "static" queries

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#774]
https://ldspdi.bdrc.io/lib/allCollections

and 

https://ldspdi.bdrc.io/lib/femaleAuthorsGraph

are two queries that give regular search results but don't take any argument. There should be a corresponding URL for each on BUDA. Currently there wouldn't be any link to these pages but we'll add some later

**Comment by berger-n** [comment]
done: 
- https://library-dev.bdrc.io/all-collections
 
![image](https://user-images.githubusercontent.com/33383857/195343413-5b22b3a3-ee30-4780-be98-0bbee57c250e.png)
---

- https://library-dev.bdrc.io/female-authors

![image](https://user-images.githubusercontent.com/33383857/195343733-92bee5a7-b2a6-4b5d-82df-65b5e6ed05ec.png)
---

**Comment by eroux** [comment]
wonderful, thanks! Is it possible to add `tmp:nbMembers` and `tmp:nbParts` to the display of the collections? Also, can you add a route for future `worksByFemaleAuthors` and `instancesByFemaleAuthors` ? I'll write the query later

**Comment by berger-n** [comment]
done: 
- https://library-dev.bdrc.io/all-collections
  
  ![image](https://user-images.githubusercontent.com/33383857/195549124-ba557b45-93f2-4e4d-9803-d8e9db1515e7.png)
  
  - note that `nbParts` is most often 0 in [query](https://ldspdi-dev.bdrc.io/lib/allCollections?format=json)
and when it's not I'm not sure what to be expected, for example here (`nbParts:2`): https://library-dev.bdrc.io/show/bdr:PR0GN1001?s=all-collections%3Ft%3DProduct%26s%3Dtitle%2520forced%26n%3D30
  - is it normal for some collections not to have a `nbMembers`?

---

- other new routes ready:
  https://library-dev.bdrc.io/instances-by-female-authors
  https://library-dev.bdrc.io/works-by-female-authors
  
  ![image](https://user-images.githubusercontent.com/33383857/195549685-a5b5036b-0224-450a-98dd-f43f38d7e15d.png)
  
  - any new static route can now be added here (with corresponding query & expected return type) and that should be it:
https://github.com/buda-base/public-digital-library/blob/e7952c52780339d86e47bc1741cfc025f6729a57/src/lib/api.js#L90-L95
