### ISSUE TITLE
duplicate "parallels in" display in case of sameas

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#775]
in https://library.bdrc.io/show/bdr:WA4CZ16799 I see a spurious entry in the values of the "parallels in" property

![Capture d’écran de 2022-10-20 18-34-16](https://user-images.githubusercontent.com/60868/197007122-47b38da2-ecaf-46b1-86fc-2745f87b5aa5.png)

the first one is a link to 84000: https://read.84000.co/translation/toh113.html

but the query only has 4 values:

https://ldspdi.bdrc.io/query/graph/ResInfo-SameAs?R_RES=bdr%3AWA4CZ16799&format=json

**Comment by berger-n** [comment]
not sure what's to do here? everything's looks fine (once a few css glitches are fixed):

![image](https://user-images.githubusercontent.com/33383857/197160332-fc04d195-90c6-4e94-96e0-e869b9b4324d.png)

as the extra value comes from a `workHasParallelsIn` in `eftr:WAITOH113`:

![image](https://user-images.githubusercontent.com/33383857/197160584-b4949868-fbe9-4916-a161-d372e8e11601.png)
---

and this 84000 record as no `sameAs` so it can only be displayed as is, as an external link:

![image](https://user-images.githubusercontent.com/33383857/197160863-7917feac-a682-48ac-b302-91ba0564c8db.png)

**Comment by eroux** [comment]
ah thanks, I'll have a look

**Comment by eroux** [comment]
ok that works, sorry for that!

**Comment by berger-n** [comment]
actually it was a good occasion to add missing SAT provider label on versions
and improve IAST line-breaking when there's some space in the label: https://library.bdrc.io/show/bdr:WA4CZ16799

![image](https://user-images.githubusercontent.com/33383857/197172702-3b2f2c78-3e48-4847-b458-c1ea6660c804.png)

**Comment by eroux** [comment]
great, thanks!

**Comment by eroux** [comment]
perhaps the SAT thing could appear on https://library.bdrc.io/search?q=%22saddharmapundarika%22&lg=inc-x-ndia&t=Instance&f=asset,inc,tmp:possibleAccess&f=asset,inc,tmp:catalogOnly too?

**Comment by berger-n** [comment]
indeed! https://library.bdrc.io/search?q=%22saddharmapundarika%22&lg=inc-x-ndia&t=Instance&f=asset,inc,tmp:possibleAccess&f=asset,inc,tmp:catalogOnly&n=5

![image](https://user-images.githubusercontent.com/33383857/197508352-94b3e60e-f991-4e66-a4f4-14bb8002416d.png)
