### ISSUE TITLE
Auth-0 returns user to a random previous search

### ISSUE THREAD

**Issue by JannTibetan** [buda-base/public-digital-library#776]
For about a week now, after logging in I am taken to a work record that I visited at some point last month. In other words, BUDA no longer returns the user to the exact page they were on when initiating the log in.

**Comment by JannTibetan** [comment]
UPDATE: I just tried this on a different browser and did not encounter this problem. I guess it is a problem with my cache and a not a BUDA bug.

**Comment by berger-n** [comment]
I have been able to reproduce this
@eroux I think this is related to https redirection not in place: if you log in from from http://library.bdrc.io it will redirect you to last page you logged from at https://library.bdrc.io

**Comment by eroux** [comment]
the redirection is done for library and editor, it should be better now

**Comment by berger-n** [comment]
perfect! thanks

**Comment by JannTibetan** [comment]
Thanks
