### ISSUE TITLE
impossible to search with a + character in ewts

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#777]
If I search `maN+Dal` in the search bar I reach

https://library.bdrc.io/search?q=%22maN%20Dal%20bzhi%20pa%22~1&lg=bo-x-ewts&t=Topic&s=closest%20matches%20forced

(with a space `%20` instead of a plus `%2B`), we should instead get the search results with the +

**Comment by berger-n** [comment]
fixed: https://library.bdrc.io/search?q=%22maN%2BDal%20bzhi%20pa%22~1&lg=bo-x-ewts&t=Topic

![image](https://user-images.githubusercontent.com/33383857/198563335-71c58929-15ac-4ac5-b52e-f9c7741e27b2.png)

**Comment by eroux** [comment]
thanks!
