### ISSUE TITLE
Request to add "content synopsis" field to outline display on BUDA

### ISSUE THREAD

**Issue by JannTibetan** [buda-base/public-digital-library#779]
It seems like the content synopsis field on legacy outlines is not displayed on BUDA. Can we make it visible on the BUDA UI?

**Comment by eroux** [comment]
do you have an example in mind?

**Comment by eroux** [comment]
ah, I see, the "content synopsis" field of each node has been migrated as the "summary" of the corresponding work, for instance https://library.bdrc.io/show/bdr:WA0XL202B7D5C3D0B

We could display the summary of the work in the outlines nodes, why not.

@berger-n for next week, can you:
- add a link to the work near the "Open on Internet Archive"
- not display the "version of work" property when the name of the work is exactly the same as the title
- display the summary of the work (I need to add it in the queries, I'll do that on Monday)

**Comment by JannTibetan** [comment]
Excellent solution. Thanks.

**Comment by eroux** [comment]
@berger-n the summary is now in the query: https://ldspdi.bdrc.io/query/graph/Outline_root?R_RES=bdr%3AMW1GS60403 (property is `bdo:catalogInfo`)

**Comment by berger-n** [comment]
done, see for example here: https://library-dev.bdrc.io/show/bdr:MW1GS60403?part=bdr:MW1GS60403_2806B0

![image](https://user-images.githubusercontent.com/33383857/201697924-3ab15836-40c9-4c91-8891-33cddfea88f7.png)
--

I'm not sure where to find an example of a version of a work that has a different name though?

**Comment by eroux** [comment]
great, thanks a lot! This a  good improvement

Here's an example: https://library.bdrc.io/show/bdr:MW22703?part=bdr:MW22703_0101

**Comment by berger-n** [comment]
thanks! seems to be working in this case as well now: https://library-dev.bdrc.io/show/bdr:MW22703?part=bdr:MW22703_0101

![image](https://user-images.githubusercontent.com/33383857/201703734-72e972fc-a8aa-400e-b374-3be4638795c8.png)

**Comment by eroux** [comment]
yes, that's perfect, thanks!

**Comment by JannTibetan** [comment]
Wonderful, thanks. Will the change go into effect on the main site tomorrow?

**Comment by eroux** [comment]
Ah right, @berger-n is it deployed in prod?

**Comment by berger-n** [comment]
it is now:
https://library.bdrc.io/show/bdr:MW1GS60403?part=bdr:MW1GS60403_2806B0
https://library.bdrc.io/show/bdr:MW22703?part=bdr:MW22703_0101

**Comment by eroux** [comment]
thanks!
