### ISSUE TITLE
minor reshuffle of properties

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#782]
In https://library.bdrc.io/show/bdr:MW1NLM22_O1NLM22_001 :

- contentWidth and contentHeight should get the same treatment as dimWidth / dimHeight and be merged into a "content dimensions" property
- paginationExtent, conditiongrade and readability grade should go to extended properties
- dimensions and contentdimensions should go to extended properties

**Comment by berger-n** [comment]
done: https://library-dev.bdrc.io/show/bdr:MW1NLM22_O1NLM22_001

![image](https://user-images.githubusercontent.com/33383857/202459352-f016d2b9-214f-406a-af45-16af553ffd45.png)
