### ISSUE TITLE
some labels displayed in English when UI language is set to Tibetan

### ISSUE THREAD

**Issue by berger-n** [buda-base/public-digital-library#785]
see https://library.bdrc.io/show/bdr:MW23703_4125 after switching to Tibetan in language menu
(not occurring in private window so must be related to data language user preferences)

**Comment by eroux** [comment]
opening https://library.bdrc.io/show/bdr:MW23703_4125?uilang=bo in a private window, I see a few labels in English:

![Capture d’écran de 2022-11-28 10-48-37](https://user-images.githubusercontent.com/60868/204247044-286e8bdb-4965-41b3-9be8-ac11f89fff13.png)

**Comment by berger-n** [comment]
fixed: https://library.bdrc.io/show/bdr:MW23703_4125

![image](https://user-images.githubusercontent.com/33383857/204507285-8a903fde-9c18-4db7-9833-0282036ba800.png)

**Comment by eroux** [comment]
thanks!
