### ISSUE TITLE
missing topics facet in associated works search

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#790]
for instance in https://library.bdrc.io/search?r=bdr:P1638&t=Work there should be a topics and genre facet on the left

**Comment by berger-n** [comment]
no topic/genre data is returned by query: https://ldspdi.bdrc.io/lib/associatedWorks?R_RES=bdr%3AP1638&format=json

![image](https://user-images.githubusercontent.com/33383857/211279987-74766eba-bdf8-49fb-8966-5437c4c2354a.png)

**Comment by eroux** [comment]
Ah I see, thanks, I didn't look at that part of the query, it's fixed now, thanks!

**Comment by berger-n** [comment]
excellent! thanks
