### ISSUE TITLE
"see all" link for etext collections

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#791]
https://library.bdrc.io/show/bdr:PR1ER1 is the first collection of etexts, when I try to list them all by clicking on "see more" at the bottom I get to the page of associated scans: https://library.bdrc.io/search?r=bdr:PR1ER1&t=Scan . I'm actually not sure where it should lead... do we have an "associated etext instances" page? If not we need to create it. This is relatively urgent

**Comment by berger-n** [comment]
I guess we do need an `associatedEtextInstances` query because all these return nothing:
- https://ldspdi-dev.bdrc.io/lib/associatedSimpleTypes?R_RES=bdr%3APR1ER1&R_TYPE=bdo%3AEtext&format=json
- https://ldspdi-dev.bdrc.io/lib/associatedInstances?R_RES=bdr%3APR1ER1&format=json

**Comment by eroux** [comment]
ok yes, I'll do that in a few minutes

**Comment by eroux** [comment]
http://ldspdi-dev.bdrc.io/lib/associatedEInstances?R_RES=bdr%3APR1ER1&format=json seems to work

**Comment by berger-n** [comment]
perfect, thanks! works better now: https://library-dev.bdrc.io/show/bdr:PR1ER1

![image](https://user-images.githubusercontent.com/33383857/214098522-3a610fdc-cd71-4d5d-86ca-deb943774f6d.png)

---

![image](https://user-images.githubusercontent.com/33383857/214098583-4e013c6b-abf0-4b74-a309-d51ac255a311.png)

---

![image](https://user-images.githubusercontent.com/33383857/214098662-5b360dec-8bce-4064-a66e-472d5ff8f406.png)

---

a few more glitches to fix on results page though:
- [ ] no need for "Show all matches"
- [ ] what about the facets? not sure which should be available
- [ ] at least there should be the "Relation" [should be straightforward, in the config file]

**Comment by berger-n** [comment]
BTW we need to improve this test:

https://github.com/buda-base/public-digital-library/blob/583378dd66e98fa53a307c32cde0d04610692757/src/components/ResourceViewer.js#L8802

maybe add something in http://purl.bdrc.io/resource/PR1ER1.ttl? wdyt?

**Comment by eroux** [comment]
great, thanks a lot! 

as for the test, good question... it's not bad as it is actually but yes, this should be somewhere in the data

**Comment by eroux** [comment]
about the facets (sorry I'm just reading it now after clicking "comment", basically the facets should be the same as those of the Instance search I think...

**Comment by berger-n** [comment]
facets are back: https://library-dev.bdrc.io/search?r=bdr:PR1ER1&t=Etext&pg=1&f=asset,exc,tmp:hasOpen

![image](https://user-images.githubusercontent.com/33383857/214256985-c588f1e9-9dc1-4515-a610-e07c6517d037.png)

**Comment by eroux** [comment]
thanks! perhaps we might add the topics too? I think the query returns them

**Comment by berger-n** [comment]
done: https://library-dev.bdrc.io/search?r=bdr:PR1ER1&t=Etext

![image](https://user-images.githubusercontent.com/33383857/214278047-fe86cd76-6675-4776-9c20-c76e02ea26c4.png)

**Comment by eroux** [comment]
wonderful, thanks! can we deploy?

**Comment by berger-n** [comment]
deployed: https://library.bdrc.io/search?r=bdr:PR1ER1&t=Etext&pg=1

**Comment by eroux** [comment]
perfect, thanks!
