### ISSUE TITLE
over-interpretation of some dates as edtf

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#793]
On https://library.bdrc.io/show/bdr:P6161 the dates come from the DILA database and are objects of the `bdo:onYear` property, of type `xsd:integer`, but they're interpreted as EDTF. Is it possible to interpret them as integers instead?

**Comment by berger-n** [comment]
fixed: https://library.bdrc.io/show/bdr:P6161

![image](https://user-images.githubusercontent.com/33383857/217204724-dd3a3f24-f11a-431c-afb9-aead9b39a986.png)

![image](https://user-images.githubusercontent.com/33383857/217204768-e9574070-4ac7-4a3e-901f-7d2a16fafef1.png)

**Comment by eroux** [comment]
perfect, thanks!
