### ISSUE TITLE
Images not available for recently synced works

### ISSUE THREAD

**Issue by TBRC-Travis** [buda-base/public-digital-library#794]
@eroux the website is reporting "images not available" for the following works that I recently synced:

https://library.bdrc.io/show/bdr:W4CZ354978
https://library.bdrc.io/show/bdr:W4CZ354991
https://library.bdrc.io/show/bdr:W4CZ354992
https://library.bdrc.io/show/bdr:W8CZ128
https://library.bdrc.io/show/bdr:W8CZ64

**Comment by eroux** [comment]
@TBRC-Travis they work for me, can you make a screenshot of what you're experiencing and where?

**Comment by TBRC-Travis** [comment]
Whatever the issue was seems to have resolved itself.  Last night none of the images were loading for these and the website reported "images not yet available".  Now they're all loading perfectly.  Sorry for the false alarm.
