### ISSUE TITLE
replacing NotoSansTibetan with NotoSerifTibetan

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#798]
Google changed the name of the Tibetan font to NotoSerifTibetan:

https://fonts.google.com/noto/specimen/Noto+Serif+Tibetan?query=tibetan

(it makes a bit more sense), we should update our css files. Although looking at the inspector I couldn't really find any reference to NotoxxxTibetan, example:

![Capture d’écran de 2023-02-14 14-47-23](https://user-images.githubusercontent.com/60868/218758404-3ca5b2b3-49e7-47a2-90b7-9a43023222c3.png)

**Comment by berger-n** [comment]
indeed... :thinking: 
I've updated css so Noto Serif Tibetan is now in use everywhere: https://library-dev.bdrc.io/?uilang=bo

**Comment by eroux** [comment]
great, thanks! I think we can deploy

**Comment by berger-n** [comment]
deployed: https://library.bdrc.io/?uilang=bo
