### ISSUE TITLE
Monlam Dictionary integration UX feedback

### ISSUE THREAD

**Issue by berger-n** [buda-base/public-digital-library#800]
- [x] toggle both dictionary and etext to Wylie/uchen
  ~~use icon with text on hover~~
- [x] dictionary on when opening viewer
- [x] fix spelling
- [x] fix bottom bar on mobile (remove dictionary)
- [x] open/close image instead of reading view when click on image

[edit: [`fix spelling + dictionary on when opening viewer`](https://github.com/buda-base/public-digital-library/commit/6c76d124b6df19a35b0243bf1f51d3a32ee1b93c) (#800) ]

**Comment by berger-n** [comment]
- Cmd+C should work now on Mac @evanyerburgh 
  everything else as well: https://library.bdrc.io/show/bdr:UTIE0OPI44484488_I3CN3541?backToEtext=bdr:IE0OPI44484488&backToEtext=bdr:UTIE0OPI44484488_I3CN3541#open-viewer

  ![simplescreenrecorder-2023-02-27_18 23 34 mkv](https://user-images.githubusercontent.com/33383857/221637462-8c93dccf-e709-4efc-a20e-c5080805bbfb.gif)

---

- regarding dictionary icon/text redundancy though, I'm not sure what to do as this icon+text(+checkbox when needed) pattern is in use elsewhere in the site, see for example the image viewer top/bottom bars: https://library.bdrc.io/show/bdr:W22084#open-viewer

  ![image](https://user-images.githubusercontent.com/33383857/221640286-cadec2d4-7a4b-4257-84ad-05beafeda8c5.png)

  as long as there's space to display text why not show it? especially when the meaning of an icon (like Monlam logo or Etext in the screenshot above) is not as straightforward to get as the download button 

---

- image viewer bottom bar needs to be fixed when between 800 and 900px:
  ![image](https://user-images.githubusercontent.com/33383857/221642545-c391c402-e8c2-483f-b51e-f19a1946403c.png)

**Comment by evanyerburgh** [comment]
@berger-n Great! Yep, Control+C works for me now.

> as long as there's space to display text why not show it?

I agree. And I like how when the browser window gets narrower, they drop down to icons.

Testing it just now, I noticed two more things about narrow screens...

- Monlam doesn't show up on my android phone. 
- When I made my window narrower, the Monlam option disappeared. 

Here's a screencast from my computer. Notice also that when I highlighted text while the browser is narrow, it didn't unselect the previously selected text (which you can see when the window gets wider again.)

https://user-images.githubusercontent.com/51434640/221777768-a3629f9a-ae3b-4b90-869b-6083f92a90e1.mp4

**Comment by berger-n** [comment]
dictionary now enabled on mobile, you can test it here: http://library-dev.bdrc.io/show/bdr:UTIE0OPI44484488_I3CN3541?backToEtext=bdr:W3CN3328#open-viewer
click on "Copy" after selecting text to open Monlam popup
(not perfect in terms of UX as it sure needs to be documented, but it does not seem possible for a website to add an option in a mobile's native contextual menu I'm afraid)

![screen-20230228-180019 mkv](https://user-images.githubusercontent.com/33383857/221925727-78d4110d-9b48-42e2-a565-1cd1f8f44676.gif)
---

oh and I added swipe support for closing both Monlam results panel and the bottom bar (which close button is really small)

**Comment by eroux** [comment]
very nice, thanks!!

**Comment by evanyerburgh** [comment]
Awesome, looks great! Thanks, Nicolas

**Comment by JannTibetan** [comment]
when searching within etexts, the initial search string is highlighted in the etext. This is a wonderful. However, this highlighted text cannot be subsequently highlighted by the Monlam Dictionary feature. 

https://user-images.githubusercontent.com/44705185/222219471-fcfc2c35-3c65-4336-9cf4-4c84ba6db547.mov

**Comment by berger-n** [comment]
oh that's surprising, thanks! 
actually it already can on my computer though (using Chrome): [link](https://library.bdrc.io/show/bdr:UT22920_001_0001?s=q%3D%2522%25E0%25BD%2590%25E0%25BD%25BC%25E0%25BD%2582%25E0%25BC%258B%25E0%25BD%2598%25E0%25BD%25A0%25E0%25BD%25B2%25E0%25BC%258B%25E0%25BD%25A0%25E0%25BD%25BC%25E0%25BD%2591%25E0%25BC%258B%25E0%25BD%2582%25E0%25BD%25A6%25E0%25BD%25A3%2522~1%26lg%3Dbo%26t%3DEtext%26pg%3D1%26f%3DhasMatch%2Cinc%2Ctmp%3AhasExactMatch%26n%3D10&startChar=-1000&keyword=%22%E0%BD%90%E0%BD%BC%E0%BD%82%E0%BC%8B%E0%BD%98%E0%BD%A0%E0%BD%B2%E0%BC%8B%E0%BD%A0%E0%BD%BC%E0%BD%91%E0%BC%8B%E0%BD%82%E0%BD%A6%E0%BD%A3%22~1@bo#open-viewer)

![simplescreenrecorder-2023-03-02_09 52 58 mkv](https://user-images.githubusercontent.com/33383857/222380409-e23f5100-5a00-4ecb-bc90-00e63bcb3aab.gif)

---

but let me check what's going on in Safari! 
(or is it Firefox?)

**Comment by berger-n** [comment]
ah it works for me in Safari as well...

**Comment by JannTibetan** [comment]
OK it did work for me once on Safari but most of the time it doesn't. It works very smoothly on Firefox. 
Anyway, this is an incredible new feature. People will certainly ask why they can't just query the dictionary directly but this is samsara and desires are endless...

**Comment by eroux** [comment]
well, they can on https://monlamdic.com/ ... but it's true that we don't have a link... perhaps the at the top of the results could have a link to it?

**Comment by berger-n** [comment]
> OK it did work for me once on Safari but most of the time it doesn't.

it is intriguing... I'll dig into this

> well, they can on https://monlamdic.com/ ... but it's true that we don't have a link... perhaps the at the top of the results could have a link to it?

(actually the title & icon at the top of the results are already links to monlamdic.com)

**Comment by berger-n** [comment]
- @JannTibetan can you test this update: [\<link to library-dev\>](https://library-dev.bdrc.io/show/bdr:UTIE0OPI7944B80B_I1KG12053?startChar=215574&s=q%3D(%2522dga%2527%2520rab%2520rdo%2520rje%2522%2520AND%2520%2522zhal%2520chems%2522%2520AND%2520%2522tshig%2520gsum%2520gnad%2522)%26lg%3Dbo-x-ewts%26t%3DEtext%26n%3D4&keyword=(%22dga%27%20rab%20rdo%20rje%22%20AND%20%22zhal%20chems%22%20AND%20%22tshig%20gsum%20gnad%22)@bo-x-ewts#open-viewer)

  ![simplescreenrecorder-2023-03-03_17 25 54 mkv](https://user-images.githubusercontent.com/33383857/222774462-8388045d-f491-4d56-89b8-09e837c8bb9a.gif)
  
  you'll see that when dictionary mode is on, hovering on a page with some keyword makes the highlighting disappear 
  (it disappears when you click anywhere on the page as well)
  this should fix the issue with Safari that I cannot reproduce

- @eroux I've also implemented the first two items of @ngawangtrinley 's feedback:
  - dictionary won't close if you click anywhere on the page (you have to click the dedicated button in the top-right corner)
  - once dictionary panel is open you just have to select text to show results (no popup to click anymore)
  - not implemented the third one yet (limiting the maximum number of syllables to send to dictionary) 
    what should be the limit? 20 syllables? 30?

**Comment by berger-n** [comment]
@eroux what about a new sort by "quality" on the [etext results page](https://library-dev.bdrc.io/search?q=(%22dga%27%20rab%20rdo%20rje%22%20AND%20%22zhal%20chems%22%20AND%20%22tshig%20gsum%20gnad%22)&lg=bo-x-ewts&t=Etext&n=8)?
- we could use *OCR Mean Confidence Index* when available
- `1` in the case of computer input?
- `0.999` for `bdo:OPFOCRSoftware  "norbuketaka"`?

**Comment by eroux** [comment]
good idea! Thanks for the changes, I think a good limit could be pretty high, let's start maybe at 40

**Comment by JannTibetan** [comment]
@berger-n I tested the link you sent and it works well on Safari. Thanks

**Comment by berger-n** [comment]
- added both a "quality" facet (with label `NEW`, open when loading page) and a "sort by quality" option, not sure about the wording: [\<link\>](https://library-dev.bdrc.io/search?q=(%22dga%27%20rab%20rdo%20rje%22%20AND%20%22zhal%20chems%22%20AND%20%22tshig%20gsum%20gnad%22)&lg=bo-x-ewts&t=Etext&s=quality)

![image](https://user-images.githubusercontent.com/33383857/223496627-349b90d1-afec-4c73-aad2-cda5be48fbdf.png)


- there's now a maximum length allowed for the text selection used by dictionary (arbitrarily set limit to 80 chars because handling a number of syllables was not that straightforward... :sweat_smile:): [\<link\>](https://library-dev.bdrc.io/show/bdr:UT23605_002_0002?s=q%3D(%2522dga%2527%2520rab%2520rdo%2520rje%2522%2520AND%2520%2522zhal%2520chems%2522%2520AND%2520%2522tshig%2520gsum%2520gnad%2522)%26lg%3Dbo-x-ewts%26t%3DEtext%26s%3Dquality%26n%3D1&startChar=4956&keyword=(%22dga%27%20rab%20rdo%20rje%22%20AND%20%22zhal%20chems%22%20AND%20%22tshig%20gsum%20gnad%22)@bo-x-ewts#open-viewer)

![simplescreenrecorder-2023-03-07_18 14 07 mkv](https://user-images.githubusercontent.com/33383857/223498474-49c61794-abf0-4a08-9fbd-05bd638dd13c.gif)

**Comment by eroux** [comment]
this is great, thanks! perhaps 120 characters is safer. Also, maybe "OCR quality" would be good?

**Comment by JannTibetan** [comment]
Or, "accuracy (ranking)"
Quality is probably not self explanatory enough.

**Comment by berger-n** [comment]
thanks @JannTibetan! 
what about simplifying these labels for filter values as well? 
something like this: [\<link>](https://library-dev.bdrc.io/search?q=(%22dga%27%20rab%20rdo%20rje%22%20AND%20%22zhal%20chems%22%20AND%20%22tshig%20gsum%20gnad%22)&lg=bo-x-ewts&t=Etext&s=accuracy)

![image](https://user-images.githubusercontent.com/33383857/225086818-63fc4a6a-445e-429d-a958-9e37e8e1659e.png)

**Comment by JannTibetan** [comment]
Sure. Great idea. Filters are much more visible than rankings so let's build in some redundancy about this so that people know what to expect from the texts. Thanks.
