### ISSUE TITLE
W4CZ45314 synced but reporting images not available

### ISSUE THREAD

**Issue by TBRC-Travis** [buda-base/public-digital-library#801]
@eroux I synced [W4CZ45314](https://library.bdrc.io/show/bdr:W4CZ45314) on Friday but it's still reporting as "images not yet available".

**Comment by eroux** [comment]
duplicate of https://github.com/buda-base/archive-ops/issues/866 I think

**Comment by jimk-bdrc** [comment]
Same cause, so I'll close this.
