### ISSUE TITLE
searching instances of work leads to a search on works

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#802]
this is rather strange: when I go to https://library.bdrc.io/show/bdr:WA0RK0016 and then click on "browse all ..." beneath the versions overview, I'm then redirected to https://library.bdrc.io/search?i=bdr:WA0RK0016&t=Work which does its job wel... except that it says it displays work results (at the top of the left bar) while they are instance results, which is a bit confusing

**Comment by berger-n** [comment]
fixed: https://library.bdrc.io/search?i=bdr:WA0RK0016&t=Work

![image](https://user-images.githubusercontent.com/33383857/222429630-f42ec232-988a-40d7-a359-127007643dd3.png)
