### ISSUE TITLE
vertical view in etext viewer

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#807]
Since a lot of the new etexts are book format, it would be a good idea to have a configuration of the etext viewer to have the image on the left and the text on the right (or vice versa?) instead of the text below the image. An example where that would be very relevant is https://library.bdrc.io/show/bdr:UTIE0OPIED8BF09F_I4PD2789?backToEtext=bdr:IE0OPIED8BF09F#open-viewer

**Comment by berger-n** [comment]
done (with a url parameter to test where to put the image and see what's best)

- image on the right: https://library-dev.bdrc.io/show/bdr:UTIE0OPIED8BF09F_I4PD2789?backToEtext=bdr:IE0OPIED8BF09F&right=true#open-viewer

![image](https://user-images.githubusercontent.com/33383857/224094098-9a25ad15-e1f9-45ad-b684-04dc36097dba.png)

---

- image on the left: https://library-dev.bdrc.io/show/bdr:UTIE0OPIED8BF09F_I4PD2789?backToEtext=bdr:IE0OPIED8BF09F#open-viewer
  (to me this one seems better, especially when dictionary on)
![image](https://user-images.githubusercontent.com/33383857/224091589-cfe63c1d-f669-44df-b19e-d82a0b8a9b7f.png)

---

- [ ] TODO: fix responsive

**Comment by eroux** [comment]
thanks! I tend to prefer the image on the right but the argument of the dictionary is quite convincing... @JannTibetan what do you think?

**Comment by JannTibetan** [comment]
Image on left, etext on right please. Thanks guys!

**Comment by eroux** [comment]
great, thanks, that's a good improvement!
