### ISSUE TITLE
thumbnail missing sometimes in version

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#808]
to reproduce:
- go to https://library.bdrc.io/search?r=bdr:PR1TIBET00&t=Scan&s=title%20forced
- click on any of the results
- click on the version tab

result:

![Capture d’écran de 2023-03-12 12-33-58](https://user-images.githubusercontent.com/60868/224541927-06a7a1b1-2bc7-4367-86ca-fd9efe8d21b7.png)

reload, result:

![Capture d’écran de 2023-03-12 12-34-03](https://user-images.githubusercontent.com/60868/224541936-a7a0b665-e962-41c5-8519-06859d31cc0c.png)

**Comment by berger-n** [comment]
fixed: https://library.bdrc.io/search?r=bdr:PR1TIBET00&t=Scan&s=title%20forced

![simplescreenrecorder-2023-03-13_18 27 14 mkv](https://user-images.githubusercontent.com/33383857/224780542-a66abddb-49d3-4ddb-94db-218e3ec6381b.gif)
