### ISSUE TITLE
buggy redirection when closing the image viewer

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#809]
to reproduce:
- go to https://library.bdrc.io/show/bdr:W0TTBBC0035?s=r%3Dbdr%3APR1TIBET00%26t%3DScan%26s%3Dtitle%2520forced%26n%3D2#open-viewer
- press escape

land on https://library.bdrc.io/search?title%20forced instead of https://library.bdrc.io/show/bdr:W0TTBBC0035?s=r%3Dbdr%3APR1TIBET00%26t%3DScan%26s%3Dtitle%2520forced%26n%3D2

**Comment by berger-n** [comment]
fixed: https://library.bdrc.io/show/bdr:W0TTBBC0035?s=r%3Dbdr%3APR1TIBET00%26t%3DScan%26s%3Dtitle%2520forced%26n%3D2#open-viewer

![simplescreenrecorder-2023-03-13_18 22 26 mkv](https://user-images.githubusercontent.com/33383857/224779742-bd3e93e0-ee7a-4ce3-9008-2deff35f499c.gif)

**Comment by eroux** [comment]
tanks!
