### ISSUE TITLE
external resources for Taisho

### ISSUE THREAD

**Issue by JannTibetan** [buda-base/public-digital-library#810]
<img width="574" alt="Screenshot 2023-03-14 at 9 16 46 PM" src="https://user-images.githubusercontent.com/44705185/225179297-b1bc8958-05c0-4377-8edd-378ebf2efab9.png">

Is the second data provider missing? I will be presenting in front of both of them tomorrow morning.

**Comment by JannTibetan** [comment]
Also I seem to be unable to load SAT texts in the IIIF viewer https://library.bdrc.io/show/bdr:W0SATT0278#open-viewer

**Comment by berger-n** [comment]
> Is the second data provider missing? I will be presenting in front of both of them tomorrow morning.

indeed there's no link to SAT in [the data for MW0TTT0278](http://purl.bdrc.io/query/graph/ResInfo-SameAs?R_RES=bdr%3AMW0TTT0278&format=jsonld) so SAT logo is not shown:

![image](https://user-images.githubusercontent.com/33383857/225272859-a888d0a1-2925-4e2d-be60-8882b4e6afd7.png)
---

![image](https://user-images.githubusercontent.com/33383857/225271393-c1fa66d4-2164-49c0-a54b-2a9b599cd46f.png)

---

yet it's there in [the data for the corresponding work WA0TTET0278](http://purl.bdrc.io/query/graph/ResInfo-SameAs?R_RES=bdr%3AWA0TTET0278&format=json)

![image](https://user-images.githubusercontent.com/33383857/225272174-7502462a-3760-4977-9618-9efdad7a0434.png)
---

![image](https://user-images.githubusercontent.com/33383857/225272411-e87f670f-901a-4e34-914d-d151e8df1126.png)

---

@eroux wdyt?

**Comment by eroux** [comment]
me too, there's a JS error from mirador when I try, @berger-n can you take a look?

**Comment by berger-n** [comment]
fixed https://library.bdrc.io/show/bdr:W0SATT0278#open-viewer:

![simplescreenrecorder-2023-03-15_11 12 07 mkv](https://user-images.githubusercontent.com/33383857/225279164-2c322262-43b3-4dea-8fcb-3fda4a85be30.gif)

**Comment by eroux** [comment]
and the SAT link is back, copy/paste error, sorry for that

**Comment by JannTibetan** [comment]
Thanks for you help on this. Prof. Shimoda was very impressed with the demo.
