### ISSUE TITLE
Scans tab not appearing

### ISSUE THREAD

**Issue by JannTibetan** [buda-base/public-digital-library#811]
<img width="1176" alt="Screenshot 2023-03-14 at 9 25 04 PM" src="https://user-images.githubusercontent.com/44705185/225180221-037a2c9a-58a5-44f7-b4be-6ffbd1975c2b.png">

**Comment by berger-n** [comment]
to me it's so by design, @eroux wdyt? images from an outline are always displayed as a Version with no Scans, see for example https://library.bdrc.io/show/bdr:MW1KG12048_ADC9FC

![image](https://user-images.githubusercontent.com/33383857/225268671-fc3ce0e5-049d-4b4d-a497-82014c494cd0.png)

**Comment by JannTibetan** [comment]
OK thanks for confirming. We can work on a 2-tab format later.
