### ISSUE TITLE
Rendering [untitled] in Tibetan

### ISSUE THREAD

**Issue by JannTibetan** [buda-base/public-digital-library#815]
Just checking in on the plans for rendering it in Tibetan
<img width="856" alt="Screenshot 2023-03-18 at 3 52 25 PM" src="https://user-images.githubusercontent.com/44705185/226134537-a6e8b421-6756-40be-bf4f-c5c41cf85c4c.png">

**Comment by eroux** [comment]
Good question! What would be a good translation?

**Comment by JannTibetan** [comment]
@karmagongde How should we represent [untitled] in Tibetan? 

In the past we have written མཚན་བྱང་མེད་པ། [first line] ཞེས་སོགས། (I like this.) Can it be automated from the incipit title?
<img width="856" alt="Screenshot 2023-03-19 at 8 22 54 AM" src="https://user-images.githubusercontent.com/44705185/226174865-45b1f890-f3dc-44ef-9047-3bc0447cbddd.png">

**Comment by JannTibetan** [comment]
<img width="856" alt="Screenshot 2023-03-19 at 8 25 57 AM" src="https://user-images.githubusercontent.com/44705185/226175019-3db81401-8ddf-425a-afd9-aca127cc1ee6.png">

The first title says "Untitled/unnamed notes written in khyukyig" and then second is just Untitled without the incipit.

**Comment by eroux** [comment]
`[untitled]` is in the UI, not in the data (I think?), so it's just a matter of translation

**Comment by eroux** [comment]
well, it's not... that's probably why it's not translated... let me look at it tomorrow

**Comment by eroux** [comment]
done!

![Capture d’écran de 2023-03-20 09-04-15](https://user-images.githubusercontent.com/60868/226280676-d598c64c-7eb4-4ceb-8f01-7e7aba066a23.png)

**Comment by JannTibetan** [comment]
For me the [Untitled] NLM texts aren't findable in either language
<img width="1247" alt="Screen Shot 2023-03-20 at 10 18 56 AM" src="https://user-images.githubusercontent.com/44705185/226368219-eec0ce90-b9fd-4d31-aefa-d823cfe2fde1.png">

**Comment by karmagongde** [comment]
In metadata, there are 6 outline nodes that have"མཚན་བྱང་མེད་པ་" on the title. If the field is selected "incipit title" no need for "མཚན་བྱང་མེད་པ་" on the title.
Here is a few suggestions for translation for the "incipit title" 
འགོ་བརྗོད་ཡིག་འབྲུ།
འགོ་བརྗོད་ཡིག་འབྲུའི་མཚན་བྱང་།
འགོ་འཛུགས་ཡིག་འབྲུ།
འགོ་འཛུགས་ཡིག་འབྲུའི་མཚན་བྱང་།

**Comment by JannTibetan** [comment]
> Here is a few suggestions for translation for the "incipit title"
> འགོ་བརྗོད་ཡིག་འབྲུ།
> འགོ་བརྗོད་ཡིག་འབྲུའི་མཚན་བྱང་།
> འགོ་འཛུགས་ཡིག་འབྲུ།
> འགོ་འཛུགས་ཡིག་འབྲུའི་མཚན་བྱང་།

Thanks for the translations of Incipit Title. I like འགོ་བརྗོད་ཡིག་འབྲུ། because it has the verb བརྗོད་, which will remind people of the main term for opening section: མཆོད་བརྗོད་

**Comment by eroux** [comment]
right, what happens is that the data doesn't contain a title, it doesn't contain a title with the value "untitled", so it can't be found that way. 

Thanks for the suggestions Karma! I think what we need is just "incipit", not just "incipit title". For the cases where we have the incipit and no title, I don't import a title, I just import the incipit as an incipit (not as a title)

**Comment by eroux** [comment]
the current translation of `incipit` in the ontology is `མཚན་བྱང་བར་མ།`

**Comment by JannTibetan** [comment]
Interesting. That translation doesn't seem very accurate to me. It is not an "intermediate title" but instead a record of the opening words of the text that are used in place of a formal title. I prefer Karma's proposed translations.

**Comment by eroux** [comment]
sure, what would be a good translation for "incipit" then? (just "incipit", not "incipit title")

**Comment by JannTibetan** [comment]
Karma should decide but I liked his translation འགོ་བརྗོད་ཡིག་འབྲུ།

**Comment by karmagongde** [comment]
"incipit" is under the title field menu so translating only "incipit" would be fine. We should go with འགོ་བརྗོད་ཡིག་འབྲུ། which has the meaning of incipit.

**Comment by eroux** [comment]
oh, these are two different things:

![Capture d’écran de 2023-03-21 14-54-40](https://user-images.githubusercontent.com/60868/226628315-b1c5f846-16cb-4896-94b5-78e0cba025d4.png)
![Capture d’écran de 2023-03-21 14-54-51](https://user-images.githubusercontent.com/60868/226628327-22442ab0-ccf0-463c-9a4e-b37ac5ffa66d.png)

- incipit title is the title that is extracted from the incipit (typically in the case of translation "bod skad du ...")
- incipit is the first few sentences of a text, whether there's a title or not

**Comment by karmagongde** [comment]
Then, translation for "incipit title" should be འགོ་བརྗོད་ཡིག་འབྲུའི་མཚན་བྱང་།

**Comment by eroux** [comment]
perfect, thanks! I'll integrate that

**Comment by eroux** [comment]
done (perhaps it will take a few reloads to get the UI on BUDA or the editor)
