### ISSUE TITLE
warning about OCR quality

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#817]
We don't seem to have a warning about the OCR, on https://library.bdrc.io/show/bdr:IE0OPI37EFE30E for instance, can we put it back? Also, having a popup in that case when the etext viewer opens will be useful

**Comment by berger-n** [comment]
warning's back: https://library.bdrc.io/show/bdr:IE0OPI37EFE30E

![image](https://user-images.githubusercontent.com/33383857/226883127-d510f6b8-4f66-4027-8ea4-e7c7c4a27929.png)

**Comment by eroux** [comment]
thanks!
