### ISSUE TITLE
W8CZ12 not displaying on BUDA

### ISSUE THREAD

**Issue by TBRC-Travis** [buda-base/public-digital-library#819]
@eroux W8CZ12 was synced on June 29th but still doesn't show on the website for some reason:

https://library.bdrc.io/show/bdr:W8CZ12

Strangely it is showing two entries for Volume 1:

Volume 1 [I8CZ18]
Volume 1 [I8CZ12]

I8CZ12 is the correct one.  Maybe this has something to do with the issue?

**Comment by eroux** [comment]
fixed, thanks for spotting it! it was an error that could be made using an old version of the editor, it shouldn't happen again

**Comment by TBRC-Travis** [comment]
thanks!
