### ISSUE TITLE
Etext and image pairing off by 1 page in http://purl.bdrc.io/resource/UTIE0OPI0429C400_I1PD27523

### ISSUE THREAD

**Issue by JannTibetan** [buda-base/public-digital-library#820]
http://purl.bdrc.io/resource/UTIE0OPI0429C400_I1PD27523

The alignment is off throughout the text.The etext is always off by one page and appears one page after the image:
<img width="1672" alt="Screen Shot 2023-04-15 at 10 14 28 AM" src="https://user-images.githubusercontent.com/44705185/232229984-8d78178a-4fa3-43f7-9b29-e2dd910270a0.png">
<img width="1672" alt="Screen Shot 2023-04-15 at 10 14 34 AM" src="https://user-images.githubusercontent.com/44705185/232229991-9151d2a0-9d3c-4adc-9f99-e76137f80c87.png">

If it's just this one text its not a big deal but I'm posting an issue just in case there is a larger problem.

**Comment by eroux** [comment]
this is an interesting case of the biggest flaw (to me) in our current workflow: we did the OCR of this volume in 2020, but then in 2022 the images changed (probably an image was inserted or something), but in our current workflow we can't know how the old images map to the new ones, so we can't remap the OCR to the new images, we have to re-run it completely. This has actually been one of the main topic in my interactions with Claire and Kari
