### ISSUE TITLE
X-ing out of the etext viewer 

### ISSUE THREAD

**Issue by JannTibetan** [buda-base/public-digital-library#821]
Currently, when you you X out of the etext viewer it takes you to a partial record of the etext. It is partial because it lacks the search function. It would be better if it took you directly to the search box for searching within that particular text/sungbum.
Caveat: this happens only when your initial path to the etext is through an etext search, as you see in this screencast:

https://user-images.githubusercontent.com/44705185/233852152-2e71a149-67dc-4c20-9918-fd39fe7b0440.mov

**Comment by berger-n** [comment]
thanks! should be fixed now: https://library.bdrc.io/search?q=%22%27jam%20dpal%20dbyangs%22~1&lg=bo-x-ewts&t=Etext

![simplescreenrecorder-2023-04-24_17 27 51 mkv](https://user-images.githubusercontent.com/33383857/234044265-d08776f5-9343-4b1c-8256-374ffe3ebd53.gif)

**Comment by berger-n** [comment]
regarding Andrew Quintman's issue about *the 13-volume sungbum of Chos kyi dbang phyug*
I think I've fixed at least a part of the problem when you open a text from its permalink and land on the UTxyz text page: [link](https://library-dev.bdrc.io/show/bdr:UTIE0OPIF378E009_I1KG14559?s=q%3D%2522chos%2520kyi%2520dbang%2520phyug%2522~1%26lg%3Dbo-x-ewts%26t%3DEtext%26n%3D2&backToEtext=bdr:IE0OPIF378E009&startChar=8330&keyword=%22chos%20kyi%20dbang%20phyug%22~1@bo-x-ewts)
now if you open the etext viewer then close it you are redirected to the outline and the text you've just closed:

![simplescreenrecorder-2023-05-10_14 08 34 mkv](https://github.com/buda-base/public-digital-library/assets/33383857/1f9f5425-aa23-4e3f-a79f-1c8b3b6da7be)

---

from search results: [link](https://library-dev.bdrc.io/search?q=%22chos%20kyi%20dbang%20phyug%22~1&lg=bo-x-ewts&t=Etext)

![simplescreenrecorder-2023-05-10_14 14 34 mkv](https://github.com/buda-base/public-digital-library/assets/33383857/3f53071e-6b31-4649-be8f-08d8a25ab044)

---

case of multiple texts in a volume: [link](https://library-dev.bdrc.io/show/bdr:UT1KG14_017_0007)

![simplescreenrecorder-2023-05-10_14 36 29 mkv](https://github.com/buda-base/public-digital-library/assets/33383857/951482de-f641-4f8c-b036-ac348352c053)

**Comment by eroux** [comment]
LGTM, thanks!
