### ISSUE TITLE
small change in the etext chunk API

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#823]
There's a change in policy that I'm about to implement in the etext search / chunk context policy and that might require a bit of sync between the queries and the JS.

Basically the change is that the search will now return results in copyrighted texts. This doesn't have a lot of impact on the UI except here: when querying the context for a character range in a copyrighted etext, the query won't return any `:chunkContents`, it will only return the rest. In that case, that means that the initial result returned by the search is the only thing that can be displayed as an excerpt. Can you make sure the code can handle that?

**Comment by berger-n** [comment]
it should work as is, yes, from what I see the default behaviour is already to show data from main query when there's nothing to show from context query
