### ISSUE TITLE
indicate copyright status in etext results

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#824]
Search results are now returned in copyrighted etexts, but we need to indicate it quite clearly. On this example:

https://library.bdrc.io/search?q=%22%E0%BD%A1%E0%BD%B2%E0%BC%8B%E0%BD%82%E0%BD%BA%E0%BD%A0%E0%BD%B2%E0%BC%8B%E0%BD%A2%E0%BE%A3%E0%BD%98%E0%BC%8B%E0%BD%82%E0%BD%9E%E0%BD%82%E0%BC%8B%E0%BD%A2%E0%BE%92%E0%BE%B1%E0%BD%A6%E0%BC%8B%E0%BD%94%E0%BD%A2%E0%BC%8B%E0%BD%96%E0%BD%A4%E0%BD%91%22~1&lg=bo&t=Etext

it's quite unclear for instance. The third result should have the usual restriction icon. Also perhaps the "open in etext" should be grayed out?

**Comment by eroux** [comment]
I added the necessary data in the query, the icon appeared so it's almost good, the graying out is less urgent I think

**Comment by berger-n** [comment]
ok thanks! in the case of a copyrighted etext we could remove both the *Expand* and *Open* links, couldn't we? note that text is not hidden to admin users so it could make sense to keep them in that case

**Comment by eroux** [comment]
expand hold some information (especially if there's an outline), but it's true that it doesn't really do the same as the usual "expand", so maybe replacing it with "details" is a good idea indeed

**Comment by berger-n** [comment]
removed links to context and replaced label by *Details*: https://library.bdrc.io/search?q=%22%E0%BD%A1%E0%BD%B2%E0%BC%8B%E0%BD%82%E0%BD%BA%E0%BD%A0%E0%BD%B2%E0%BC%8B%E0%BD%A2%E0%BE%A3%E0%BD%98%E0%BC%8B%E0%BD%82%E0%BD%9E%E0%BD%82%E0%BC%8B%22~1&lg=bo&t=Etext

![simplescreenrecorder-2023-05-31_18 19 59 mkv](https://github.com/buda-base/public-digital-library/assets/33383857/d55f2b30-1e21-4c53-bf0f-9d0c22e2c433)

**Comment by eroux** [comment]
LGTM, thanks!
