### ISSUE TITLE
Request to explore the feasibility of a new feature on Monlam Dictionary interface

### ISSUE THREAD

**Issue by JannTibetan** [buda-base/public-digital-library#826]
Might it be possible to add a new feature to the Monlam interface that allows the user to select between "begins with" and "contains." 
The Monlam Dictionary mobile app allows for this:
![IMG_0319](https://github.com/buda-base/public-digital-library/assets/44705185/6a280333-5bf9-4d2e-aaf4-11a67e6429b6)

Google Docs also allows for this: 
<img width="461" alt="Screen Shot 2023-05-10 at 1 13 06 PM" src="https://github.com/buda-base/public-digital-library/assets/44705185/cf910a62-1177-4d72-9833-198eda0ad3b9">

The idea is that after highlighting a word and launching the dictionary, the user will have the option of selecting between "contains" and "begin with." This will not solve all the issues with variant forms not appearing in the dictionary, but it will help.
<img width="461" alt="Screen Shot 2023-05-10 at 1 24 26 PM" src="https://github.com/buda-base/public-digital-library/assets/44705185/8ce5bd8f-6a63-44ff-98b9-49ff1b257fd2">

I'm sorry I didn't think of this during the testing phase but it's not too late to add it, if it would be possible.

**Comment by eroux** [comment]
the current reasoning for the results is that we display results that make sense in the context of the etext, so if the dictionary contains "rdor sems dkar", the etext contains "rdor sems dmar" (this is totally random, sorry if it doesn't make sense in Tibetan), then if the user highlights "rdor sems" we don't display the result for "rdor sems dkar" because it's not the context of the etext. It has nothing to do with the keyword in the dictionary beginning with the queried word or not.

I'm a bit surprised because it's also quite different from what we discussed the other day... what you seem to want in this issue is more a general search in the keywords in the dictionary, not taking the etext into account. This is fine, we can have a second batch of results that are just searches of the highlighted keyword in the dictionary.

What we discussed the other day is actually having another third set of results which is the results that contain the queried word in the definition, we can also add that.

Since these two new sets of results are totally disconnected from the etext, perhaps in addition to what we already have we want a general search bar in the dictionary on the right panel? We can rethink the UI, no problem, we just have to be clear that it takes time

**Comment by JannTibetan** [comment]
I'm still thinking within the context of searching only on words highlighted in an etext. I'm just saying that after highlighting a word one would have the option of displaying results that show only headwords with your search string at the begin or somewhere within the headword. 
This is not a request for a standalone search on the dictionary. Sorry, the examples from his app and Google Docs probably gave the wrong impression here. The last screen grab and explanation are the main point: highlight a word, launch dictionary, and then select whether you see results with a match at the beginning of the headword or within it.

**Comment by eroux** [comment]
ok yes, let's talk about the distinction "starts with" / "contains", which I think it not the right concept here. Do you have a specific example where you feel the results in "contains" would be different from the results we have now? (with a link to the etext)

**Comment by JannTibetan** [comment]
Here is an example. The dictionary doesn't return a result for བྱང་ཆུབ་ལམ་རིམ་ (basically, short for LamRim Chenmo).

<img width="895" alt="Screen Shot 2023-05-10 at 2 15 48 PM" src="https://github.com/buda-base/public-digital-library/assets/44705185/3587e804-244d-492e-98fc-840987958215">

But the full dictionary on the mobile app has a record with the fuller version of the title བྱང་ཆུབ་ལམ་རིམ་ཆེན་མོ་

![IMG_0353](https://github.com/buda-base/public-digital-library/assets/44705185/0be7cab9-eb36-4109-8b8d-c2640a084c9e)

We want users to be able to get to the relevant headword, even if it is not exactly the same as the word appearing in the etext

**Comment by eroux** [comment]
sure, we can:
- put the current results (if any) under the title "exact matches of the context"
- have a second category "entries containing the highlighted text"

that's totally fine. We can even have a third category "definitions containing the highlighted word". What do you think of these titles?

**Comment by JannTibetan** [comment]
Let's have all three categories! Searching within the definitions will be really helpful because I suspect the writers of the definitions used a lot of the same abbreviations that are found in our etexts.

**Comment by eroux** [comment]
ok! I'll have to change the API a bit but it's not too big

**Comment by JannTibetan** [comment]
Wonderful, thanks. Anytime this month will do.

**Comment by eroux** [comment]
@berger-n I've implemented (but not put online yet) a modification of the json results for `entriesForChunk`, the main difference is that there is now a `type` key for all results, with the following possible values:
- `e` is exact match
- `c` is match in the etext context
- `k` is a match of the highlighted text in a keyword, which may or may not be in context
- `d` is a match of the highlighted text in a definition

for entries of the last 2 types, the usual fields (`chunk_offset_end`, `nb_tokens`, etc.) are always `0` since they don't make a lot of sense. On the other hand the `word` or `definition` now has the usual highlight indications (`↦xxx↤`). There's an example of the format in:

[example.json.zip](https://github.com/buda-base/public-digital-library/files/11453994/example.json.zip)

I think the UI could be to have 3 sections of results, with the first non-empty section open by default.

Note that the endpoint currently limits the number of results to 200, I'm not sure it makes a lot of sense to provide thousands of results in the UI, that would require some rework.

Once you feel the code is ready I can deploy ldspdi

**Comment by berger-n** [comment]
ok thanks! I'll let you know when code is ready (probably tomorrow)

**Comment by berger-n** [comment]
@eroux deployed a test with your data here: [link](https://library-dev.bdrc.io/show/bdr:UTIE0OPIE4EC34A8_I1KG17128?backToEtext=bdr:IE0OPIE4EC34A8#open-viewer)

(need to be logged in and an admin user
then each query to Monlam loads the same example.json
see img.9 l.4 for an occurrence of རིགས for the sake of realism :smile:
for further testing next week we could use ldspdi-dev, couldn't we?)

NB: not sure this is the right place for Feedbucket icon when dictionary is open... see #804

![simplescreenrecorder-2023-05-12_18 43 32 mkv](https://github.com/buda-base/public-digital-library/assets/33383857/052146d1-8ec8-44cd-9d0f-24d3a771b181)

**Comment by JannTibetan** [comment]
Thanks all, this looks very good. My apologies for taking so long to try it out and acknowledge your work. It's going to give the users much deeper access to the dictionary. 
Can we have a meeting about this on Wednesday? The three of us can share a screen and test out its performance on various multi-syllabic words and phrases to see if any additional refinements are needed.

**Comment by berger-n** [comment]
hi @JannTibetan, new version deployed and working here: https://library-dev.bdrc.io/show/bdr:UTIE0OPIFAC9F61B_I3CN4692?backToEtext=bdr:IE0OPIFAC9F61B#open-viewer

![simplescreenrecorder-2023-05-16_17 39 22 mkv](https://github.com/buda-base/public-digital-library/assets/33383857/b5708e38-05e4-45ae-9b27-87ebd9e5189b)

**Comment by JannTibetan** [comment]
Very cool and powerful new features! Thank you.
Wednesday morning I'll schedule a time for us to share a screen and take a closer look.

**Comment by eroux** [comment]
good idea! don't hesitate to test on a few queries to see if some results are missing

**Comment by JannTibetan** [comment]
The Tibetan analyzer at work! Super helpful.
<img width="959" alt="Screen Shot 2023-05-17 at 8 31 41 AM" src="https://github.com/buda-base/public-digital-library/assets/44705185/f47d3512-13d9-45c2-938b-698275106b49">

**Comment by JannTibetan** [comment]
Speaking of the Tibetan analyzer, can it be programmed to overlook the ནི་ topicalized particle?

<img width="694" alt="Screen Shot 2023-05-17 at 8 38 16 AM" src="https://github.com/buda-base/public-digital-library/assets/44705185/bb3b6157-3cff-42b1-9c1c-738be2862d30">

 **Versus**

<img width="694" alt="Screen Shot 2023-05-17 at 8 38 30 AM" src="https://github.com/buda-base/public-digital-library/assets/44705185/aba536af-cf36-4658-9829-edbb8cb7b8d9">

**Comment by JannTibetan** [comment]
This seems like a peculiar behavior. 

འཁོར་བའི་ཉེས་དམིགས།, the defects of Samsara, is a common phrase. 
When this phrase is searched on, the dictionary displays no results:
<img width="806" alt="Screen Shot 2023-05-17 at 8 43 03 AM" src="https://github.com/buda-base/public-digital-library/assets/44705185/dfa25855-d0ce-4a39-b4a5-6f447cd919b2">

BUT then when you search simply on ཉེས་དམིགས།, defect, then one of the entries is the full phrase འཁོར་བའི་ཉེས་དམིགས།
<img width="806" alt="Screen Shot 2023-05-17 at 8 42 53 AM" src="https://github.com/buda-base/public-digital-library/assets/44705185/bd516c5e-077d-4e48-906c-d835f810a650">

**Comment by JannTibetan** [comment]
Re: Definitions containing the highlighted word, can we highlight the search string in a way that is more noticeable? 
<img width="445" alt="Screen Shot 2023-05-17 at 8 48 28 AM" src="https://github.com/buda-base/public-digital-library/assets/44705185/5cfbcf15-3a18-469a-b5a5-e51f25b33046">

**Comment by JannTibetan** [comment]
The dictionary return two identical definitions of this word. 
<img width="918" alt="Screen Shot 2023-05-17 at 8 52 06 AM" src="https://github.com/buda-base/public-digital-library/assets/44705185/a4b8f985-d9ff-4b40-920b-742ffaf7ec2d">

**Comment by eroux** [comment]
@JannTibetan thanks for the input, really helpful! Overlooking ནི is possible, although I anticipate there will be complaints like the one we had that རམ was impossible to find. If you're confident nobody will search ནི I can add it to the list of stop words

Just as a note, the query that should contain འཁོར་བའི་ཉེས་དམིགས is [this one](https://ldspdi.bdrc.io/lexicography/entriesForChunk?chunk=%E0%BD%A2%E0%BC%8B%E0%BD%96%E0%BE%B1%E0%BD%A0%E0%BD%BC%E0%BC%8D%20%E0%BC%8D%E0%BD%96%E0%BD%9E%E0%BD%B2%E0%BC%8B%E0%BD%94%E0%BC%8D%20%E0%BD%A0%E0%BD%81%E0%BD%BC%E0%BD%A2%E0%BC%8B%E0%BD%96%E0%BD%A0%E0%BD%B2%E0%BC%8B%E0%BD%89%E0%BD%BA%E0%BD%A6%E0%BC%8B%E0%BD%91%E0%BD%98%E0%BD%B2%E0%BD%82%E0%BD%A6%E0%BC%8B%E0%BD%96%E0%BD%A6%E0%BD%98%E0%BC%8B%E0%BD%94%E0%BC%8D%E0%BD%A0%E0%BD%81%E0%BD%BC%E0%BD%A2%E0%BC%8B%E0%BD%96%E0%BD%A0%E0%BD%B2%E0%BC%8B%E0%BD%89%E0%BD%BA%E0%BD%A6%E0%BC%8B%E0%BD%91%E0%BD%98%E0%BD%B2%E0%BD%82%E0%BD%A6%E0%BC%8B%E0%BD%96%E0%BD%A6%E0%BD%98%E0%BC%8B%E0%BD%94%E0%BC%8B%E0%BD%A3%E0%BC%8B%E0%BD%90%E0%BD%BC%E0%BD%82%E0%BC%8B%E0%BD%98%E0%BD%A2%E0%BC%8B%E0%BD%91%E0%BD%98%E0%BC%8B%E0%BD%86%E0%BD%BC%E0%BD%A6%E0%BC%8B%E0%BD%A2%E0%BE%AB%E0%BD%BC%E0%BD%82%E0%BD%A6%E0%BC%8B%E0%BD%94%E0%BC%8B%E0%BD%86%E0%BD%BA%E0%BD%93%E0%BC%8B%E0%BD%94%E0%BD%BC%E0%BD%A0%E0%BD%B2&cursor_end=34&cursor_start=16&lang=bo) (I have no idea why this behavior appears yet)

and the query with two duplicate results is [this one](https://ldspdi.bdrc.io/lexicography/entriesForChunk?chunk=%E0%BC%8B%E0%BD%89%E0%BD%B2%E0%BC%8B%E0%BD%A4%E0%BD%B4%E0%BC%8B%E0%BD%A2%E0%BE%A9%E0%BC%8B%E0%BD%91%E0%BE%B2%E0%BD%B4%E0%BD%82%E0%BC%8B%E0%BD%A6%E0%BE%9F%E0%BD%BA%E0%BC%8D%20%E0%BD%89%E0%BD%93%E0%BC%8B%E0%BD%94%E0%BC%8B%E0%BD%94%E0%BD%BC%E0%BC%8B%E0%BD%A0%E0%BD%91%E0%BD%B4%E0%BD%82%E0%BC%8B%E0%BD%94%E0%BC%8B%E0%BD%A3%E0%BC%8B%E0%BD%A0%E0%BD%82%E0%BE%B2%E0%BD%BA%E0%BD%84%E0%BC%8B%E0%BD%A6%E0%BE%9F%E0%BD%BA%E0%BC%8B%E0%BD%86%E0%BD%BC%E0%BD%A6%E0%BC%8B%E0%BD%A0%E0%BD%86%E0%BD%91%E0%BC%8B%E0%BD%94%E0%BC%8B%E0%BD%91%E0%BD%84%E0%BC%8B%E0%BC%8D%20%E0%BD%89%E0%BD%A3%E0%BC%8B%0A%E0%BD%96%E0%BC%8B%E0%BD%A3%E0%BC%8B%E0%BD%A0%E0%BD%91%E0%BD%B4%E0%BD%82%E0%BC%8B%E0%BD%A6%E0%BE%9F%E0%BD%BA%E0%BC%8B%E0%BD%86%E0%BD%BC%E0%BD%A6%E0%BC%8B%E0%BD%A0%E0%BD%86%E0%BD%91%E0%BC%8B&cursor_end=54&cursor_start=47&lang=bo) (this is easy to fix)

**Comment by JannTibetan** [comment]
I think we might have a conflict between our analyzers and the Dictionary regarding the term ཞེས་ (used to end quotations; more of a function word). The Dictionary has a definition for it.
<img width="918" alt="Screen Shot 2023-05-17 at 8 55 55 AM" src="https://github.com/buda-base/public-digital-library/assets/44705185/1b7b6e07-e552-4f59-ba24-d04454d2603e">

**Comment by eroux** [comment]
hmmm that's a very good question... I think they might be in a random order or in the order returned by Lucene... I don't think I have code to do alphabetical order in Java (and our version is probably too old for the new data we provided Unicode) but I'll investigate. A plan B is to do it in the browser directly

**Comment by JannTibetan** [comment]
Sometimes, but not all the time, the "Definitions containing the highlighted word" results only give you snippets of the definition and not the full definition 
<img width="1046" alt="Screen Shot 2023-05-17 at 9 07 43 AM" src="https://github.com/buda-base/public-digital-library/assets/44705185/13a238e3-be32-46bc-bb65-95915e684653">

**Comment by berger-n** [comment]
@JannTibetan thanks a lot! looking at some of your screenshots like these it seems your browser is not using the latest version

![image](https://github.com/buda-base/public-digital-library/assets/33383857/dff01a01-e454-40ec-9791-49298da0ced2)

![image](https://github.com/buda-base/public-digital-library/assets/33383857/468c7ff7-3074-4bef-80d4-9559beb10a57)

is it on ios ? if so it seems there's this tip to force refreshing the page: https://apple.stackexchange.com/questions/74797/can-i-force-a-cache-refresh-in-safari-running-on-ios#answer-392786
(reloading with wifi off then with wifi on); if not you can check https://fabricdigital.co.nz/blog/how-to-hard-refresh-your-browser-and-clear-cache

**Comment by JannTibetan** [comment]
> @JannTibetan thanks a lot! looking at some of your screenshots like these it seems your browser is not using the latest version

Oh ok. Let me switch from Safari to Chrome and retry. Thanks

**Comment by JannTibetan** [comment]
> 

You are right. Now I am using Chrome and I have the ability to expand and collapse lists easily. Thanks!

**Comment by JannTibetan** [comment]
Random question, is it true that no definitions contain the phrase གསང་སྔགས་, secret mantra?
<img width="1005" alt="Screen Shot 2023-05-17 at 9 14 09 AM" src="https://github.com/buda-base/public-digital-library/assets/44705185/a2fcecaf-bf0d-43b8-b7ab-a113cdb7911e">

**Comment by JannTibetan** [comment]
Sure, that is a good policy. If a term is so common that it appears 250 (or even 1000) times then it's meaning should be discernible from the preceding two lists of entries.

**Comment by berger-n** [comment]
> Sometimes, but not all the time, the "Definitions containing the highlighted word" results only give you snippets of the definition and not the full definition

@eroux it's in the data, see `type:"d"` entries [here](http://purl.bdrc.io/lexicography/entriesForChunk?chunk=%E0%BC%8B%E0%BD%A6%E0%BE%A4%E0%BD%84%E0%BC%8B%E0%BD%91%E0%BD%82%E0%BD%BC%E0%BD%A6%E0%BC%8D%20%20%E0%BD%91%E0%BD%BA%E0%BC%8B%E0%BD%A1%E0%BD%84%E0%BC%8B%E0%BD%89%E0%BD%BC%E0%BD%93%E0%BC%8B%0A%E0%BD%98%E0%BD%BC%E0%BD%84%E0%BD%A6%E0%BC%8B%E0%BD%94%E0%BC%8B%E0%BD%A2%E0%BE%A3%E0%BD%98%E0%BD%A6%E0%BC%8B%E0%BD%A3%E0%BD%A6%E0%BC%8B%E0%BD%84%E0%BC%8B%E0%BD%A2%E0%BE%92%E0%BE%B1%E0%BD%A3%E0%BC%8B%E0%BD%91%E0%BD%84%E0%BC%8C%E0%BC%8D%20%E0%BD%95%E0%BE%B2%E0%BD%82%E0%BC%8B%E0%BD%91%E0%BD%BC%E0%BD%82%E0%BC%8B%E0%BD%82%E0%BD%89%E0%BD%B2%E0%BD%A6%E0%BC%8B%E0%BD%94%E0%BD%BC%E0%BC%8B%E0%BD%A0%E0%BD%91%E0%BD%B2%E0%BC%8B%E0%BD%84%E0%BD%BC%E0%BD%A6%E0%BC%8B%0A%E0%BD%9F%E0%BD%B2%E0%BD%93%E0%BC%8B%E0%BD%91%E0%BD%80%E0%BD%A0%E0%BC%8B%E0%BD%96%E0%BD%A6%E0%BC%8B%E0%BD%A2%E0%BD%84%E0%BC%8B%E0%BD%A2%E0%BE%92%E0%BE%B1&cursor_end=62&cursor_start=50&lang=bo)
(I guess it's on purpose, to avoid returning like the full dictionary itself?  :smile: )

**Comment by JannTibetan** [comment]
Here is case that may be similar to the one I posted about འཁོར་བའི་ཉེས་དམིགས་
<img width="943" alt="Screen Shot 2023-05-17 at 9 31 30 AM" src="https://github.com/buda-base/public-digital-library/assets/44705185/0833d697-ec7a-458f-b782-7f65ec5408de">

VERSUS 

<img width="943" alt="Screen Shot 2023-05-17 at 9 31 40 AM" src="https://github.com/buda-base/public-digital-library/assets/44705185/45bf6cb2-6ca6-4b1a-be25-194a2696e0d5">

**Comment by eroux** [comment]
not really, it looks like a bug in the dictionary itself, looking on https://monlamdic.com/ there's even no entry at all...

**Comment by JannTibetan** [comment]
> (I guess it's on purpose, to avoid returning like the full dictionary itself? 😄 )

OK. Can we add an "expand" button to the snippets?
<img width="943" alt="Screen Shot 2023-05-17 at 9 34 48 AM" src="https://github.com/buda-base/public-digital-library/assets/44705185/baf3abf5-e665-41f9-882c-d5a6ea6ad1d6">

**Comment by eroux** [comment]
it's the only thing that's in the dictionary it seems, these are maybe unfinished entries

**Comment by eroux** [comment]
I believe that everything is in order now (including the alphabetical order, thanks to our contribution to Unicode actually!), I've just updated the server

**Comment by JannTibetan** [comment]
This is a good example of the usefulness of the "Entries containing highlighted text" feature 
<img width="1181" alt="Screen Shot 2023-05-17 at 12 23 51 PM" src="https://github.com/buda-base/public-digital-library/assets/44705185/904802b3-9428-45dd-adf0-dee2b40c6bea">

**Comment by berger-n** [comment]
now working from mirador as well: https://library-dev.bdrc.io/show/bdr:W3CN4690?s=%2Fshow%2Fbdr%3AMW3CN4690#open-viewer

![simplescreenrecorder-2023-05-22_18 22 49 mkv](https://github.com/buda-base/public-digital-library/assets/33383857/192589a3-d13f-48d4-8ce9-9caba8fcb38c)

**Comment by eroux** [comment]
great! I think we can deploy in prod?

**Comment by berger-n** [comment]
deployed: https://library.bdrc.io/show/bdr:UTIE0OPIFAC9F61B_I3CN4692?backToEtext=bdr:MW3CN4690#open-viewer

**Comment by JannTibetan** [comment]
It works really well. Thank you!
