### ISSUE TITLE
search in versions limitted to subscribed collections

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#827]
From a subscribing institution: it would be helpful to have a search bar that provides results only in the subscribed collections.

I'm not quite sure how that would look from a UI perspective, but from the server side it's just creating a new LDS query on the model of `instanceFacetGraph`

perhaps a checkbox "restrict to subscribed collections" ?

**Comment by berger-n** [comment]
- it reminds me of the guided search on the Cambodia website:
https://khmer-manuscripts.bdrc.io/search?t=Instance&f=collection,inc,bdr:PR1KDPP00&q=dhammapada&lg=pi-x-ndia
  where we use the standard query but with a facet selected by default:
 
  ![image](https://github.com/buda-base/public-digital-library/assets/33383857/651cc18f-a9f1-4296-b4ec-efd2276bc8d4)
  
  we could just add a specific facet and that should work as is 
  (so as user don't have to uncheck the fifteen collections :sweat_smile:)

---

- but actually there might be another issue, have you tried searching anything from the accesspoint they've provided in the email? it fails with a 400 error whatever the query used:

  ![image](https://github.com/buda-base/public-digital-library/assets/33383857/ddabe691-bb53-45f4-9f47-2d2210a2e949)

  strange thing is that the query works in the browser 
  but not in a terminal with curl (where BTW it works if I add an "Accept: *" in the header... let me try to fix this from library)

**Comment by berger-n** [comment]
> strange thing is that the query works in the browser
> but not in a terminal with curl (where BTW it works if I add an "Accept: *" in the header... let me try to fix this from library)

it worked! so now we can already have [that sort of results](https://library-1bdrc-1io-1e7aa8fzo0722.erf.sbb.spk-berlin.de/search?q=%22padma%20gling%20pa%27i%22~1&lg=bo-x-ewts&t=Instance&pg=1&f=asset,inc,tmp:possibleAccess&f=asset,inc,tmp:catalogOnly&f=collection,inc,bdr:PR1CTC10&f=collection,inc,bdr:PR1CTC17&f=collection,inc,bdr:PR1CTC12&f=collection,inc,bdr:PR3JW7543&f=collection,inc,bdr:PRHD01&f=collection,inc,bdr:PRHD02&f=collection,inc,bdr:PR01JW11672&f=collection,inc,bdr:PR60CTX96&f=collection,inc,bdr:PR00JW501092&f=collection,inc,bdr:PR1GS49488&f=collection,inc,bdr:PR01CTC09)

![image](https://github.com/buda-base/public-digital-library/assets/33383857/09491265-76fe-4920-917e-c6ede42f07a2)
---

now I think it wouldn't be too complicated to add an *In Subscribed Collections* value for *In Collection* facet that would act like having all the corresponding values selected 
let me have a deeper look

**Comment by eroux** [comment]
excellent! If it can work that way then yes, let's do it!

I'm a bit surprised by https://github.com/buda-base/public-digital-library/commit/f2f33d6b1b21a88c91688431b581fea0fac10c78 but... why not!

**Comment by eroux** [comment]
Actually I think the filter on subscribed collections should be there by default, just like on the Khmer website, it would make a lot of sense in that context

**Comment by berger-n** [comment]
might need some more testing but seems to be working already: 

![image](https://github.com/buda-base/public-digital-library/assets/33383857/9f7cf8e0-131a-40b6-81c3-a1a4f9c50a47)

---

BTW I've also updated the query (inspired by allCollections query):

![image](https://github.com/buda-base/public-digital-library/assets/33383857/433fb06c-9ba4-4075-9e4f-eb14f200ef43)

**Comment by eroux** [comment]
this looks really good, can we also limit the search to open access material by default when a proxy is detected?

**Comment by berger-n** [comment]
done: 

![image](https://github.com/buda-base/public-digital-library/assets/33383857/b137295f-7955-425e-98cd-5effed9828e7)

**Comment by eroux** [comment]
wonderful, thanks!

**Comment by eroux** [comment]
LGTM
