### ISSUE TITLE
download PDF from proxied url?

### ISSUE THREAD

**Issue by berger-n** [buda-base/public-digital-library#829]
something to be checked here:
- for now it's not possible at all from resource page (menu is hidden for some Auth related reason I guess)
  
  ![image](https://github.com/buda-base/public-digital-library/assets/33383857/7d890023-3b26-4364-8e8c-25af863df691)

---

- it's possible from mirador (but shouldn't something need to be checked first? and login's sometimes mandatory, I should check that case as well)
  
  ![image](https://github.com/buda-base/public-digital-library/assets/33383857/149b0e0f-b1dc-4c73-8ff0-6aae4efb67b9)

**Comment by eroux** [comment]
Oh, that's not normal, the menu to download PDFs should always be present everywhere. The specificity of the proxied version is that in case of a 401, the message should be adjusted to something like "this PDF is not part of a collection subscribed to by your institution, please visit the BDRC platform and log in for access.". This is related to https://github.com/buda-base/public-digital-library/issues/492

**Comment by berger-n** [comment]
- [x] display pdf download popup

![image](https://github.com/buda-base/public-digital-library/assets/33383857/150a3d41-a32c-4e34-8a59-3def5b2bafd3)
---

- [x] update error message when 401 
 
![image](https://github.com/buda-base/public-digital-library/assets/33383857/2d7bceff-b227-4934-9b46-59487c2c0e18)

---

- [ ] in mirador as well

**Comment by eroux** [comment]
Excellent, thanks!

**Comment by berger-n** [comment]
- 401 ok from mirador:

![image](https://github.com/buda-base/public-digital-library/assets/33383857/843bc280-fd9d-411a-85a1-8ee2035fb6ea)
---

- removed lang/donation/cookie popups that were shown very visit

**Comment by eroux** [comment]
great, thanks!

**Comment by eroux** [comment]
I think it's all good, thanks!
