### ISSUE TITLE
duplicate volumes in outline when virtual image instance available

### ISSUE THREAD

**Issue by berger-n** [buda-base/public-digital-library#848]
see https://library.bdrc.io/show/bdr:MW1BL6?tabs=bdr:W1ER156

![image](https://github.com/buda-base/public-digital-library/assets/33383857/ae4082b6-18d6-48b3-8b93-40d438276c60)

---

the outline seems to contain volumes from both: https://ldspdi.bdrc.io/query/graph/Outline_root_volumes?R_RES=bdr%3AMW1BL6

![image](https://github.com/buda-base/public-digital-library/assets/33383857/d0d10c8f-a54f-4aa9-94a1-349885f1dd52)

**Comment by eroux** [comment]
fixed, thanks!

**Comment by berger-n** [comment]
not related but there's a link to the rKTs resource that leads to nowhere: http://purl.rkts.eu/resource/WEGgk

![image](https://github.com/buda-base/public-digital-library/assets/33383857/5f28e1d7-7835-4676-b409-797330d63419)

---

![image](https://github.com/buda-base/public-digital-library/assets/33383857/2a524914-24da-435a-8936-35b38f644b39)
