### ISSUE TITLE
outline authorship statement not displayed in some cases

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#851]
in https://library.bdrc.io/show/bdr:MW1KG14896 the outline authorship statement is not displayed despite being present in the query, or so it seems... Nicolas, it's probably not much so would you have a little time to look at this?

**Comment by berger-n** [comment]
fixed conflict with `authorshipStatement`: https://library.bdrc.io/show/bdr:MW1KG14896

![image](https://github.com/buda-base/public-digital-library/assets/33383857/6e224b6d-1ebf-4851-beb3-ca7a811ccf64)

---

noticed that there's something wrong with the outline from the original issue #783 though: https://library.bdrc.io/show/bdr:MW1NLM22
(no `authorshipStatement` and no data/title etc. for parts of root node in [outline data](https://ldspdi.bdrc.io/query/graph/Outline_root?R_RES=bdr%3AMW1NLM22))

![image](https://github.com/buda-base/public-digital-library/assets/33383857/4cf6d40e-3d22-4b21-af53-2c8325f952f9)

**Comment by eroux** [comment]
thanks!
