### ISSUE TITLE
display issues in bdr:W1FEMC020013

### ISSUE THREAD

**Issue by berger-n** [buda-base/public-digital-library#86]
* titles now look a bit better: http://library.bdrc.io/show/bdr:W1FEMC020013

* I guess dates such as `"2486"^^bdo:beDate` need more specific rendering than just `2486`

* regarding `Notes` I wonder how this is supposed to be rendered too:
```
bdr:NT5FFD1A061FB7  a  bdo:Note ;
   bdo:noteLocationStatement  "3" ;
   bdo:noteText  "Catalog" ;
   bdo:noteWork  bda:PR1FEMC02 .

bdr:NTBA2765BFDBFA  a  bdo:Note ;
   bdo:noteText  "Collection Institution" ;
   bdo:noteWork  bda:PR1KDPP01 .

bdr:NTDA88B89ACD5C  a  bdo:Note ;
   bdo:noteLocationStatement  "1" ;
   bdo:noteText  "Fascicles" .

bdr:NTE38A9ECDAD31  a  bdo:Note ;
   bdo:noteLocationStatement  "1" ;
   bdo:noteText  "Work Number" .
```
especially w.r.t these `Notes` in [bdr:P1583](http://library.bdrc.io/show/bdr:P1583) :
```
bdr:NT93D338F6A346  a  bdo:Note ;
   bdo:noteLocationStatement  "v. 2, pp.104-112" ;
   bdo:noteText  "biography\ndates: 1308-1363"@en ;
   bdo:noteWork  bdr:W25268 .

bdr:NTABB307C08F28  a  bdo:Note ;
   bdo:noteLocationStatement  "251" ;
   bdo:noteText  "biodata\n\nSubsequent main lineage holders include lha btsun chen po/ gter chen 'gyur med rdo rje/ 'bri gung rin chen phun tshogs/ rig 'dzin 'jigs med gling pa/ mi 'gyur nam mkha'i rdo rje/ 'jam dbyangs mkhyen brtse'i dbang po\n\nAmong them, 'jigs med gling pa received the nye brgyud via direct vision of klong chen pa.  'jigs med gling pa passed his lineage to rdo grub phrin las 'od zer, who passed it to mi 'gyur nam mkha' rdo rje, who in turn had a vision of klong chen pa and received the yang tig from him."@en ;
   bdo:noteWork  bdr:W27401 .

bdr:NTB25CDA7F0516  a  bdo:Note ;
   bdo:noteLocationStatement  "p. 6" ;
   bdo:noteWork  bdr:W19822 .
```

**Comment by berger-n** [comment]
BTW in http://purl.bdrc.io/admindata/PR1FEMC02.ttl
is `bda:PR1FEMC02  adm:adminAbout  bda:PR1FEMC02` correct?
(need to fix a recursive loop in any case)

**Comment by eroux** [comment]
let's fix that loop just in case yes, it could be a correct case. Honestly I'm a bit reluctant to spend some energy on it now, as the data will change in the near future... let's ignore the UI for notes and dates for now.

**Comment by berger-n** [comment]
ok

**Comment by xristy** [comment]
@berger-n thanks. The titles and dates look nice. 

One more thing is that the FEMC Volume II works, e.g., [W1FEMC021300](http://library.bdrc.io/show/bdr:W1FEMC021300), have a triple like:

> [bda:W1FEMC021300](http://library.bdrc.io/show/bda:W1FEMC021300) adm:contentProvider  [bda:CP041](http://library.bdrc.io/show/bda:CP041) .

and, when present, it would be nice to display for the `bdr:W1FEMC02xxxx`, just as the `adm:metadataLegal` property currently is displayed.

We have many `adm:ContentProviders` defined and it with time more `:Works` will have a `adm:contentProvider` (and `adm:metadataProvider`) so this change would be of general value.

**Comment by xristy** [comment]
@berger-n Thanks for the contentProvider. It all looks very nice now
