### ISSUE TITLE
better indication of copyright restrictions

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#863]
Restriction of etexts and images are not always easy to follow and there's a lot of exceptions, with sometimes one reproduction being under strict restriction and another in open access.

We should redesign the process a little bit to make the different access statuses of reproductions clear in the UI. There are different types of restrictions of access:
- open access
- images / etext not online (this is kind of silly but it needs to be displayed in full English)
- images / etext restricted by BDRC, or temporarily
- images / etext restricted by tradition / sealed
- images where only a snippet (first and last 20 pages) is available online because it's copyrighted by a third party (except in China where we offer no snippet at all)
- etexts where we only allow search but no download / display because of copyright (kind of equivalent as the one before)

    //   1: no access
    //   2: search only
    //   3: open access

    // scans access:
    //   1: no access
    //   2: extract only
    //   3: IA
    //   4: open access through IIIF
    //   5: open access on BDRC

**Comment by roopeux** [comment]
From UX point of view, we need to communicate clearly.  Would this belong to this ticket?
1. Available at BDRC
2. Available in the original collection with link
3. Available at Archive.org with link
4. Available to buy from publisher or reseller?  Link to web shop.
5. Restricted because of the above mentioned reasons.

**Comment by roopeux** [comment]
Note to self: Indicate lending policies https://library.bdrc.io/show/bdr:W25096

**Comment by eroux** [comment]
that's an interesting framework, perhaps it could be refined in the following way:

1. open access on BDRC
2. available in full through controlled digital lending on Internet Archive
3. restricted by tradition, please contact BDRC if you have received the proper traditional authorization
4. only catalog is available, open access not currently possible, please contact the original owners / publishers
5. access not allowed, sorry

**Comment by eroux** [comment]
actually maybe 5 and 6 could just be merged together, we actually don't want to tell users that we have images but restrict them, it makes them angry

**Comment by roopeux** [comment]
When there is only a snippet, is it in etext or scans?

**Comment by eroux** [comment]
ah yes, good point, here's another attempt:


1. scan/etext: open access on BDRC
2. scan: only snippet available on BDRC, available in full through controlled digital lending on Internet Archive
3. scan: only snippet available on BDRC, text not available on Internet Archive
4. etext: search only, no download / viewing allowed
5. etext / scan:  restricted by tradition, please contact BDRC if you have received the proper traditional authorization
6. general: only catalog is available, open access not currently possible, please contact the original owners / publishers
7. etext / scans: access not allowed, sorry

**Comment by roopeux** [comment]
@berger-n, The different restriction levels are prototyped in Figma.  Click the "Scans" section to rotate through them.  Waiting for approval from @eroux or Jann.


![Image](https://github.com/buda-base/public-digital-library/assets/38666030/0c621e85-cccc-480f-8d86-34dd97b06e67)
