### ISSUE TITLE
handle version collections

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#871]
The https://library.bdrc.io/show/bdr:PR1PL480 collection is now a collection of versions (MW),  not scans (W), but when clicking on the "show all" button it tries Etexts. Maybe it can detect from the small sample that these are MWs and link to Instances instead?

**Comment by berger-n** [comment]
fixed: https://library.bdrc.io/show/bdr:PR1PL480

![simplescreenrecorder-2024-05-16_13 41 26 mkv](https://github.com/buda-base/public-digital-library/assets/33383857/61afbfe3-f251-4498-bcc4-4f51906f9faf)

**Comment by eroux** [comment]
thanks!
