### ISSUE TITLE
donate popup impossible to close on mobile

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#873]
Here's a screenshot from Karma:

![Donate_flyer_can't_close_on_Phone](https://github.com/buda-base/public-digital-library/assets/60868/54d7b524-b620-4208-93ae-5faf089523ba)

**Comment by berger-n** [comment]
should be fixed now: https://library.bdrc.io/?uilang=bo

![simplescreenrecorder-2024-05-18_15 03 40 mkv](https://github.com/buda-base/public-digital-library/assets/33383857/3bcb0252-080d-4e74-ade3-2f8c815bf230)

**Comment by eroux** [comment]
thanks a lot, really appreciated!
