### ISSUE TITLE
new results page

### ISSUE THREAD

**Issue by berger-n** [buda-base/public-digital-library#879]
just deployed a first draft: https://library-dev.bdrc.io/osearch/search?q=ta%20la%27i%20bla%20ma&type%5B0%5D=Person&sortBy=publicationDate_desc

![image](https://github.com/buda-base/public-digital-library/assets/33383857/2a4341c9-7a1e-4947-b661-7ae7aad1212a)

**Comment by berger-n** [comment]
(investigating something odd with the query results though, compared to `opensearch-ui-prototype`)

**Comment by berger-n** [comment]
added labels in the filters sidebar (from the ontology and/or the translation files, when available):
https://library-dev.bdrc.io/osearch/search?q=spyod%20%27jug

https://github.com/buda-base/public-digital-library/assets/33383857/d1917d60-69f0-4ed5-80f8-7178fcc53ca4

**Comment by berger-n** [comment]
working on the results: https://library-dev.bdrc.io/osearch/search?q=ta%20la%27i%20bla%20ma

![image](https://github.com/buda-base/public-digital-library/assets/33383857/a4f32f5b-32d4-42ef-9baf-e8ca3c66468d)
---

next steps are to transliterate the highlighted text, and to split highlighted data when a same field has matched multiple times: https://library-dev.bdrc.io/osearch/search?q=spyod%20%27jug 

![image](https://github.com/buda-base/public-digital-library/assets/33383857/854273d1-6d37-48a1-9d21-69428aa8a54a)

**Comment by berger-n** [comment]
improved highlighting/display of matching labels (using first `prefLabel` as the title, then the other ones + matching `altLabel` when there are some, as other name/title; removed the space between contiguous matching words): 
https://library-dev.bdrc.io/osearch/search?q=spyod%20%27jug

https://github.com/buda-base/public-digital-library/assets/33383857/42bbe539-3ec6-437c-829e-fc37aa55fc1f

**Comment by berger-n** [comment]
almost working: https://library-dev.bdrc.io/osearch/search?q=spyod%20%27jug

![image](https://github.com/buda-base/public-digital-library/assets/33383857/ad25de66-ce77-4eab-90a7-28cccb802f71)

(but for now you have to click on a facet again once labels are loaded - working on it)

**Comment by berger-n** [comment]
looks fine to me now:

![simplescreenrecorder-2024-06-25_18 37 17 mkv](https://github.com/buda-base/public-digital-library/assets/33383857/07819621-dccf-4e77-9d95-a94ddf2e8f2c)

**Comment by eroux** [comment]
wonderful, it's really starting to look good!

**Comment by berger-n** [comment]
added the thumbnails (using `inRootInstance` when there was one, is that ok?): 
https://library-dev.bdrc.io/osearch/search?q=spyod%20%27jug

![image](https://github.com/buda-base/public-digital-library/assets/33383857/68ff6bd4-9f0f-48b1-86a4-aab2a121a93b)

---

also found these collections with no label on the left, does that ring a bell? looking at the records I couldn't find these collection in their data so I don't know where it came from in the results...
https://library-dev.bdrc.io/osearch/search?q=spyod%20%27jug&inCollection%5B0%5D=PR0ET005&inCollection%5B1%5D=PR0ET010&type%5B0%5D=Instance

![image](https://github.com/buda-base/public-digital-library/assets/33383857/7a7f3c26-ab70-48a2-9160-6edb0de77b20)

**Comment by eroux** [comment]
Thanks! that starts to look familiar :)

yep, root instance is good

ah yes, these collections... I need to clean things up a bit

**Comment by eroux** [comment]
hmmm not quite:

https://purl.bdrc.io/graph/W1PD181145.ttl still has

```
bdo:volumePagesTotal  0
```

it should have more

**Comment by berger-n** [comment]
I think we now are not far from good here: https://library-dev.bdrc.io/osearch/search?q=spyod%20%27jug

![image](https://github.com/user-attachments/assets/2a5f0c03-4255-4cf7-bbdc-21561d5aed38)

**Comment by eroux** [comment]
this is great, thanks a lot!
