### ISSUE TITLE
access and quality UX on results page

### ISSUE THREAD

**Issue by berger-n** [buda-base/public-digital-library#881]
currently we have these access/quality indications:

- [restricted by tbrc](https://library.bdrc.io/search?q=%22spyod%20%27jug%22~1&lg=bo-x-ewts&t=Instance&pg=1&f=asset,exc,tmp:possibleAccess&f=asset,exc,tmp:catalogOnly):

![image](https://github.com/buda-base/public-digital-library/assets/33383857/6247e333-66c6-4418-8b46-ae625d753f2a)

- [sealed/fair use (with possible IA link)](https://library.bdrc.io/search?q=%22thabs%20lam%20snying%22~1&lg=bo-x-ewts&t=Instance&pg=1&f=asset,exc,tmp:hasOpen):

![image](https://github.com/buda-base/public-digital-library/assets/33383857/d08a7912-aba7-433e-ae32-d9685eddbc39)

- [temporarily restricted](https://library.bdrc.io/search?q=%22byang%20chub%20lam%20rim%20khrid%22~1&lg=bo-x-ewts&t=Instance&pg=1&f=asset,exc,tmp:possibleAccess):

![image](https://github.com/buda-base/public-digital-library/assets/33383857/227b0355-e628-4456-824f-b0ff6198b102)

- [low quality](https://library.bdrc.io/search?q=%22%27gro%20kun%20dad%20pa%27i%20zhing%20sar%20bden%20don%20chos%20char%22~1&lg=bo-x-ewts&t=Instance&f=asset,inc,tmp:possibleAccess&f=asset,inc,tmp:catalogOnly):

![image](https://github.com/buda-base/public-digital-library/assets/33383857/c93843bf-1225-46ee-bde2-8abd5ba14403)

---

now the question is how to display it using this new indicator:
https://github.com/buda-base/git-to-dbs/blob/elasticsearch/src/main/java/io/bdrc/gittodbs/ESUtils.java#L820-L831
```
    // rank_features must be strictly positive (non-zero)
    // etext access:
    //   1: no access
    //   2: search only
    //   3: open access

    // scans access:
    //   1: no access
    //   2: extract only
    //   3: IA
    //   4: open access through IIIF
    //   5: open access on BDRC
```

**Comment by berger-n** [comment]
added the scans/etext access filters: https://library-dev.bdrc.io/osearch/search?q=bka%27%20%27gyur

![image](https://github.com/buda-base/public-digital-library/assets/33383857/b839ce78-e56e-4fb2-b850-62c6f9d5fdf1)

**Comment by berger-n** [comment]
regarding quality, I think we can have a widget but I'll need more category names like: 
- 4: computer input I guess? 
- 3: excellent 
- 2: very good 
- 1-0.66: good 
- 0.66-0.33: average 
- 0.33-0: poor?

https://library-dev.bdrc.io/osearch/search

![image](https://github.com/buda-base/public-digital-library/assets/33383857/18ece547-8550-4a60-a2dd-7a51e9c902b7)

**Comment by eroux** [comment]
thanks! For etexts I think we need stronger standards:
- 1.0-0.95 : very good OCR
- 0.95-0.8: usable OCR
- 0.8-0: poor quality OCR

**Comment by eroux** [comment]
and let's not make an aggregate with scans_quality, there's almost no data for it (yet)

**Comment by berger-n** [comment]
now with etext quality ranges: 
https://library-dev.bdrc.io/osearch/search?etext_quality%5B0%5D=2.99-3.01&sortBy=firstScanSyncDate_desc
(note that there are a few `scans_quality` already available/displayed, should I remove them for now?
everything is ready to use, we just have to update the ranges/labels [here](https://github.com/buda-base/public-digital-library/blob/bd2bb018a96aa0e0333eb0cca2c7ec0b3b61dc27/src/lib/searchkit/api/ElasticAPI.js#L12) and [here](https://github.com/buda-base/public-digital-library/blob/bd2bb018a96aa0e0333eb0cca2c7ec0b3b61dc27/src/translations/en.json#L808))

![image](https://github.com/buda-base/public-digital-library/assets/33383857/4e8dcb4d-c8cd-43b2-a62e-7ce828fa5928)

---

BTW I think I've fixed the issue with sorting not returning the same results/returning too many results:
(this used to return like ~1000 results)
https://library-dev.bdrc.io/osearch/search?q=%27ba%27%20bro&sortBy=firstScanSyncDate_desc

![simplescreenrecorder-2024-07-03_15 57 41 mkv](https://github.com/buda-base/public-digital-library/assets/33383857/14608d14-a4e5-4825-b4f3-be3bd8ff704c)
