### ISSUE TITLE
display the provenance of images on the new results page

### ISSUE THREAD

**Issue by berger-n** [buda-base/public-digital-library#883]
currently we have [something like this](https://library.bdrc.io/search?q=%22bka%27%20%27gyur%22~1&lg=bo-x-ewts&t=Instance&pg=1&f=asset,inc,tmp:possibleAccess&f=asset,inc,tmp:catalogOnly&f=provider,inc,bda:CP037&f=provider,inc,bda:CP053&f=provider,inc,bda:CP026&f=printMethod,exc,bdr:PrintMethod_Modern):

![image](https://github.com/buda-base/public-digital-library/assets/33383857/1673fe49-8aa1-457c-abf3-7e4d43dd47fe)

**Comment by roopeux** [comment]
@eroux, does this require something?

**Comment by eroux** [comment]
yes, basically what Nicolas showed in his screenshot of the old website is that for search results that have images outside of BDRC, we communicate their provenance to the user through an icon in the bottom right corner of the thumbnail. The dev website doesn't have such a mechanism: when you search

https://library-dev.bdrc.io/osearch/search?q=bka%27%20%27gyur%2F%20(spyi%20zhing%2F)

there's no indication that the images are from the Endangered Archive Project at the British Library. It's quite important not just to the users but also to make sure our partners are confortable having us include their catalog in our search results, attribution is quite important politically

**Comment by roopeux** [comment]
@eroux, There was a miscommunication earlier when I had added the logos on some thumbnails and you said "the logos are not needed" so I removed them.  Is it ok to tell @berger-n do them as they were done before?

**Comment by eroux** [comment]
sure!
