### ISSUE TITLE
do not overwrite user input in search bar

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#884]
I'm in a place where internet bandwidth is a bit slow, and when I type in the search bar the code keeps overriding what I'm typing. It's not very clear in the screencast but especially towards the end the search bar becomes just unusable. Is it possible to never override the user input before the user clicks on something?

[Capture d’écran vidéo de 30-06-2024 10:39:19.webm](https://github.com/buda-base/public-digital-library/assets/60868/6d622efc-c1ad-477b-a569-1ddd40415fd4)

**Comment by berger-n** [comment]
should be fixed now, is it still possible for you to test it?

**Comment by eroux** [comment]
I have a better bandwidth now but it seems to work perfectly, thanks!
