### ISSUE TITLE
missing info on some search results

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#885]
I'm trying to give a preview of the search on latest syncs to a user, I have something I'm quite happy with on

https://library-dev.bdrc.io/osearch/search?language%5B0%5D=LangBo&type%5B0%5D=Instance&sortBy=firstScanSyncDate_desc&firstScanSyncDate_before=2023-07-13&page=4

but it's lacking scans and etext availability in the results, so we can't see what's available and what's not

**Comment by berger-n** [comment]
fixed: https://library-dev.bdrc.io/osearch/search?language%5B0%5D=LangBo&type%5B0%5D=Instance&sortBy=firstScanSyncDate_desc&firstScanSyncDate_before=2023-07-13&page=4

![image](https://github.com/buda-base/public-digital-library/assets/33383857/d6f06562-a34b-45be-81ad-ee04eeefc502)

**Comment by eroux** [comment]
looks good, thanks!
