### ISSUE TITLE
image not shown for some instances

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#887]
https://library-dev.bdrc.io/show/bdr:MW8CZ134 should display an image of the scans. Looking at the network tab there is actually a successful request to the IIIF server so it seems to be just a display issue

**Comment by berger-n** [comment]
updated using the new figma: https://library-dev.bdrc.io/show/bdr:MW8CZ134

![image](https://github.com/buda-base/public-digital-library/assets/33383857/5905dea2-4dce-4680-bf73-fbcfb3ade3ce)

**Comment by eroux** [comment]
wonderful, thanks!
