### ISSUE TITLE
prefLabel not entirely returned as highlighted when matching

### ISSUE THREAD

**Issue by berger-n** [buda-base/public-digital-library#888]
when the prefLabel is too long it is not entirely returned in its highlighted form:

![image](https://github.com/buda-base/public-digital-library/assets/33383857/518d127b-a6f9-41f1-b4b9-0385d5a543d4)
---

> setting fragment_size in the highlight should fix it*

**Comment by berger-n** [comment]
it worked, thanks! just set `fragment_size` to 500 for `prefLabel` & `altLabel`:
https://library-dev.bdrc.io/osearch/search?q=pe%20cin


![image](https://github.com/user-attachments/assets/bc1d1740-e605-4785-a4b6-0847f4a0c2f3)

**Comment by eroux** [comment]
wonderful, thanks!
