### ISSUE TITLE
ability to "force" search

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#890]
Currently if I type

`rig grol gyis mdzad pa`

in the search, I get stuck with one autosuggest result but I don't want it, I just want to search on what I typed, which it appears I cannot do, it would be good to allow search when the user presses enter

**Comment by berger-n** [comment]
fixed: https://library-dev.bdrc.io/

![simplescreenrecorder-2024-07-15_17 40 00 mkv](https://github.com/user-attachments/assets/7384bf8e-f54e-4b50-8c2c-6770e3cda7dc)
