### ISSUE TITLE
image viewer not working for some FPL works

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#899]
For instance https://library.bdrc.io/show/bdr:W1FPL2985#open-viewer I don't really an obvious error in the manifests

**Comment by berger-n** [comment]
fixed: https://library.bdrc.io/show/bdr:W1FPL2985#open-viewer

![image](https://github.com/user-attachments/assets/6c09e244-61b5-4699-840b-5eca3ad93178)

note that the [manifest](https://iiifpres.bdrc.io/collection/wio:bdr:MW1FPL2985::bdr:W1FPL2985) has an empty string as title, but shouldn't we display a *[no title]* in that case?

![image](https://github.com/user-attachments/assets/a1b543b2-8277-461b-bfe2-b32a6cca5a6f)

**Comment by eroux** [comment]
wonderful, thanks!
