### ISSUE TITLE
missing bar in image viewer on Safari

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#901]
A user reported that in the images viewer in Safari the top bar diappears:

normal:

![normal](https://github.com/user-attachments/assets/2327baa2-586e-472e-8be2-ddbbc2c98e94)

in Safari:

![safari](https://github.com/user-attachments/assets/ba610391-8d54-47b1-bddc-dc8c9251aadc)

**Comment by berger-n** [comment]
looks fixed: 

![image](https://github.com/user-attachments/assets/40ccf12a-e7dd-4166-8eb7-353d1fcbcf8d)

**Comment by eroux** [comment]
thanks!
