### ISSUE TITLE
double scroll bar in the images viewer (volume view)

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#905]
When I open the image viewer (in the -dev website), I'm getting this when I scroll with the mouse:

![Capture d’écran de 2024-08-02 16-48-38](https://github.com/user-attachments/assets/83d3b313-824a-4835-bb7e-f1eb4a204515)

which has a little handler on the right, which is nice, but then when I try to reach the handler with the mouse, another scrollbar appears on top and I can't get to the handler for scrolling

![Capture d’écran de 2024-08-02 16-47-34](https://github.com/user-attachments/assets/11e29aba-c38b-4a6f-ac27-66e0b9ee2e79)

**Comment by berger-n** [comment]
fixed: [link](https://library-dev.bdrc.io/show/bdr:W2PD19446?s=%2Fshow%2Fbdr%3AMW2PD19446%3Ftabs%3Dbdr%3AW2PD19446#open-viewer)

![simplescreenrecorder-2024-08-02_17 42 37 mkv](https://github.com/user-attachments/assets/d06e84a3-e003-454f-abff-e6aaf58fec18)

**Comment by eroux** [comment]
wonderful, thanks!

**Comment by eroux** [comment]
This issue came back, can you take another look @berger-n ?

**Comment by berger-n** [comment]
fixed: https://library-dev.bdrc.io/show/bdr:W2PD19446?s=%2Fshow%2Fbdr%3AMW2PD19446#open-viewer

![simplescreenrecorder-2024-11-06_16 43 35 mkv](https://github.com/user-attachments/assets/f6439d71-68b0-4031-b632-ac7b37ba2a1f)

**Comment by eroux** [comment]
looks good, thanks!
