### ISSUE TITLE
small bugs in the new UI

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#906]
- [ ] the autosuggest UI should respond to keyboard keys up / down (especially from the search box) so it's easy to select one of the results without having to use the mouse
- [ ] when searching, "search in etexts only" is activated by default, it shouldn't
- [ ] when clicking on "search in etexts only" in Firefox the box gets duplicated:

![Capture d’écran de 2024-08-05 08-15-51](https://github.com/user-attachments/assets/2593f10b-ec2b-4721-b78a-829329095821)

- [ ] it seems there are always to identical requests sent to the API:

![Capture d’écran de 2024-08-05 08-18-10](https://github.com/user-attachments/assets/5018cdbb-ebf7-475c-953a-6da0a270a09b)

**Comment by berger-n** [comment]
seems alright now: https://library-dev.bdrc.io/osearch/search?q=spyod%20%27jug

![simplescreenrecorder-2024-08-12_17 47 59 mkv](https://github.com/user-attachments/assets/a11829e5-d372-4756-819c-81bde3b350db)
---

![simplescreenrecorder-2024-08-12_17 42 38 mkv](https://github.com/user-attachments/assets/f4cfb54e-433d-4c45-b7d8-2914ee7f4402)
---

![simplescreenrecorder-2024-08-12_17 44 27 mkv](https://github.com/user-attachments/assets/fe28b65a-3271-459c-901e-6ec2e2cea967)

**Comment by eroux** [comment]
looks good, thanks a lot!
