### ISSUE TITLE
Search placeholders

### ISSUE THREAD

**Issue by roopeux** [buda-base/public-digital-library#912]
Indicate the scope of search in the placeholders of each search box, throughout the website.

- [x] No scope: "Search the website"
- [x] Person: "Search texts by this person or about this person"
- [x] Text: "Search this text"
- [x] Place: "Search material related to this place"
- [x] Collection (as in Khmer Manuscript): "Search texts in this collection"
- [x] Collection (as a text that has volumes or subtexts): "Search these texts".

In the etext viewer:

- [x] "Search this collection"
- [x] "Search this volume"
- [x] "Search this text"

depending on what user has selected in the left panel

If Figma says otherwise, use the copy from here, or ask @roopeux

This will be crucial for UX, because scoped search is notoriously difficult for users.

**Comment by berger-n** [comment]
looks all done to me:

![image](https://github.com/user-attachments/assets/2344731e-85e5-45b1-a88b-4c374105eadf)

---

![image](https://github.com/user-attachments/assets/8ea1dcb3-9a87-48f1-a42a-d2a09c014e00)

---

![image](https://github.com/user-attachments/assets/ac33b983-b0d6-4ce2-992d-0be7caea0ee3)

---

![image](https://github.com/user-attachments/assets/63e468a5-3eb9-45d6-8b83-245552f8b31b)

---

(see also #913 for this one, in progress)
![image](https://github.com/user-attachments/assets/1cf30b33-0d14-47be-8115-dbade8c232a6)

---

![simplescreenrecorder-2024-09-13_17 57 27 mkv](https://github.com/user-attachments/assets/0512940b-5449-45bb-a7d1-84ba1356b68d)

**Comment by roopeux** [comment]
Looks great!  Thanks @berger-n
