### ISSUE TITLE
clickable icon?

### ISSUE THREAD

**Issue by ngawangtrinley** [buda-base/public-digital-library#92]
In smaller windows it can be difficult to click on the thumbnails....
![gif](https://user-images.githubusercontent.com/17675331/64154555-b11c0b00-ce63-11e9-896f-a0d97d039767.gif)

Also note the full screen button hiding behind the zoom tool

**Comment by eroux** [comment]
hmm right, @berger-n maybe:
- the zoom could be hidden when in manifest mode (or whatever the name of the initial mode where there's no real image)
- in the manifest list, the logo could be on the right of the image perhaps?
