### ISSUE TITLE
Fit Tibetan in the search box (for test)

### ISSUE THREAD

**Issue by berger-n** [buda-base/public-digital-library#928]
![Image](https://github.com/user-attachments/assets/7ffd94c3-e71f-4ac4-982c-386b47d1dbd3)

**Comment by berger-n** [comment]
fixed: [link](https://library-dev.bdrc.io/osearch/search?q=%E0%BD%96%E0%BE%B1%E0%BD%84%E0%BC%8B%E0%BD%86%E0%BD%B4%E0%BD%96%E0%BC%8B%E0%BD%A6%E0%BD%BA%E0%BD%98%E0%BD%A6%E0%BC%8B%E0%BD%91%E0%BD%94%E0%BD%A0%E0%BD%B2%E0%BC%8B%E0%BD%A6%E0%BE%A4%E0%BE%B1%E0%BD%BC%E0%BD%91%E0%BC%8B%E0%BD%94%E0%BC%8B%E0%BD%A3%E0%BC%8B%E0%BD%A0%E0%BD%87%E0%BD%B4%E0%BD%82%E0%BC%8B%E0%BD%94)

![image](https://github.com/user-attachments/assets/d07df0ef-f59c-4894-a66a-bc953a129553)

**Comment by roopeux** [comment]
Thanks, great!
