### ISSUE TITLE
Make back button work for search results (for test)

### ISSUE THREAD

**Issue by berger-n** [buda-base/public-digital-library#935]
**Search result to search result** 
1. Search for "my search 1"
2. Search for "my search 2"
3. Click the back button
4. BUG: Nothing changes on the page, although URL changes.  EXPECTED: The search box should say "my search 1" and show the corresponding results

**From content page back to search results**
1. Search for "my search 1"
2. Search for "my search 2"
3. Click one of the results
4. Click Back
5. BUG: The search box shows "my search 1".  EXPECTED: "my search 2"

**Comment by berger-n** [comment]
fixed the issue but only from https://library-dev.bdrc.io/osearch/search, can you confirm @roopeux?
(from home https://library-dev.bdrc.io/ I have a fix that works locally but not once deployed, still working on it)

![simplescreenrecorder-2024-09-23_18 55 42 mkv](https://github.com/user-attachments/assets/08bac54f-9ab5-4158-a803-5ca74f180eaf)

**Comment by roopeux** [comment]
Great, thanks!

**Comment by berger-n** [comment]
took me three full days but it now looks all fixed to me! 
the url always gets updated with the keyword or when a filter is set/unset, so you can go back/forth without a glitch: 
https://library-dev.bdrc.io/

![simplescreenrecorder-2024-09-27_17 47 10 mkv](https://github.com/user-attachments/assets/664a804a-30ba-443c-b76d-dbbe9662ec0a)

**Comment by eroux** [comment]
excellent job, thanks a lot!

**Comment by berger-n** [comment]
just fixed that kind of glitch, related to a major upgrade of the routing package: 
https://library-dev.bdrc.io/show/bdr:IE0OPICADB8DF8
(note that there could be more of them "gray screen freeze" due to a route not properly handled yet for some reason)

![simplescreenrecorder-2024-09-27_18 28 41 mkv](https://github.com/user-attachments/assets/725ad592-a32d-49b2-94c6-8d82f06a8bff)
