### ISSUE TITLE
Showing collection in record

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#936]
In many records (like https://library-dev.bdrc.io/show/bdr:MW1NLM1) the information about collection is not in the version but in the scans. These two records are merged in the UI, but the collection information from the scans is not shown. Can we display it along with the scan info ?

**Comment by roopeux** [comment]
I don't exactly know what information is missing, but I think it should be shown if it is relevant.

**Comment by berger-n** [comment]
done: https://library-dev.bdrc.io/show/bdr:MW1KG1279

![image](https://github.com/user-attachments/assets/d65949ae-d9a2-4da4-90a8-d93aaf64f28e)

**Comment by eroux** [comment]
Ah perfect, thanks!
