### ISSUE TITLE
Don't add zero hits in autosuggest (from test)

### ISSUE THREAD

**Issue by roopeux** [buda-base/public-digital-library#938]
Add user's queries in personal autosuggest only if there are hits.

**Comment by eroux** [comment]
oh, another related idea: maybe we should remove suggestions from the autosuggest if they're already in the search history? (unfortunately I can't really do screenshots as it kills the popup, but it's easy to reproduce). What do you think @roopeux ?

**Comment by roopeux** [comment]
Which search history do you mean?

**Comment by berger-n** [comment]
some fixes for the history: https://library-dev.bdrc.io/
- set total to 8 entries (max. 3 from history when there's at least 5 from autosuggest)
- when no results, the entry is not added to the history
- when an entry from history is also in the autosuggest, it's not displayed as a autosuggest

![simplescreenrecorder-2024-10-17_19 00 06 mkv](https://github.com/user-attachments/assets/2511fe29-7a49-4833-ad09-796e8e0ec25b)
