### ISSUE TITLE
Add volume numbers in outline (from test)

### ISSUE THREAD

**Issue by berger-n** [buda-base/public-digital-library#958]
Maybe easiest to prepend to the volume title

![Image](https://github.com/user-attachments/assets/0ef77ab8-00f3-48e7-9c63-2a0824f2a444)

**Comment by berger-n** [comment]
done: https://library-dev.bdrc.io/show/bdr:MW22084

![image](https://github.com/user-attachments/assets/c925553f-c91a-4035-b99f-7d171129f08b)

in etexts as well: [link](https://library-dev.bdrc.io/show/bdr:IE0OPI6440489A?back=bdr%3AMW22084&openEtext=bdr:VLIE0OPI6440489A_I0890#open-viewer)

![image](https://github.com/user-attachments/assets/3dd307d6-c0f6-4353-abe4-00df56189a2a)

@eroux @roopeux feel free to tell me how I should fine tune this / when not to show the index number maybe?

**Comment by roopeux** [comment]
It looks great @berger-n.  To alleviate the slight cosmetic issue with numbered volumes, maybe always add a right bracket: "14) volume 14"

**Comment by berger-n** [comment]
thanks @roopeux good idea! done: https://library-dev.bdrc.io/show/bdr:MW22084

![image](https://github.com/user-attachments/assets/d70f26da-dde6-4712-9996-7c075411a8e9)

**Comment by eroux** [comment]
that's nice but also a bit confusing.. maybe we can keep the volume number for nodes of type volume only? Having the numbers for sections, texts, etc. is a bit puzzling (I actually can't make sense of the screenshot from the previous comment)

**Comment by eroux** [comment]
that looks good to me, closing, let's reopen if needed
