### ISSUE TITLE
removing translators from the author field in search results?

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#960]
in https://library-dev.bdrc.io/osearch/search?q=zhi%20ba%20lha%20spyod%20%27jug

![Capture d’écran de 2024-11-15 08-28-19](https://github.com/user-attachments/assets/713a432f-609a-4e78-aad2-6936e2877027)

the authors field also contains the translators (from the "translators" field in the results json), I think we should only display the author

**Comment by berger-n** [comment]
done: https://library-dev.bdrc.io/osearch/search?q=zhi%20ba%20lha%20spyod%20%27jug

![image](https://github.com/user-attachments/assets/909a10e8-bcf3-430c-a1ff-f839c5bbd543)

**Comment by eroux** [comment]
wonderful, thanks!
