### ISSUE TITLE
Search box redesign (from test)

### ISSUE THREAD

**Issue by berger-n** [buda-base/public-digital-library#962]
Magnifying glass on the right
Show X only after user has typed something (unlike in the screenshot)
![Image](https://github.com/user-attachments/assets/b6849ba0-8a71-488d-b1b0-9d5f139aba4f)

The same with scope search

**Comment by berger-n** [comment]
done: https://library-dev.bdrc.io/show/bdr:P9902

![simplescreenrecorder-2024-11-15_18 43 18 mkv](https://github.com/user-attachments/assets/d2c103a7-13b4-4dd2-9386-441cd1bbb5a8)

**Comment by eroux** [comment]
wonderful, thanks!
