### ISSUE TITLE
Remove link from volume in etext viewer

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#968]
Based on #964, remove the link from "Volume" in etexts
![Image](https://github.com/user-attachments/assets/37bcbcf2-81d6-4533-84fb-669b1dec4a55)

**Comment by eroux** [comment]
minor, but also maybe let's not upper case "volume"

**Comment by berger-n** [comment]
done: [link](https://library-dev.bdrc.io/show/bdr:IE0OPI6440489A?back=bdr%3AMW22084&openEtext=bdr:VLIE0OPI6440489A_I0886#open-viewer)

![image](https://github.com/user-attachments/assets/36d7117c-3193-4193-b8c7-c72b3674a912)

**Comment by eroux** [comment]
great, thanks!
