### ISSUE TITLE
crash in the interface

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#970]
When I go to https://library.bdrc.io/search?r=bdr:P4184&t=Work&pg=3&n=101

then page 3, I click on "see 2 versions" for WA3CN22722, then the website crashes

![Capture d’écran de 2024-11-27 18-18-41](https://github.com/user-attachments/assets/81529c4f-d9fa-4d43-a3e6-62f199194433)

**Comment by berger-n** [comment]
fixed: https://library.bdrc.io/search?r=bdr:P4184&t=Work&pg=3&n=101
(it seems there's a typo in https://ldspdi.bdrc.io/resource/MW1LT0811.ttl:
```
skos:altLabel  "                                              "@bo-x-ewts ;
```
)

![image](https://github.com/user-attachments/assets/1cdcbfaa-bf59-4d56-92a4-b648bd826057)

**Comment by eroux** [comment]
oh, that's original :) thanks for the fix!
