### ISSUE TITLE
display work ID in the version page

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#971]
Our librarians need to be able to know the work ID (WA...) corresponding to the page they're on (for instance on https://library-dev.bdrc.io/show/bdr:MW22084 they need to see `WA0BC001`). There are different ways to do that, one would be "BDRC work number" in the Extended properties, one would be 

BDRC work: Kangyur (WA0BC001)

just above "other versions of this work". I kind of like this solution as it makes the "work" in "other versions of this work" easier to understand.

what do you think @roopeux ?

**Comment by roopeux** [comment]
It is a good idea to place the ID near the other versions.
"Work ID", "Text ID" and "Book ID" would mean pretty much the same thing for the user.  The three words are very close in the English language and we cannot change that.

Since we want to convey an idea we need to be more verbose.

My suggestion would be "Collective ID for the versions:"
If this would just above the version list, users will understand what it means.

**Comment by eroux** [comment]
well, I agree we could go in that direction, but when you say "the user" you're ignoring:
- advanced users who need to understand what's going on and have consistent vocabulary
- users who got used to BUDA

so I disagree with getting rid of the term "work" completely. Maybe "BDRC Work (group of versions)"?

**Comment by roopeux** [comment]
Where I am coming from is that web designers used to come up with neologisms to create mini brands like "Mini Moon" for a short honeymoon.  Travel sites said "Click here for a Mini Moon".  Business suffered.

It does not matter how systematically we repeat the three synonyms, they are even worse than the neologisms.  You cannot change the English language and give "book", "work" or "text" meanings that they don't naturally carry.

Especially when we have the "advanced users who need to understand", please come up with more verbose terms that explicitly convey the meaning.  There is a handful of "old BUDA users" who finally learned the terms "version" and "work", but it will be easier for them too if the language is clear.

This is my advice as a UX consultant.  I am running out of hours to say much more than this, but please take this as a friendly advice.

**Comment by berger-n** [comment]
done: https://library-dev.bdrc.io/show/bdr:MW1PD88781
(note that on `library-dev` the link has to be hardcoded like `/show/bdr:...`, rather than using the permalink, as the latter redirects to `library` not `library-dev`)

![image](https://github.com/user-attachments/assets/9915d2cc-5893-4faa-8ce4-e7381dd3cc71)

**Comment by eroux** [comment]
excellent, thanks!

**Comment by roopeux** [comment]
What will prevent users from accidentally referencing the work page when they want to reference the version page they are on?

**Comment by eroux** [comment]
What kind of mechanism are you thinking of?

**Comment by eroux** [comment]
that's what the big red "permalink" button is for, but if it's not visible enough, please propose an update

**Comment by roopeux** [comment]
Redesigning of the permalink button is not the right solution, because the "BDRC Work ID" is misleading and will continue to mislead, regardless of the permalink design.  

KVP has 100 linked references to BDRC from back matter, and half of them use permalinks, which I assume roughly represents all our user base.  It would not be easy to raise this percentage.  With the new misleading code, this percentage will be lower.

Left as such, a part of references to BDRC will be unintentionally pointing to a wrong place, because it looks like the right code, although it is not.  Users will notice this later and some will be vocal.

**Comment by berger-n** [comment]
> Our librarians need to be able to know the work ID (WA...) corresponding to the page they're on

if nobody else is involved we should just show it to them (like, the *admin* user group or something)
@eroux WDYT?

**Comment by roopeux** [comment]
It is not only the librarians.  AFAIK, this is currently the only way to get to the work pages at all.  Is it?

**Comment by roopeux** [comment]
There would be plenty of solutions but it seems that proposing any is futile because you are so set on this.  BTW, is it that you don't believe in the downsides mentioned above, or you think it won't matter if references point to a wrong page? @eroux

**Comment by berger-n** [comment]
> AFAIK, this is currently the only way to get to the work pages at all. Is it?

actually the advanced search can return them all: 
https://library-dev.bdrc.io/search?q=%22spyod%20%27jug%22~1&lg=bo-x-ewts&t=Work

other than that, some fields like *Parallels in* or *Serial instance of* link to a work as well:
https://library-dev.bdrc.io/show/bdr:MW4CZ301801?
https://library-dev.bdrc.io/show/bdr:MW3KG263?s=%2Fshow%2Fbdr%3AWAS8LS66540&

> If there's no solution then there's no problem :)

looking at the comment in the tooltip, I'm thinking it could have something saying this is not the permalink
and/or maybe add a *Legacy* in the field name itself?

**Comment by eroux** [comment]
> add a Legacy in the field name itself?

it's not legacy, it's just advanced

**Comment by roopeux** [comment]
Tooltips are not very reliable.  Whatever we decide to write in some hidden text will have little effect.  This is based on observing hundreds of users.

**Comment by roopeux** [comment]
A simple solution would be to link to the work page with a call-to-action like

**Work page**: See the "work" page which combines all the different versions of this text.

The main point is to leave out the work page ID from the version page.

<img width="586" alt="image" src="https://github.com/user-attachments/assets/263986c1-1cb8-4783-9a76-1ca9cf4479ab">

**Comment by eroux** [comment]
that's a good idea, but also significantly less convenient for advanced users. Can you make a proposal that includes the user ID somewhere in the sentence? (and that's easy to copy/paste)

**Comment by roopeux** [comment]
Convenience is not about having the least amount of clicks, but making every click easy to understand.  Do you seriously claim that one click more would be "signigicantly less convenient" for an advanced user?  Is this something that they do in bulk hundreds of times?

**Comment by eroux** [comment]
yes. I would like to move our energy to other topics if that's ok

**Comment by roopeux** [comment]
@berger-n this would be the final

<img width="1061" alt="image" src="https://github.com/user-attachments/assets/941c5721-9d70-4de9-b561-f28827b5dd0b">

[See the "work" page which combines all the different versions of this text.](https://library-dev.bdrc.io/show/bdr:WA0RT3216) The ID of this version is MW8LS76623. The overarching work ID is WA0RT321

**Comment by berger-n** [comment]
ok! done: https://library-dev.bdrc.io/show/bdr:MW1PD88781?

![image](https://github.com/user-attachments/assets/2d99103b-54a1-49a3-8a2c-894c1c4d1f90)

**Comment by eroux** [comment]
thanks!

**Comment by roopeux** [comment]
Thanks @berger-n, there is one space missing after the full stop.

**Comment by berger-n** [comment]
indeed @roopeux thanks, not anymore: https://library-dev.bdrc.io/show/bdr:MW1PD88781?

![image](https://github.com/user-attachments/assets/13206867-e71f-41d0-9e48-defb3e21e27c)
