### ISSUE TITLE
html title and header

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#972]
Currently when I visit https://library-dev.bdrc.io/show/bdr:MW22084 I see "bdr:IE0OPI6440489A" in my browser tab:

![Capture d’écran de 2024-11-29 11-05-29](https://github.com/user-attachments/assets/8b35300d-ad67-4184-9db8-71426aac3a36)

let's make it so that on this kind of page the title of the MW is always displayed

**Comment by berger-n** [comment]
fixed: https://library-dev.bdrc.io/show/bdr:MW22084

![image](https://github.com/user-attachments/assets/5dfd5512-9e21-486c-bfec-2f0f1bc25261)

---

BTW not really related but very recent, [the chunks query](https://ldspdi-dev.bdrc.io/osearch/etextchunks?cstart=1&cend=10001&id=bdr%3AVLIE0OPI6440489A_I0886) returns 500 here

**Comment by eroux** [comment]
Great, thanks! I'll open a separate issue for the error, thanks for the report!
