### ISSUE TITLE
page for works

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#973]
For some use cases we still need a page for works (for instance, external links to a work page, there will be more and more of that). I propose we just use the exact same as the page for versions except we don't show any of the version properties (reproductions, etc.) and instead of "other versions of this work" we would have "versions of this work". What do you think @roopeux ?

**Comment by berger-n** [comment]
looks ok already but feel free to comment further: https://library-dev.bdrc.io/show/bdr:WA0BC001

![image](https://github.com/user-attachments/assets/28cf150c-4c57-43ea-b703-4d1086a36db9)

**Comment by eroux** [comment]
yes that looks good, thanks! The titles are a bit funny... but that's a data issue

**Comment by berger-n** [comment]
> The titles are a bit funny... but that's a data issue

in what way? because I remember having to do something with the new query (like, force selecting the first label) so as it looks like the old query (the new default was to label them all *bka' 'gyur* because of the lexical ordering )

**Comment by berger-n** [comment]
ok thanks!

**Comment by eroux** [comment]
the labels are much better now
