### ISSUE TITLE
scope autosuggest on other tradition pages 

### ISSUE THREAD

**Issue by berger-n** [buda-base/public-digital-library#978]
the other traditions page are online (with the new home deployed BTW): https://library-dev.bdrc.io/

regarding the configuration of the content I've used these filters:

https://github.com/buda-base/public-digital-library/blob/e905bb0dd088c3fee43434f877b48d713d966ee2/src/components/TraditionViewer.js#L358-L363

---

now the issue is I don't think these can be used as a scope for autosuggest, can they @roopeux @eroux? 

![image](https://github.com/user-attachments/assets/56583207-dd3f-4463-aef9-b32f56008210)

**Comment by eroux** [comment]
oh thanks! I think we can probably make it work with the autocomplete by adding a field, right Roope? On the other hand there won't be too much overlap in the search so it's not particularly urgent to add that...

For Tibetan though we should add `OR script:ScriptTibt` (some are misclassified like that)

**Comment by roopeux** [comment]
This is the line to modify in `indexer-autosuggest.py`, we can basically add any field and use its values in the `scope` of the autosuggest json
```
            elif field in ['associatedTradition', 'inRootInstance', 'associated_res']:
                scope += value
```
I can do it if you give me the field, or @eroux, as you want.

**Comment by berger-n** [comment]
thanks @roope @eroux! so I guess the additional field would be `language` and `script`

**Comment by berger-n** [comment]
it works now, thanks @roopeux: https://library-dev.bdrc.io/tradition/sa/

![simplescreenrecorder-2024-12-20_13 33 04 mkv](https://github.com/user-attachments/assets/9b7e827c-3347-4f91-a674-790a3b675d82)

---

(I need to fix the issue with space in highlighting here)

![image](https://github.com/user-attachments/assets/1e3e12da-b3dd-448d-8eed-f04e5295a909)

**Comment by berger-n** [comment]
fixed: https://library-dev.bdrc.io/tradition/sa/?sortBy=firstScanSyncDate_desc&q=Ar%2ByASh%2BTasAhasrikA%20pradz%2BnyApAramitA

![image](https://github.com/user-attachments/assets/aa38b5b2-b3d3-4e8d-9d2e-7ae242e40107)
