### ISSUE TITLE
can't find etext from work page

### ISSUE THREAD

**Issue by berger-n** [buda-base/public-digital-library#99]
see http://library.bdrc.io/show/bdr:UT4CZ5369_I1KG9127_0000
it is impossible to find it from http://library.bdrc.io/show/bdr:W4CZ5369 / http://library.bdrc.io/show/bdr:I4CZ5369_E001
(BTW there could be a more direct/readable link to Etext from Work page, such as "Has Etext")

**Comment by eroux** [comment]
I think it's sort of fine, it's just not labelled properly: there's one etext item (which contains all the volumes, including the one you mention), it's listed on  http://library.bdrc.io/show/bdr:W4CZ5369 as I4CZ5369_E001 and the link works... Now, what's a bit weird is that when I go there and click on http://library.bdrc.io/show/bdr:VL159718C716C7 there's no link to bdr:ER58D7BD9E7EB3 (which is there in the data). I think fixing this should be ok.

BTW, when an item (such as I4CZ5369_E001) is not of type `:ItemImageAsset`, there should be no attempt to get the manifest from the iiifpres service
